'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { PortalShell } from '@/components/portal-shell';
import { apiRequest } from '@/lib/api';

type Language='fr'|'en'|'de'|'it'|'es'|'pt';
type Client={id:string;name:string};
type EventItem={id:string;name:string;startsAt:string;status:string;venueName?:string|null};
type Readiness={state:'READY'|'ATTENTION'|'BLOCKED';stations:Array<{mode:string;online:boolean;stale:boolean}>;media:{pending:number;failed:number;synced:number};recommendedAction:string;alerts:Array<{message:string}>};
type Conversation={id:string;status:string};
const TEXT:Record<Language,Record<string,string>>={
fr:{title:'Aujourd’hui dans KHE Booth',subtitle:'L’essentiel pour préparer et piloter votre prochaine prestation.',create:'Créer un événement',clients:'Clients',next:'Prochain événement',noNext:'Aucun événement à venir.',eventReady:'Ouvrir Event Ready',stations:'Stations',media:'Médias à synchroniser',messages:'Messages',allGood:'Tout est prêt côté serveur. Lancez le contrôle matériel sur les tablettes.',connectCapture:'Connectez la station CAPTURE.',connectSharing:'Connectez la station SHARING.',rescueSync:'Corrigez la synchronisation avant la prestation.',review:'Vérifiez les points signalés avant le démarrage.',tabletCheck:'Lancez Event Ready sur les tablettes pour confirmer le matériel.',recent:'Activité récente',events:'Voir les événements',help:'Aide & messagerie',ready:'PRÊT',attention:'À VÉRIFIER',blocked:'ACTION REQUISE',online:'connectée(s)',pending:'en attente',failed:'en échec',open:'conversation(s) ouverte(s)',today:'Aujourd’hui',tomorrow:'Demain'},
en:{title:'Today in KHE Booth',subtitle:'What matters most to prepare and run your next event.',create:'Create event',clients:'Clients',next:'Next event',noNext:'No upcoming event.',eventReady:'Open Event Ready',stations:'Stations',media:'Media to sync',messages:'Messages',allGood:'Server-side checks are clear. Run the hardware check on the tablets.',connectCapture:'Connect the CAPTURE station.',connectSharing:'Connect the SHARING station.',rescueSync:'Fix synchronization before the event.',review:'Review the reported points before starting.',tabletCheck:'Run Event Ready on the tablets to confirm hardware.',recent:'Recent activity',events:'View events',help:'Help & messaging',ready:'READY',attention:'CHECK',blocked:'ACTION REQUIRED',online:'online',pending:'pending',failed:'failed',open:'open conversation(s)',today:'Today',tomorrow:'Tomorrow'},
de:{title:'Heute in KHE Booth',subtitle:'Das Wichtigste für die nächste Veranstaltung.',create:'Event erstellen',clients:'Kunden',next:'Nächstes Event',noNext:'Kein bevorstehendes Event.',eventReady:'Event Ready öffnen',stations:'Stationen',media:'Zu synchronisierende Medien',messages:'Nachrichten',allGood:'Serverseitig ist alles bereit. Hardwareprüfung auf den Tablets starten.',connectCapture:'CAPTURE-Station verbinden.',connectSharing:'SHARING-Station verbinden.',rescueSync:'Synchronisierung vor dem Event korrigieren.',review:'Gemeldete Punkte vor dem Start prüfen.',tabletCheck:'Event Ready auf den Tablets starten, um die Hardware zu bestätigen.',recent:'Letzte Aktivität',events:'Events ansehen',help:'Hilfe & Nachrichten',ready:'BEREIT',attention:'PRÜFEN',blocked:'AKTION ERFORDERLICH',online:'verbunden',pending:'ausstehend',failed:'fehlgeschlagen',open:'offene Unterhaltung(en)',today:'Heute',tomorrow:'Morgen'},
it:{title:'Oggi in KHE Booth',subtitle:'L’essenziale per preparare e gestire il prossimo evento.',create:'Crea evento',clients:'Clienti',next:'Prossimo evento',noNext:'Nessun evento in arrivo.',eventReady:'Apri Event Ready',stations:'Stazioni',media:'Media da sincronizzare',messages:'Messaggi',allGood:'I controlli server sono pronti. Avvia il controllo hardware sui tablet.',connectCapture:'Connetti la stazione CAPTURE.',connectSharing:'Connetti la stazione SHARING.',rescueSync:'Correggi la sincronizzazione prima dell’evento.',review:'Controlla i punti segnalati prima di iniziare.',tabletCheck:'Avvia Event Ready sui tablet per confermare l’hardware.',recent:'Attività recente',events:'Vedi eventi',help:'Aiuto & messaggi',ready:'PRONTO',attention:'CONTROLLARE',blocked:'AZIONE RICHIESTA',online:'connessa/e',pending:'in attesa',failed:'in errore',open:'conversazione/i aperta/e',today:'Oggi',tomorrow:'Domani'},
es:{title:'Hoy en KHE Booth',subtitle:'Lo esencial para preparar y dirigir el próximo evento.',create:'Crear evento',clients:'Clientes',next:'Próximo evento',noNext:'No hay próximos eventos.',eventReady:'Abrir Event Ready',stations:'Estaciones',media:'Medios por sincronizar',messages:'Mensajes',allGood:'Los controles del servidor están listos. Ejecuta la comprobación de hardware en las tabletas.',connectCapture:'Conecta la estación CAPTURE.',connectSharing:'Conecta la estación SHARING.',rescueSync:'Corrige la sincronización antes del evento.',review:'Revisa los puntos señalados antes de empezar.',tabletCheck:'Ejecuta Event Ready en las tabletas para confirmar el hardware.',recent:'Actividad reciente',events:'Ver eventos',help:'Ayuda & mensajes',ready:'LISTO',attention:'REVISAR',blocked:'ACCIÓN NECESARIA',online:'conectada(s)',pending:'pendientes',failed:'con error',open:'conversación(es) abierta(s)',today:'Hoy',tomorrow:'Mañana'},
pt:{title:'Hoje no KHE Booth',subtitle:'O essencial para preparar e operar o próximo evento.',create:'Criar evento',clients:'Clientes',next:'Próximo evento',noNext:'Não existem próximos eventos.',eventReady:'Abrir Event Ready',stations:'Estações',media:'Conteúdos por sincronizar',messages:'Mensagens',allGood:'Os controlos do servidor estão prontos. Execute a verificação de hardware nos tablets.',connectCapture:'Ligue a estação CAPTURE.',connectSharing:'Ligue a estação SHARING.',rescueSync:'Corrija a sincronização antes do evento.',review:'Verifique os pontos assinalados antes de começar.',tabletCheck:'Execute Event Ready nos tablets para confirmar o hardware.',recent:'Atividade recente',events:'Ver eventos',help:'Ajuda & mensagens',ready:'PRONTO',attention:'VERIFICAR',blocked:'AÇÃO NECESSÁRIA',online:'ligada(s)',pending:'pendentes',failed:'com erro',open:'conversa(s) aberta(s)',today:'Hoje',tomorrow:'Amanhã'}
};
function readLanguage():Language{if(typeof window==='undefined')return'fr';const value=window.localStorage.getItem('khe.web.language');return value&&value in TEXT?value as Language:'fr';}
function stateStyle(state?:Readiness['state']){if(state==='READY')return{color:'#93e5af',border:'rgba(90,205,126,.3)',background:'rgba(48,164,92,.12)'};if(state==='BLOCKED')return{color:'#ffaaaa',border:'rgba(211,72,72,.35)',background:'rgba(211,72,72,.12)'};return{color:'#f0cf78',border:'rgba(219,169,51,.35)',background:'rgba(219,169,51,.12)'};}
export default function DashboardPage(){
 const[language,setLanguage]=useState<Language>('fr');const[clients,setClients]=useState<Client[]>([]);const[events,setEvents]=useState<EventItem[]>([]);const[readiness,setReadiness]=useState<Readiness|null>(null);const[conversations,setConversations]=useState<Conversation[]>([]);const[error,setError]=useState('');const t=TEXT[language];const locale=language==='fr'?'fr-CH':language;
 useEffect(()=>{setLanguage(readLanguage());const h=(event:Event)=>{const detail=(event as CustomEvent<string>).detail;if(detail&&detail in TEXT)setLanguage(detail as Language);};window.addEventListener('khe-language-changed',h);Promise.all([apiRequest<Client[]>('/clients'),apiRequest<EventItem[]>('/events'),apiRequest<Conversation[]>('/support/conversations/me').catch(()=>[])]).then(async([clientItems,eventItems,conversationItems])=>{setClients(clientItems);setEvents(eventItems);setConversations(conversationItems);const nextEvent=eventItems.filter(item=>new Date(item.startsAt).getTime()>=Date.now()).sort((a,b)=>new Date(a.startsAt).getTime()-new Date(b.startsAt).getTime())[0];if(nextEvent){try{setReadiness(await apiRequest<Readiness>(`/events/${nextEvent.id}/readiness`));}catch{setReadiness(null);}}}).catch(caught=>setError(caught instanceof Error?caught.message:'Unable to load dashboard'));return()=>window.removeEventListener('khe-language-changed',h);},[]);
 const upcoming=useMemo(()=>events.filter(item=>new Date(item.startsAt).getTime()>=Date.now()).sort((a,b)=>new Date(a.startsAt).getTime()-new Date(b.startsAt).getTime()),[events]);const nextEvent=upcoming[0]??null;const activeConversations=conversations.filter(item=>item.status!=='RESOLVED').length;const onlineStations=readiness?.stations.filter(item=>item.online).length??0;
 const action=readiness?.recommendedAction==='CONNECT_CAPTURE'?t.connectCapture:readiness?.recommendedAction==='CONNECT_SHARING'?t.connectSharing:readiness?.recommendedAction==='RESCUE_SYNC'?t.rescueSync:readiness?.recommendedAction==='REVIEW_WARNINGS'?t.review:readiness?t.tabletCheck:t.allGood;const stateLabel=readiness?.state==='READY'?t.ready:readiness?.state==='BLOCKED'?t.blocked:t.attention;
 return <PortalShell><div style={{display:'grid',gap:20}}>
  <header style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',gap:16,flexWrap:'wrap'}}><div><div className="muted" style={{fontSize:12,fontWeight:900,letterSpacing:'.14em'}}>KHE BOOTH / COMMAND CENTER</div><h1 style={{fontSize:'clamp(28px,5vw,44px)',margin:'7px 0'}}>{t.title}</h1><p className="muted" style={{margin:0,maxWidth:650}}>{t.subtitle}</p></div><Link className="button" href="/events/new">{t.create}</Link></header>
  {error?<p className="error">{error}</p>:null}
  {nextEvent?<section className="card" style={{padding:26,border:'1px solid rgba(210,173,79,.3)',background:'radial-gradient(circle at 90% 0%,rgba(210,173,79,.16),transparent 34%),linear-gradient(145deg,#131920,#0c1015)'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',gap:16,flexWrap:'wrap'}}><div><div className="muted" style={{fontWeight:900,fontSize:12,letterSpacing:'.1em'}}>{t.next.toUpperCase()}</div><h2 style={{fontSize:28,margin:'8px 0 4px'}}>{nextEvent.name}</h2><div className="muted">{new Date(nextEvent.startsAt).toLocaleString(locale)}{nextEvent.venueName?` · ${nextEvent.venueName}`:''}</div></div>{readiness?<span style={{padding:'10px 14px',borderRadius:999,fontSize:12,fontWeight:900,border:`1px solid ${stateStyle(readiness.state).border}`,background:stateStyle(readiness.state).background,color:stateStyle(readiness.state).color}}>{stateLabel}</span>:null}</div><div style={{marginTop:22,padding:16,borderRadius:18,background:'rgba(255,255,255,.035)',border:'1px solid rgba(255,255,255,.07)'}}><strong>{action}</strong>{readiness?.alerts[0]?<div className="muted" style={{marginTop:6}}>{readiness.alerts[0].message}</div>:null}</div><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:18}}><Link className="button" href={`/events/${nextEvent.id}/ready`}>{t.eventReady}</Link><Link className="button secondary" href={`/events/${nextEvent.id}`}>{nextEvent.name}</Link></div></section>:<section className="card"><h2>{t.next}</h2><div className="empty">{t.noNext}</div></section>}
  <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12}}><article className="card" style={{minHeight:132}}><div className="muted">{t.stations}</div><div style={{fontSize:34,fontWeight:900,marginTop:10}}>{onlineStations}<span className="muted" style={{fontSize:14,fontWeight:600}}> / {readiness?.stations.length??0}</span></div><div className="muted" style={{fontSize:12}}>{t.online}</div></article><article className="card" style={{minHeight:132}}><div className="muted">{t.media}</div><div style={{fontSize:34,fontWeight:900,marginTop:10}}>{readiness?.media.pending??0}</div><div className="muted" style={{fontSize:12}}>{readiness?.media.failed??0} {t.failed}</div></article><article className="card" style={{minHeight:132}}><div className="muted">{t.messages}</div><div style={{fontSize:34,fontWeight:900,marginTop:10}}>{activeConversations}</div><div className="muted" style={{fontSize:12}}>{t.open}</div></article><article className="card" style={{minHeight:132}}><div className="muted">{t.clients}</div><div style={{fontSize:34,fontWeight:900,marginTop:10}}>{clients.length}</div><div style={{marginTop:8}}><Link href="/clients" className="muted">{t.clients} →</Link></div></article></section>
  <section className="card"><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><h2 style={{margin:'0 0 5px'}}>{t.recent}</h2><div className="muted">{upcoming.slice(1,4).map(item=>item.name).join(' · ')||t.noNext}</div></div><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><Link href="/events" className="button secondary">{t.events}</Link><Link href="/help" className="button secondary">{t.help}</Link></div></div></section>
 </div></PortalShell>;
}
