import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import type { AuthenticatedUser } from '../auth/auth.types';
import { PrismaService } from '../prisma/prisma.service';

type LivePolicy={organizationId:string;enabled:boolean;startEarlyMinutes:number;startGraceMinutes:number;noShowAlertMinutes:number;autoCloseMinutes:number;requireActiveShiftForRouting:boolean;updatedAt:Date};
type LiveShift={id:string;organizationId:string;userId:string;startsAt:Date;endsAt:Date;status:string;confirmationStatus:string;liveStatus:string;actualStartedAt:Date|null;actualEndedAt:Date|null;pauseStartedAt:Date|null;pausedSeconds:number;lastLiveActionAt:Date|null;agentEmail:string;agentFirstName:string|null;agentLastName:string|null};

@Injectable()
export class LiveShiftService{
  constructor(private readonly prisma:PrismaService){}
  private number(value:unknown,min:number,max:number,fallback:number){const n=Math.trunc(Number(value));return Number.isFinite(n)?Math.min(max,Math.max(min,n)):fallback;}
  private name(v:{agentEmail:string;agentFirstName?:string|null;agentLastName?:string|null}){return[v.agentFirstName,v.agentLastName].filter(Boolean).join(' ')||v.agentEmail;}

  async policy(organizationId:string):Promise<LivePolicy>{await this.prisma.$executeRaw`INSERT INTO "LiveShiftPolicy" ("organizationId") VALUES (${organizationId}::uuid) ON CONFLICT ("organizationId") DO NOTHING`;const rows=await this.prisma.$queryRaw<LivePolicy[]>`SELECT * FROM "LiveShiftPolicy" WHERE "organizationId"=${organizationId}::uuid LIMIT 1`;return rows[0];}
  async updatePolicy(organizationId:string,body:Record<string,unknown>){const current=await this.policy(organizationId);const early=this.number(body.startEarlyMinutes,0,180,current.startEarlyMinutes),grace=this.number(body.startGraceMinutes,0,180,current.startGraceMinutes),noShow=this.number(body.noShowAlertMinutes,1,180,current.noShowAlertMinutes),autoClose=this.number(body.autoCloseMinutes,0,240,current.autoCloseMinutes);await this.prisma.$executeRaw`UPDATE "LiveShiftPolicy" SET enabled=${body.enabled!==false},"startEarlyMinutes"=${early},"startGraceMinutes"=${grace},"noShowAlertMinutes"=${noShow},"autoCloseMinutes"=${autoClose},"requireActiveShiftForRouting"=${body.requireActiveShiftForRouting===true},"updatedAt"=CURRENT_TIMESTAMP WHERE "organizationId"=${organizationId}::uuid`;return this.policy(organizationId);}

  private async shift(organizationId:string,id:string){const rows=await this.prisma.$queryRaw<LiveShift[]>`SELECT s.id,s."organizationId",s."userId",s."startsAt",s."endsAt",s.status,s."confirmationStatus",s."liveStatus",s."actualStartedAt",s."actualEndedAt",s."pauseStartedAt",s."pausedSeconds",s."lastLiveActionAt",u.email "agentEmail",u."firstName" "agentFirstName",u."lastName" "agentLastName" FROM "AgentWorkShift" s JOIN "User" u ON u.id=s."userId" WHERE s.id=${id}::uuid AND s."organizationId"=${organizationId}::uuid LIMIT 1`;return rows[0];}
  private async event(organizationId:string,shiftId:string,userId:string,action:string,metadata:Record<string,unknown>={}){await this.prisma.$executeRaw`INSERT INTO "AgentWorkShiftLiveEvent" ("organizationId","shiftId","userId",action,metadata) VALUES (${organizationId}::uuid,${shiftId}::uuid,${userId}::uuid,${action},${JSON.stringify(metadata)}::jsonb)`;}
  private async syncPresence(userId:string,state:'ACTIVE'|'PAUSED'|'ENDED'){if(state==='ACTIVE')await this.prisma.$executeRaw`UPDATE "AgentPresence" SET availability='AVAILABLE',"acceptingAssignments"=TRUE,"availableSince"=COALESCE("availableSince",CURRENT_TIMESTAMP),"updatedAt"=CURRENT_TIMESTAMP WHERE "userId"=${userId}::uuid`;else if(state==='PAUSED')await this.prisma.$executeRaw`UPDATE "AgentPresence" SET availability='AWAY',"acceptingAssignments"=FALSE,"updatedAt"=CURRENT_TIMESTAMP WHERE "userId"=${userId}::uuid`;else await this.prisma.$executeRaw`UPDATE "AgentPresence" SET availability='UNAVAILABLE',"acceptingAssignments"=FALSE,"availableSince"=NULL,"updatedAt"=CURRENT_TIMESTAMP WHERE "userId"=${userId}::uuid`;}
  private async notifyManagers(organizationId:string,title:string,body:string){const managers=await this.prisma.$queryRaw<Array<{id:string}>>`SELECT id FROM "User" WHERE "organizationId"=${organizationId}::uuid AND "isActive"=TRUE AND role IN ('OWNER','ADMIN')`;for(const m of managers)await this.prisma.$executeRaw`INSERT INTO "AgentWorkforceNotice" ("organizationId","userId",kind,title,body,"actionUrl") VALUES (${organizationId}::uuid,${m.id}::uuid,'LIVE_SHIFT',${title},${body},'/operations/workforce/live/team')`;}

  async compact(user:AuthenticatedUser){const rows=await this.prisma.$queryRaw<any[]>`SELECT id,"startsAt","endsAt","liveStatus","confirmationStatus","actualStartedAt","pauseStartedAt" FROM "AgentWorkShift" WHERE "organizationId"=${user.organizationId}::uuid AND "userId"=${user.id}::uuid AND ((status='PLANNED' AND "endsAt">CURRENT_TIMESTAMP-INTERVAL '30 minutes') OR "liveStatus" IN ('ACTIVE','PAUSED')) ORDER BY CASE WHEN "liveStatus" IN ('ACTIVE','PAUSED') THEN 0 ELSE 1 END,"startsAt" ASC LIMIT 1`;return{shift:rows[0]??null,policy:await this.policy(user.organizationId)};}

  async mine(user:AuthenticatedUser){const shifts=await this.prisma.$queryRaw<any[]>`SELECT s.id,s."startsAt",s."endsAt",s.status,s."confirmationStatus",s."liveStatus",s."actualStartedAt",s."actualEndedAt",s."pauseStartedAt",s."pausedSeconds",s."lastLiveActionAt",COALESCE(ps.languages,ARRAY[]::text[]) languages,COALESCE(ps.skills,ARRAY[]::text[]) skills FROM "AgentWorkShift" s LEFT JOIN "WorkforceScheduleProposalShift" ps ON ps.id=s."proposalShiftId" WHERE s."organizationId"=${user.organizationId}::uuid AND s."userId"=${user.id}::uuid AND s."endsAt">CURRENT_TIMESTAMP-INTERVAL '1 day' AND s."startsAt"<CURRENT_TIMESTAMP+INTERVAL '14 days' ORDER BY s."startsAt" ASC`;const events=await this.prisma.$queryRaw<any[]>`SELECT e.id,e."shiftId",e.action,e.metadata,e."createdAt" FROM "AgentWorkShiftLiveEvent" e WHERE e."organizationId"=${user.organizationId}::uuid AND e."userId"=${user.id}::uuid ORDER BY e."createdAt" DESC LIMIT 50`;const active=shifts.find(s=>['ACTIVE','PAUSED'].includes(s.liveStatus));return{policy:await this.policy(user.organizationId),summary:{active:shifts.filter(s=>s.liveStatus==='ACTIVE').length,paused:shifts.filter(s=>s.liveStatus==='PAUSED').length,scheduled:shifts.filter(s=>s.status==='PLANNED'&&s.liveStatus==='SCHEDULED').length,missed:shifts.filter(s=>s.liveStatus==='MISSED').length},activeShift:active??null,shifts,events};}

  async start(user:AuthenticatedUser,id:string){const shift=await this.shift(user.organizationId,id);if(!shift||shift.userId!==user.id)throw new NotFoundException('Shift introuvable');if(shift.status!=='PLANNED'||shift.confirmationStatus!=='ACCEPTED')throw new BadRequestException('Le shift doit être planifié et accepté avant démarrage');if(!['SCHEDULED','MISSED'].includes(shift.liveStatus))throw new BadRequestException('Ce shift est déjà démarré ou terminé');const policy=await this.policy(user.organizationId);const now=new Date();if(now.getTime()<new Date(shift.startsAt).getTime()-policy.startEarlyMinutes*60000)throw new BadRequestException(`Le shift peut être démarré au maximum ${policy.startEarlyMinutes} min avant l’heure prévue`);if(now>=new Date(shift.endsAt))throw new BadRequestException('Ce shift est déjà terminé');const late=now.getTime()>new Date(shift.startsAt).getTime()+policy.startGraceMinutes*60000;await this.prisma.$transaction(async tx=>{await tx.$executeRaw`UPDATE "AgentWorkShift" SET "liveStatus"='ACTIVE',"actualStartedAt"=COALESCE("actualStartedAt",CURRENT_TIMESTAMP),"pauseStartedAt"=NULL,"lastLiveActionAt"=CURRENT_TIMESTAMP,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${id}::uuid`;await tx.$executeRaw`UPDATE "LiveShiftAlert" SET status='RESOLVED',"resolvedAt"=CURRENT_TIMESTAMP,"updatedAt"=CURRENT_TIMESTAMP WHERE "shiftId"=${id}::uuid AND type='NO_SHOW' AND status<>'RESOLVED'`;});await this.event(user.organizationId,id,user.id,'START',{late});await this.syncPresence(user.id,'ACTIVE');if(late)await this.notifyManagers(user.organizationId,'Shift démarré en retard',`${this.name(shift)} a démarré son shift après la marge prévue. KHE n’applique aucune sanction automatique.`);await this.prisma.auditLog.create({data:{organizationId:user.organizationId,userId:user.id,action:'WORKFORCE_LIVE_SHIFT_START',entityType:'AgentWorkShift',entityId:id,metadata:{late}}});return this.shift(user.organizationId,id);}

  async pause(user:AuthenticatedUser,id:string){const shift=await this.shift(user.organizationId,id);if(!shift||shift.userId!==user.id)throw new NotFoundException('Shift introuvable');if(shift.liveStatus!=='ACTIVE')throw new BadRequestException('Seul un shift actif peut être mis en pause');await this.prisma.$executeRaw`UPDATE "AgentWorkShift" SET "liveStatus"='PAUSED',"pauseStartedAt"=CURRENT_TIMESTAMP,"lastLiveActionAt"=CURRENT_TIMESTAMP,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${id}::uuid`;await this.event(user.organizationId,id,user.id,'PAUSE');await this.syncPresence(user.id,'PAUSED');return this.shift(user.organizationId,id);}
  async resume(user:AuthenticatedUser,id:string){const shift=await this.shift(user.organizationId,id);if(!shift||shift.userId!==user.id)throw new NotFoundException('Shift introuvable');if(shift.liveStatus!=='PAUSED'||!shift.pauseStartedAt)throw new BadRequestException('Ce shift n’est pas en pause');await this.prisma.$executeRaw`UPDATE "AgentWorkShift" SET "liveStatus"='ACTIVE',"pausedSeconds"="pausedSeconds"+GREATEST(0,EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP-"pauseStartedAt"))::int),"pauseStartedAt"=NULL,"lastLiveActionAt"=CURRENT_TIMESTAMP,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${id}::uuid`;await this.event(user.organizationId,id,user.id,'RESUME');await this.syncPresence(user.id,'ACTIVE');return this.shift(user.organizationId,id);}
  async end(user:AuthenticatedUser,id:string){const shift=await this.shift(user.organizationId,id);if(!shift||shift.userId!==user.id)throw new NotFoundException('Shift introuvable');if(!['ACTIVE','PAUSED'].includes(shift.liveStatus))throw new BadRequestException('Aucun shift actif à terminer');await this.prisma.$executeRaw`UPDATE "AgentWorkShift" SET status='COMPLETED',"liveStatus"='COMPLETED',"actualEndedAt"=CURRENT_TIMESTAMP,"pausedSeconds"="pausedSeconds"+CASE WHEN "pauseStartedAt" IS NULL THEN 0 ELSE GREATEST(0,EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP-"pauseStartedAt"))::int) END,"pauseStartedAt"=NULL,"lastLiveActionAt"=CURRENT_TIMESTAMP,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${id}::uuid`;await this.event(user.organizationId,id,user.id,'END');await this.syncPresence(user.id,'ENDED');await this.prisma.auditLog.create({data:{organizationId:user.organizationId,userId:user.id,action:'WORKFORCE_LIVE_SHIFT_END',entityType:'AgentWorkShift',entityId:id}});return this.shift(user.organizationId,id);}

  async team(user:AuthenticatedUser){const policy=await this.policy(user.organizationId);const shifts=await this.prisma.$queryRaw<any[]>`SELECT s.id,s."userId",s."startsAt",s."endsAt",s.status,s."confirmationStatus",s."liveStatus",s."actualStartedAt",s."actualEndedAt",s."pauseStartedAt",s."pausedSeconds",u.email,u."firstName",u."lastName" FROM "AgentWorkShift" s JOIN "User" u ON u.id=s."userId" WHERE s."organizationId"=${user.organizationId}::uuid AND s."endsAt">CURRENT_TIMESTAMP-INTERVAL '2 hours' AND s."startsAt"<CURRENT_TIMESTAMP+INTERVAL '24 hours' ORDER BY s."startsAt" ASC`;const alerts=await this.prisma.$queryRaw<any[]>`SELECT a.*,u.email,u."firstName",u."lastName",s."startsAt",s."endsAt" FROM "LiveShiftAlert" a JOIN "AgentWorkShift" s ON s.id=a."shiftId" JOIN "User" u ON u.id=s."userId" WHERE a."organizationId"=${user.organizationId}::uuid AND a.status<>'RESOLVED' ORDER BY a."createdAt" DESC`;return{policy,summary:{active:shifts.filter(s=>s.liveStatus==='ACTIVE').length,paused:shifts.filter(s=>s.liveStatus==='PAUSED').length,scheduled:shifts.filter(s=>s.liveStatus==='SCHEDULED'&&s.status==='PLANNED').length,missed:shifts.filter(s=>s.liveStatus==='MISSED').length,openAlerts:alerts.length},shifts:shifts.map(s=>({...s,agentName:[s.firstName,s.lastName].filter(Boolean).join(' ')||s.email})),alerts};}
  async acknowledge(user:AuthenticatedUser,id:string){const rows=await this.prisma.$queryRaw<Array<{id:string}>>`UPDATE "LiveShiftAlert" SET status='ACKNOWLEDGED',"acknowledgedByUserId"=${user.id}::uuid,"acknowledgedAt"=CURRENT_TIMESTAMP,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${id}::uuid AND "organizationId"=${user.organizationId}::uuid AND status='OPEN' RETURNING id`;if(!rows.length)throw new NotFoundException('Alerte introuvable');return{ok:true};}

  async pulse(user:AuthenticatedUser){const policy=await this.policy(user.organizationId);if(!policy.enabled)return{enabled:false,noShowAlerts:0,autoClosed:0,missed:0};const noShow=await this.prisma.$queryRaw<Array<{id:string;agentEmail:string;agentFirstName:string|null;agentLastName:string|null}>>`SELECT s.id,u.email "agentEmail",u."firstName" "agentFirstName",u."lastName" "agentLastName" FROM "AgentWorkShift" s JOIN "User" u ON u.id=s."userId" WHERE s."organizationId"=${user.organizationId}::uuid AND s.status='PLANNED' AND s."confirmationStatus"='ACCEPTED' AND s."liveStatus"='SCHEDULED' AND s."startsAt"<=CURRENT_TIMESTAMP-${policy.noShowAlertMinutes}*INTERVAL '1 minute' AND s."endsAt">CURRENT_TIMESTAMP AND NOT EXISTS(SELECT 1 FROM "LiveShiftAlert" a WHERE a."shiftId"=s.id AND a.type='NO_SHOW')`;for(const s of noShow){await this.prisma.$executeRaw`INSERT INTO "LiveShiftAlert" ("organizationId","shiftId",type,severity) VALUES (${user.organizationId}::uuid,${s.id}::uuid,'NO_SHOW','HIGH') ON CONFLICT ("shiftId",type) DO NOTHING`;await this.notifyManagers(user.organizationId,'Agent confirmé non démarré',`${this.name(s)} n’a pas démarré son shift après la marge de ${policy.noShowAlertMinutes} min. Vérifiez la couverture et utilisez le remplacement seulement si nécessaire.`);}
    const missed=await this.prisma.$queryRaw<Array<{id:string;userId:string}>>`UPDATE "AgentWorkShift" SET status='COMPLETED',"liveStatus"='MISSED',"actualEndedAt"=COALESCE("actualEndedAt","endsAt"),"lastLiveActionAt"=CURRENT_TIMESTAMP,"updatedAt"=CURRENT_TIMESTAMP WHERE "organizationId"=${user.organizationId}::uuid AND status='PLANNED' AND "liveStatus"='SCHEDULED' AND "endsAt"<=CURRENT_TIMESTAMP RETURNING id,"userId"`;for(const s of missed)await this.event(user.organizationId,s.id,s.userId,'MISSED');
    const autoClosed=await this.prisma.$queryRaw<Array<{id:string;userId:string}>>`UPDATE "AgentWorkShift" SET status='COMPLETED',"liveStatus"='COMPLETED',"actualEndedAt"=COALESCE("actualEndedAt","endsAt"),"pausedSeconds"="pausedSeconds"+CASE WHEN "pauseStartedAt" IS NULL THEN 0 ELSE GREATEST(0,EXTRACT(EPOCH FROM ("endsAt"-"pauseStartedAt"))::int) END,"pauseStartedAt"=NULL,"lastLiveActionAt"=CURRENT_TIMESTAMP,"updatedAt"=CURRENT_TIMESTAMP WHERE "organizationId"=${user.organizationId}::uuid AND status='PLANNED' AND "liveStatus" IN ('ACTIVE','PAUSED') AND "endsAt"+${policy.autoCloseMinutes}*INTERVAL '1 minute'<=CURRENT_TIMESTAMP RETURNING id,"userId"`;for(const s of autoClosed){await this.event(user.organizationId,s.id,s.userId,'AUTO_END');await this.syncPresence(s.userId,'ENDED');}
    return{enabled:true,noShowAlerts:noShow.length,autoClosed:autoClosed.length,missed:missed.length};}
}
