import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { NotificationKind } from '@prisma/client';
import type { AuthenticatedUser } from '../auth/auth.types';
import { PrismaService } from '../prisma/prisma.service';

type ConversationRow={id:string;subject:string;status:string;assignedToUserId:string|null;requesterUserId:string;priority:string;routingTopic:string;requestedLanguage:string;customerTier:string;lastMessageAt:Date};
type CandidateRow={id:string;email:string;firstName:string|null;lastName:string|null;role:string;skills:string[];languages:string[];activeConversations:number;activeTasks:number;pendingHandovers:number;maxConversations:number;maxTasks:number;priorityBias:number;averageRating:number;resolvedCount:number};

@Injectable()
export class ShiftHandoverService{
  constructor(private readonly prisma:PrismaService){}

  private note(value:unknown,max=500){return String(value??'').trim().slice(0,max)||null;}
  private name(v:{email:string;firstName?:string|null;lastName?:string|null}){return[v.firstName,v.lastName].filter(Boolean).join(' ')||v.email;}
  private async notifyUser(organizationId:string,userId:string,kind:'SYSTEM'|'ASSIGNMENT'|'MANAGER',title:string,body:string,actionUrl:string){await this.prisma.$executeRaw`INSERT INTO "AgentWorkforceNotice" ("organizationId","userId",kind,title,body,"actionUrl") VALUES (${organizationId}::uuid,${userId}::uuid,${kind},${title},${body},${actionUrl})`;}
  private async notifyManagers(organizationId:string,title:string,body:string){const managers=await this.prisma.$queryRaw<Array<{id:string}>>`SELECT id FROM "User" WHERE "organizationId"=${organizationId}::uuid AND "isActive"=TRUE AND role IN ('OWNER','ADMIN')`;for(const manager of managers)await this.notifyUser(organizationId,manager.id,'MANAGER',title,body,'/operations/workforce/handover');}

  private async conversation(organizationId:string,id:string){const rows=await this.prisma.$queryRaw<ConversationRow[]>`SELECT id,subject,status::text status,"assignedToUserId","requesterUserId",COALESCE(priority,'NORMAL') priority,COALESCE("routingTopic",'GENERAL') "routingTopic",COALESCE("requestedLanguage",'fr') "requestedLanguage",COALESCE("customerTier",'STANDARD') "customerTier","lastMessageAt" FROM "SupportConversation" WHERE id=${id}::uuid AND "organizationId"=${organizationId}::uuid LIMIT 1`;return rows[0];}

  private async candidatesForConversation(organizationId:string,conversationId:string,fromUserId:string){
    const conversation=await this.conversation(organizationId,conversationId);if(!conversation)return[];
    const rows=await this.prisma.$queryRaw<CandidateRow[]>`
      WITH candidates AS (
        SELECT u.id,u.email,u."firstName",u."lastName",u.role::text role,
          COALESCE(rp.skills,ARRAY[]::text[]) skills,COALESCE(rp.languages,ARRAY['fr']::text[]) languages,
          COALESCE(rp."maxActiveConversations",5)::int "maxConversations",COALESCE(rp."maxActiveTasks",15)::int "maxTasks",COALESCE(rp."priorityBias",0)::int "priorityBias",
          (SELECT count(*)::int FROM "SupportConversation" c WHERE c."assignedToUserId"=u.id AND c.status<>'RESOLVED') "activeConversations",
          (SELECT count(*)::int FROM "SupportTask" t WHERE t."assignedToUserId"=u.id AND t.status<>'DONE') "activeTasks",
          (SELECT count(*)::int FROM "ShiftHandoverItem" h WHERE h."suggestedUserId"=u.id AND h.status='PENDING') "pendingHandovers",
          COALESCE((SELECT avg(f.rating)::float8 FROM "SupportFeedback" f WHERE f."agentUserId"=u.id),4.0) "averageRating",
          COALESCE((SELECT count(*)::int FROM "SupportConversation" rc WHERE rc."assignedToUserId"=u.id AND rc.status='RESOLVED'),0) "resolvedCount"
        FROM "User" u
        JOIN "AgentPresence" p ON p."userId"=u.id
        LEFT JOIN "AgentRoutingProfile" rp ON rp."userId"=u.id
        WHERE u."organizationId"=${organizationId}::uuid AND u."isActive"=TRUE AND u.role IN ('OWNER','ADMIN','OPERATOR') AND u.id<>${fromUserId}::uuid
          AND COALESCE(rp.enabled,TRUE)=TRUE AND p.availability='AVAILABLE' AND p."acceptingAssignments"=TRUE AND p."lastHeartbeatAt">CURRENT_TIMESTAMP-INTERVAL '90 seconds'
          AND EXISTS(SELECT 1 FROM "AgentWorkShift" s WHERE s."organizationId"=${organizationId}::uuid AND s."userId"=u.id AND s.status='PLANNED' AND s."liveStatus"='ACTIVE')
          AND NOT EXISTS(SELECT 1 FROM "AgentAvailabilityBlock" b WHERE b."userId"=u.id AND b.status='ACTIVE' AND b."startsAt"<CURRENT_TIMESTAMP+INTERVAL '5 minutes' AND b."endsAt">CURRENT_TIMESTAMP)
      ) SELECT * FROM candidates WHERE "activeConversations"<"maxConversations" AND "activeTasks"<"maxTasks"`;
    const topic=String(conversation.routingTopic||'GENERAL').toUpperCase(),language=String(conversation.requestedLanguage||'fr').toLowerCase(),priority=String(conversation.priority||'NORMAL').toUpperCase();
    return rows.map(row=>{const skills=(row.skills??[]).map(x=>x.toUpperCase()),languages=(row.languages??[]).map(x=>x.toLowerCase());const skillMatch=topic==='GENERAL'||skills.includes(topic);const languageMatch=languages.includes(language);let score=row.activeConversations*100+row.activeTasks*10+row.pendingHandovers*25+(skillMatch?0:60)+(languageMatch?0:40)+Math.round((5-Number(row.averageRating||4))*8)-Math.min(20,Math.floor((row.resolvedCount||0)/5))-(row.priorityBias||0);if(priority==='CRITICAL'&&skillMatch)score-=20;if(row.role==='OPERATOR')score-=8;else if(row.role==='ADMIN')score-=4;return{...row,name:this.name(row),score,skillMatch,languageMatch,reason:`${skillMatch?'compétence adaptée':'compétence générale'} · ${languageMatch?`langue ${language}`:`langue ${language} non couverte`} · ${row.activeConversations}/${row.maxConversations} conversation(s) active(s) · ${row.pendingHandovers} relais en attente`};}).sort((a,b)=>a.score-b.score||a.activeConversations-b.activeConversations||a.email.localeCompare(b.email));
  }

  async prepareForShift(organizationId:string,shiftId:string,fromUserId:string,trigger:'MANUAL_END'|'CATCH_UP'='CATCH_UP'){
    const shifts=await this.prisma.$queryRaw<Array<{id:string;userId:string;status:string;liveStatus:string}>>`SELECT id,"userId",status,"liveStatus" FROM "AgentWorkShift" WHERE id=${shiftId}::uuid AND "organizationId"=${organizationId}::uuid AND "userId"=${fromUserId}::uuid LIMIT 1`;
    if(!shifts[0]||shifts[0].status!=='COMPLETED')return null;
    const inserted=await this.prisma.$queryRaw<Array<{id:string}>>`INSERT INTO "ShiftHandoverBatch" ("organizationId","shiftId","fromUserId",trigger) VALUES (${organizationId}::uuid,${shiftId}::uuid,${fromUserId}::uuid,${trigger}) ON CONFLICT ("shiftId") DO NOTHING RETURNING id`;
    if(!inserted.length){const existing=await this.prisma.$queryRaw<Array<{id:string}>>`SELECT id FROM "ShiftHandoverBatch" WHERE "shiftId"=${shiftId}::uuid LIMIT 1`;return existing[0]?this.batchDetail(organizationId,existing[0].id):null;}
    const batchId=inserted[0].id;
    const conversations=await this.prisma.$queryRaw<ConversationRow[]>`SELECT id,subject,status::text status,"assignedToUserId","requesterUserId",COALESCE(priority,'NORMAL') priority,COALESCE("routingTopic",'GENERAL') "routingTopic",COALESCE("requestedLanguage",'fr') "requestedLanguage",COALESCE("customerTier",'STANDARD') "customerTier","lastMessageAt" FROM "SupportConversation" WHERE "organizationId"=${organizationId}::uuid AND "assignedToUserId"=${fromUserId}::uuid AND status<>'RESOLVED' ORDER BY CASE priority WHEN 'CRITICAL' THEN 0 WHEN 'HIGH' THEN 1 WHEN 'NORMAL' THEN 2 ELSE 3 END,"lastMessageAt" DESC`;
    for(const conversation of conversations){const candidates=await this.candidatesForConversation(organizationId,conversation.id,fromUserId);const suggested=candidates[0]??null;const snapshot={subject:conversation.subject,priority:conversation.priority,topic:conversation.routingTopic,language:conversation.requestedLanguage,customerTier:conversation.customerTier,lastMessageAt:conversation.lastMessageAt};await this.prisma.$executeRaw`INSERT INTO "ShiftHandoverItem" ("batchId","organizationId","conversationId","fromUserId","suggestedUserId",score,reason,snapshot) VALUES (${batchId}::uuid,${organizationId}::uuid,${conversation.id}::uuid,${fromUserId}::uuid,${suggested?.id??null}::uuid,${suggested?.score??null},${suggested?.reason??'Aucun agent actuellement en service et éligible'},${JSON.stringify(snapshot)}::jsonb) ON CONFLICT ("batchId","conversationId") DO NOTHING`;}
    await this.prisma.$executeRaw`UPDATE "ShiftHandoverBatch" SET "openConversationCount"=${conversations.length},status=${conversations.length?'DRAFT':'COMPLETED'},"completedAt"=${conversations.length?null:new Date()},"updatedAt"=CURRENT_TIMESTAMP WHERE id=${batchId}::uuid`;
    if(conversations.length){await this.notifyManagers(organizationId,'Passage de relais à valider',`${conversations.length} conversation(s) ouverte(s) restent attribuées à un agent dont le shift est terminé. KHE a préparé des suggestions sans transférer automatiquement.`);await this.notifyUser(organizationId,fromUserId,'SYSTEM','Passage de relais préparé',`${conversations.length} conversation(s) ouverte(s) ont été ajoutées au passage de relais. Vous pouvez ajouter une note opérationnelle pour aider le prochain agent.`,'/operations/workforce/handover/me');}
    return this.batchDetail(organizationId,batchId);
  }

  private group(rows:any[]){const map=new Map<string,any>();for(const row of rows){let batch=map.get(row.batchId);if(!batch){batch={id:row.batchId,status:row.batchStatus,trigger:row.trigger,openConversationCount:row.openConversationCount,preparedAt:row.preparedAt,completedAt:row.completedAt,createdAt:row.batchCreatedAt,shiftId:row.shiftId,shiftStartsAt:row.shiftStartsAt,shiftEndsAt:row.shiftEndsAt,fromUserId:row.fromUserId,fromAgentName:this.name({email:row.fromEmail,firstName:row.fromFirstName,lastName:row.fromLastName}),items:[]};map.set(row.batchId,batch);}if(row.itemId)batch.items.push({id:row.itemId,status:row.itemStatus,conversationId:row.conversationId,subject:row.subject,conversationStatus:row.conversationStatus,currentAssignedToUserId:row.currentAssignedToUserId,priority:row.priority,routingTopic:row.routingTopic,requestedLanguage:row.requestedLanguage,lastMessageAt:row.lastMessageAt,suggestedUserId:row.suggestedUserId,suggestedAgentName:row.suggestedEmail?this.name({email:row.suggestedEmail,firstName:row.suggestedFirstName,lastName:row.suggestedLastName}):null,selectedUserId:row.selectedUserId,selectedAgentName:row.selectedEmail?this.name({email:row.selectedEmail,firstName:row.selectedFirstName,lastName:row.selectedLastName}):null,score:row.score,reason:row.reason,agentNote:row.agentNote,managerNote:row.managerNote,snapshot:row.snapshot,appliedAt:row.appliedAt});}return[...map.values()];}

  private async batchDetail(organizationId:string,batchId:string){const rows=await this.prisma.$queryRaw<any[]>`SELECT b.id "batchId",b.status "batchStatus",b.trigger,b."openConversationCount",b."preparedAt",b."completedAt",b."createdAt" "batchCreatedAt",b."shiftId",b."fromUserId",s."startsAt" "shiftStartsAt",s."endsAt" "shiftEndsAt",fu.email "fromEmail",fu."firstName" "fromFirstName",fu."lastName" "fromLastName",i.id "itemId",i.status "itemStatus",i."conversationId",i."suggestedUserId",i."selectedUserId",i.score,i.reason,i."agentNote",i."managerNote",i.snapshot,i."appliedAt",c.subject,c.status::text "conversationStatus",c."assignedToUserId" "currentAssignedToUserId",c.priority,c."routingTopic",c."requestedLanguage",c."lastMessageAt",su.email "suggestedEmail",su."firstName" "suggestedFirstName",su."lastName" "suggestedLastName",sel.email "selectedEmail",sel."firstName" "selectedFirstName",sel."lastName" "selectedLastName" FROM "ShiftHandoverBatch" b JOIN "AgentWorkShift" s ON s.id=b."shiftId" JOIN "User" fu ON fu.id=b."fromUserId" LEFT JOIN "ShiftHandoverItem" i ON i."batchId"=b.id LEFT JOIN "SupportConversation" c ON c.id=i."conversationId" LEFT JOIN "User" su ON su.id=i."suggestedUserId" LEFT JOIN "User" sel ON sel.id=i."selectedUserId" WHERE b.id=${batchId}::uuid AND b."organizationId"=${organizationId}::uuid ORDER BY i."createdAt" ASC`;return this.group(rows)[0]??null;}

  async mine(user:AuthenticatedUser){const rows=await this.prisma.$queryRaw<any[]>`SELECT b.id "batchId",b.status "batchStatus",b.trigger,b."openConversationCount",b."preparedAt",b."completedAt",b."createdAt" "batchCreatedAt",b."shiftId",b."fromUserId",s."startsAt" "shiftStartsAt",s."endsAt" "shiftEndsAt",fu.email "fromEmail",fu."firstName" "fromFirstName",fu."lastName" "fromLastName",i.id "itemId",i.status "itemStatus",i."conversationId",i."suggestedUserId",i."selectedUserId",i.score,i.reason,i."agentNote",i."managerNote",i.snapshot,i."appliedAt",c.subject,c.status::text "conversationStatus",c."assignedToUserId" "currentAssignedToUserId",c.priority,c."routingTopic",c."requestedLanguage",c."lastMessageAt",su.email "suggestedEmail",su."firstName" "suggestedFirstName",su."lastName" "suggestedLastName",sel.email "selectedEmail",sel."firstName" "selectedFirstName",sel."lastName" "selectedLastName" FROM "ShiftHandoverBatch" b JOIN "AgentWorkShift" s ON s.id=b."shiftId" JOIN "User" fu ON fu.id=b."fromUserId" LEFT JOIN "ShiftHandoverItem" i ON i."batchId"=b.id LEFT JOIN "SupportConversation" c ON c.id=i."conversationId" LEFT JOIN "User" su ON su.id=i."suggestedUserId" LEFT JOIN "User" sel ON sel.id=i."selectedUserId" WHERE b."organizationId"=${user.organizationId}::uuid AND b."fromUserId"=${user.id}::uuid AND b."createdAt">CURRENT_TIMESTAMP-INTERVAL '14 days' ORDER BY b."createdAt" DESC,i."createdAt" ASC`;const batches=this.group(rows);return{summary:{batches:batches.length,pending:batches.reduce((n,b)=>n+b.items.filter((i:any)=>i.status==='PENDING').length,0),applied:batches.reduce((n,b)=>n+b.items.filter((i:any)=>i.status==='APPLIED').length,0)},batches};}

  async team(user:AuthenticatedUser){const rows=await this.prisma.$queryRaw<any[]>`SELECT b.id "batchId",b.status "batchStatus",b.trigger,b."openConversationCount",b."preparedAt",b."completedAt",b."createdAt" "batchCreatedAt",b."shiftId",b."fromUserId",s."startsAt" "shiftStartsAt",s."endsAt" "shiftEndsAt",fu.email "fromEmail",fu."firstName" "fromFirstName",fu."lastName" "fromLastName",i.id "itemId",i.status "itemStatus",i."conversationId",i."suggestedUserId",i."selectedUserId",i.score,i.reason,i."agentNote",i."managerNote",i.snapshot,i."appliedAt",c.subject,c.status::text "conversationStatus",c."assignedToUserId" "currentAssignedToUserId",c.priority,c."routingTopic",c."requestedLanguage",c."lastMessageAt",su.email "suggestedEmail",su."firstName" "suggestedFirstName",su."lastName" "suggestedLastName",sel.email "selectedEmail",sel."firstName" "selectedFirstName",sel."lastName" "selectedLastName" FROM "ShiftHandoverBatch" b JOIN "AgentWorkShift" s ON s.id=b."shiftId" JOIN "User" fu ON fu.id=b."fromUserId" LEFT JOIN "ShiftHandoverItem" i ON i."batchId"=b.id LEFT JOIN "SupportConversation" c ON c.id=i."conversationId" LEFT JOIN "User" su ON su.id=i."suggestedUserId" LEFT JOIN "User" sel ON sel.id=i."selectedUserId" WHERE b."organizationId"=${user.organizationId}::uuid AND (b.status IN ('DRAFT','PARTIAL') OR b."createdAt">CURRENT_TIMESTAMP-INTERVAL '7 days') ORDER BY CASE b.status WHEN 'DRAFT' THEN 0 WHEN 'PARTIAL' THEN 1 ELSE 2 END,b."createdAt" DESC,i."createdAt" ASC`;const batches=this.group(rows);return{summary:{batchesNeedingAction:batches.filter(b=>['DRAFT','PARTIAL'].includes(b.status)).length,pending:batches.reduce((n,b)=>n+b.items.filter((i:any)=>i.status==='PENDING').length,0),withoutSuggestion:batches.reduce((n,b)=>n+b.items.filter((i:any)=>i.status==='PENDING'&&!i.suggestedUserId).length,0),applied:batches.reduce((n,b)=>n+b.items.filter((i:any)=>i.status==='APPLIED').length,0)},batches};}

  async updateNote(user:AuthenticatedUser,itemId:string,body:Record<string,unknown>){const note=this.note(body.note);const rows=await this.prisma.$queryRaw<Array<{id:string}>>`UPDATE "ShiftHandoverItem" SET "agentNote"=${note},"updatedAt"=CURRENT_TIMESTAMP WHERE id=${itemId}::uuid AND "organizationId"=${user.organizationId}::uuid AND "fromUserId"=${user.id}::uuid AND status='PENDING' RETURNING id`;if(!rows.length)throw new NotFoundException('Relais introuvable ou déjà traité');return{ok:true,note};}

  async candidates(user:AuthenticatedUser,itemId:string){const items=await this.prisma.$queryRaw<Array<{conversationId:string;fromUserId:string;status:string}>>`SELECT "conversationId","fromUserId",status FROM "ShiftHandoverItem" WHERE id=${itemId}::uuid AND "organizationId"=${user.organizationId}::uuid LIMIT 1`;const item=items[0];if(!item)throw new NotFoundException('Relais introuvable');return{itemId,candidates:(await this.candidatesForConversation(user.organizationId,item.conversationId,item.fromUserId)).slice(0,8)};}

  private async refreshBatchState(organizationId:string,batchId:string){await this.prisma.$executeRaw`UPDATE "ShiftHandoverBatch" b SET status=CASE WHEN x.pending=0 THEN 'COMPLETED' WHEN x.done>0 THEN 'PARTIAL' ELSE 'DRAFT' END,"completedAt"=CASE WHEN x.pending=0 THEN COALESCE(b."completedAt",CURRENT_TIMESTAMP) ELSE NULL END,"updatedAt"=CURRENT_TIMESTAMP FROM (SELECT count(*) FILTER(WHERE status='PENDING')::int pending,count(*) FILTER(WHERE status<>'PENDING')::int done FROM "ShiftHandoverItem" WHERE "batchId"=${batchId}::uuid) x WHERE b.id=${batchId}::uuid AND b."organizationId"=${organizationId}::uuid`;}

  async refreshBatch(user:AuthenticatedUser,batchId:string){const items=await this.prisma.$queryRaw<Array<{id:string;conversationId:string;fromUserId:string}>>`SELECT id,"conversationId","fromUserId" FROM "ShiftHandoverItem" WHERE "batchId"=${batchId}::uuid AND "organizationId"=${user.organizationId}::uuid AND status='PENDING' ORDER BY "createdAt"`;for(const item of items){const conversation=await this.conversation(user.organizationId,item.conversationId);if(!conversation||conversation.status==='RESOLVED'||conversation.assignedToUserId!==item.fromUserId){await this.prisma.$executeRaw`UPDATE "ShiftHandoverItem" SET status='STALE',reason='Conversation résolue ou déjà réattribuée',"updatedAt"=CURRENT_TIMESTAMP WHERE id=${item.id}::uuid`;continue;}const candidate=(await this.candidatesForConversation(user.organizationId,item.conversationId,item.fromUserId))[0]??null;await this.prisma.$executeRaw`UPDATE "ShiftHandoverItem" SET "suggestedUserId"=${candidate?.id??null}::uuid,score=${candidate?.score??null},reason=${candidate?.reason??'Aucun agent actuellement en service et éligible'},"updatedAt"=CURRENT_TIMESTAMP WHERE id=${item.id}::uuid`;}
    await this.refreshBatchState(user.organizationId,batchId);return this.batchDetail(user.organizationId,batchId);}

  async applyItem(user:AuthenticatedUser,itemId:string,body:Record<string,unknown>={}){const initial=await this.prisma.$queryRaw<Array<{id:string;batchId:string;conversationId:string;fromUserId:string;suggestedUserId:string|null;status:string}>>`SELECT id,"batchId","conversationId","fromUserId","suggestedUserId",status FROM "ShiftHandoverItem" WHERE id=${itemId}::uuid AND "organizationId"=${user.organizationId}::uuid LIMIT 1`;const item=initial[0];if(!item)throw new NotFoundException('Relais introuvable');if(item.status==='APPLIED')return{ok:true,alreadyApplied:true};if(item.status!=='PENDING')throw new BadRequestException('Ce relais est déjà traité');const targetId=String(body.agentId??item.suggestedUserId??'');if(!targetId)throw new BadRequestException('Aucun agent de reprise sélectionné');const currentCandidates=await this.candidatesForConversation(user.organizationId,item.conversationId,item.fromUserId);const candidate=currentCandidates.find(c=>c.id===targetId);if(!candidate)throw new ConflictException('Cet agent n’est plus en service, disponible ou dans sa capacité. Actualisez les suggestions.');const managerNote=this.note(body.note,500);
    const outcome=await this.prisma.$transaction(async tx=>{const locked=await tx.$queryRaw<any[]>`SELECT i.id,i."batchId",i.status,i."fromUserId",i."conversationId",c.status::text "conversationStatus",c."assignedToUserId",c."requesterUserId" FROM "ShiftHandoverItem" i JOIN "SupportConversation" c ON c.id=i."conversationId" WHERE i.id=${itemId}::uuid AND i."organizationId"=${user.organizationId}::uuid FOR UPDATE OF i,c`;const row=locked[0];if(!row)throw new NotFoundException('Relais introuvable');if(row.status==='APPLIED')return{alreadyApplied:true,batchId:row.batchId,conversationId:row.conversationId,requesterUserId:row.requesterUserId};if(row.status!=='PENDING')throw new BadRequestException('Ce relais est déjà traité');if(row.conversationStatus==='RESOLVED'||row.assignedToUserId!==row.fromUserId){await tx.$executeRaw`UPDATE "ShiftHandoverItem" SET status='STALE',reason='Conversation résolue ou déjà réattribuée',"updatedAt"=CURRENT_TIMESTAMP WHERE id=${itemId}::uuid`;return{stale:true,batchId:row.batchId,conversationId:row.conversationId,requesterUserId:row.requesterUserId};}const eligible=await tx.$queryRaw<Array<{id:string}>>`SELECT u.id FROM "User" u JOIN "AgentPresence" p ON p."userId"=u.id LEFT JOIN "AgentRoutingProfile" rp ON rp."userId"=u.id WHERE u.id=${targetId}::uuid AND u."organizationId"=${user.organizationId}::uuid AND u."isActive"=TRUE AND u.role IN ('OWNER','ADMIN','OPERATOR') AND COALESCE(rp.enabled,TRUE)=TRUE AND p.availability='AVAILABLE' AND p."acceptingAssignments"=TRUE AND p."lastHeartbeatAt">CURRENT_TIMESTAMP-INTERVAL '90 seconds' AND EXISTS(SELECT 1 FROM "AgentWorkShift" s WHERE s."userId"=u.id AND s."organizationId"=${user.organizationId}::uuid AND s.status='PLANNED' AND s."liveStatus"='ACTIVE') AND (SELECT count(*) FROM "SupportConversation" c2 WHERE c2."assignedToUserId"=u.id AND c2.status<>'RESOLVED')<COALESCE(rp."maxActiveConversations",5) LIMIT 1`;if(!eligible.length)throw new ConflictException('L’agent sélectionné n’est plus éligible au relais');await tx.$executeRaw`UPDATE "SupportConversation" SET "assignedToUserId"=${targetId}::uuid,status='ASSIGNED',"updatedAt"=CURRENT_TIMESTAMP WHERE id=${row.conversationId}::uuid`;await tx.$executeRaw`INSERT INTO "SupportMessage" (id,"conversationId",author,body,"createdAt") VALUES (gen_random_uuid(),${row.conversationId}::uuid,'SYSTEM','Passage de relais KHE : un nouvel agent reprend cette conversation afin d’assurer la continuité du support.',CURRENT_TIMESTAMP)`;await tx.$executeRaw`UPDATE "ShiftHandoverItem" SET status='APPLIED',"selectedUserId"=${targetId}::uuid,"managerNote"=${managerNote},"appliedByUserId"=${user.id}::uuid,"appliedAt"=CURRENT_TIMESTAMP,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${itemId}::uuid`;return{batchId:row.batchId,conversationId:row.conversationId,requesterUserId:row.requesterUserId};});
    await this.refreshBatchState(user.organizationId,outcome.batchId);if((outcome as any).stale)return{ok:false,stale:true};if(!(outcome as any).alreadyApplied){const updatedConversation=await this.conversation(user.organizationId,outcome.conversationId);await this.notifyUser(user.organizationId,targetId,'ASSIGNMENT','Conversation reprise après passage de relais',`Une conversation vous a été confiée après la fin du shift d’un autre agent. Sujet : ${updatedConversation?.subject??'Support KHE'}`,`/help?agentConversation=${outcome.conversationId}`);await this.prisma.appNotification.create({data:{organizationId:user.organizationId,kind:NotificationKind.SUPPORT,title:'Votre conversation KHE change d’agent',body:'Un nouvel agent reprend votre conversation afin d’assurer la continuité du support.',actionUrl:`/help?conversation=${outcome.conversationId}`}});await this.prisma.auditLog.create({data:{organizationId:user.organizationId,userId:user.id,action:'WORKFORCE_SHIFT_HANDOVER_APPLIED',entityType:'SupportConversation',entityId:outcome.conversationId,metadata:{fromUserId:item.fromUserId,toUserId:targetId,handoverItemId:itemId}}});}
    return{ok:true,conversationId:outcome.conversationId,agentId:targetId,agentName:candidate.name};}

  async skipItem(user:AuthenticatedUser,itemId:string,body:Record<string,unknown>={}){const note=this.note(body.note,500);const rows=await this.prisma.$queryRaw<Array<{batchId:string}>>`UPDATE "ShiftHandoverItem" SET status='SKIPPED',"managerNote"=${note},"updatedAt"=CURRENT_TIMESTAMP WHERE id=${itemId}::uuid AND "organizationId"=${user.organizationId}::uuid AND status='PENDING' RETURNING "batchId"`;if(!rows.length)throw new NotFoundException('Relais introuvable ou déjà traité');await this.refreshBatchState(user.organizationId,rows[0].batchId);return{ok:true};}

  async applySafe(user:AuthenticatedUser,batchId:string){const items=await this.prisma.$queryRaw<Array<{id:string;suggestedUserId:string|null}>>`SELECT id,"suggestedUserId" FROM "ShiftHandoverItem" WHERE "batchId"=${batchId}::uuid AND "organizationId"=${user.organizationId}::uuid AND status='PENDING' ORDER BY "createdAt"`;let applied=0,blocked=0;const errors:Array<{itemId:string;message:string}>=[];for(const item of items){if(!item.suggestedUserId){blocked++;errors.push({itemId:item.id,message:'Aucune suggestion active'});continue;}try{await this.applyItem(user,item.id,{agentId:item.suggestedUserId});applied++;}catch(e){blocked++;errors.push({itemId:item.id,message:e instanceof Error?e.message:'Relais impossible'});}}return{applied,blocked,errors,batch:await this.batchDetail(user.organizationId,batchId)};}

  async pulse(user:AuthenticatedUser){const shifts=await this.prisma.$queryRaw<Array<{id:string;userId:string}>>`SELECT s.id,s."userId" FROM "AgentWorkShift" s WHERE s."organizationId"=${user.organizationId}::uuid AND s.status='COMPLETED' AND s."liveStatus" IN ('COMPLETED','MISSED') AND COALESCE(s."actualEndedAt",s."updatedAt")>CURRENT_TIMESTAMP-INTERVAL '24 hours' AND NOT EXISTS(SELECT 1 FROM "ShiftHandoverBatch" b WHERE b."shiftId"=s.id) ORDER BY COALESCE(s."actualEndedAt",s."updatedAt") DESC LIMIT 50`;let prepared=0,conversations=0;for(const shift of shifts){const batch=await this.prepareForShift(user.organizationId,shift.id,shift.userId,'CATCH_UP');if(batch){prepared++;conversations+=Number(batch.openConversationCount||0);}}return{prepared,conversations};}
}
