import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import type { AuthenticatedUser } from '../auth/auth.types';
import { PrismaService } from '../prisma/prisma.service';

type BriefPolicy={organizationId:string;enabled:boolean;prepareBeforeMinutes:number;slaUrgentMinutes:number;coverageLookaheadMinutes:number;notifyAgent:boolean;notifyManagers:boolean;updatedAt:Date};
type ShiftRow={id:string;userId:string;startsAt:Date;endsAt:Date;status:string;liveStatus:string};
type ConversationRow={id:string;subject:string;status:string;assignedToUserId:string|null;priority:string;routingTopic:string;requestedLanguage:string;customerTier:string;lastMessageAt:Date;slaFirstResponseDueAt:Date|null;slaResolutionDueAt:Date|null;firstAgentResponseAt:Date|null};
type CandidateRow={id:string;email:string;firstName:string|null;lastName:string|null;role:string;skills:string[];languages:string[];activeConversations:number;activeTasks:number;pendingHandovers:number;maxConversations:number;maxTasks:number;coverageStatus:string};

@Injectable()
export class ShiftBriefService{
  constructor(private readonly prisma:PrismaService){}
  private number(value:unknown,min:number,max:number,fallback:number){const n=Math.trunc(Number(value));return Number.isFinite(n)?Math.min(max,Math.max(min,n)):fallback;}
  private note(value:unknown,max=500){return String(value??'').trim().slice(0,max)||null;}
  private name(v:{email:string;firstName?:string|null;lastName?:string|null}){return[v.firstName,v.lastName].filter(Boolean).join(' ')||v.email;}
  private async notifyUser(organizationId:string,userId:string,kind:'REMINDER'|'MANAGER',title:string,body:string,actionUrl:string){await this.prisma.$executeRaw`INSERT INTO "AgentWorkforceNotice" ("organizationId","userId",kind,title,body,"actionUrl") VALUES (${organizationId}::uuid,${userId}::uuid,${kind},${title},${body},${actionUrl})`;}
  private async notifyManagers(organizationId:string,title:string,body:string){const managers=await this.prisma.$queryRaw<Array<{id:string}>>`SELECT id FROM "User" WHERE "organizationId"=${organizationId}::uuid AND "isActive"=TRUE AND role IN ('OWNER','ADMIN')`;for(const manager of managers)await this.notifyUser(organizationId,manager.id,'MANAGER',title,body,'/operations/workforce/brief/team');}

  async policy(organizationId:string):Promise<BriefPolicy>{await this.prisma.$executeRaw`INSERT INTO "ShiftBriefPolicy" ("organizationId") VALUES (${organizationId}::uuid) ON CONFLICT ("organizationId") DO NOTHING`;const rows=await this.prisma.$queryRaw<BriefPolicy[]>`SELECT * FROM "ShiftBriefPolicy" WHERE "organizationId"=${organizationId}::uuid LIMIT 1`;return rows[0];}
  async updatePolicy(organizationId:string,body:Record<string,unknown>){const current=await this.policy(organizationId);const enabled=typeof body.enabled==='boolean'?body.enabled:current.enabled,notifyAgent=typeof body.notifyAgent==='boolean'?body.notifyAgent:current.notifyAgent,notifyManagers=typeof body.notifyManagers==='boolean'?body.notifyManagers:current.notifyManagers;const prepare=this.number(body.prepareBeforeMinutes,5,120,current.prepareBeforeMinutes),sla=this.number(body.slaUrgentMinutes,15,240,current.slaUrgentMinutes),coverage=this.number(body.coverageLookaheadMinutes,30,360,current.coverageLookaheadMinutes);await this.prisma.$executeRaw`UPDATE "ShiftBriefPolicy" SET enabled=${enabled},"prepareBeforeMinutes"=${prepare},"slaUrgentMinutes"=${sla},"coverageLookaheadMinutes"=${coverage},"notifyAgent"=${notifyAgent},"notifyManagers"=${notifyManagers},"updatedAt"=CURRENT_TIMESTAMP WHERE "organizationId"=${organizationId}::uuid`;return this.policy(organizationId);}

  private async shift(organizationId:string,shiftId:string){const rows=await this.prisma.$queryRaw<ShiftRow[]>`SELECT id,"userId","startsAt","endsAt",status,"liveStatus" FROM "AgentWorkShift" WHERE id=${shiftId}::uuid AND "organizationId"=${organizationId}::uuid LIMIT 1`;return rows[0];}
  private nextDue(c:ConversationRow){const due:Date[]=[];if(!c.firstAgentResponseAt&&c.slaFirstResponseDueAt)due.push(new Date(c.slaFirstResponseDueAt));if(c.slaResolutionDueAt)due.push(new Date(c.slaResolutionDueAt));return due.length?new Date(Math.min(...due.map(d=>d.getTime()))):null;}
  private risk(c:ConversationRow,shiftEndsAt:Date,urgentMinutes:number){const due=this.nextDue(c);if(!due)return{level:'NORMAL',due:null};const now=Date.now(),end=new Date(shiftEndsAt).getTime();if(due.getTime()<now)return{level:'OVERDUE',due};if(due.getTime()<=end+urgentMinutes*60000)return{level:'URGENT',due};if(due.getTime()<=end+240*60000)return{level:'WATCH',due};return{level:'NORMAL',due};}

  private async candidates(organizationId:string,conversation:ConversationRow,fromUserId:string,handoverAt:Date){const rows=await this.prisma.$queryRaw<CandidateRow[]>`
    WITH candidates AS (
      SELECT u.id,u.email,u."firstName",u."lastName",u.role::text role,COALESCE(rp.skills,ARRAY[]::text[]) skills,COALESCE(rp.languages,ARRAY['fr']::text[]) languages,
        COALESCE(rp."maxActiveConversations",5)::int "maxConversations",COALESCE(rp."maxActiveTasks",15)::int "maxTasks",
        (SELECT count(*)::int FROM "SupportConversation" c WHERE c."assignedToUserId"=u.id AND c.status<>'RESOLVED') "activeConversations",
        (SELECT count(*)::int FROM "SupportTask" t WHERE t."assignedToUserId"=u.id AND t.status<>'DONE') "activeTasks",
        (SELECT count(*)::int FROM "ShiftHandoverItem" h WHERE COALESCE(h."selectedUserId",h."suggestedUserId")=u.id AND h.status='PENDING') "pendingHandovers",
        CASE WHEN EXISTS(SELECT 1 FROM "AgentWorkShift" a WHERE a."userId"=u.id AND a."organizationId"=${organizationId}::uuid AND a.status='PLANNED' AND a."liveStatus"='ACTIVE') THEN 'ACTIVE' ELSE 'INCOMING' END "coverageStatus"
      FROM "User" u LEFT JOIN "AgentRoutingProfile" rp ON rp."userId"=u.id
      WHERE u."organizationId"=${organizationId}::uuid AND u."isActive"=TRUE AND u.role IN ('OWNER','ADMIN','OPERATOR') AND u.id<>${fromUserId}::uuid AND COALESCE(rp.enabled,TRUE)=TRUE
        AND EXISTS(SELECT 1 FROM "AgentWorkShift" s WHERE s."organizationId"=${organizationId}::uuid AND s."userId"=u.id AND s.status='PLANNED' AND s."confirmationStatus"='ACCEPTED' AND s."startsAt"<=${handoverAt}+INTERVAL '15 minutes' AND s."endsAt">${handoverAt})
        AND NOT EXISTS(SELECT 1 FROM "AgentAvailabilityBlock" b WHERE b."userId"=u.id AND b.status='ACTIVE' AND b."startsAt"<${handoverAt}+INTERVAL '15 minutes' AND b."endsAt">${handoverAt}-INTERVAL '15 minutes')
    ) SELECT * FROM candidates WHERE "activeConversations"<"maxConversations" AND "activeTasks"<"maxTasks"`;
    const topic=String(conversation.routingTopic||'GENERAL').toUpperCase(),language=String(conversation.requestedLanguage||'fr').toLowerCase();return rows.map(row=>{const skills=(row.skills??[]).map(x=>x.toUpperCase()),languages=(row.languages??[]).map(x=>x.toLowerCase());const skillMatch=topic==='GENERAL'||skills.includes(topic),languageMatch=languages.includes(language);let score=row.activeConversations*100+row.activeTasks*10+row.pendingHandovers*25+(skillMatch?0:60)+(languageMatch?0:40)+(row.coverageStatus==='INCOMING'?5:0);if(row.role==='OPERATOR')score-=8;else if(row.role==='ADMIN')score-=4;return{...row,name:this.name(row),skillMatch,languageMatch,score,reason:`${row.coverageStatus==='ACTIVE'?'déjà en service':'shift entrant confirmé'} · ${skillMatch?'compétence adaptée':'compétence générale'} · ${languageMatch?`langue ${language}`:`langue ${language} non couverte`} · ${row.activeConversations}/${row.maxConversations} conversation(s) active(s)`};}).sort((a,b)=>a.score-b.score||a.activeConversations-b.activeConversations||a.email.localeCompare(b.email));}

  private async detail(organizationId:string,briefId:string){const rows=await this.prisma.$queryRaw<any[]>`SELECT b.id "briefId",b.status "briefStatus",b."openConversationCount",b."urgentSlaCount",b."missingNoteCount",b."candidateCoverageCount",b."incomingAgentCount",b."preparedAt",b."lastRefreshedAt",b."shiftId",b."userId",s."startsAt" "shiftStartsAt",s."endsAt" "shiftEndsAt",u.email "agentEmail",u."firstName" "agentFirstName",u."lastName" "agentLastName",i.id "itemId",i."conversationId",i."riskLevel",i."nextSlaDueAt",i."suggestedUserId",i.score,i.reason,i."agentNote",i.snapshot,c.subject,c.status::text "conversationStatus",c.priority,c."routingTopic",c."requestedLanguage",c."lastMessageAt",su.email "suggestedEmail",su."firstName" "suggestedFirstName",su."lastName" "suggestedLastName" FROM "ShiftBrief" b JOIN "AgentWorkShift" s ON s.id=b."shiftId" JOIN "User" u ON u.id=b."userId" LEFT JOIN "ShiftBriefItem" i ON i."briefId"=b.id LEFT JOIN "SupportConversation" c ON c.id=i."conversationId" LEFT JOIN "User" su ON su.id=i."suggestedUserId" WHERE b.id=${briefId}::uuid AND b."organizationId"=${organizationId}::uuid ORDER BY CASE i."riskLevel" WHEN 'OVERDUE' THEN 0 WHEN 'URGENT' THEN 1 WHEN 'WATCH' THEN 2 ELSE 3 END,c."lastMessageAt" DESC`;
    if(!rows.length)return null;const first=rows[0],items=rows.filter(r=>r.itemId).map(r=>({id:r.itemId,conversationId:r.conversationId,subject:r.subject,conversationStatus:r.conversationStatus,priority:r.priority,routingTopic:r.routingTopic,requestedLanguage:r.requestedLanguage,lastMessageAt:r.lastMessageAt,riskLevel:r.riskLevel,nextSlaDueAt:r.nextSlaDueAt,suggestedUserId:r.suggestedUserId,suggestedAgentName:r.suggestedEmail?this.name({email:r.suggestedEmail,firstName:r.suggestedFirstName,lastName:r.suggestedLastName}):null,score:r.score,reason:r.reason,agentNote:r.agentNote,snapshot:r.snapshot}));return{id:first.briefId,status:first.briefStatus,shiftId:first.shiftId,userId:first.userId,agentName:this.name({email:first.agentEmail,firstName:first.agentFirstName,lastName:first.agentLastName}),shiftStartsAt:first.shiftStartsAt,shiftEndsAt:first.shiftEndsAt,openConversationCount:first.openConversationCount,urgentSlaCount:first.urgentSlaCount,missingNoteCount:first.missingNoteCount,candidateCoverageCount:first.candidateCoverageCount,incomingAgentCount:first.incomingAgentCount,preparedAt:first.preparedAt,lastRefreshedAt:first.lastRefreshedAt,items};}

  private async recalc(organizationId:string,briefId:string){const counts=await this.prisma.$queryRaw<Array<{openCount:number;urgentCount:number;missingCount:number;coveredCount:number}>>`SELECT count(*)::int "openCount",count(*) FILTER(WHERE "riskLevel" IN ('OVERDUE','URGENT'))::int "urgentCount",count(*) FILTER(WHERE "agentNote" IS NULL OR btrim("agentNote")='')::int "missingCount",count(*) FILTER(WHERE "suggestedUserId" IS NOT NULL)::int "coveredCount" FROM "ShiftBriefItem" WHERE "briefId"=${briefId}::uuid`;const c=counts[0]??{openCount:0,urgentCount:0,missingCount:0,coveredCount:0};await this.prisma.$executeRaw`UPDATE "ShiftBrief" SET "openConversationCount"=${c.openCount},"urgentSlaCount"=${c.urgentCount},"missingNoteCount"=${c.missingCount},"candidateCoverageCount"=${c.coveredCount},status=CASE WHEN status='CLOSED' THEN status WHEN ${c.missingCount}=0 THEN 'READY' ELSE 'OPEN' END,"lastRefreshedAt"=CURRENT_TIMESTAMP,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${briefId}::uuid AND "organizationId"=${organizationId}::uuid`;}

  async prepareForShift(organizationId:string,shiftId:string,userId:string){const policy=await this.policy(organizationId);if(!policy.enabled)return null;const shift=await this.shift(organizationId,shiftId);if(!shift||shift.userId!==userId||shift.status!=='PLANNED'||!['ACTIVE','PAUSED'].includes(shift.liveStatus))return null;const now=Date.now(),end=new Date(shift.endsAt).getTime();if(now<end-policy.prepareBeforeMinutes*60000||now>=end)return null;const inserted=await this.prisma.$queryRaw<Array<{id:string}>>`INSERT INTO "ShiftBrief" ("organizationId","shiftId","userId") VALUES (${organizationId}::uuid,${shiftId}::uuid,${userId}::uuid) ON CONFLICT ("shiftId") DO NOTHING RETURNING id`;const briefRows=inserted.length?inserted:await this.prisma.$queryRaw<Array<{id:string}>>`SELECT id FROM "ShiftBrief" WHERE "shiftId"=${shiftId}::uuid AND "organizationId"=${organizationId}::uuid LIMIT 1`;const briefId=briefRows[0]?.id;if(!briefId)return null;
    const conversations=await this.prisma.$queryRaw<ConversationRow[]>`SELECT id,subject,status::text status,"assignedToUserId",COALESCE(priority,'NORMAL') priority,COALESCE("routingTopic",'GENERAL') "routingTopic",COALESCE("requestedLanguage",'fr') "requestedLanguage",COALESCE("customerTier",'STANDARD') "customerTier","lastMessageAt","slaFirstResponseDueAt","slaResolutionDueAt","firstAgentResponseAt" FROM "SupportConversation" WHERE "organizationId"=${organizationId}::uuid AND "assignedToUserId"=${userId}::uuid AND status<>'RESOLVED' ORDER BY CASE priority WHEN 'CRITICAL' THEN 0 WHEN 'HIGH' THEN 1 WHEN 'NORMAL' THEN 2 ELSE 3 END,"lastMessageAt" DESC`;
    await this.prisma.$executeRaw`DELETE FROM "ShiftBriefItem" i WHERE i."briefId"=${briefId}::uuid AND NOT EXISTS(SELECT 1 FROM "SupportConversation" c WHERE c.id=i."conversationId" AND c."organizationId"=${organizationId}::uuid AND c."assignedToUserId"=${userId}::uuid AND c.status<>'RESOLVED')`;
    for(const conversation of conversations){const risk=this.risk(conversation,shift.endsAt,policy.slaUrgentMinutes),candidate=(await this.candidates(organizationId,conversation,userId,shift.endsAt))[0]??null,snapshot={subject:conversation.subject,priority:conversation.priority,topic:conversation.routingTopic,language:conversation.requestedLanguage,customerTier:conversation.customerTier,lastMessageAt:conversation.lastMessageAt,nextSlaDueAt:risk.due};await this.prisma.$executeRaw`INSERT INTO "ShiftBriefItem" ("briefId","organizationId","conversationId","fromUserId","suggestedUserId","riskLevel","nextSlaDueAt",score,reason,snapshot) VALUES (${briefId}::uuid,${organizationId}::uuid,${conversation.id}::uuid,${userId}::uuid,${candidate?.id??null}::uuid,${risk.level},${risk.due},${candidate?.score??null},${candidate?.reason??'Aucune relève confirmée ne couvre actuellement cette conversation'},${JSON.stringify(snapshot)}::jsonb) ON CONFLICT ("briefId","conversationId") DO UPDATE SET "suggestedUserId"=EXCLUDED."suggestedUserId","riskLevel"=EXCLUDED."riskLevel","nextSlaDueAt"=EXCLUDED."nextSlaDueAt",score=EXCLUDED.score,reason=EXCLUDED.reason,snapshot=EXCLUDED.snapshot,"updatedAt"=CURRENT_TIMESTAMP`;}
    const incoming=await this.prisma.$queryRaw<Array<{count:number}>>`SELECT count(DISTINCT s."userId")::int count FROM "AgentWorkShift" s WHERE s."organizationId"=${organizationId}::uuid AND s."userId"<>${userId}::uuid AND s.status='PLANNED' AND s."confirmationStatus"='ACCEPTED' AND s."startsAt"<${shift.endsAt}+${policy.coverageLookaheadMinutes}*INTERVAL '1 minute' AND s."endsAt">${shift.endsAt}`;await this.prisma.$executeRaw`UPDATE "ShiftBrief" SET "incomingAgentCount"=${incoming[0]?.count??0},"updatedAt"=CURRENT_TIMESTAMP WHERE id=${briefId}::uuid`;await this.recalc(organizationId,briefId);
    if(inserted.length&&conversations.length){if(policy.notifyAgent){await this.notifyUser(organizationId,userId,'REMINDER','Brief de fin de shift prêt',`${conversations.length} conversation(s) ouverte(s) sont à préparer avant la fin de votre service. Ajoutez les notes utiles sans données sensibles.`,'/operations/workforce/brief');await this.prisma.$executeRaw`UPDATE "ShiftBrief" SET "agentNotifiedAt"=CURRENT_TIMESTAMP WHERE id=${briefId}::uuid`;}if(policy.notifyManagers){await this.notifyManagers(organizationId,'Brief de fin de shift à surveiller',`${conversations.length} conversation(s) restent ouvertes avant la fin d’un shift. KHE affiche les risques SLA et la couverture entrante sans transférer automatiquement.`);await this.prisma.$executeRaw`UPDATE "ShiftBrief" SET "managerNotifiedAt"=CURRENT_TIMESTAMP WHERE id=${briefId}::uuid`;}}
    return this.detail(organizationId,briefId);}

  async compact(user:AuthenticatedUser){const rows=await this.prisma.$queryRaw<Array<{id:string;status:string;shiftEndsAt:Date;openConversationCount:number;urgentSlaCount:number;missingNoteCount:number}>>`SELECT b.id,b.status,s."endsAt" "shiftEndsAt",b."openConversationCount",b."urgentSlaCount",b."missingNoteCount" FROM "ShiftBrief" b JOIN "AgentWorkShift" s ON s.id=b."shiftId" WHERE b."organizationId"=${user.organizationId}::uuid AND b."userId"=${user.id}::uuid AND b.status IN ('OPEN','READY') AND s."endsAt">CURRENT_TIMESTAMP ORDER BY s."endsAt" ASC LIMIT 1`;return{brief:rows[0]??null};}
  async mine(user:AuthenticatedUser){const rows=await this.prisma.$queryRaw<Array<{id:string}>>`SELECT id FROM "ShiftBrief" WHERE "organizationId"=${user.organizationId}::uuid AND "userId"=${user.id}::uuid AND "createdAt">CURRENT_TIMESTAMP-INTERVAL '2 days' ORDER BY "createdAt" DESC LIMIT 10`;const briefs=[];for(const row of rows){const detail=await this.detail(user.organizationId,row.id);if(detail)briefs.push(detail);}return{summary:{briefs:briefs.length,open:briefs.filter(b=>['OPEN','READY'].includes(b.status)).length,urgent:briefs.reduce((n,b)=>n+Number(b.urgentSlaCount||0),0),missingNotes:briefs.reduce((n,b)=>n+Number(b.missingNoteCount||0),0)},briefs};}
  async team(user:AuthenticatedUser){const rows=await this.prisma.$queryRaw<Array<{id:string}>>`SELECT id FROM "ShiftBrief" WHERE "organizationId"=${user.organizationId}::uuid AND (status IN ('OPEN','READY') OR "createdAt">CURRENT_TIMESTAMP-INTERVAL '2 days') ORDER BY CASE status WHEN 'OPEN' THEN 0 WHEN 'READY' THEN 1 ELSE 2 END,"createdAt" DESC LIMIT 30`;const briefs=[];for(const row of rows){const detail=await this.detail(user.organizationId,row.id);if(detail)briefs.push(detail);}return{policy:await this.policy(user.organizationId),summary:{activeBriefs:briefs.filter(b=>['OPEN','READY'].includes(b.status)).length,urgent:briefs.reduce((n,b)=>n+Number(b.urgentSlaCount||0),0),missingNotes:briefs.reduce((n,b)=>n+Number(b.missingNoteCount||0),0),uncovered:briefs.reduce((n,b)=>n+Math.max(0,Number(b.openConversationCount||0)-Number(b.candidateCoverageCount||0)),0)},briefs};}
  async updateNote(user:AuthenticatedUser,itemId:string,body:Record<string,unknown>){const note=this.note(body.note);const rows=await this.prisma.$queryRaw<Array<{briefId:string}>>`UPDATE "ShiftBriefItem" i SET "agentNote"=${note},"updatedAt"=CURRENT_TIMESTAMP FROM "ShiftBrief" b WHERE i.id=${itemId}::uuid AND i."briefId"=b.id AND i."organizationId"=${user.organizationId}::uuid AND i."fromUserId"=${user.id}::uuid AND b.status IN ('OPEN','READY') RETURNING i."briefId"`;if(!rows.length)throw new NotFoundException('Brief introuvable ou déjà clôturé');await this.recalc(user.organizationId,rows[0].briefId);return{ok:true,note};}
  async refreshCurrent(user:AuthenticatedUser){const shifts=await this.prisma.$queryRaw<Array<{id:string}>>`SELECT id FROM "AgentWorkShift" WHERE "organizationId"=${user.organizationId}::uuid AND "userId"=${user.id}::uuid AND status='PLANNED' AND "liveStatus" IN ('ACTIVE','PAUSED') AND "endsAt">CURRENT_TIMESTAMP ORDER BY "endsAt" ASC LIMIT 1`;if(!shifts.length)throw new BadRequestException('Aucun shift actif à préparer');const brief=await this.prepareForShift(user.organizationId,shifts[0].id,user.id);if(!brief)throw new BadRequestException('Le brief sera disponible dans la fenêtre configurée avant la fin du shift');return brief;}
  async refreshBrief(user:AuthenticatedUser,briefId:string){const rows=await this.prisma.$queryRaw<Array<{shiftId:string;userId:string}>>`SELECT "shiftId","userId" FROM "ShiftBrief" WHERE id=${briefId}::uuid AND "organizationId"=${user.organizationId}::uuid LIMIT 1`;if(!rows.length)throw new NotFoundException('Brief introuvable');const brief=await this.prepareForShift(user.organizationId,rows[0].shiftId,rows[0].userId);if(!brief)throw new BadRequestException('Ce brief ne peut plus être rafraîchi');return brief;}
  async pulse(user:AuthenticatedUser){const policy=await this.policy(user.organizationId);if(!policy.enabled)return{enabled:false,prepared:0};const shifts=await this.prisma.$queryRaw<Array<{id:string;userId:string}>>`SELECT s.id,s."userId" FROM "AgentWorkShift" s WHERE s."organizationId"=${user.organizationId}::uuid AND s.status='PLANNED' AND s."liveStatus" IN ('ACTIVE','PAUSED') AND s."endsAt">CURRENT_TIMESTAMP AND s."endsAt"<=CURRENT_TIMESTAMP+${policy.prepareBeforeMinutes}*INTERVAL '1 minute' ORDER BY s."endsAt" ASC LIMIT 30`;let prepared=0;for(const shift of shifts){const brief=await this.prepareForShift(user.organizationId,shift.id,shift.userId);if(brief)prepared++;}return{enabled:true,prepared};}
}
