import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import type { AuthenticatedUser } from '../auth/auth.types';
import { PrismaService } from '../prisma/prisma.service';

type WorkforceConfig={organizationId:string;enabled:boolean;historyDays:number;forecastDays:number;slotMinutes:number;forecastTimezone:string;targetUtilizationPct:number;safetyBufferPct:number;serviceMinutesPerRequest:number;minAgentsPerDemandSlot:number;alertGapAgents:number;notifyUnderstaffing:boolean;countryForecastEnabled:boolean;lastPulseAt:Date|null;updatedAt:Date};
type HistoricalRow={createdAt:Date;priority:string;requestedLanguage:string;routingTopic:string;countryCode:string|null};
type AgentProfile={id:string;email:string;firstName:string|null;lastName:string|null;enabled:boolean;skills:string[];languages:string[];timezone:string|null;workingDays:number[];workStartLocal:string|null;workEndLocal:string|null;maxActiveConversations:number;maxActiveTasks:number;availability:string|null;acceptingAssignments:boolean|null;lastHeartbeatAt:Date|null};
type ShiftRow={id:string;userId:string;agentEmail:string;agentFirstName:string|null;agentLastName:string|null;startsAt:Date;endsAt:Date;status:string;source:string;note:string|null;createdAt:Date;updatedAt:Date};

const PRIORITY_WEIGHT:Record<string,number>={CRITICAL:2.5,HIGH:1.6,NORMAL:1,LOW:.6};
const WEEKDAY:Record<string,number>={Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6,Sun:7};

@Injectable()
export class WorkforceIntelligenceService{
  constructor(private readonly prisma:PrismaService){}

  private number(value:unknown,min:number,max:number,fallback:number){const parsed=Math.trunc(Number(value));return Number.isFinite(parsed)?Math.min(max,Math.max(min,parsed)):fallback;}
  private timezone(value:unknown,fallback='Europe/Zurich'){const zone=String(value??fallback).trim().slice(0,80)||fallback;try{new Intl.DateTimeFormat('en-US',{timeZone:zone}).format(new Date());return zone;}catch{throw new BadRequestException('Fuseau horaire invalide');}}
  private date(value:unknown,label:string){const parsed=new Date(String(value??''));if(!Number.isFinite(parsed.getTime()))throw new BadRequestException(`${label} invalide`);return parsed;}
  private localParts(date:Date,timeZone:string){const parts=new Intl.DateTimeFormat('en-GB',{timeZone,weekday:'short',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date);const map=Object.fromEntries(parts.map(p=>[p.type,p.value]));return{dow:WEEKDAY[map.weekday]??1,hour:Number(map.hour),minute:Number(map.minute),dateKey:`${map.year}-${map.month}-${map.day}`};}
  private minutesOfDay(hour:number,minute:number){return hour*60+minute;}
  private parseTime(value:string|null){if(!value)return null;const [h,m]=value.slice(0,5).split(':').map(Number);return Number.isFinite(h)&&Number.isFinite(m)?h*60+m:null;}
  private top(map:Map<string,number>,limit=3){return [...map.entries()].sort((a,b)=>b[1]-a[1]).slice(0,limit).map(([key])=>key);}
  private name(agent:{email:string;firstName?:string|null;lastName?:string|null}){return[agent.firstName,agent.lastName].filter(Boolean).join(' ')||agent.email;}

  async config(organizationId:string):Promise<WorkforceConfig>{
    await this.prisma.$executeRaw`INSERT INTO "WorkforceIntelligenceConfig" ("organizationId") VALUES (${organizationId}::uuid) ON CONFLICT ("organizationId") DO NOTHING`;
    const rows=await this.prisma.$queryRaw<WorkforceConfig[]>`SELECT * FROM "WorkforceIntelligenceConfig" WHERE "organizationId"=${organizationId}::uuid LIMIT 1`;
    return rows[0];
  }

  async updateConfig(organizationId:string,body:Record<string,unknown>){
    const current=await this.config(organizationId);const slot=[30,60].includes(Number(body.slotMinutes))?Number(body.slotMinutes):current.slotMinutes;const zone=this.timezone(body.forecastTimezone,current.forecastTimezone);
    const values={historyDays:this.number(body.historyDays,14,365,current.historyDays),forecastDays:this.number(body.forecastDays,1,30,current.forecastDays),targetUtilizationPct:this.number(body.targetUtilizationPct,40,95,current.targetUtilizationPct),safetyBufferPct:this.number(body.safetyBufferPct,0,100,current.safetyBufferPct),serviceMinutesPerRequest:this.number(body.serviceMinutesPerRequest,5,120,current.serviceMinutesPerRequest),minAgentsPerDemandSlot:this.number(body.minAgentsPerDemandSlot,0,20,current.minAgentsPerDemandSlot),alertGapAgents:this.number(body.alertGapAgents,1,20,current.alertGapAgents)};
    await this.prisma.$executeRaw`
      UPDATE "WorkforceIntelligenceConfig" SET enabled=${body.enabled!==false},"historyDays"=${values.historyDays},"forecastDays"=${values.forecastDays},"slotMinutes"=${slot},"forecastTimezone"=${zone},
      "targetUtilizationPct"=${values.targetUtilizationPct},"safetyBufferPct"=${values.safetyBufferPct},"serviceMinutesPerRequest"=${values.serviceMinutesPerRequest},"minAgentsPerDemandSlot"=${values.minAgentsPerDemandSlot},
      "alertGapAgents"=${values.alertGapAgents},"notifyUnderstaffing"=${body.notifyUnderstaffing===true},"countryForecastEnabled"=${body.countryForecastEnabled!==false},"updatedAt"=CURRENT_TIMESTAMP
      WHERE "organizationId"=${organizationId}::uuid
    `;
    return this.config(organizationId);
  }

  private async agents(organizationId:string){
    return this.prisma.$queryRaw<AgentProfile[]>`
      SELECT u.id,u.email,u."firstName",u."lastName",COALESCE(rp.enabled,TRUE) enabled,COALESCE(rp.skills,ARRAY[]::text[]) skills,COALESCE(rp.languages,ARRAY['fr']::text[]) languages,
        COALESCE(rp.timezone,p.timezone) timezone,COALESCE(rp."workingDays",ARRAY[]::integer[]) "workingDays",rp."workStartLocal"::text "workStartLocal",rp."workEndLocal"::text "workEndLocal",
        COALESCE(rp."maxActiveConversations",5) "maxActiveConversations",COALESCE(rp."maxActiveTasks",15) "maxActiveTasks",p.availability,p."acceptingAssignments",p."lastHeartbeatAt"
      FROM "User" u LEFT JOIN "AgentRoutingProfile" rp ON rp."userId"=u.id LEFT JOIN "AgentPresence" p ON p."userId"=u.id
      WHERE u."organizationId"=${organizationId}::uuid AND u."isActive"=TRUE AND u.role IN ('OWNER','ADMIN','OPERATOR') ORDER BY u.email ASC
    `;
  }

  private recurringScheduled(agent:AgentProfile,slotStart:Date,configZone:string){
    if(agent.enabled===false||!agent.workingDays?.length)return false;const zone=agent.timezone||configZone;let parts;try{parts=this.localParts(slotStart,zone);}catch{return false;}
    if(!agent.workingDays.includes(parts.dow))return false;const start=this.parseTime(agent.workStartLocal),end=this.parseTime(agent.workEndLocal);if(start===null||end===null)return true;const minute=this.minutesOfDay(parts.hour,parts.minute);return start<=end?(minute>=start&&minute<end):(minute>=start||minute<end);
  }

  private async inputs(user:AuthenticatedUser,config:WorkforceConfig,daysOverride?:number){
    const now=new Date();const historyStart=new Date(now.getTime()-config.historyDays*86400000);const forecastDays=Math.max(1,Math.min(daysOverride??config.forecastDays,30));const forecastEnd=new Date(now.getTime()+forecastDays*86400000);
    const [history,agents,shifts,backlog,alerts]=await Promise.all([
      this.prisma.$queryRaw<HistoricalRow[]>`
        SELECT c."createdAt",c.priority,c."requestedLanguage",c."routingTopic",loc."countryCode"
        FROM "SupportConversation" c
        LEFT JOIN LATERAL (SELECT s."countryCode" FROM "UserActivitySession" s WHERE s."userId"=c."requesterUserId" AND s."locationSharingEnabled"=TRUE AND s."countryCode" IS NOT NULL ORDER BY s."lastSeenAt" DESC LIMIT 1) loc ON TRUE
        WHERE c."organizationId"=${user.organizationId}::uuid AND c."createdAt">=${historyStart} ORDER BY c."createdAt" DESC LIMIT 10000
      `,
      this.agents(user.organizationId),
      this.prisma.$queryRaw<ShiftRow[]>`
        SELECT s.id,s."userId",u.email "agentEmail",u."firstName" "agentFirstName",u."lastName" "agentLastName",s."startsAt",s."endsAt",s.status,s.source,s.note,s."createdAt",s."updatedAt"
        FROM "AgentWorkShift" s JOIN "User" u ON u.id=s."userId"
        WHERE s."organizationId"=${user.organizationId}::uuid AND s."endsAt">=${now} AND s."startsAt"<=${forecastEnd} ORDER BY s."startsAt" ASC
      `,
      this.prisma.$queryRaw<any[]>`
        SELECT count(*)::int open,count(*) FILTER(WHERE "assignedToUserId" IS NULL)::int unassigned,count(*) FILTER(WHERE priority='CRITICAL')::int critical,count(*) FILTER(WHERE priority='HIGH')::int high,
          count(*) FILTER(WHERE "firstAgentResponseAt" IS NULL AND "slaFirstResponseDueAt"<CURRENT_TIMESTAMP)::int "firstResponseOverdue",count(*) FILTER(WHERE "slaResolutionDueAt"<CURRENT_TIMESTAMP)::int "resolutionOverdue"
        FROM "SupportConversation" WHERE "organizationId"=${user.organizationId}::uuid AND status<>'RESOLVED'
      `,
      this.prisma.$queryRaw<any[]>`SELECT * FROM "WorkforceAlert" WHERE "organizationId"=${user.organizationId}::uuid AND (status<>'RESOLVED' OR "slotStart">=CURRENT_TIMESTAMP-INTERVAL '1 day') ORDER BY "slotStart" ASC LIMIT 200`,
    ]);
    return{now,forecastEnd,forecastDays,history,agents,shifts,backlog:backlog[0]??{open:0,unassigned:0,critical:0,high:0,firstResponseOverdue:0,resolutionOverdue:0},alerts};
  }

  private forecast(config:WorkforceConfig,input:Awaited<ReturnType<WorkforceIntelligenceService['inputs']>>){
    const weeks=Math.max(1,config.historyDays/7);const historyBuckets=new Map<string,{count:number;weighted:number;languages:Map<string,number>;topics:Map<string,number>;countries:Map<string,number>}>();const overallLanguages=new Map<string,number>(),overallTopics=new Map<string,number>(),overallCountries=new Map<string,number>();
    for(const row of input.history){const p=this.localParts(new Date(row.createdAt),config.forecastTimezone);const bucket=Math.floor(this.minutesOfDay(p.hour,p.minute)/config.slotMinutes);const key=`${p.dow}:${bucket}`;const entry=historyBuckets.get(key)??{count:0,weighted:0,languages:new Map(),topics:new Map(),countries:new Map()};const weight=PRIORITY_WEIGHT[row.priority]??1;entry.count++;entry.weighted+=weight;entry.languages.set(row.requestedLanguage,(entry.languages.get(row.requestedLanguage)??0)+weight);entry.topics.set(row.routingTopic,(entry.topics.get(row.routingTopic)??0)+weight);if(config.countryForecastEnabled&&row.countryCode)entry.countries.set(row.countryCode,(entry.countries.get(row.countryCode)??0)+1);historyBuckets.set(key,entry);overallLanguages.set(row.requestedLanguage,(overallLanguages.get(row.requestedLanguage)??0)+1);overallTopics.set(row.routingTopic,(overallTopics.get(row.routingTopic)??0)+1);if(config.countryForecastEnabled&&row.countryCode)overallCountries.set(row.countryCode,(overallCountries.get(row.countryCode)??0)+1);}
    const slotMs=config.slotMinutes*60000;let cursor=new Date(Math.ceil(input.now.getTime()/slotMs)*slotMs);const slots:any[]=[];
    while(cursor<input.forecastEnd){const slotStart=new Date(cursor);const slotEnd=new Date(cursor.getTime()+slotMs);const local=this.localParts(slotStart,config.forecastTimezone);const bucket=Math.floor(this.minutesOfDay(local.hour,local.minute)/config.slotMinutes);const hist=historyBuckets.get(`${local.dow}:${bucket}`);const expected=hist?hist.count/weeks:0;const weighted=hist?hist.weighted/weeks:0;const utilization=config.targetUtilizationPct/100;const buffered=weighted*(1+config.safetyBufferPct/100);let required=expected<.15?0:Math.ceil((buffered*config.serviceMinutesPerRequest)/(config.slotMinutes*utilization));if(required>0)required=Math.max(required,config.minAgentsPerDemandSlot);
      const scheduled=input.agents.filter(agent=>{if(agent.enabled===false)return false;const manual=input.shifts.some(shift=>shift.userId===agent.id&&shift.status==='PLANNED'&&new Date(shift.startsAt)<slotEnd&&new Date(shift.endsAt)>slotStart);return manual||this.recurringScheduled(agent,slotStart,config.forecastTimezone);});
      const languages=hist?this.top(hist.languages):[];const topics=hist?this.top(hist.topics):[];const countries=hist?this.top(hist.countries):[];const gap=Math.max(0,required-scheduled.length);const severity=gap>=2||gap>=Math.max(1,required)?'CRITICAL':gap>0?'HIGH':required>0&&scheduled.length===required?'WATCH':'OK';const coveredLanguages=new Set(scheduled.flatMap(a=>a.languages??[]));const coveredSkills=new Set(scheduled.flatMap(a=>a.skills??[]));const missingLanguages=languages.filter(x=>!coveredLanguages.has(x));const missingSkills=topics.filter(x=>x!=='GENERAL'&&!coveredSkills.has(x));
      slots.push({slotStart,slotEnd,expectedRequests:Number(expected.toFixed(2)),weightedDemand:Number(weighted.toFixed(2)),requiredAgents:required,scheduledAgents:scheduled.length,gapAgents:gap,severity,languages,topics,countryCodes:countries,missingLanguages,missingSkills,scheduledAgentIds:scheduled.map(a=>a.id)});cursor=slotEnd;}
    const risky=slots.filter(s=>s.gapAgents>0).sort((a,b)=>b.gapAgents-a.gapAgents||b.requiredAgents-a.requiredAgents||new Date(a.slotStart).getTime()-new Date(b.slotStart).getTime());const recommendations=risky.slice(0,12).map(slot=>{const when=new Date(slot.slotStart).toLocaleString('fr-CH',{timeZone:config.forecastTimezone,weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});const skills=slot.missingSkills.length?` Compétences à couvrir : ${slot.missingSkills.join(', ')}.`:'';const languages=slot.missingLanguages.length?` Langues manquantes : ${slot.missingLanguages.join(', ')}.`:` Langues dominantes : ${slot.languages.join(', ')||'non déterminées'}.`;return`${when} : prévoir +${slot.gapAgents} agent(s) pour atteindre ${slot.requiredAgents} agent(s).${skills}${languages}`;});if(!recommendations.length)recommendations.push('La couverture planifiée répond à la demande estimée sur l’horizon actuel. Continuer à enrichir l’historique pour améliorer la précision.');
    return{slots,recommendations,overall:{languages:this.top(overallLanguages,6),topics:this.top(overallTopics,8),countryCodes:this.top(overallCountries,8)},sampleSize:input.history.length};
  }

  async dashboard(user:AuthenticatedUser,daysOverride?:number){const config=await this.config(user.organizationId);const input=await this.inputs(user,config,daysOverride);const projection=this.forecast(config,input);const now=Date.now();const online=input.agents.filter(a=>a.lastHeartbeatAt&&now-new Date(a.lastHeartbeatAt).getTime()<90000).length;const available=input.agents.filter(a=>a.acceptingAssignments&&a.availability==='AVAILABLE'&&a.lastHeartbeatAt&&now-new Date(a.lastHeartbeatAt).getTime()<90000).length;const scheduledHours=input.agents.map(agent=>{const shifts=input.shifts.filter(s=>s.userId===agent.id&&s.status==='PLANNED');return{id:agent.id,email:agent.email,firstName:agent.firstName,lastName:agent.lastName,name:this.name(agent),skills:agent.skills,languages:agent.languages,timezone:agent.timezone,workingDays:agent.workingDays,workStartLocal:agent.workStartLocal,workEndLocal:agent.workEndLocal,plannedShifts:shifts.length,online:Boolean(agent.lastHeartbeatAt&&now-new Date(agent.lastHeartbeatAt).getTime()<90000),available:Boolean(agent.acceptingAssignments&&agent.availability==='AVAILABLE'&&agent.lastHeartbeatAt&&now-new Date(agent.lastHeartbeatAt).getTime()<90000)};});return{config,summary:{agents:input.agents.length,online,available,openBacklog:Number(input.backlog.open||0),unassignedBacklog:Number(input.backlog.unassigned||0),criticalBacklog:Number(input.backlog.critical||0),overdueBacklog:Number(input.backlog.firstResponseOverdue||0)+Number(input.backlog.resolutionOverdue||0),understaffedSlots:projection.slots.filter(s=>s.gapAgents>0).length,criticalForecastSlots:projection.slots.filter(s=>s.severity==='CRITICAL').length},sampleSize:projection.sampleSize,forecastTimezone:config.forecastTimezone,forecast:projection.slots,recommendations:projection.recommendations,dominant:projection.overall,agents:scheduledHours,shifts:input.shifts,alerts:input.alerts};}

  async createShift(user:AuthenticatedUser,body:Record<string,unknown>){const agentId=String(body.agentId??'');const agent=await this.prisma.$queryRaw<Array<{id:string}>>`SELECT id FROM "User" WHERE id=${agentId}::uuid AND "organizationId"=${user.organizationId}::uuid AND "isActive"=TRUE AND role IN ('OWNER','ADMIN','OPERATOR') LIMIT 1`;if(!agent[0])throw new NotFoundException('Agent introuvable');const startsAt=this.date(body.startsAt,'Début');const endsAt=this.date(body.endsAt,'Fin');if(endsAt<=startsAt)throw new BadRequestException('La fin doit être après le début');if(endsAt.getTime()-startsAt.getTime()>14*86400000)throw new BadRequestException('Un shift ne peut pas dépasser 14 jours');const note=String(body.note??'').trim().slice(0,500)||null;const rows=await this.prisma.$queryRaw<any[]>`INSERT INTO "AgentWorkShift" ("organizationId","userId","startsAt","endsAt",note,"createdByUserId") VALUES (${user.organizationId}::uuid,${agentId}::uuid,${startsAt},${endsAt},${note},${user.id}::uuid) RETURNING *`;return rows[0];}

  async updateShift(user:AuthenticatedUser,id:string,body:Record<string,unknown>){const existing=await this.prisma.$queryRaw<ShiftRow[]>`SELECT s.*,u.email "agentEmail",u."firstName" "agentFirstName",u."lastName" "agentLastName" FROM "AgentWorkShift" s JOIN "User" u ON u.id=s."userId" WHERE s.id=${id}::uuid AND s."organizationId"=${user.organizationId}::uuid LIMIT 1`;const shift=existing[0];if(!shift)throw new NotFoundException('Shift introuvable');const startsAt=body.startsAt===undefined?new Date(shift.startsAt):this.date(body.startsAt,'Début');const endsAt=body.endsAt===undefined?new Date(shift.endsAt):this.date(body.endsAt,'Fin');if(endsAt<=startsAt)throw new BadRequestException('La fin doit être après le début');const requested=body.status===undefined?shift.status:String(body.status).toUpperCase();if(!['PLANNED','CANCELLED','COMPLETED'].includes(requested))throw new BadRequestException('Statut de shift invalide');const note=body.note===undefined?shift.note:String(body.note??'').trim().slice(0,500)||null;const rows=await this.prisma.$queryRaw<any[]>`UPDATE "AgentWorkShift" SET "startsAt"=${startsAt},"endsAt"=${endsAt},status=${requested},note=${note},"updatedAt"=CURRENT_TIMESTAMP WHERE id=${id}::uuid AND "organizationId"=${user.organizationId}::uuid RETURNING *`;return rows[0];}

  async acknowledgeAlert(user:AuthenticatedUser,id:string){const rows=await this.prisma.$queryRaw<any[]>`UPDATE "WorkforceAlert" SET status='ACKNOWLEDGED',"acknowledgedByUserId"=${user.id}::uuid,"acknowledgedAt"=CURRENT_TIMESTAMP,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${id}::uuid AND "organizationId"=${user.organizationId}::uuid RETURNING *`;if(!rows[0])throw new NotFoundException('Alerte introuvable');return rows[0];}

  async pulse(user:AuthenticatedUser){const config=await this.config(user.organizationId);if(!config.enabled)return{processed:false,reason:'disabled'};const gate=await this.prisma.$queryRaw<any[]>`UPDATE "WorkforceIntelligenceConfig" SET "lastPulseAt"=CURRENT_TIMESTAMP WHERE "organizationId"=${user.organizationId}::uuid AND ("lastPulseAt" IS NULL OR "lastPulseAt"<CURRENT_TIMESTAMP-INTERVAL '5 minutes') RETURNING "lastPulseAt"`;if(!gate[0])return{processed:false,reason:'throttled'};const data=await this.dashboard(user,1);const upcoming=data.forecast.slice(0,Math.ceil(6*60/config.slotMinutes));const first=upcoming[0],last=upcoming[upcoming.length-1];if(first&&last)await this.prisma.$executeRaw`UPDATE "WorkforceAlert" SET status='RESOLVED',"updatedAt"=CURRENT_TIMESTAMP WHERE "organizationId"=${user.organizationId}::uuid AND status='OPEN' AND "slotStart">=${new Date(first.slotStart)} AND "slotStart"<=${new Date(last.slotStart)}`;let created=0;for(const slot of upcoming.filter((s:any)=>s.gapAgents>=config.alertGapAgents)){const inserted=await this.prisma.$queryRaw<any[]>`INSERT INTO "WorkforceAlert" ("organizationId","slotStart","slotEnd",severity,"requiredAgents","scheduledAgents","gapAgents",languages,topics,"countryCodes") VALUES (${user.organizationId}::uuid,${new Date(slot.slotStart)},${new Date(slot.slotEnd)},${slot.severity},${slot.requiredAgents},${slot.scheduledAgents},${slot.gapAgents},${slot.languages}::text[],${slot.topics}::text[],${slot.countryCodes}::text[]) ON CONFLICT ("organizationId","slotStart","slotEnd") DO NOTHING RETURNING id`;if(inserted[0])created++;await this.prisma.$executeRaw`UPDATE "WorkforceAlert" SET severity=${slot.severity},"requiredAgents"=${slot.requiredAgents},"scheduledAgents"=${slot.scheduledAgents},"gapAgents"=${slot.gapAgents},languages=${slot.languages}::text[],topics=${slot.topics}::text[],"countryCodes"=${slot.countryCodes}::text[],status=CASE WHEN status='ACKNOWLEDGED' THEN status ELSE 'OPEN' END,"updatedAt"=CURRENT_TIMESTAMP WHERE "organizationId"=${user.organizationId}::uuid AND "slotStart"=${new Date(slot.slotStart)} AND "slotEnd"=${new Date(slot.slotEnd)}`;}await this.prisma.$executeRaw`UPDATE "WorkforceAlert" SET status='RESOLVED',"updatedAt"=CURRENT_TIMESTAMP WHERE "organizationId"=${user.organizationId}::uuid AND status IN ('OPEN','ACKNOWLEDGED') AND "slotEnd"<CURRENT_TIMESTAMP`;return{processed:true,created,openGaps:upcoming.filter((s:any)=>s.gapAgents>=config.alertGapAgents).length};}
}
