'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { PortalShell } from '@/components/portal-shell';
import { apiRequest } from '@/lib/api';

type PermissionMap=Record<string,boolean>;
type Member={id:string;email:string;firstName?:string|null;lastName?:string|null;phone?:string|null;role:string;isActive:boolean;permissions:PermissionMap;permissionOverrides?:PermissionMap;createdAt:string};
type Invitation={id:string;email:string;role:string;permissions:PermissionMap;permissionOverrides?:PermissionMap;expiresAt:string;createdAt:string};
type TeamPayload={availablePermissions:string[];members:Member[];invitations:Invitation[]};
const ROLES=['ADMIN','OPERATOR','SHARE_HOST'] as const;
const LABELS:Record<string,string>={
'dashboard.view':'Voir Dashboard','clients.view':'Voir clients','clients.manage':'Modifier clients','clients.delete':'Supprimer clients','events.view':'Voir événements','events.manage':'Créer/modifier événements','events.delete':'Supprimer événements','studio.view':'Voir Studio/Presets','studio.manage':'Modifier Studio/Presets','studio.delete':'Supprimer Presets','marketing.view':'Voir Marketing','marketing.manage':'Gérer Marketing','communications.manage':'Communications clients','site.manage':'Configurer le site','billing.manage':'Gérer facturation','team.manage':'Gérer équipe','reports.export':'Exporter rapports'};

export default function TeamPage(){
 const[data,setData]=useState<TeamPayload|null>(null);const[message,setMessage]=useState('');const[error,setError]=useState('');const[email,setEmail]=useState('');const[role,setRole]=useState('OPERATOR');const[invitePermissions,setInvitePermissions]=useState<PermissionMap>({});const[busy,setBusy]=useState(false);
 const load=useCallback(()=>apiRequest<TeamPayload>('/team').then(setData).catch((e)=>setError(e instanceof Error?e.message:'Équipe indisponible')),[]);useEffect(()=>{void load();},[load]);
 const grouped=useMemo(()=>{const values=data?.availablePermissions||[];return{Gestion:values.filter((p)=>p.includes('clients')||p.includes('events')||p.includes('studio')||p.includes('dashboard')),Marketing:values.filter((p)=>p.includes('marketing')||p.includes('communications')||p.includes('reports')),Administration:values.filter((p)=>p.includes('site')||p.includes('billing')||p.includes('team'))};},[data]);
 async function invite(){setBusy(true);setError('');setMessage('');try{const result=await apiRequest<{inviteUrl:string;emailSent:boolean}>('/team/invitations',{method:'POST',body:JSON.stringify({email,role,permissions:invitePermissions})});setMessage(result.emailSent?'✓ Invitation envoyée par e-mail.':`Invitation créée. E-mail serveur non configuré : ${result.inviteUrl}`);setEmail('');setInvitePermissions({});await load();}catch(e){setError(e instanceof Error?e.message:'Invitation impossible');}finally{setBusy(false);}}
 async function saveMember(member:Member,patch:Partial<Member>){setError('');setMessage('Enregistrement…');try{await apiRequest(`/team/members/${member.id}`,{method:'PATCH',body:JSON.stringify({role:patch.role??member.role,isActive:patch.isActive??member.isActive,permissions:patch.permissionOverrides??member.permissionOverrides??{}})});await load();setMessage('✓ Autorisations mises à jour.');}catch(e){setError(e instanceof Error?e.message:'Modification impossible');}}
 function updateLocal(memberId:string,patch:Partial<Member>){setData((current)=>current?{...current,members:current.members.map((member)=>member.id===memberId?{...member,...patch}:member)}:current);}
 if(!data)return <PortalShell><h1>Équipe</h1><p>{error||'Chargement…'}</p></PortalShell>;
 return <PortalShell><div className="page-header"><div><div className="eyebrow">ÉQUIPE & SÉCURITÉ</div><h1>Membres et autorisations</h1><p className="muted">Invitez d’autres utilisateurs, assignez un rôle puis ajustez leurs permissions individuellement.</p></div></div>{error?<p className="error">{error}</p>:null}{message?<p className="success">{message}</p>:null}
 <section className="card" style={{display:'grid',gap:14}}><h2 style={{margin:0}}>Inviter un membre</h2><div className="grid two"><label>E-mail<input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} placeholder="membre@entreprise.ch"/></label><label>Rôle<select value={role} onChange={(e)=>setRole(e.target.value)}>{ROLES.map((item)=><option key={item}>{item}</option>)}</select></label></div><div className="grid three">{Object.entries(grouped).map(([group,permissions])=><div key={group}><strong>{group}</strong><div style={{display:'grid',gap:7,marginTop:8}}>{permissions.map((permission)=><label key={permission} style={{display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" checked={Boolean(invitePermissions[permission])} onChange={(e)=>setInvitePermissions({...invitePermissions,[permission]:e.target.checked})}/><span>{LABELS[permission]||permission}</span></label>)}</div></div>)}</div><button className="button" disabled={busy||!email} onClick={()=>void invite()}>{busy?'Création…':'Envoyer l’invitation'}</button></section>
 <div style={{height:16}}/><div className="grid two">{data.members.map((member)=>{const overrides=member.permissionOverrides||{};return <section className="card" key={member.id} style={{display:'grid',gap:12}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><div><strong>{[member.firstName,member.lastName].filter(Boolean).join(' ')||member.email}</strong><div className="muted" style={{fontSize:12}}>{member.email}</div></div><span style={{padding:'6px 9px',borderRadius:999,background:member.isActive?'#e0f3e7':'#f5dddd',fontSize:11,fontWeight:900}}>{member.isActive?'ACTIF':'DÉSACTIVÉ'}</span></div><label>Rôle<select disabled={member.role==='OWNER'} value={member.role} onChange={(e)=>updateLocal(member.id,{role:e.target.value})}><option>OWNER</option><option>ADMIN</option><option>OPERATOR</option><option>SHARE_HOST</option></select></label><div style={{display:'grid',gap:6,maxHeight:260,overflow:'auto',paddingRight:4}}>{data.availablePermissions.map((permission)=><label key={permission} style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center',padding:'7px 9px',borderRadius:10,background:'#f8f5f0'}}><span style={{fontSize:12}}>{LABELS[permission]||permission}</span><input type="checkbox" disabled={member.role==='OWNER'} checked={member.role==='OWNER'?true:Boolean(member.permissions[permission])} onChange={(e)=>{const next={...overrides,[permission]:e.target.checked};updateLocal(member.id,{permissionOverrides:next,permissions:{...member.permissions,[permission]:e.target.checked}});}}/></label>)}</div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{member.role!=='OWNER'?<button className="button secondary" onClick={()=>void saveMember(member,{})}>Enregistrer les droits</button>:null}{member.role!=='OWNER'?<button className="button secondary" onClick={()=>void saveMember(member,{isActive:!member.isActive})}>{member.isActive?'Désactiver':'Réactiver'}</button>:null}</div></section>})}</div>
 {data.invitations.length?<><div style={{height:16}}/><section className="card"><h2>Invitations en attente</h2>{data.invitations.map((invitation)=><div key={invitation.id} style={{display:'flex',justifyContent:'space-between',gap:12,padding:'10px 0',borderBottom:'1px solid #eee'}}><div><strong>{invitation.email}</strong><div className="muted">{invitation.role} · expire le {new Date(invitation.expiresAt).toLocaleDateString('fr-CH')}</div></div><button className="button secondary" onClick={()=>void apiRequest(`/team/invitations/${invitation.id}`,{method:'DELETE'}).then(load)}>Révoquer</button></div>)}</section></>:null}
 </PortalShell>;
}
