'use client';

import { useParams } from 'next/navigation';
import { ChangeEvent, useCallback, useEffect, useMemo, useState } from 'react';

const configuredApiUrl=process.env.NEXT_PUBLIC_API_URL?.trim();
const API_URL=configuredApiUrl?configuredApiUrl.replace(/\/$/,''):process.env.NODE_ENV==='production'?'https://khebooth-api.vercel.app/api':'http://localhost:3001/api';

const COUNTRIES=[['CH','Suisse'],['FR','France'],['BE','Belgique'],['DE','Allemagne'],['IT','Italie'],['ES','Espagne'],['PT','Portugal'],['NL','Pays-Bas'],['LU','Luxembourg'],['AT','Autriche'],['IE','Irlande'],['GB','Royaume-Uni'],['CM','Cameroun'],['CI','Côte d’Ivoire'],['SN','Sénégal'],['MA','Maroc'],['DZ','Algérie'],['TN','Tunisie'],['NG','Nigeria'],['GH','Ghana'],['ZA','Afrique du Sud'],['KE','Kenya'],['CD','RDC'],['CG','Congo'],['GA','Gabon'],['EG','Égypte'],['US','États-Unis'],['CA','Canada'],['MX','Mexique'],['BR','Brésil'],['AR','Argentine'],['CL','Chili'],['CO','Colombie'],['PE','Pérou'],['AE','Émirats arabes unis'],['SA','Arabie saoudite'],['QA','Qatar'],['IN','Inde'],['CN','Chine'],['JP','Japon'],['KR','Corée du Sud'],['SG','Singapour'],['TH','Thaïlande'],['VN','Vietnam'],['PH','Philippines'],['ID','Indonésie'],['MY','Malaisie'],['AU','Australie'],['NZ','Nouvelle-Zélande']];

type Field={key:string;label:string;type?:string;required?:boolean;min?:number;max?:number};
type FormData={client:{name:string;email?:string|null;companyName?:string|null};onboarding:{status:string;countryCode:string;desiredUsers:number;answers:Record<string,unknown>;privacyAcceptedAt?:string|null;truthConfirmedAt?:string|null;submittedAt?:string|null;reviewNotes?:string|null;rejectionReason?:string|null};template:{name:string;jurisdiction:string;fields:Field[];privacyNotice:string;legalReviewRequired:boolean;identityRequirements:Record<string,unknown>};documents:Array<{id:string;documentType:string;originalFileName:string;status:string;uploadedAt:string;rejectionReason?:string|null}>;security:{manualReview:boolean;platformAccessAutomatic:boolean;ownerApprovalRequired:boolean}};

async function publicRequest<T>(path:string,init:RequestInit={}):Promise<T>{const headers=new Headers(init.headers);if(init.body)headers.set('Content-Type','application/json');const response=await fetch(`${API_URL}${path}`,{...init,headers,cache:'no-store'});if(!response.ok){let message=`Erreur (${response.status})`;try{const data=await response.json() as {message?:string|string[]};message=Array.isArray(data.message)?data.message.join(', '):data.message||message;}catch{}throw new Error(message);}return response.json() as Promise<T>;}

export default function EnterpriseOnboardingPage(){
  const params=useParams<{token:string}>();const token=String(params?.token||'');
  const[data,setData]=useState<FormData|null>(null);const[answers,setAnswers]=useState<Record<string,unknown>>({});const[countryCode,setCountryCode]=useState('CH');const[desiredUsers,setDesiredUsers]=useState(1);const[privacyAccepted,setPrivacyAccepted]=useState(false);const[truthConfirmed,setTruthConfirmed]=useState(false);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');

  const hydrate=useCallback((next:FormData)=>{setData(next);setAnswers(next.onboarding.answers||{});setCountryCode(next.onboarding.countryCode||'CH');setDesiredUsers(next.onboarding.desiredUsers||1);setPrivacyAccepted(Boolean(next.onboarding.privacyAcceptedAt));setTruthConfirmed(Boolean(next.onboarding.truthConfirmedAt));},[]);
  const load=useCallback(async()=>{if(!token)return;setLoading(true);setError('');try{hydrate(await publicRequest<FormData>(`/enterprise/onboarding/${encodeURIComponent(token)}`));}catch(caught){setError(caught instanceof Error?caught.message:'Lien Enterprise indisponible.');}finally{setLoading(false);}},[token,hydrate]);
  useEffect(()=>{void load();},[load]);

  async function save(submit=false){setBusy(true);setError('');setMessage('');try{const next=await publicRequest<FormData>(`/enterprise/onboarding/${encodeURIComponent(token)}`,{method:'PATCH',body:JSON.stringify({countryCode,desiredUsers,answers,privacyAccepted,truthConfirmed,submit})});hydrate(next);setMessage(submit?'Formulaire envoyé. Ajoutez maintenant les justificatifs requis.':'Brouillon enregistré et formulaire adapté au pays.');}catch(caught){setError(caught instanceof Error?caught.message:'Enregistrement impossible.');}finally{setBusy(false);}}

  async function uploadDocument(documentType:string,file:File){setBusy(true);setError('');setMessage('');try{const ticket=await publicRequest<{pathname:string;uploadUrl:string;documentType:string;originalFileName:string}>(`/enterprise/onboarding/${encodeURIComponent(token)}/documents/upload`,{method:'POST',body:JSON.stringify({documentType,contentType:file.type,byteSize:file.size,originalFileName:file.name})});const uploaded=await fetch(ticket.uploadUrl,{method:'PUT',headers:{'Content-Type':file.type},body:file});if(!uploaded.ok)throw new Error(`Upload cloud impossible (${uploaded.status})`);await publicRequest(`/enterprise/onboarding/${encodeURIComponent(token)}/documents/confirm`,{method:'POST',body:JSON.stringify({pathname:ticket.pathname,documentType,originalFileName:file.name})});setMessage('Document transmis de manière sécurisée.');await load();}catch(caught){setError(caught instanceof Error?caught.message:'Transmission impossible.');}finally{setBusy(false);}}

  const statusLabel=useMemo(()=>({PAYMENT_PENDING:'Paiement en attente',FORM_AVAILABLE:'Formulaire à compléter',FORM_SUBMITTED:'Formulaire envoyé',IDENTITY_PENDING:'Justificatifs requis',UNDER_REVIEW:'Vérification KHE en cours',CHANGES_REQUESTED:'Complément demandé',VERIFIED:'Vérifié par un agent KHE',APPROVED:'Dossier approuvé',REJECTED:'Dossier refusé'} as Record<string,string>)[data?.onboarding.status||'']||data?.onboarding.status||'',[data]);

  if(loading)return <main style={styles.page}><section style={styles.card}><p>Chargement du formulaire sécurisé KHE BOOTH…</p></section></main>;
  if(!data)return <main style={styles.page}><section style={styles.card}><h1>KHE BOOTH Enterprise</h1><p style={{color:'#ffaaaa'}}>{error||'Lien invalide ou expiré.'}</p></section></main>;

  const closed=['APPROVED','REJECTED'].includes(data.onboarding.status);
  return <main style={styles.page}>
    <section style={styles.hero}><div><div style={styles.kicker}>KURTIS HYPNOTIC EVENTS • KHE BOOTH</div><h1 style={{margin:'8px 0 6px',fontSize:'clamp(30px,5vw,52px)'}}>Onboarding Enterprise</h1><p style={{color:'#c7ccd3',maxWidth:720}}>Un formulaire simple, sécurisé et adapté à votre pays pour préparer votre accès KHE BOOTH Enterprise.</p></div><span style={styles.status}>{statusLabel}</span></section>
    {error?<p style={styles.error}>{error}</p>:null}{message?<p style={styles.success}>{message}</p>:null}

    <section style={styles.card}><h2 style={{marginTop:0}}>Votre dossier</h2><div style={styles.summary}><div><small>CLIENT</small><strong>{data.client.name}</strong></div><div><small>E-MAIL</small><strong>{data.client.email||'—'}</strong></div><div><small>FORMULAIRE</small><strong>{data.template.name}</strong></div></div></section>

    <section style={styles.card}><div style={styles.sectionHead}><div><div style={styles.kicker}>01 • PAYS & IDENTITÉ ENTREPRISE</div><h2>Informations de l’entreprise</h2></div><button style={styles.secondaryButton} disabled={busy||closed} onClick={()=>void save(false)}>Adapter au pays</button></div>
      <label style={styles.label}>Pays d’enregistrement *</label><select style={styles.input} value={countryCode} disabled={closed} onChange={(event)=>setCountryCode(event.target.value)}>{COUNTRIES.map(([value,label])=><option key={value} value={value}>{label} ({value})</option>)}</select>
      <div style={styles.grid}>{(data.template.fields||[]).map((field)=>{if(field.key==='desiredUsers')return null;const value=String(answers[field.key]??'');return <div key={field.key} style={field.type==='textarea'?{gridColumn:'1 / -1'}:undefined}><label style={styles.label}>{field.label}{field.required?' *':''}</label>{field.type==='textarea'?<textarea style={{...styles.input,minHeight:100}} value={value} disabled={closed} onChange={(e)=>setAnswers(current=>({...current,[field.key]:e.target.value}))}/>:<input style={styles.input} type={field.type==='url'?'url':'text'} value={value} disabled={closed} onChange={(e)=>setAnswers(current=>({...current,[field.key]:e.target.value}))}/>}</div>;})}</div>
      <label style={styles.label}>Nombre d’utilisateurs / membres de votre équipe *</label><input style={styles.input} type="number" min={1} max={10000} value={desiredUsers} disabled={closed} onChange={(e)=>setDesiredUsers(Math.max(1,Number(e.target.value)||1))}/>
      <div style={styles.notice}><strong>Confidentialité</strong><p>{data.template.privacyNotice}</p>{data.template.legalReviewRequired?<p style={{color:'#e9c86c'}}>Le modèle applicable à ce pays contient une base internationale et peut nécessiter une adaptation juridique locale par KHE.</p>:null}</div>
      <label style={styles.check}><input type="checkbox" checked={privacyAccepted} disabled={closed} onChange={(e)=>setPrivacyAccepted(e.target.checked)}/> J’ai lu l’information relative au traitement de mes données.</label>
      <label style={styles.check}><input type="checkbox" checked={truthConfirmed} disabled={closed} onChange={(e)=>setTruthConfirmed(e.target.checked)}/> Je confirme que les informations fournies sont exactes et que je suis habilité(e) à représenter l’entreprise.</label>
      <div style={styles.actions}><button style={styles.secondaryButton} disabled={busy||closed} onClick={()=>void save(false)}>Enregistrer le brouillon</button><button style={styles.primaryButton} disabled={busy||closed} onClick={()=>void save(true)}>Envoyer le formulaire</button></div>
    </section>

    <section style={styles.card}><div style={styles.kicker}>02 • VERSION MANUELLE</div><h2>Télécharger et remplir hors ligne</h2><p style={{color:'#aeb5bf'}}>Vous pouvez télécharger le formulaire, le compléter manuellement puis le remettre dans cet espace.</p><div style={styles.actions}>{['pdf','docx','xlsx'].map(format=><a key={format} style={styles.secondaryButton as any} href={`${API_URL}/enterprise/onboarding/${encodeURIComponent(token)}/export/${format}`}>Télécharger {format==='docx'?'Word':format==='xlsx'?'Excel':'PDF'}</a>)}</div>
      <label style={styles.label}>Remettre un formulaire complété</label><input type="file" accept=".pdf,.docx,.xlsx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" disabled={busy||closed} onChange={(event)=>{const file=event.target.files?.[0];if(!file)return;const type=file.name.toLowerCase().endsWith('.docx')?'MANUAL_FORM_DOCX':file.name.toLowerCase().endsWith('.xlsx')?'MANUAL_FORM_XLSX':'MANUAL_FORM_PDF';void uploadDocument(type,file);}}/>
    </section>

    <section style={styles.card}><div style={styles.kicker}>03 • VÉRIFICATION D’IDENTITÉ</div><h2>Justificatifs sécurisés</h2><p style={{color:'#aeb5bf'}}>Après le formulaire, KHE BOOTH demande une pièce d’identité ou un passeport valable et une preuve de domicile. Ces fichiers sont privés et accessibles uniquement aux personnes KHE autorisées à vérifier votre dossier.</p>
      <div style={styles.grid}><div><label style={styles.label}>Pièce d’identité</label><select id="identity-type" style={styles.input} defaultValue="PASSPORT"><option value="PASSPORT">Passeport</option><option value="IDENTITY_CARD">Carte d’identité</option></select><input style={{marginTop:10}} type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,application/pdf,image/jpeg,image/png,image/webp" disabled={busy||closed} onChange={(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;const select=document.getElementById('identity-type') as HTMLSelectElement|null;void uploadDocument(select?.value||'PASSPORT',file);}}/></div><div><label style={styles.label}>Preuve de domicile</label><input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,application/pdf,image/jpeg,image/png,image/webp" disabled={busy||closed} onChange={(event)=>{const file=event.target.files?.[0];if(file)void uploadDocument('PROOF_OF_ADDRESS',file);}}/></div></div>
      <div style={{display:'grid',gap:8,marginTop:18}}>{data.documents.length===0?<p style={{color:'#838b96'}}>Aucun document transmis.</p>:data.documents.map(doc=><div key={doc.id} style={styles.doc}><div><strong>{doc.originalFileName}</strong><div style={{fontSize:12,color:'#929aa5'}}>{doc.documentType}</div></div><span style={{fontWeight:900,color:doc.status==='VERIFIED'?'#8fe0aa':doc.status==='REJECTED'?'#ff9d9d':'#e9c86c'}}>{doc.status}</span></div>)}</div>
    </section>

    <section style={styles.card}><div style={styles.kicker}>04 • VALIDATION KHE</div><h2>Accès sous contrôle</h2><p style={{color:'#c3c8cf'}}>Le paiement seul n’ouvre pas la plateforme. Un agent KHE vérifie le formulaire et les justificatifs. Le OWNER KHE BOOTH conserve l’approbation finale avant activation du tenant Enterprise.</p>{data.onboarding.reviewNotes?<div style={styles.notice}><strong>Message de l’équipe KHE</strong><p>{data.onboarding.reviewNotes}</p></div>:null}{data.onboarding.rejectionReason?<p style={styles.error}>{data.onboarding.rejectionReason}</p>:null}</section>
  </main>;
}

const styles:Record<string,React.CSSProperties>={page:{minHeight:'100vh',background:'radial-gradient(circle at 15% 0%,#34260c 0,#0b0d11 36%,#060709 100%)',color:'#f5f6f8',padding:'34px 16px 80px',fontFamily:'Arial,sans-serif'},hero:{maxWidth:1040,margin:'0 auto 18px',padding:'24px 26px',border:'1px solid rgba(218,178,78,.35)',borderRadius:24,background:'linear-gradient(145deg,rgba(24,28,34,.96),rgba(18,15,8,.96))',display:'flex',justifyContent:'space-between',gap:20,alignItems:'flex-start',flexWrap:'wrap'},card:{maxWidth:1040,margin:'14px auto',padding:'24px',border:'1px solid #292f38',borderRadius:22,background:'rgba(16,19,24,.96)',boxShadow:'0 18px 50px rgba(0,0,0,.22)'},kicker:{fontSize:11,fontWeight:900,letterSpacing:2,color:'#d7b45a'},status:{padding:'9px 13px',borderRadius:999,background:'#2b2413',border:'1px solid #6c5826',color:'#efd77d',fontWeight:900,fontSize:12},sectionHead:{display:'flex',justifyContent:'space-between',alignItems:'flex-start',gap:14,flexWrap:'wrap'},summary:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12},grid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:14,marginTop:14},label:{display:'block',fontSize:12,fontWeight:850,color:'#c9cdd3',margin:'13px 0 7px'},input:{width:'100%',boxSizing:'border-box',padding:'12px 13px',border:'1px solid #363d47',borderRadius:12,background:'#0b0e12',color:'#fff',fontSize:15},notice:{marginTop:18,padding:'15px 16px',border:'1px solid #55451f',borderRadius:14,background:'#1a160d',color:'#d8dbe0',lineHeight:1.55},check:{display:'flex',gap:10,alignItems:'flex-start',marginTop:14,color:'#d5d8dd',fontSize:14},actions:{display:'flex',gap:10,flexWrap:'wrap',marginTop:18},primaryButton:{display:'inline-block',border:0,borderRadius:12,padding:'12px 16px',background:'linear-gradient(135deg,#d6b24f,#9d7621)',color:'#111',fontWeight:950,cursor:'pointer',textDecoration:'none'},secondaryButton:{display:'inline-block',border:'1px solid #59616d',borderRadius:12,padding:'11px 15px',background:'#171b21',color:'#fff',fontWeight:850,cursor:'pointer',textDecoration:'none'},doc:{display:'flex',justifyContent:'space-between',gap:14,alignItems:'center',padding:'12px 14px',border:'1px solid #303741',borderRadius:12,background:'#0d1014'},error:{maxWidth:1040,margin:'12px auto',padding:'12px 15px',borderRadius:12,background:'#3a1717',color:'#ffb2b2'},success:{maxWidth:1040,margin:'12px auto',padding:'12px 15px',borderRadius:12,background:'#14301f',color:'#9de2b3'}};
