'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { PortalShell } from '@/components/portal-shell';
import { apiRequest } from '@/lib/api';

type ApplicationItem={id:string;applicationNumber:string;status:string;firstName:string;lastName:string;email:string;city:string;countryCode:string;experienceYears:number;documentCount:number;pendingDocumentCount:number;submittedAt:string};
const STATUS:Record<string,string>={SUBMITTED:'Reçue',UNDER_REVIEW:'En revue',CHANGES_REQUESTED:'Complément demandé',CONTRACT_PENDING:'Contrat en attente',CONTRACT_SIGNED:'Contrat signé',ACTIVATION_SENT:'Activation envoyée',ACTIVATED:'Agent activé',REJECTED:'Refusée'};

export default function ApplicationsPage(){const[items,setItems]=useState<ApplicationItem[]>([]);const[statuses,setStatuses]=useState<string[]>([]);const[status,setStatus]=useState('');const[search,setSearch]=useState('');const[error,setError]=useState('');const[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);try{const query=new URLSearchParams();if(status)query.set('status',status);if(search.trim())query.set('search',search.trim());const data=await apiRequest<{items:ApplicationItem[];statuses:string[]}>(`/agent-recruitment/applications?${query}`);setItems(data.items);setStatuses(data.statuses);setError('');}catch(caught){setError(caught instanceof Error?caught.message:'Chargement impossible');}finally{setLoading(false);}},[search,status]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),search?350:0);return()=>window.clearTimeout(timer);},[load,search]);
 const summary=useMemo(()=>({new:items.filter((item)=>item.status==='SUBMITTED').length,review:items.filter((item)=>['UNDER_REVIEW','CHANGES_REQUESTED'].includes(item.status)).length,contracts:items.filter((item)=>['CONTRACT_PENDING','CONTRACT_SIGNED'].includes(item.status)).length,ready:items.filter((item)=>item.status==='CONTRACT_SIGNED'&&item.pendingDocumentCount===0).length}),[items]);
 return <PortalShell><div style={{display:'grid',gap:20}}><header className="application-list-header"><div><div className="eyebrow">KHE BOOTH · RECRUTEMENT</div><h1 style={{fontSize:'clamp(30px,5vw,48px)',margin:'8px 0'}}>Candidatures agents</h1><p className="muted" style={{margin:0}}>Du premier contact jusqu’à l’activation et à la présence de l’agent dans les opérations.</p></div><Link className="button secondary" href="/become-agent" target="_blank">Voir le formulaire public ↗</Link></header><section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:12}}><Metric label="Nouvelles" value={summary.new}/><Metric label="En revue" value={summary.review}/><Metric label="Contrats" value={summary.contracts}/><Metric label="Prêtes à activer" value={summary.ready}/></section><section className="card"><div className="application-filters"><input aria-label="Rechercher" placeholder="Nom, e-mail ou n° dossier…" value={search} onChange={(event)=>setSearch(event.target.value)}/><select aria-label="Filtrer par statut" value={status} onChange={(event)=>setStatus(event.target.value)}><option value="">Tous les statuts</option>{statuses.map((value)=><option value={value} key={value}>{STATUS[value]||value}</option>)}</select><button className="button secondary" type="button" onClick={()=>void load()}>Actualiser</button></div></section>{error?<p className="error">{error}</p>:null}<section className="application-cards">{loading?<div className="empty">Chargement des dossiers…</div>:items.length?items.map((item)=><article className="application-card" key={item.id}><div><strong>{item.firstName} {item.lastName}</strong><small>{item.applicationNumber}<br/>{item.email}</small></div><div><small>Statut</small><br/><span className="status-badge">{STATUS[item.status]||item.status}</span></div><div><small>Zone</small><br/><strong>{item.city} · {item.countryCode}</strong></div><div><small>Documents</small><br/><strong>{item.documentCount||0}</strong>{item.pendingDocumentCount?<small> · {item.pendingDocumentCount} à vérifier</small>:null}</div><Link className="button" href={`/applications/${item.id}`}>Ouvrir le dossier</Link></article>):<div className="empty">Aucune candidature ne correspond à ces filtres.</div>}</section></div></PortalShell>}

function Metric({label,value}:{label:string;value:number}){return <article className="card"><div className="muted" style={{fontSize:12}}>{label}</div><div style={{fontSize:32,fontWeight:950,marginTop:8}}>{value}</div></article>}
