'use client';

import Link from 'next/link';
import { FormEvent, useState } from 'react';
const API_BASE=(process.env.NEXT_PUBLIC_API_URL||'https://khebooth-api.vercel.app/api').replace(/\/$/,'');

export default function ReviewPage(){
  const[email,setEmail]=useState('');const[kheCode,setKheCode]=useState('');const[displayName,setDisplayName]=useState('');const[rating,setRating]=useState(5);const[title,setTitle]=useState('');const[body,setBody]=useState('');const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setMessage('Vérification de votre abonnement…');try{const response=await fetch(`${API_BASE}/commerce/public/reviews`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,kheCode,displayName,rating,title,body})});const data=await response.json() as{message?:string};if(!response.ok)throw new Error(data.message||'Avis refusé');setMessage('✓ Merci. Votre avis d’abonné vérifié est publié sur KHE Booth.');}catch(e){setMessage(e instanceof Error?e.message:'Impossible de publier votre avis.');}finally{setBusy(false);}}
  return <main className="marketing-page" style={{minHeight:'100vh'}}><header className="marketing-nav"><Link className="marketing-brand" href="/">KHE <span>BOOTH</span></Link><Link className="marketing-login" href="/account/subscription">Mon abonnement</Link></header><section className="marketing-section"><div className="section-heading centered"><div className="marketing-kicker"><span/> AVIS VÉRIFIÉ</div><h1>Partagez votre expérience KHE Booth.</h1><p>Cette page est réservée aux clients ayant effectué un paiement d’abonnement vérifié.</p></div><form className="card" onSubmit={submit} style={{display:'grid',gap:14,maxWidth:680,margin:'0 auto'}}><label>Adresse e-mail<input required type="email" value={email} onChange={(e)=>setEmail(e.target.value)}/></label><label>KHE ID<input required value={kheCode} onChange={(e)=>setKheCode(e.target.value.toUpperCase())} placeholder="KHE-XXXXXXXXXX"/></label><label>Nom affiché<input value={displayName} onChange={(e)=>setDisplayName(e.target.value)} placeholder="Votre nom ou entreprise"/></label><label>Note<select value={rating} onChange={(e)=>setRating(Number(e.target.value))}>{[5,4,3,2,1].map((n)=><option key={n} value={n}>{'★'.repeat(n)}{'☆'.repeat(5-n)} · {n}/5</option>)}</select></label><label>Titre<input value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="Votre impression en quelques mots"/></label><label>Votre avis<textarea required minLength={10} maxLength={2000} rows={7} value={body} onChange={(e)=>setBody(e.target.value)} placeholder="Expliquez ce que KHE Booth vous apporte…"/></label><button className="button" disabled={busy}>{busy?'Vérification…':'Publier mon avis vérifié'}</button>{message?<p>{message}</p>:null}</form></section></main>;
}
