import Link from 'next/link';
import { headers } from 'next/headers';
import { AnalyticsBeacon } from '@/components/analytics-beacon';
import { CurrencySelector } from '@/components/currency-selector';
import { HowItWorksShowcase } from '@/components/how-it-works-showcase';
import { AddToCartButton, MarketingCart } from '@/components/marketing-cart';
import { PromoStoryReel } from '@/components/promo-story-reel';
import { SUBSCRIPTION_CATALOG } from '@/lib/subscriptions';

type Market={country:string;region?:string;currency:string;locale:string;unitSystem:'metric'|'imperial';billingUnit:'month'};
type RegionPolicy={enabled:boolean;showPrices:boolean;showDownload:boolean;showReviews:boolean;showPromoVideo:boolean;forceCurrency?:string;announcement?:string};
type Plan={code:string;name:string;tagline:string;priceMonthlyChf:number|null;priceMonthlyCents:number|null;currency:string;features:string[];highlighted:boolean};
type Site={heroTitle:string;heroSubtitle:string;primaryCta:string;appDownloadUrl?:string|null;latestVersion?:string;paymentMethods?:string[];faq?:Array<{question?:string;answer?:string}>;plans:Plan[];market:Market;supportedCurrencies:string[];regionPolicy?:RegionPolicy;media?:Record<string,string>};
type Promotion={id:string;name:string;planCode?:string|null;discountPercent:number;endsAt:string;messageTitle?:string|null;messageBody?:string|null}|null;
type Review={id:string;rating:number;title?:string|null;body:string;displayName:string;verifiedSubscriber:boolean};
const API=(process.env.NEXT_PUBLIC_API_URL||'https://khebooth-api.vercel.app/api').replace(/\/$/,'');
const fallbackMarket:Market={country:'CH',region:'SWITZERLAND',currency:'CHF',locale:'fr-CH',unitSystem:'metric',billingUnit:'month'};
const fallback:Site={heroTitle:'Transformez chaque événement en moment que l’on partage.',heroSubtitle:'Capture, création, cloud et partage invité réunis dans KHE Booth.',primaryCta:'Commencer avec KHE Booth',appDownloadUrl:'https://expo.dev/accounts/kurtis-hypnotic-event/projects/kurtis-hypnotic-events/builds',paymentMethods:['card','apple_pay','google_pay','twint'],market:fallbackMarket,supportedCurrencies:['CHF','EUR','GBP','USD','CAD','AUD'],regionPolicy:{enabled:true,showPrices:true,showDownload:true,showReviews:true,showPromoVideo:true},media:{},plans:SUBSCRIPTION_CATALOG.map((p)=>({code:p.id,name:p.name,tagline:p.tagline,priceMonthlyChf:p.priceMonthlyChf===null?null:Math.round(p.priceMonthlyChf*100),priceMonthlyCents:p.priceMonthlyChf===null?null:Math.round(p.priceMonthlyChf*100),currency:'CHF',features:[...p.features],highlighted:Boolean(p.highlighted)}))};
const FEATURE_DETAILS=[
  {title:'CAPTURE',summary:'Photo et vidéo offline-first.',detail:'Capturez même lorsque la connexion est instable. Les médias restent disponibles sur la station puis se synchronisent dès que le réseau revient.',benefits:['Formats photo et vidéo adaptés aux événements','Continuité de service hors connexion','Synchronisation sécurisée vers votre espace KHE'],cta:'Choisir une offre avec Capture'},
  {title:'SHARING',summary:'Galerie cloud sur une seconde station.',detail:'Séparez la captation et le partage : une station filme pendant qu’une autre permet aux invités de consulter et recevoir leurs médias.',benefits:['Galerie cloud actualisée rapidement','Expérience fluide avec deux stations','Partage sans interrompre la captation'],cta:'Activer le partage instantané'},
  {title:'STUDIO',summary:'Design, effets et musique.',detail:'Préparez une identité visuelle cohérente pour chaque événement avec les cadres, effets, textes et ambiances sonores de votre choix.',benefits:['Modèles réutilisables par événement','Personnalisation aux couleurs du client','Préparation avant l’arrivée sur le terrain'],cta:'Créer mon expérience Studio'},
  {title:'QR',summary:'Partage invité sécurisé.',detail:'Chaque parcours de partage utilise un accès conçu pour les invités afin de limiter les manipulations et accélérer la remise des médias.',benefits:['Accès simple depuis le téléphone','Lien invité adapté à l’événement','Partage plus rapide et mieux encadré'],cta:'Découvrir le partage QR'},
  {title:'ABONNEMENT',summary:'Paiement et statut automatisés.',detail:'Choisissez une formule adaptée à votre rythme d’activité et suivez votre statut, vos paiements et vos capacités depuis un seul espace.',benefits:['Offres lisibles selon votre niveau d’activité','Devise et paiement adaptés au marché','Gestion centralisée de la souscription'],cta:'Comparer les abonnements'},
  {title:'MARKETING',summary:'Analytics, campagnes et rapports PDF.',detail:'Transformez les signaux de consultation et de conversion en décisions concrètes pour améliorer vos offres et vos campagnes.',benefits:['Indicateurs de visites et de conversion','Segmentation par intention et zone consentie','Rapports exploitables pour le suivi commercial'],cta:'Développer ma visibilité'},
] as const;
async function get<T>(path:string,value:T):Promise<T>{try{const r=await fetch(`${API}${path}`,{cache:'no-store'});return r.ok?await r.json() as T:value;}catch{return value;}}
function money(cents:number,currency:string,locale:string){return new Intl.NumberFormat(locale,{style:'currency',currency,minimumFractionDigits:0,maximumFractionDigits:2}).format(cents/100);}
function period(locale:string){if(locale.startsWith('en'))return'/month';if(locale.startsWith('de'))return'/Monat';if(locale.startsWith('it'))return'/mese';if(locale.startsWith('es'))return'/mes';if(locale.startsWith('pt'))return'/mês';return'/mois';}

export default async function HomePage({searchParams}:{searchParams:Promise<{currency?:string}>}){
  const requestHeaders=await headers();const query=await searchParams;const country=requestHeaders.get('x-vercel-ip-country')||'CH';const requestedCurrency=(query.currency||'').toUpperCase();
  const sitePath=`/commerce/public/site?country=${encodeURIComponent(country)}${requestedCurrency?`&currency=${encodeURIComponent(requestedCurrency)}`:''}`;
  const[site,promo,reviews]=await Promise.all([get<Site>(sitePath,fallback),get<Promotion>('/marketing/public/promotion',null),get<Review[]>('/commerce/public/reviews',[])]);
  const faq=site.faq?.filter((x)=>x.question&&x.answer)??[];const market=site.market||fallbackMarket;const region=site.regionPolicy||fallback.regionPolicy!;const media=site.media||{};
  if(!region.enabled)return <main className="marketing-page"><header className="marketing-nav"><Link className="marketing-brand" href="/">KHE <span>BOOTH</span></Link><div className="marketing-nav-actions"><Link className="marketing-login" href="/login">Connexion</Link></div></header><section className="marketing-hero" style={{minHeight:'70vh',alignItems:'center'}}><div className="hero-copy"><div className="marketing-kicker"><span/> KHE BOOTH</div><h1>Service momentanément indisponible dans votre région.</h1><p className="hero-lead">Notre équipe prépare l’accès KHE Booth pour cette zone. La connexion à un compte existant reste disponible.</p><div className="hero-actions"><Link className="marketing-ghost" href="/login">Se connecter</Link></div></div></section></main>;
  return <main className="marketing-page"><AnalyticsBeacon/>
    <header className="marketing-nav"><Link className="marketing-brand" href="/">KHE <span>BOOTH</span></Link><nav className="marketing-nav-links"><a href="#features">Fonctionnalités</a><a href="#mode-emploi">Mode d’emploi</a>{region.showPrices?<a href="#tarifs">Tarifs</a>:null}{region.showReviews?<a href="#avis">Avis</a>:null}<a href="#faq">FAQ</a></nav><div className="marketing-nav-actions"><MarketingCart currency={market.currency} plans={site.plans.map((plan)=>{const base=plan.priceMonthlyCents;const applies=Boolean(promo&&(!promo.planCode||promo.planCode===plan.code)&&base&&base>0);const price=applies?Math.round(base!*(100-promo!.discountPercent)/100):base;return{code:plan.code,name:plan.name,tagline:plan.tagline,priceLabel:price===null?'Sur mesure':money(price,market.currency,market.locale)+period(market.locale)};})}/><CurrencySelector compact currency={market.currency} supportedCurrencies={site.supportedCurrencies||fallback.supportedCurrencies}/><Link className="marketing-login" href="/account/subscription">Mon abonnement</Link><Link className="marketing-login" href="/login">Connexion</Link></div></header>
    {region.announcement?<div style={{padding:'11px 20px',textAlign:'center',fontWeight:900,background:'#111',color:'#d2ad4f'}}>{region.announcement}</div>:promo?<div style={{padding:'11px 20px',textAlign:'center',fontWeight:900,background:'#d2ad4f',color:'#111'}}>{promo.messageTitle||promo.name} · -{promo.discountPercent}% jusqu’au {new Date(promo.endsAt).toLocaleDateString(market.locale)}</div>:null}
    <section className="marketing-hero"><div className="hero-glow hero-glow-one"/><div className="hero-copy"><div className="marketing-kicker"><span/> KURTIS HYPNOTIC EVENTS PRÉSENTE</div><h1>{site.heroTitle}</h1><p className="hero-lead">{site.heroSubtitle}</p><div className="hero-actions">{region.showPrices?<a className="marketing-cta" href="#tarifs">{site.primaryCta}</a>:<a className="marketing-cta" href="#features">{site.primaryCta}</a>}{region.showDownload&&site.appDownloadUrl?<a className="marketing-ghost" href={site.appDownloadUrl}>↓ Télécharger l’application</a>:null}</div><div className="hero-proof"><div><strong>2</strong><span>stations</span></div><div><strong>1</strong><span>profil synchronisé</span></div><div><strong>24/7</strong><span>automatisation</span></div></div></div><div className="hero-product"><div className="promo-device promo-device-front"><div className="device-top"><span>KHE BOOTH</span><b>CAPTURE</b></div><div className="capture-preview"><div className="capture-event">KHE EXPERIENCE</div><div className="capture-title">Capturez.<br/>Synchronisez.<br/>Partagez.</div><div className="capture-ring"><i/></div><div className="capture-controls"><span>9:16</span><span>CLOUD</span><span>QR</span></div></div></div></div></section>
    {region.showPromoVideo?<PromoStoryReel media={media}/>:null}
    <HowItWorksShowcase media={media}/>
    <section id="features" className="marketing-section"><div className="section-heading centered"><div className="marketing-kicker"><span/> PLATEFORME SAAS</div><h2>Tout est synchronisé.</h2><p>Choisissez une rubrique pour comprendre son fonctionnement, ses bénéfices et l’action recommandée.</p></div><div className="marketing-feature-grid">{FEATURE_DETAILS.map((feature,i)=><details className="marketing-feature marketing-feature-detail" key={feature.title}><summary><div className="feature-icon">0{i+1}</div><div className="feature-summary-copy"><h3>{feature.title}</h3><p>{feature.summary}</p></div><span className="feature-expand-icon" aria-hidden="true">+</span></summary><div className="feature-detail-body"><p>{feature.detail}</p><ul>{feature.benefits.map((benefit)=><li key={benefit}>{benefit}</li>)}</ul><a className="marketing-cta" href="#tarifs">{feature.cta} →</a></div></details>)}</div></section>
    {region.showPrices?<section id="tarifs" className="marketing-section pricing-section"><div className="section-heading centered"><div className="marketing-kicker"><span/> TARIFS LOCALISÉS</div><h2>Choisissez votre abonnement.</h2><p>Devise : <strong>{market.currency}</strong> · Pays : <strong>{market.country}</strong>. Ajoutez une offre au panier puis poursuivez vers la souscription sécurisée.</p></div><div className="pricing-grid">{site.plans.map((plan)=>{const base=plan.priceMonthlyCents;const applies=Boolean(promo&&(!promo.planCode||promo.planCode===plan.code)&&base&&base>0);const price=applies?Math.round(base!*(100-promo!.discountPercent)/100):base;const cartPlan={code:plan.code,name:plan.name,tagline:plan.tagline,priceLabel:price===null?'Sur mesure':money(price,market.currency,market.locale)+period(market.locale)};return <article className={'pricing-card'+(plan.highlighted?' pricing-highlighted':'')} key={plan.code}>{plan.highlighted?<div className="popular-tag">POPULAIRE</div>:null}{applies?<div className="eyebrow">OFFRE -{promo!.discountPercent}%</div>:null}<div className="pricing-name">{plan.name}</div><p>{plan.tagline}</p><div className="pricing-price">{price===null?<strong>Sur mesure</strong>:<><strong>{money(price,market.currency,market.locale)}</strong><small>{period(market.locale)}</small></>}</div>{applies&&base!==price?<p className="muted">au lieu de {money(base!,market.currency,market.locale)}</p>:null}<ul>{plan.features.map((feature)=><li key={feature}>✓ {feature}</li>)}</ul><div className="pricing-actions"><AddToCartButton plan={cartPlan}/><Link className="marketing-ghost pricing-button pricing-secondary-action" href={'/subscribe?plan='+encodeURIComponent(plan.code)+'&currency='+encodeURIComponent(market.currency)}>{plan.priceMonthlyChf===0?'Voir l’offre gratuite':plan.priceMonthlyChf===null?'Demander une offre':'Voir les détails de l’offre'}</Link></div></article>})}</div><p className="pricing-note">Paiements : {(site.paymentMethods??[]).map((method)=>method==='card'?'Carte':method==='apple_pay'?'Apple Pay':method==='google_pay'?'Google Pay':method==='twint'?'TWINT':method).join(' · ')}. TWINT est présenté en CHF.</p></section>:null}
    {region.showReviews?<section id="avis" className="marketing-section"><div className="section-heading centered"><div className="marketing-kicker"><span/> AVIS VÉRIFIÉS</div><h2>Les clients KHE Booth témoignent.</h2><p>Publication réservée aux abonnés ayant un paiement vérifié.</p></div>{reviews.length?<div className="marketing-feature-grid">{reviews.slice(0,6).map((r)=><article className="marketing-feature" key={r.id}><div style={{color:'#d2ad4f',fontSize:20}}>{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</div><h3>{r.title||'Expérience KHE Booth'}</h3><p>{r.body}</p><strong>{r.displayName}</strong><div className="muted">✓ Abonné vérifié</div></article>)}</div>:<div className="card" style={{maxWidth:680,margin:'0 auto',textAlign:'center'}}>Les premiers avis vérifiés apparaîtront ici.</div>}<div style={{textAlign:'center',marginTop:20}}><Link className="marketing-ghost" href="/review">Laisser un avis vérifié</Link></div></section>:null}
    <section id="faq" className="marketing-section faq-section"><div className="section-heading"><div className="marketing-kicker"><span/> FAQ</div><h2>Questions fréquentes.</h2></div><div className="faq-grid">{(faq.length?faq:[{question:'L’abonnement est-il renouvelé automatiquement ?',answer:'Oui pour les abonnements récurrents compatibles, après accord explicite. Il reste résiliable depuis Mon abonnement.'},{question:'TWINT est-il disponible ?',answer:'TWINT standard est disponible comme paiement ponctuel en CHF. Le débit TWINT récurrent nécessite un contrat marchand User on File.'},{question:'Comment la devise est-elle choisie ?',answer:'KHE Booth détecte le pays du visiteur et affiche une devise locale supportée. Le client peut aussi sélectionner manuellement une autre devise.'}]).map((x)=><article className="faq-item" key={x.question}><h3>{x.question}</h3><p>{x.answer}</p></article>)}</div></section>
    <section className="marketing-final-cta"><div><div className="marketing-kicker"><span/> PRÊT ?</div><h2>Activez KHE Booth maintenant.</h2><p>Le client doit comprendre l’expérience avant même l’installation : c’est pourquoi le site montre désormais le produit en action.</p></div><div className="final-actions">{region.showPrices?<Link className="marketing-cta" href={`/subscribe?currency=${market.currency}`}>Choisir mon abonnement</Link>:null}{region.showDownload&&site.appDownloadUrl?<a className="marketing-ghost" href={site.appDownloadUrl}>Télécharger l’application</a>:null}</div></section>
    <footer className="marketing-footer"><div><Link className="marketing-brand" href="/">KHE <span>BOOTH</span></Link><p>Une solution Kurtis Hypnotic Events.</p></div><div className="footer-links"><Link href="/account/subscription">Mon abonnement</Link>{region.showReviews?<Link href="/review">Avis</Link>:null}<Link href="/login">Connexion</Link></div><p className="footer-copy">© 2026 KHE Booth</p></footer>
  </main>;
}
