import Link from 'next/link';
import { AnalyticsBeacon } from '@/components/analytics-beacon';
import { SUBSCRIPTION_CATALOG } from '@/lib/subscriptions';

type Plan={code:string;name:string;tagline:string;priceMonthlyChf:number|null;features:string[];highlighted:boolean};
type Site={heroTitle:string;heroSubtitle:string;primaryCta:string;appDownloadUrl?:string|null;latestVersion?:string;paymentMethods?:string[];faq?:Array<{question?:string;answer?:string}>;plans:Plan[]};
type Promotion={id:string;name:string;planCode?:string|null;discountPercent:number;endsAt:string;messageTitle?:string|null;messageBody?:string|null}|null;
type Review={id:string;rating:number;title?:string|null;body:string;displayName:string;verifiedSubscriber:boolean};
const API=(process.env.NEXT_PUBLIC_API_URL||'https://khebooth-api.vercel.app/api').replace(/\/$/,'');
const fallback:Site={heroTitle:'Transformez chaque événement en moment que l’on partage.',heroSubtitle:'Capture, création, cloud et partage invité réunis dans KHE Booth.',primaryCta:'Commencer avec KHE Booth',appDownloadUrl:'https://expo.dev/accounts/kurtis-hypnotic-event/projects/kurtis-hypnotic-events/builds',paymentMethods:['card','apple_pay','google_pay','twint'],plans:SUBSCRIPTION_CATALOG.map((p)=>({code:p.id,name:p.name,tagline:p.tagline,priceMonthlyChf:p.priceMonthlyChf===null?null:Math.round(p.priceMonthlyChf*100),features:[...p.features],highlighted:Boolean(p.highlighted)}))};
async function get<T>(path:string,value:T):Promise<T>{try{const r=await fetch(`${API}${path}`,{cache:'no-store'});return r.ok?await r.json() as T:value;}catch{return value;}}

export default async function HomePage(){
  const[site,promo,reviews]=await Promise.all([get<Site>('/commerce/public/site',fallback),get<Promotion>('/marketing/public/promotion',null),get<Review[]>('/commerce/public/reviews',[])]);
  const faq=site.faq?.filter((x)=>x.question&&x.answer)??[];
  return <main className="marketing-page"><AnalyticsBeacon/>
    <header className="marketing-nav"><Link className="marketing-brand" href="/">KHE <span>BOOTH</span></Link><nav className="marketing-nav-links"><a href="#features">Fonctionnalités</a><a href="#tarifs">Tarifs</a><a href="#avis">Avis</a><a href="#faq">FAQ</a></nav><div className="marketing-nav-actions"><Link className="marketing-login" href="/account/subscription">Mon abonnement</Link><Link className="marketing-login" href="/login">Connexion</Link></div></header>
    {promo?<div style={{padding:'11px 20px',textAlign:'center',fontWeight:900,background:'#d2ad4f',color:'#111'}}>{promo.messageTitle||promo.name} · -{promo.discountPercent}% jusqu’au {new Date(promo.endsAt).toLocaleDateString('fr-CH')}</div>:null}
    <section className="marketing-hero"><div className="hero-glow hero-glow-one"/><div className="hero-copy"><div className="marketing-kicker"><span/> KURTIS HYPNOTIC EVENTS PRÉSENTE</div><h1>{site.heroTitle}</h1><p className="hero-lead">{site.heroSubtitle}</p><div className="hero-actions"><a className="marketing-cta" href="#tarifs">{site.primaryCta}</a>{site.appDownloadUrl?<a className="marketing-ghost" href={site.appDownloadUrl}>↓ Télécharger l’application</a>:null}</div><div className="hero-proof"><div><strong>2</strong><span>stations</span></div><div><strong>1</strong><span>profil synchronisé</span></div><div><strong>24/7</strong><span>automatisation</span></div></div></div><div className="hero-product"><div className="promo-device promo-device-front"><div className="device-top"><span>KHE BOOTH</span><b>CAPTURE</b></div><div className="capture-preview"><div className="capture-event">KHE EXPERIENCE</div><div className="capture-title">Capturez.<br/>Synchronisez.<br/>Partagez.</div><div className="capture-ring"><i/></div><div className="capture-controls"><span>9:16</span><span>CLOUD</span><span>QR</span></div></div></div></div></section>
    <section id="features" className="marketing-section"><div className="section-heading centered"><div className="marketing-kicker"><span/> PLATEFORME SAAS</div><h2>Tout est synchronisé.</h2></div><div className="marketing-feature-grid">{[['CAPTURE','Photo et vidéo offline-first.'],['SHARING','Galerie cloud sur une seconde station.'],['STUDIO','Design, effets et musique.'],['QR','Partage invité sécurisé.'],['ABONNEMENT','Paiement et statut automatisés.'],['MARKETING','Analytics, campagnes et rapports PDF.']].map(([t,x],i)=><article className="marketing-feature" key={t}><div className="feature-icon">0{i+1}</div><h3>{t}</h3><p>{x}</p></article>)}</div></section>
    <section id="tarifs" className="marketing-section pricing-section"><div className="section-heading centered"><div className="marketing-kicker"><span/> TARIFS SYNCHRONISÉS</div><h2>Choisissez votre abonnement.</h2><p>Les prix et promotions viennent directement de KHE Booth.</p></div><div className="pricing-grid">{site.plans.map((plan)=>{const applies=Boolean(promo&&(!promo.planCode||promo.planCode===plan.code)&&plan.priceMonthlyChf&&plan.priceMonthlyChf>0);const price=applies?Math.round(plan.priceMonthlyChf!*(100-promo!.discountPercent)/100):plan.priceMonthlyChf;return <article className={`pricing-card${plan.highlighted?' pricing-highlighted':''}`} key={plan.code}>{plan.highlighted?<div className="popular-tag">POPULAIRE</div>:null}{applies?<div className="eyebrow">OFFRE -{promo!.discountPercent}%</div>:null}<div className="pricing-name">{plan.name}</div><p>{plan.tagline}</p><div className="pricing-price">{price===null?<strong>Sur mesure</strong>:<><span>CHF</span><strong>{(price/100).toFixed(0)}</strong><small>/mois</small></>}</div>{applies?<p className="muted">au lieu de CHF {(plan.priceMonthlyChf!/100).toFixed(2)}</p>:null}<ul>{plan.features.map((f)=><li key={f}>✓ {f}</li>)}</ul><Link className={plan.highlighted?'marketing-cta pricing-button':'marketing-ghost pricing-button'} href={`/subscribe?plan=${plan.code}`}>{plan.priceMonthlyChf===0?'Commencer gratuitement':plan.priceMonthlyChf===null?'Nous contacter':'Choisir cette offre'}</Link></article>})}</div><p className="pricing-note">Paiements : {(site.paymentMethods??[]).map((m)=>m==='card'?'Carte':m==='apple_pay'?'Apple Pay':m==='google_pay'?'Google Pay':m==='twint'?'TWINT':m).join(' · ')}</p></section>
    <section id="avis" className="marketing-section"><div className="section-heading centered"><div className="marketing-kicker"><span/> AVIS VÉRIFIÉS</div><h2>Les clients KHE Booth témoignent.</h2><p>Publication réservée aux abonnés ayant un paiement vérifié.</p></div>{reviews.length?<div className="marketing-feature-grid">{reviews.slice(0,6).map((r)=><article className="marketing-feature" key={r.id}><div style={{color:'#d2ad4f',fontSize:20}}>{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</div><h3>{r.title||'Expérience KHE Booth'}</h3><p>{r.body}</p><strong>{r.displayName}</strong><div className="muted">✓ Abonné vérifié</div></article>)}</div>:<div className="card" style={{maxWidth:680,margin:'0 auto',textAlign:'center'}}>Les premiers avis vérifiés apparaîtront ici.</div>}<div style={{textAlign:'center',marginTop:20}}><Link className="marketing-ghost" href="/review">Laisser un avis vérifié</Link></div></section>
    <section id="faq" className="marketing-section faq-section"><div className="section-heading"><div className="marketing-kicker"><span/> FAQ</div><h2>Questions fréquentes.</h2></div><div className="faq-grid">{(faq.length?faq:[{question:'L’abonnement est-il renouvelé automatiquement ?',answer:'Oui pour les abonnements récurrents compatibles, après accord explicite. Il reste résiliable depuis Mon abonnement.'},{question:'TWINT est-il disponible ?',answer:'TWINT standard est disponible comme paiement ponctuel. Le débit TWINT récurrent nécessite un contrat marchand User on File.'},{question:'Puis-je modifier le site ?',answer:'Oui. Les tarifs, textes, médias, liens, maintenance et paramètres marketing sont administrables depuis KHE Booth.'}]).map((x)=><article className="faq-item" key={x.question}><h3>{x.question}</h3><p>{x.answer}</p></article>)}</div></section>
    <section className="marketing-final-cta"><div><div className="marketing-kicker"><span/> PRÊT ?</div><h2>Activez KHE Booth maintenant.</h2></div><div className="final-actions"><Link className="marketing-cta" href="/subscribe">Choisir mon abonnement</Link>{site.appDownloadUrl?<a className="marketing-ghost" href={site.appDownloadUrl}>Télécharger l’application</a>:null}</div></section>
    <footer className="marketing-footer"><div><Link className="marketing-brand" href="/">KHE <span>BOOTH</span></Link><p>Une solution Kurtis Hypnotic Events.</p></div><div className="footer-links"><Link href="/account/subscription">Mon abonnement</Link><Link href="/review">Avis</Link><Link href="/login">Connexion</Link></div><p className="footer-copy">© 2026 KHE Booth</p></footer>
  </main>;
}
