'use client';

import { FormEvent, useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';

const API=(process.env.NEXT_PUBLIC_API_URL||'https://khebooth-api.vercel.app/api').replace(/\/$/,'');
type Invitation={email:string;role:string;expiresAt:string};

export default function InvitePage(){const params=useParams<{token:string}>();const router=useRouter();const token=params.token;const[invite,setInvite]=useState<Invitation|null>(null);const[firstName,setFirstName]=useState('');const[lastName,setLastName]=useState('');const[phone,setPhone]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);
 useEffect(()=>{fetch(`${API}/team/invitations/${encodeURIComponent(token)}`,{cache:'no-store'}).then(async(response)=>{if(!response.ok)throw new Error((await response.json().catch(()=>({})))?.message||'Invitation indisponible');return response.json() as Promise<Invitation>;}).then(setInvite).catch((e)=>setError(e instanceof Error?e.message:'Invitation indisponible'));},[token]);
 async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{const response=await fetch(`${API}/team/invitations/${encodeURIComponent(token)}/accept`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({firstName,lastName,phone,password})});const payload=await response.json().catch(()=>({})) as {message?:string};if(!response.ok)throw new Error(payload.message||'Création du compte impossible');router.replace('/login?invited=1');}catch(e){setError(e instanceof Error?e.message:'Création impossible');}finally{setBusy(false);}}
 return <main className="login"><section className="login-card" style={{maxWidth:620}}><div className="brand">KHE <span>BOOTH</span></div><div className="eyebrow" style={{marginTop:18}}>INVITATION ÉQUIPE</div><h1>Rejoindre KHE Booth</h1>{error?<p className="error">{error}</p>:null}{invite?<><p>Invitation pour <strong>{invite.email}</strong> avec le rôle <strong>{invite.role}</strong>.</p><p className="muted">Valable jusqu’au {new Date(invite.expiresAt).toLocaleString('fr-CH')}.</p><form className="form" onSubmit={submit}><div className="grid two"><label>Prénom *<input required value={firstName} onChange={(e)=>setFirstName(e.target.value)}/></label><label>Nom *<input required value={lastName} onChange={(e)=>setLastName(e.target.value)}/></label></div><label>Téléphone<input type="tel" value={phone} onChange={(e)=>setPhone(e.target.value)}/></label><label>Mot de passe *<input type="password" minLength={10} required value={password} onChange={(e)=>setPassword(e.target.value)}/></label><p className="muted">10 caractères minimum. Les permissions attribuées par l’administrateur seront appliquées automatiquement.</p><button className="button" disabled={busy}>{busy?'Création…':'Créer mon compte KHE'}</button></form></>:!error?<p>Chargement de l’invitation…</p>:null}</section></main>;}
