'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { PortalShell } from '@/components/portal-shell';
import { apiRequest } from '@/lib/api';

type Plan={code:string;name:string;tagline:string;priceMonthlyChf:number|null;localizedPrices?:Record<string,number>;features:string[];active:boolean;highlighted:boolean;stripePriceId?:string|null;sortOrder:number};
type Config={heroTitle:string;heroSubtitle:string;primaryCta:string;appDownloadUrl?:string|null;supportEmail?:string|null;latestVersion:string;releaseNotes:string;maintenanceActive:boolean;maintenanceMessage?:string|null;paymentMethods:string[];faq:Array<{question?:string;answer?:string}>;media?:Record<string,string>;seo?:Record<string,string>;socialLinks?:Record<string,string>;announcement?:Record<string,unknown>;contentBlocks?:Array<Record<string,unknown>>;plans:Plan[]};
const LOCAL_CURRENCIES=['EUR','GBP','USD','CAD','AUD'] as const;

export default function SiteConfigurationPage(){
  const[config,setConfig]=useState<Config|null>(null);const[message,setMessage]=useState('');
  const load=useCallback(()=>apiRequest<Config>('/commerce/admin/site').then((value)=>setConfig({...value,plans:value.plans.map((p)=>({...p,localizedPrices:p.localizedPrices||{}})),media:value.media||{},seo:value.seo||{},socialLinks:value.socialLinks||{},announcement:value.announcement||{},contentBlocks:value.contentBlocks||[]})).catch((e)=>setMessage(e instanceof Error?e.message:'Erreur de chargement')),[]);
  useEffect(()=>{void load();},[load]);
  async function saveSite(event:FormEvent){event.preventDefault();if(!config)return;setMessage('Enregistrement…');try{await apiRequest('/commerce/admin/site-content',{method:'PATCH',body:JSON.stringify({media:config.media,seo:config.seo,socialLinks:config.socialLinks,announcement:config.announcement,contentBlocks:config.contentBlocks})});await apiRequest('/commerce/admin/site',{method:'PATCH',body:JSON.stringify(config)});await load();setMessage('✓ Site marketing, médias et paramètres synchronisés.');}catch(e){setMessage(e instanceof Error?e.message:'Erreur');}}
  async function savePlan(plan:Plan){setMessage(`Synchronisation de ${plan.name}…`);try{await apiRequest(`/commerce/admin/plans/${plan.code}`,{method:'PATCH',body:JSON.stringify(plan)});await apiRequest(`/commerce/admin/plans/${plan.code}/localized-prices`,{method:'PATCH',body:JSON.stringify({localizedPrices:plan.localizedPrices||{}})});await load();setMessage(`✓ Offre ${plan.name} synchronisée sur KHE Booth, le site et la grille multi-devise.`);}catch(e){setMessage(e instanceof Error?e.message:'Erreur');}}
  function patchPlan(code:string,patch:Partial<Plan>){setConfig((current)=>current?{...current,plans:current.plans.map((p)=>p.code===code?{...p,...patch}:p)}:current);}
  function patchLocalizedPrice(plan:Plan,currency:string,value:string){const localizedPrices={...(plan.localizedPrices||{})};if(value==='')delete localizedPrices[currency];else localizedPrices[currency]=Number(value);patchPlan(plan.code,{localizedPrices});}
  if(!config)return <PortalShell><h1>Configuration du site web</h1><p>{message||'Chargement…'}</p></PortalShell>;
  const media=config.media||{};const seo=config.seo||{};const social=config.socialLinks||{};const announcement=config.announcement||{};
  return <PortalShell><div className="page-header"><div><div className="eyebrow">MARKETING & COMMERCE</div><h1>Configuration du site web</h1><p className="muted">Vous pilotez ici le contenu public, les prix, les devises, le téléchargement, les visuels, le SEO, la maintenance et les moyens de paiement visibles.</p></div></div>
    <form className="card" onSubmit={saveSite} style={{display:'grid',gap:14}}><h2>Contenu principal</h2><label>Titre principal<input value={config.heroTitle} onChange={(e)=>setConfig({...config,heroTitle:e.target.value})}/></label><label>Sous-titre<textarea value={config.heroSubtitle} onChange={(e)=>setConfig({...config,heroSubtitle:e.target.value})}/></label><label>Bouton principal<input value={config.primaryCta} onChange={(e)=>setConfig({...config,primaryCta:e.target.value})}/></label><label>Lien direct de téléchargement de l’application<input placeholder="https://…apk" value={config.appDownloadUrl||''} onChange={(e)=>setConfig({...config,appDownloadUrl:e.target.value})}/></label><label>E-mail commercial/support<input type="email" value={config.supportEmail||''} onChange={(e)=>setConfig({...config,supportEmail:e.target.value})}/></label>
      <div className="grid two"><label>Image / affiche Hero<input value={media.heroImageUrl||''} onChange={(e)=>setConfig({...config,media:{...media,heroImageUrl:e.target.value}})}/></label><label>Vidéo promotionnelle<input value={media.promoVideoUrl||''} onChange={(e)=>setConfig({...config,media:{...media,promoVideoUrl:e.target.value}})}/></label></div><div className="grid two"><label>Titre SEO<input value={seo.title||''} onChange={(e)=>setConfig({...config,seo:{...seo,title:e.target.value}})}/></label><label>Description SEO<input value={seo.description||''} onChange={(e)=>setConfig({...config,seo:{...seo,description:e.target.value}})}/></label></div><div className="grid two"><label>Instagram<input value={social.instagram||''} onChange={(e)=>setConfig({...config,socialLinks:{...social,instagram:e.target.value}})}/></label><label>Facebook<input value={social.facebook||''} onChange={(e)=>setConfig({...config,socialLinks:{...social,facebook:e.target.value}})}/></label></div><div className="grid two"><label>TikTok<input value={social.tiktok||''} onChange={(e)=>setConfig({...config,socialLinks:{...social,tiktok:e.target.value}})}/></label><label>YouTube<input value={social.youtube||''} onChange={(e)=>setConfig({...config,socialLinks:{...social,youtube:e.target.value}})}/></label></div><label>Bannière d’annonce<input value={String(announcement.text||'')} onChange={(e)=>setConfig({...config,announcement:{...announcement,text:e.target.value}})}/></label>
      <div className="grid two"><label>Version publiée<input value={config.latestVersion} onChange={(e)=>setConfig({...config,latestVersion:e.target.value})}/></label><label>Maintenance active<select value={config.maintenanceActive?'yes':'no'} onChange={(e)=>setConfig({...config,maintenanceActive:e.target.value==='yes'})}><option value="no">Non</option><option value="yes">Oui</option></select></label></div><label>Notes de mise à jour<textarea value={config.releaseNotes} onChange={(e)=>setConfig({...config,releaseNotes:e.target.value})}/></label><label>Message de maintenance<textarea value={config.maintenanceMessage||''} onChange={(e)=>setConfig({...config,maintenanceMessage:e.target.value})}/></label><fieldset><legend>Moyens de paiement visibles</legend>{['card','apple_pay','google_pay','twint'].map((method)=><label key={method} style={{marginRight:18}}><input type="checkbox" checked={config.paymentMethods.includes(method)} onChange={(e)=>setConfig({...config,paymentMethods:e.target.checked?[...config.paymentMethods,method]:config.paymentMethods.filter((x)=>x!==method)})}/>{' '}{method==='card'?'Carte':method==='apple_pay'?'Apple Pay':method==='google_pay'?'Google Pay':'TWINT'}</label>)}</fieldset><label>FAQ personnalisée (JSON avancé)<textarea rows={5} value={JSON.stringify(config.faq||[],null,2)} onChange={(e)=>{try{const value=JSON.parse(e.target.value);if(Array.isArray(value))setConfig({...config,faq:value});}catch{}}}/></label><label>Blocs marketing avancés (JSON)<textarea rows={6} value={JSON.stringify(config.contentBlocks||[],null,2)} onChange={(e)=>{try{const value=JSON.parse(e.target.value);if(Array.isArray(value))setConfig({...config,contentBlocks:value});}catch{}}}/></label><button className="button" type="submit">Enregistrer et synchroniser le site</button></form>
    <div style={{height:18}}/><div className="page-header"><div><div className="eyebrow">ABONNEMENTS MULTI-DEVISES</div><h2>Tarifs synchronisés par pays</h2><p className="muted">Les montants sont en centimes : 2900 = 29.00. CHF est le tarif de référence ; EUR/GBP/USD/CAD/AUD sont utilisés selon la localisation ou le choix manuel.</p></div></div><div className="grid two">{config.plans.map((plan)=><section className="card" key={plan.code} style={{display:'grid',gap:10}}><div><strong>{plan.code}</strong>{plan.highlighted?' · Mis en avant':''}</div><label>Nom<input value={plan.name} onChange={(e)=>patchPlan(plan.code,{name:e.target.value})}/></label><label>Accroche<input value={plan.tagline} onChange={(e)=>patchPlan(plan.code,{tagline:e.target.value})}/></label><label>Prix mensuel CHF (centimes)<input type="number" min="0" value={plan.priceMonthlyChf??''} onChange={(e)=>patchPlan(plan.code,{priceMonthlyChf:e.target.value===''?null:Number(e.target.value)})}/></label>{plan.priceMonthlyChf!==null?<div className="grid two">{LOCAL_CURRENCIES.map((currency)=><label key={currency}>Prix {currency} (centimes)<input type="number" min="0" value={plan.localizedPrices?.[currency]??''} onChange={(e)=>patchLocalizedPrice(plan,currency,e.target.value)} placeholder="Automatique / non défini"/></label>)}</div>:null}<label>Avantages (1 par ligne)<textarea value={plan.features.join('\n')} onChange={(e)=>patchPlan(plan.code,{features:e.target.value.split('\n').filter(Boolean)})}/></label><div><label><input type="checkbox" checked={plan.active} onChange={(e)=>patchPlan(plan.code,{active:e.target.checked})}/> Offre active</label>{' · '}<label><input type="checkbox" checked={plan.highlighted} onChange={(e)=>patchPlan(plan.code,{highlighted:e.target.checked})}/> Mettre en avant</label></div><button className="button secondary" type="button" onClick={()=>void savePlan(plan)}>Synchroniser cette offre et ses devises</button></section>)}</div>{message?<p className="card" style={{marginTop:16}}>{message}</p>:null}</PortalShell>;
}
