'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { PortalShell } from '@/components/portal-shell';
import { DEFAULT_REGIONAL_SETTINGS, REGION_OPTIONS, RegionalSiteSettings, normalizeRegionalSettings, type RegionKey, type RegionalSettings } from '@/components/regional-site-settings';
import { SiteLivePreview } from '@/components/site-live-preview';
import { SiteVisualEditor } from '@/components/site-visual-editor';
import { apiRequest } from '@/lib/api';

type Plan={code:string;name:string;tagline:string;priceMonthlyChf:number|null;localizedPrices?:Record<string,number>;features:string[];active:boolean;highlighted:boolean;stripePriceId?:string|null;sortOrder:number};
type Config={heroTitle:string;heroSubtitle:string;primaryCta:string;appDownloadUrl?:string|null;supportEmail?:string|null;latestVersion:string;releaseNotes:string;maintenanceActive:boolean;maintenanceMessage?:string|null;paymentMethods:string[];faq:Array<{question?:string;answer?:string}>;media?:Record<string,string>;seo?:Record<string,string>;socialLinks?:Record<string,string>;announcement?:Record<string,unknown>;contentBlocks?:Array<Record<string,unknown>>;regionalSettings?:RegionalSettings;plans:Plan[]};
type Tab='content'|'visuals'|'regions'|'plans'|'advanced';type PreviewMode='desktop'|'mobile';
const LOCAL_CURRENCIES=['EUR','GBP','USD','CAD','AUD'] as const;
const PUBLIC_SITE='https://khebooth-rdvo.vercel.app';

export default function SiteConfigurationPage(){
  const[config,setConfig]=useState<Config|null>(null);const[message,setMessage]=useState('');const[tab,setTab]=useState<Tab>('content');const[previewMode,setPreviewMode]=useState<PreviewMode>('desktop');const[selectedRegion,setSelectedRegion]=useState<RegionKey>('SWITZERLAND');const[dirty,setDirty]=useState(false);
  const load=useCallback(()=>apiRequest<Config>('/commerce/admin/site').then((value)=>setConfig({...value,plans:value.plans.map((p)=>({...p,localizedPrices:p.localizedPrices||{}})),media:value.media||{},seo:value.seo||{},socialLinks:value.socialLinks||{},announcement:value.announcement||{},contentBlocks:value.contentBlocks||[],regionalSettings:normalizeRegionalSettings(value.regionalSettings)})).catch((e)=>setMessage(e instanceof Error?e.message:'Erreur de chargement')),[]);
  useEffect(()=>{void load();},[load]);
  const set=(next:Config)=>{setConfig(next);setDirty(true);};
  async function saveSite(event?:FormEvent){event?.preventDefault();if(!config)return;setMessage('Enregistrement et synchronisation…');try{await apiRequest('/commerce/admin/site-content',{method:'PATCH',body:JSON.stringify({media:config.media,seo:config.seo,socialLinks:config.socialLinks,announcement:config.announcement,contentBlocks:config.contentBlocks,regionalSettings:config.regionalSettings})});await apiRequest('/commerce/admin/site',{method:'PATCH',body:JSON.stringify(config)});await load();setDirty(false);setMessage('✓ Site marketing synchronisé. Les visiteurs recevront la nouvelle configuration.');}catch(e){setMessage(e instanceof Error?e.message:'Erreur');}}
  async function savePlan(plan:Plan){setMessage(`Synchronisation de ${plan.name}…`);try{await apiRequest(`/commerce/admin/plans/${plan.code}`,{method:'PATCH',body:JSON.stringify(plan)});await apiRequest(`/commerce/admin/plans/${plan.code}/localized-prices`,{method:'PATCH',body:JSON.stringify({localizedPrices:plan.localizedPrices||{}})});await load();setMessage(`✓ Offre ${plan.name} synchronisée sur KHE Booth, Stripe et le site.`);}catch(e){setMessage(e instanceof Error?e.message:'Erreur');}}
  function patchPlan(code:string,patch:Partial<Plan>){if(!config)return;set({...config,plans:config.plans.map((p)=>p.code===code?{...p,...patch}:p)});}
  function patchLocalizedPrice(plan:Plan,currency:string,value:string){const localizedPrices={...(plan.localizedPrices||{})};if(value==='')delete localizedPrices[currency];else localizedPrices[currency]=Number(value);patchPlan(plan.code,{localizedPrices});}
  if(!config)return <PortalShell><h1>Configuration du site web</h1><p>{message||'Chargement…'}</p></PortalShell>;

  const media=config.media||{};const seo=config.seo||{};const social=config.socialLinks||{};const announcement=config.announcement||{};const regions=config.regionalSettings||DEFAULT_REGIONAL_SETTINGS;const regionPolicy=regions[selectedRegion];const regionInfo=REGION_OPTIONS.find((r)=>r.key===selectedRegion)!;const previewCurrency=regionPolicy.forceCurrency||regionInfo.defaultCurrency||'CHF';const previewPlans=config.plans.filter((p)=>p.active).slice(0,3);const previewTitle=regionPolicy.heroTitle||config.heroTitle;const previewSubtitle=regionPolicy.heroSubtitle||config.heroSubtitle;const previewCta=regionPolicy.primaryCta||config.primaryCta;

  return <PortalShell>
    <div className="page-header" style={{alignItems:'center'}}><div><div className="eyebrow">SITE MARKETING • ÉDITEUR VISUEL</div><h1>Configuration du site web</h1><p className="muted">Modifiez le contenu, les visuels, les tarifs et le comportement régional avec un aperçu lisible en direct.</p></div><div className="toolbar"><a className="button secondary" href={PUBLIC_SITE} target="_blank" rel="noreferrer">↗ Voir le site en ligne</a><button type="button" className="button" disabled={!dirty} onClick={()=>void saveSite()}>{dirty?'Enregistrer les changements':'Site synchronisé ✓'}</button></div></div>
    {message?<div className="card" style={{marginBottom:14}}>{message}</div>:null}
    <div className="site-config-layout">
      <section className="card site-config-editor">
        <div className="site-config-tabbar">{([['content','Contenu'],['visuals','Visuels'],['regions','Régions'],['plans','Abonnements'],['advanced','Avancé']] as const).map(([key,label])=><button key={key} type="button" className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</div>
        <form onSubmit={saveSite} style={{display:'grid',gap:14,padding:18}}>
          {tab==='content'?<><div><h2 style={{margin:'0 0 4px'}}>Contenu principal</h2><p className="muted">Le texte reste court, contrasté et lisible sur téléphone, tablette et ordinateur.</p></div><label>Titre principal<input value={config.heroTitle} onChange={(e)=>set({...config,heroTitle:e.target.value})}/></label><label>Sous-titre<textarea rows={3} value={config.heroSubtitle} onChange={(e)=>set({...config,heroSubtitle:e.target.value})}/></label><label>Texte du bouton principal<input value={config.primaryCta} onChange={(e)=>set({...config,primaryCta:e.target.value})}/></label><div className="grid two"><label>Lien de téléchargement<input placeholder="https://…apk" value={config.appDownloadUrl||''} onChange={(e)=>set({...config,appDownloadUrl:e.target.value})}/></label><label>E-mail commercial/support<input type="email" value={config.supportEmail||''} onChange={(e)=>set({...config,supportEmail:e.target.value})}/></label></div><div className="grid two"><label>Image Hero<input value={media.heroImageUrl||''} onChange={(e)=>set({...config,media:{...media,heroImageUrl:e.target.value}})}/></label><label>Vidéo Hero optionnelle<input value={media.promoVideoUrl||''} onChange={(e)=>set({...config,media:{...media,promoVideoUrl:e.target.value}})}/></label></div><label>Bannière d’annonce<input value={String(announcement.text||'')} onChange={(e)=>set({...config,announcement:{...announcement,text:e.target.value}})}/></label><fieldset><legend>Moyens de paiement visibles</legend><div className="toolbar">{['card','apple_pay','google_pay','twint'].map((method)=><label key={method}><input type="checkbox" checked={config.paymentMethods.includes(method)} onChange={(e)=>set({...config,paymentMethods:e.target.checked?[...config.paymentMethods,method]:config.paymentMethods.filter((x)=>x!==method)})}/>{' '}{method==='card'?'Carte':method==='apple_pay'?'Apple Pay':method==='google_pay'?'Google Pay':'TWINT'}</label>)}</div></fieldset></>:null}
          {tab==='visuals'?<SiteVisualEditor media={media} onChange={(nextMedia)=>set({...config,media:nextMedia})}/>:null}
          {tab==='regions'?<><div><h2 style={{margin:'0 0 4px'}}>Comportement par région</h2><p className="muted">Chaque réglage a maintenant un contraste élevé et une mise en page adaptée aux tablettes.</p></div><RegionalSiteSettings value={regions} onChange={(regionalSettings)=>set({...config,regionalSettings})} selected={selectedRegion} onSelectedChange={setSelectedRegion}/></>:null}
          {tab==='plans'?<><div><h2 style={{margin:'0 0 4px'}}>Abonnements & devises</h2><p className="muted">Une carte par offre, avec des champs espacés pour éviter tout chevauchement.</p></div>{config.plans.map((plan)=><section key={plan.code} style={{border:'1px solid #303845',borderRadius:17,padding:16,display:'grid',gap:12,background:plan.highlighted?'linear-gradient(145deg,#2a2414,#171713)':'#151a21',minWidth:0}}><div className="toolbar" style={{justifyContent:'space-between'}}><strong>{plan.code} · {plan.name}</strong>{plan.highlighted?<span className="eyebrow">MIS EN AVANT</span>:null}</div><div className="grid two"><label>Nom<input value={plan.name} onChange={(e)=>patchPlan(plan.code,{name:e.target.value})}/></label><label>Accroche<input value={plan.tagline} onChange={(e)=>patchPlan(plan.code,{tagline:e.target.value})}/></label></div><label>Prix mensuel CHF (centimes)<input type="number" min="0" value={plan.priceMonthlyChf??''} onChange={(e)=>patchPlan(plan.code,{priceMonthlyChf:e.target.value===''?null:Number(e.target.value)})}/></label>{plan.priceMonthlyChf!==null?<div className="grid two">{LOCAL_CURRENCIES.map((currency)=><label key={currency}>Prix {currency} (centimes)<input type="number" min="0" value={plan.localizedPrices?.[currency]??''} onChange={(e)=>patchLocalizedPrice(plan,currency,e.target.value)}/></label>)}</div>:null}<label>Avantages<textarea rows={5} value={plan.features.join('\n')} onChange={(e)=>patchPlan(plan.code,{features:e.target.value.split('\n').filter(Boolean)})}/></label><div className="toolbar"><label><input type="checkbox" checked={plan.active} onChange={(e)=>patchPlan(plan.code,{active:e.target.checked})}/> Offre active</label><label><input type="checkbox" checked={plan.highlighted} onChange={(e)=>patchPlan(plan.code,{highlighted:e.target.checked})}/> Mettre en avant</label></div><button className="button secondary" type="button" onClick={()=>void savePlan(plan)}>Synchroniser cette offre</button></section>)}</>:null}
          {tab==='advanced'?<><div><h2 style={{margin:'0 0 4px'}}>Paramètres avancés</h2><p className="muted">SEO, réseaux, maintenance, FAQ et blocs de contenu.</p></div><div className="grid two"><label>Titre SEO<input value={seo.title||''} onChange={(e)=>set({...config,seo:{...seo,title:e.target.value}})}/></label><label>Description SEO<input value={seo.description||''} onChange={(e)=>set({...config,seo:{...seo,description:e.target.value}})}/></label></div><div className="grid two"><label>Instagram<input value={social.instagram||''} onChange={(e)=>set({...config,socialLinks:{...social,instagram:e.target.value}})}/></label><label>Facebook<input value={social.facebook||''} onChange={(e)=>set({...config,socialLinks:{...social,facebook:e.target.value}})}/></label><label>TikTok<input value={social.tiktok||''} onChange={(e)=>set({...config,socialLinks:{...social,tiktok:e.target.value}})}/></label><label>YouTube<input value={social.youtube||''} onChange={(e)=>set({...config,socialLinks:{...social,youtube:e.target.value}})}/></label></div><div className="grid two"><label>Version publiée<input value={config.latestVersion} onChange={(e)=>set({...config,latestVersion:e.target.value})}/></label><label>Maintenance<select value={config.maintenanceActive?'yes':'no'} onChange={(e)=>set({...config,maintenanceActive:e.target.value==='yes'})}><option value="no">Désactivée</option><option value="yes">Active</option></select></label></div><label>Notes de mise à jour<textarea rows={4} value={config.releaseNotes} onChange={(e)=>set({...config,releaseNotes:e.target.value})}/></label><label>Message de maintenance<textarea rows={3} value={config.maintenanceMessage||''} onChange={(e)=>set({...config,maintenanceMessage:e.target.value})}/></label><label>FAQ personnalisée (JSON)<textarea rows={5} value={JSON.stringify(config.faq||[],null,2)} onChange={(e)=>{try{const value=JSON.parse(e.target.value);if(Array.isArray(value))set({...config,faq:value});}catch{}}}/></label><label>Blocs marketing avancés (JSON)<textarea rows={6} value={JSON.stringify(config.contentBlocks||[],null,2)} onChange={(e)=>{try{const value=JSON.parse(e.target.value);if(Array.isArray(value))set({...config,contentBlocks:value});}catch{}}}/></label></>:null}
          <button className="button" type="submit">Enregistrer et synchroniser</button>
        </form>
      </section>

      <aside className="site-config-preview"><div className="card" style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,padding:12,flexWrap:'wrap'}}><div><strong>Aperçu en direct</strong><div className="muted" style={{fontSize:12}}>{regionInfo.label} · {previewCurrency}</div></div><div className="toolbar"><button type="button" className={previewMode==='desktop'?'button':'button secondary'} onClick={()=>setPreviewMode('desktop')}>Ordinateur</button><button type="button" className={previewMode==='mobile'?'button':'button secondary'} onClick={()=>setPreviewMode('mobile')}>Mobile</button></div></div><SiteLivePreview mode={previewMode} regionName={regionInfo.label} currency={previewCurrency} enabled={regionPolicy.enabled} announcement={regionPolicy.announcement||String(announcement.text||'')} title={previewTitle} subtitle={previewSubtitle} cta={previewCta} showDownload={regionPolicy.showDownload} downloadUrl={config.appDownloadUrl} showPrices={regionPolicy.showPrices} showReviews={regionPolicy.showReviews} plans={previewPlans} heroImageUrl={media.heroImageUrl}/><div className="card"><strong>Aperçu lisible et adaptatif.</strong><p className="muted" style={{marginBottom:0}}>Les textes sont volontairement contrastés, les cartes se replient sur tablette et les futurs médias ajoutés dans l’onglet Visuels alimentent la vitrine publique.</p></div></aside>
    </div>
  </PortalShell>;
}
