'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { PortalShell } from '@/components/portal-shell';
import { DEFAULT_REGIONAL_SETTINGS, REGION_OPTIONS, RegionalSiteSettings, normalizeRegionalSettings, type RegionKey, type RegionalSettings } from '@/components/regional-site-settings';
import { apiRequest } from '@/lib/api';

type Plan={code:string;name:string;tagline:string;priceMonthlyChf:number|null;localizedPrices?:Record<string,number>;features:string[];active:boolean;highlighted:boolean;stripePriceId?:string|null;sortOrder:number};
type Config={heroTitle:string;heroSubtitle:string;primaryCta:string;appDownloadUrl?:string|null;supportEmail?:string|null;latestVersion:string;releaseNotes:string;maintenanceActive:boolean;maintenanceMessage?:string|null;paymentMethods:string[];faq:Array<{question?:string;answer?:string}>;media?:Record<string,string>;seo?:Record<string,string>;socialLinks?:Record<string,string>;announcement?:Record<string,unknown>;contentBlocks?:Array<Record<string,unknown>>;regionalSettings?:RegionalSettings;plans:Plan[]};
type Tab='content'|'regions'|'plans'|'advanced';type PreviewMode='desktop'|'mobile';
const LOCAL_CURRENCIES=['EUR','GBP','USD','CAD','AUD'] as const;
const PUBLIC_SITE='https://khebooth-rdvo.vercel.app';

function money(cents:number|null,currency:string){if(cents===null)return'Sur mesure';return new Intl.NumberFormat(currency==='CHF'?'fr-CH':'fr-FR',{style:'currency',currency,maximumFractionDigits:2}).format(cents/100);}

export default function SiteConfigurationPage(){
  const[config,setConfig]=useState<Config|null>(null);const[message,setMessage]=useState('');const[tab,setTab]=useState<Tab>('content');const[previewMode,setPreviewMode]=useState<PreviewMode>('desktop');const[selectedRegion,setSelectedRegion]=useState<RegionKey>('SWITZERLAND');const[dirty,setDirty]=useState(false);
  const load=useCallback(()=>apiRequest<Config>('/commerce/admin/site').then((value)=>setConfig({...value,plans:value.plans.map((p)=>({...p,localizedPrices:p.localizedPrices||{}})),media:value.media||{},seo:value.seo||{},socialLinks:value.socialLinks||{},announcement:value.announcement||{},contentBlocks:value.contentBlocks||[],regionalSettings:normalizeRegionalSettings(value.regionalSettings)})).catch((e)=>setMessage(e instanceof Error?e.message:'Erreur de chargement')),[]);
  useEffect(()=>{void load();},[load]);
  const set=(next:Config)=>{setConfig(next);setDirty(true);};
  async function saveSite(event?:FormEvent){event?.preventDefault();if(!config)return;setMessage('Enregistrement et synchronisation…');try{await apiRequest('/commerce/admin/site-content',{method:'PATCH',body:JSON.stringify({media:config.media,seo:config.seo,socialLinks:config.socialLinks,announcement:config.announcement,contentBlocks:config.contentBlocks,regionalSettings:config.regionalSettings})});await apiRequest('/commerce/admin/site',{method:'PATCH',body:JSON.stringify(config)});await load();setDirty(false);setMessage('✓ Site marketing synchronisé. Les visiteurs recevront la nouvelle configuration.');}catch(e){setMessage(e instanceof Error?e.message:'Erreur');}}
  async function savePlan(plan:Plan){setMessage(`Synchronisation de ${plan.name}…`);try{await apiRequest(`/commerce/admin/plans/${plan.code}`,{method:'PATCH',body:JSON.stringify(plan)});await apiRequest(`/commerce/admin/plans/${plan.code}/localized-prices`,{method:'PATCH',body:JSON.stringify({localizedPrices:plan.localizedPrices||{}})});await load();setMessage(`✓ Offre ${plan.name} synchronisée sur KHE Booth, Stripe et le site.`);}catch(e){setMessage(e instanceof Error?e.message:'Erreur');}}
  function patchPlan(code:string,patch:Partial<Plan>){if(!config)return;set({...config,plans:config.plans.map((p)=>p.code===code?{...p,...patch}:p)});}
  function patchLocalizedPrice(plan:Plan,currency:string,value:string){const localizedPrices={...(plan.localizedPrices||{})};if(value==='')delete localizedPrices[currency];else localizedPrices[currency]=Number(value);patchPlan(plan.code,{localizedPrices});}
  if(!config)return <PortalShell><h1>Configuration du site web</h1><p>{message||'Chargement…'}</p></PortalShell>;
  const media=config.media||{};const seo=config.seo||{};const social=config.socialLinks||{};const announcement=config.announcement||{};const regions=config.regionalSettings||DEFAULT_REGIONAL_SETTINGS;const regionPolicy=regions[selectedRegion];
  const previewCurrency=regionPolicy.forceCurrency||REGION_OPTIONS.find((r)=>r.key===selectedRegion)?.defaultCurrency||'CHF';
  const previewPlans=config.plans.filter((p)=>p.active).slice(0,3);
  const previewTitle=regionPolicy.heroTitle||config.heroTitle;const previewSubtitle=regionPolicy.heroSubtitle||config.heroSubtitle;const previewCta=regionPolicy.primaryCta||config.primaryCta;

  return <PortalShell>
    <div className="page-header" style={{alignItems:'center'}}><div><div className="eyebrow">SITE MARKETING • ÉDITEUR VISUEL</div><h1>Configuration du site web</h1><p className="muted">Modifiez le contenu, les tarifs et le comportement régional tout en voyant le résultat en direct.</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><a className="button secondary" href={PUBLIC_SITE} target="_blank" rel="noreferrer">↗ Voir le site en ligne</a><button type="button" className="button" disabled={!dirty} onClick={()=>void saveSite()}>{dirty?'Enregistrer les changements':'Site synchronisé ✓'}</button></div></div>
    {message?<div className="card" style={{marginBottom:14}}>{message}</div>:null}
    <div style={{display:'grid',gridTemplateColumns:'minmax(420px,1fr) minmax(360px,.9fr)',gap:18,alignItems:'start'}}>
      <section className="card" style={{padding:0,overflow:'hidden'}}>
        <div style={{display:'flex',gap:4,padding:10,background:'#151515',flexWrap:'wrap'}}>{([['content','Contenu'],['regions','Régions'],['plans','Abonnements'],['advanced','Avancé']] as const).map(([key,label])=><button key={key} type="button" onClick={()=>setTab(key)} style={{border:0,borderRadius:10,padding:'10px 14px',fontWeight:900,cursor:'pointer',background:tab===key?'#d2ad4f':'#2b2b2b',color:tab===key?'#111':'#fff'}}>{label}</button>)}</div>
        <form onSubmit={saveSite} style={{display:'grid',gap:14,padding:18}}>
          {tab==='content'?<>
            <div><h2 style={{margin:'0 0 4px'}}>Contenu principal</h2><p className="muted">Chaque modification apparaît immédiatement dans l’aperçu.</p></div>
            <label>Titre principal<input value={config.heroTitle} onChange={(e)=>set({...config,heroTitle:e.target.value})}/></label>
            <label>Sous-titre<textarea rows={3} value={config.heroSubtitle} onChange={(e)=>set({...config,heroSubtitle:e.target.value})}/></label>
            <label>Texte du bouton principal<input value={config.primaryCta} onChange={(e)=>set({...config,primaryCta:e.target.value})}/></label>
            <div className="grid two"><label>Lien de téléchargement de l’application<input placeholder="https://…apk" value={config.appDownloadUrl||''} onChange={(e)=>set({...config,appDownloadUrl:e.target.value})}/></label><label>E-mail commercial/support<input type="email" value={config.supportEmail||''} onChange={(e)=>set({...config,supportEmail:e.target.value})}/></label></div>
            <div className="grid two"><label>Image / affiche Hero<input value={media.heroImageUrl||''} onChange={(e)=>set({...config,media:{...media,heroImageUrl:e.target.value}})}/></label><label>Vidéo promotionnelle<input value={media.promoVideoUrl||''} onChange={(e)=>set({...config,media:{...media,promoVideoUrl:e.target.value}})}/></label></div>
            <label>Bannière d’annonce<input value={String(announcement.text||'')} onChange={(e)=>set({...config,announcement:{...announcement,text:e.target.value}})}/></label>
            <fieldset><legend>Moyens de paiement visibles</legend><div style={{display:'flex',gap:12,flexWrap:'wrap'}}>{['card','apple_pay','google_pay','twint'].map((method)=><label key={method}><input type="checkbox" checked={config.paymentMethods.includes(method)} onChange={(e)=>set({...config,paymentMethods:e.target.checked?[...config.paymentMethods,method]:config.paymentMethods.filter((x)=>x!==method)})}/>{' '}{method==='card'?'Carte':method==='apple_pay'?'Apple Pay':method==='google_pay'?'Google Pay':'TWINT'}</label>)}</div></fieldset>
          </>:null}
          {tab==='regions'?<><div><h2 style={{margin:'0 0 4px'}}>Affichage par région</h2><p className="muted">Contrôlez l’accès, la devise, les sections visibles et le message commercial selon la localisation du visiteur.</p></div><RegionalSiteSettings value={regions} onChange={(regionalSettings)=>set({...config,regionalSettings})} selected={selectedRegion} onSelectedChange={setSelectedRegion}/></>:null}
          {tab==='plans'?<><div><h2 style={{margin:'0 0 4px'}}>Abonnements & devises</h2><p className="muted">Les tarifs enregistrés ici alimentent la plateforme et le site. Les tarifs Stripe sont synchronisés quand la connexion serveur est configurée.</p></div>{config.plans.map((plan)=><section key={plan.code} style={{border:'1px solid #eadfce',borderRadius:16,padding:14,display:'grid',gap:10,background:plan.highlighted?'#fff8e9':'#fff'}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><strong>{plan.code} · {plan.name}</strong>{plan.highlighted?<span className="eyebrow">MIS EN AVANT</span>:null}</div><div className="grid two"><label>Nom<input value={plan.name} onChange={(e)=>patchPlan(plan.code,{name:e.target.value})}/></label><label>Accroche<input value={plan.tagline} onChange={(e)=>patchPlan(plan.code,{tagline:e.target.value})}/></label></div><label>Prix mensuel CHF (centimes)<input type="number" min="0" value={plan.priceMonthlyChf??''} onChange={(e)=>patchPlan(plan.code,{priceMonthlyChf:e.target.value===''?null:Number(e.target.value)})}/></label>{plan.priceMonthlyChf!==null?<div className="grid two">{LOCAL_CURRENCIES.map((currency)=><label key={currency}>Prix {currency} (centimes)<input type="number" min="0" value={plan.localizedPrices?.[currency]??''} onChange={(e)=>patchLocalizedPrice(plan,currency,e.target.value)}/></label>)}</div>:null}<label>Avantages<textarea rows={5} value={plan.features.join('\n')} onChange={(e)=>patchPlan(plan.code,{features:e.target.value.split('\n').filter(Boolean)})}/></label><div style={{display:'flex',gap:14,flexWrap:'wrap'}}><label><input type="checkbox" checked={plan.active} onChange={(e)=>patchPlan(plan.code,{active:e.target.checked})}/> Offre active</label><label><input type="checkbox" checked={plan.highlighted} onChange={(e)=>patchPlan(plan.code,{highlighted:e.target.checked})}/> Mettre en avant</label></div><button className="button secondary" type="button" onClick={()=>void savePlan(plan)}>Synchroniser cette offre</button></section>)}</>:null}
          {tab==='advanced'?<><div><h2 style={{margin:'0 0 4px'}}>Paramètres avancés</h2><p className="muted">SEO, réseaux, maintenance, FAQ et blocs de contenu.</p></div><div className="grid two"><label>Titre SEO<input value={seo.title||''} onChange={(e)=>set({...config,seo:{...seo,title:e.target.value}})}/></label><label>Description SEO<input value={seo.description||''} onChange={(e)=>set({...config,seo:{...seo,description:e.target.value}})}/></label></div><div className="grid two"><label>Instagram<input value={social.instagram||''} onChange={(e)=>set({...config,socialLinks:{...social,instagram:e.target.value}})}/></label><label>Facebook<input value={social.facebook||''} onChange={(e)=>set({...config,socialLinks:{...social,facebook:e.target.value}})}/></label><label>TikTok<input value={social.tiktok||''} onChange={(e)=>set({...config,socialLinks:{...social,tiktok:e.target.value}})}/></label><label>YouTube<input value={social.youtube||''} onChange={(e)=>set({...config,socialLinks:{...social,youtube:e.target.value}})}/></label></div><div className="grid two"><label>Version publiée<input value={config.latestVersion} onChange={(e)=>set({...config,latestVersion:e.target.value})}/></label><label>Maintenance<select value={config.maintenanceActive?'yes':'no'} onChange={(e)=>set({...config,maintenanceActive:e.target.value==='yes'})}><option value="no">Désactivée</option><option value="yes">Active</option></select></label></div><label>Notes de mise à jour<textarea rows={4} value={config.releaseNotes} onChange={(e)=>set({...config,releaseNotes:e.target.value})}/></label><label>Message de maintenance<textarea rows={3} value={config.maintenanceMessage||''} onChange={(e)=>set({...config,maintenanceMessage:e.target.value})}/></label><label>FAQ personnalisée (JSON)<textarea rows={5} value={JSON.stringify(config.faq||[],null,2)} onChange={(e)=>{try{const value=JSON.parse(e.target.value);if(Array.isArray(value))set({...config,faq:value});}catch{}}}/></label><label>Blocs marketing avancés (JSON)<textarea rows={6} value={JSON.stringify(config.contentBlocks||[],null,2)} onChange={(e)=>{try{const value=JSON.parse(e.target.value);if(Array.isArray(value))set({...config,contentBlocks:value});}catch{}}}/></label></>:null}
          <button className="button" type="submit">Enregistrer et synchroniser</button>
        </form>
      </section>

      <aside style={{position:'sticky',top:18,display:'grid',gap:10}}>
        <div className="card" style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,padding:12}}><div><strong>Aperçu en direct</strong><div className="muted" style={{fontSize:12}}>{REGION_OPTIONS.find((r)=>r.key===selectedRegion)?.label} · {previewCurrency}</div></div><div style={{display:'flex',gap:6}}><button type="button" className={previewMode==='desktop'?'button':'button secondary'} onClick={()=>setPreviewMode('desktop')}>Ordinateur</button><button type="button" className={previewMode==='mobile'?'button':'button secondary'} onClick={()=>setPreviewMode('mobile')}>Mobile</button></div></div>
        <div style={{width:previewMode==='mobile'?360:'100%',maxWidth:'100%',margin:'0 auto',border:'8px solid #151515',borderRadius:previewMode==='mobile'?30:18,overflow:'hidden',boxShadow:'0 24px 70px rgba(0,0,0,.18)',background:'#0f0f10'}}>
          <div style={{height:previewMode==='mobile'?20:28,background:'#1d1d1f',display:'flex',alignItems:'center',padding:'0 10px',gap:5}}><span style={{width:7,height:7,borderRadius:7,background:'#b31520'}}/><span style={{width:7,height:7,borderRadius:7,background:'#d2ad4f'}}/><span style={{width:7,height:7,borderRadius:7,background:'#5e5e5e'}}/></div>
          {!regionPolicy.enabled?<div style={{padding:'70px 24px',textAlign:'center',color:'#fff'}}><div style={{fontSize:12,letterSpacing:3,color:'#d2ad4f',fontWeight:900}}>KHE BOOTH</div><h2>Site temporairement indisponible dans cette région</h2><p style={{color:'#aaa'}}>Le visiteur verra un message de disponibilité régionale.</p></div>:<>
            {regionPolicy.announcement||announcement.text?<div style={{background:'#d2ad4f',color:'#111',padding:'9px 12px',fontWeight:900,textAlign:'center',fontSize:12}}>{regionPolicy.announcement||String(announcement.text)}</div>:null}
            <div style={{padding:previewMode==='mobile'?'28px 18px':'42px 34px',color:'#fff',background:'radial-gradient(circle at 75% 20%, rgba(179,21,32,.35), transparent 35%), #0f0f10'}}><div style={{color:'#d2ad4f',fontSize:10,letterSpacing:2,fontWeight:900}}>KURTIS HYPNOTIC EVENTS</div><h1 style={{fontSize:previewMode==='mobile'?32:46,lineHeight:1.02,maxWidth:650,margin:'12px 0'}}>{previewTitle}</h1><p style={{color:'#c9c9c9',lineHeight:1.5,maxWidth:600}}>{previewSubtitle}</p><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:18}}><span style={{background:'#b31520',borderRadius:10,padding:'11px 14px',fontWeight:900}}>{previewCta}</span>{regionPolicy.showDownload&&config.appDownloadUrl?<span style={{border:'1px solid #d2ad4f',borderRadius:10,padding:'11px 14px',fontWeight:900,color:'#d2ad4f'}}>↓ Télécharger</span>:null}</div></div>
            {regionPolicy.showPrices?<div style={{background:'#f7f2ea',padding:previewMode==='mobile'?16:24}}><div style={{textAlign:'center',fontWeight:900,fontSize:20,marginBottom:14}}>Abonnements</div><div style={{display:'grid',gridTemplateColumns:previewMode==='mobile'?'1fr':'repeat(3,1fr)',gap:10}}>{previewPlans.map((plan)=>{const localized=previewCurrency==='CHF'?plan.priceMonthlyChf:plan.localizedPrices?.[previewCurrency]??plan.priceMonthlyChf;return <div key={plan.code} style={{background:'#fff',border:plan.highlighted?'2px solid #d2ad4f':'1px solid #e1d7c9',borderRadius:14,padding:12}}><strong>{plan.name}</strong><div style={{fontSize:22,fontWeight:900,margin:'8px 0'}}>{money(localized,previewCurrency)}</div><div style={{fontSize:11,color:'#72695f'}}>{plan.tagline}</div></div>})}</div></div>:null}
            {regionPolicy.showReviews?<div style={{padding:20,color:'#fff',textAlign:'center'}}><div style={{color:'#d2ad4f'}}>★★★★★</div><strong>Avis abonnés vérifiés</strong></div>:null}
          </>}
        </div>
        <div className="card"><strong>Ce cadre est un aperçu fonctionnel.</strong><p className="muted" style={{marginBottom:0}}>Il reflète immédiatement le titre, CTA, disponibilité régionale, devise, téléchargement, tarifs et avis. Le bouton « Voir le site en ligne » ouvre la version réellement déployée.</p></div>
      </aside>
    </div>
  </PortalShell>;
}
