'use client';

import Link from 'next/link';
import { FormEvent, useState } from 'react';
const API_BASE=(process.env.NEXT_PUBLIC_API_URL||'https://khebooth-api.vercel.app/api').replace(/\/$/,'');
type Account={name:string;email:string;kheCode:string;subscriptionPlan:string;subscriptionStatus:string;paymentStatus:string;renewalManagedByStripe:boolean};

export default function SubscriptionAccountPage(){
  const[email,setEmail]=useState('');const[kheCode,setKheCode]=useState('');const[account,setAccount]=useState<Account|null>(null);const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);
  async function load(event:FormEvent){event.preventDefault();setBusy(true);setMessage('Vérification…');try{const response=await fetch(`${API_BASE}/commerce/public/account`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,kheCode})});const data=await response.json() as Account&{message?:string};if(!response.ok)throw new Error(data.message||'Identification impossible');setAccount(data);setMessage('');}catch(e){setAccount(null);setMessage(e instanceof Error?e.message:'Erreur');}finally{setBusy(false);}}
  async function manage(){setBusy(true);setMessage('Ouverture du portail sécurisé…');try{const response=await fetch(`${API_BASE}/commerce/public/billing-portal`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,kheCode})});const data=await response.json() as{url?:string;message?:string};if(!response.ok||!data.url)throw new Error(data.message||'Portail indisponible');window.location.assign(data.url);}catch(e){setMessage(e instanceof Error?e.message:'Erreur');setBusy(false);}}
  return <main className="marketing-page" style={{minHeight:'100vh'}}><header className="marketing-nav"><Link className="marketing-brand" href="/">KHE <span>BOOTH</span></Link><Link className="marketing-login" href="/">← Site KHE Booth</Link></header><section className="marketing-section"><div className="section-heading centered"><div className="marketing-kicker"><span/> MON ABONNEMENT</div><h1>Gérer mon abonnement KHE Booth</h1><p>Consultez votre niveau, votre paiement et gérez votre abonnement récurrent.</p></div><form className="card" onSubmit={load} style={{display:'grid',gap:14,maxWidth:620,margin:'0 auto'}}><label>Adresse e-mail<input required type="email" value={email} onChange={(e)=>setEmail(e.target.value)}/></label><label>KHE ID<input required value={kheCode} onChange={(e)=>setKheCode(e.target.value.toUpperCase())} placeholder="KHE-XXXXXXXXXX"/></label><button className="button" disabled={busy}>{busy?'Vérification…':'Afficher mon abonnement'}</button>{message?<p>{message}</p>:null}</form>{account?<div className="card" style={{maxWidth:620,margin:'18px auto 0',display:'grid',gap:10}}><h2>{account.name}</h2><p>KHE ID : <strong>{account.kheCode}</strong></p><p>Offre : <strong>{account.subscriptionPlan}</strong></p><p>Statut : <strong>{account.subscriptionStatus}</strong></p><p>Paiement : <strong>{account.paymentStatus}</strong></p>{account.renewalManagedByStripe?<><p className="muted">Votre abonnement se renouvelle automatiquement jusqu’à résiliation. Dans le portail sécurisé, vous pouvez modifier votre moyen de paiement ou résilier votre abonnement. Une offre de rétention peut vous être proposée avant confirmation, mais la résiliation reste disponible.</p><button className="button secondary" disabled={busy} onClick={()=>void manage()}>Gérer / résilier mon abonnement</button></>:<p className="muted">Ce compte n’a pas d’abonnement récurrent Stripe actif. Si vous utilisez TWINT standard, le renouvellement reste manuel jusqu’à activation du mode TWINT récurrent.</p>}<Link className="marketing-ghost" href="/review">Laisser une note et un avis</Link></div>:null}</section></main>;
}
