'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { PortalShell } from '@/components/portal-shell';
import { apiRequest } from '@/lib/api';

type Policy={enabled:boolean;startEarlyMinutes:number;startGraceMinutes:number;noShowAlertMinutes:number;autoCloseMinutes:number;requireActiveShiftForRouting:boolean};
type Shift={id:string;userId:string;startsAt:string;endsAt:string;status:string;confirmationStatus:string;liveStatus:string;actualStartedAt?:string|null;actualEndedAt?:string|null;pauseStartedAt?:string|null;pausedSeconds:number;agentName:string};
type Alert={id:string;shiftId:string;type:string;severity:string;status:string;createdAt:string;email:string;firstName?:string|null;lastName?:string|null;startsAt:string;endsAt:string};
type Team={policy:Policy;summary:{active:number;paused:number;scheduled:number;missed:number;openAlerts:number};shifts:Shift[];alerts:Alert[]};
function when(v:string){return new Date(v).toLocaleString('fr-CH',{weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});}
function liveLabel(v:string){return v==='ACTIVE'?'EN SERVICE':v==='PAUSED'?'PAUSE':v==='COMPLETED'?'TERMINÉ':v==='MISSED'?'NON DÉMARRÉ':'PLANIFIÉ';}
export default function LiveShiftTeamPage(){
  const[data,setData]=useState<Team|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[message,setMessage]=useState('');
  const load=useCallback(async(quiet=false)=>{if(!quiet)setLoading(true);try{setData(await apiRequest<Team>('/operations/workforce/live/team'));if(!quiet)setMessage('');}catch(e){if(!quiet)setMessage(e instanceof Error?e.message:'Supervision Live indisponible');}finally{if(!quiet)setLoading(false);}},[]);
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(true),15000);return()=>window.clearInterval(timer);},[load]);
  const setPolicy=<K extends keyof Policy>(key:K,value:Policy[K])=>setData(d=>d?{...d,policy:{...d.policy,[key]:value}}:d);
  async function savePolicy(){if(!data)return;setSaving(true);try{await apiRequest('/operations/workforce/live/policy',{method:'PATCH',body:JSON.stringify(data.policy)});setMessage('✓ Paramètres Live enregistrés.');await load(true);}catch(e){setMessage(e instanceof Error?e.message:'Enregistrement impossible');}finally{setSaving(false);}}
  async function acknowledge(id:string){try{await apiRequest(`/operations/workforce/live/alerts/${id}/acknowledge`,{method:'POST'});setMessage('✓ Alerte prise en compte.');await load(true);}catch(e){setMessage(e instanceof Error?e.message:'Action impossible');}}
  return <PortalShell><div className="page-header"><div><div className="eyebrow">KHE • LIVE SHIFT SUPERVISION</div><h1>Équipe en service</h1><p className="muted">Suivez les shifts actifs, pauses et non-démarrages. Les alertes sont opérationnelles : elles n’entraînent aucune sanction automatique.</p><div style={{display:'flex',gap:12,flexWrap:'wrap',marginTop:8}}><Link href="/operations/workforce/team">← Confirmations</Link><Link href="/operations/workforce/handover">Passages de relais</Link><Link href="/operations/workforce/optimizer">Planning optimal</Link><Link href="/operations/routing">Routing & SLA</Link></div></div><button className="button secondary" onClick={()=>void load()}>{loading?'Chargement…':'↻ Actualiser'}</button></div>
  {message?<p className={message.startsWith('✓')?'success':'error'}>{message}</p>:null}
  {!data?null:<><div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',marginBottom:16}}>{[['En service',data.summary.active],['En pause',data.summary.paused],['À démarrer',data.summary.scheduled],['Non démarrés',data.summary.missed],['Alertes',data.summary.openAlerts]].map(([label,value])=><div className="card" key={String(label)}><div className="eyebrow">{label}</div><div style={{fontSize:28,fontWeight:950,marginTop:8}}>{value}</div></div>)}</div>
  {data.alerts.length?<section className="card" style={{marginBottom:16,border:'1px solid rgba(245,199,107,.35)'}}><div className="eyebrow">COUVERTURE LIVE</div><h2>Alertes à traiter</h2>{data.alerts.map(a=><div key={a.id} style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',padding:'10px 0',borderBottom:'1px solid #27303a'}}><div><strong style={{color:'#ff9aa4'}}>{a.type}</strong> · {[a.firstName,a.lastName].filter(Boolean).join(' ')||a.email}<div className="muted" style={{fontSize:11}}>{when(a.startsAt)} → {when(a.endsAt)} · {a.status}</div></div>{a.status==='OPEN'?<button className="button secondary" onClick={()=>void acknowledge(a.id)}>Prendre en compte</button>:<span className="muted">Acquittée</span>}</div>)}</section>:null}
  <div className="grid two" style={{alignItems:'start'}}><section className="card"><div className="eyebrow">ÉTAT TEMPS RÉEL</div><h2>Shifts ±24h</h2>{data.shifts.length?data.shifts.map(s=><div key={s.id} style={{padding:'10px 0',borderBottom:'1px solid #27303a'}}><div style={{display:'flex',justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><strong>{s.agentName}</strong><span style={{fontWeight:900,color:s.liveStatus==='ACTIVE'?'#78d59c':s.liveStatus==='PAUSED'?'#f5c76b':s.liveStatus==='MISSED'?'#ff9aa4':'#85b8ff'}}>{liveLabel(s.liveStatus)}</span></div><div className="muted" style={{fontSize:11}}>{when(s.startsAt)} → {when(s.endsAt)} · confirmation {s.confirmationStatus}</div>{s.actualStartedAt?<div className="muted" style={{fontSize:11}}>Démarré : {when(s.actualStartedAt)} · pause cumulée {Math.round((s.pausedSeconds||0)/60)} min</div>:null}</div>):<p className="muted">Aucun shift autour de la période actuelle.</p>}</section>
  <section className="card"><div className="eyebrow">POLITIQUE LIVE</div><h2>Activation progressive</h2><label style={{display:'flex',gap:8,alignItems:'center',marginBottom:12}}><input type="checkbox" checked={data.policy.enabled} onChange={e=>setPolicy('enabled',e.target.checked)}/> Live Shift Operations actif</label><div className="grid two"><label>Démarrage anticipé (min)<input className="input" type="number" min={0} max={180} value={data.policy.startEarlyMinutes} onChange={e=>setPolicy('startEarlyMinutes',Number(e.target.value))}/></label><label>Marge retard (min)<input className="input" type="number" min={0} max={180} value={data.policy.startGraceMinutes} onChange={e=>setPolicy('startGraceMinutes',Number(e.target.value))}/></label><label>Alerte non-démarrage (min)<input className="input" type="number" min={1} max={180} value={data.policy.noShowAlertMinutes} onChange={e=>setPolicy('noShowAlertMinutes',Number(e.target.value))}/></label><label>Fermeture auto après fin (min)<input className="input" type="number" min={0} max={240} value={data.policy.autoCloseMinutes} onChange={e=>setPolicy('autoCloseMinutes',Number(e.target.value))}/></label></div><label style={{display:'flex',gap:8,alignItems:'flex-start',padding:'12px 0'}}><input type="checkbox" checked={data.policy.requireActiveShiftForRouting} onChange={e=>setPolicy('requireActiveShiftForRouting',e.target.checked)}/><span><strong>Exiger un shift Live actif pour le routing</strong><br/><span className="muted" style={{fontSize:11}}>À activer seulement lorsque tous les agents utilisent le planning Live. Sinon, les agents disponibles continuent d’être routables selon les règles actuelles.</span></span></label><button className="button" disabled={saving} onClick={()=>void savePolicy()}>{saving?'Enregistrement…':'Enregistrer la politique'}</button></section></div></>}
  </PortalShell>;
}
