'use client';

import Link from 'next/link';
import { FormEvent, Suspense, useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { SecurePasswordField } from '@/components/secure-password-field';
import { apiRequest } from '@/lib/api';

type ResetContext={valid:boolean;requiresUsername:boolean;username?:string|null};
type UsernameAvailability={username:string;available:boolean;valid:boolean;message:string};

function ResetPasswordForm(){
  const params=useSearchParams();const token=params.get('token')||'';const[password,setPassword]=useState('');const[confirm,setConfirm]=useState('');const[username,setUsername]=useState('');const[requiresUsername,setRequiresUsername]=useState(false);const[contextReady,setContextReady]=useState(false);const[availability,setAvailability]=useState('');const[usernameAvailable,setUsernameAvailable]=useState<boolean|null>(null);const[message,setMessage]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[done,setDone]=useState(false);
  useEffect(()=>{if(!token){setContextReady(true);return;}apiRequest<ResetContext>(`/auth/password-reset/context?token=${encodeURIComponent(token)}`).then((ctx)=>{if(!ctx.valid){setError('Ce lien de réinitialisation est invalide ou expiré.');return;}setRequiresUsername(ctx.requiresUsername);setUsername(ctx.username||'');}).catch(()=>setError('Impossible de vérifier ce lien sécurisé.')).finally(()=>setContextReady(true));},[token]);
  async function checkUsername(){const value=username.trim();if(!value){setAvailability('');setUsernameAvailable(null);return;}try{const result=await apiRequest<UsernameAvailability>(`/auth/username-availability?username=${encodeURIComponent(value)}`);setAvailability(result.message);setUsernameAvailable(result.available&&result.valid);}catch{setAvailability('Impossible de vérifier ce nom pour le moment.');setUsernameAvailable(null);}}
  async function submit(event:FormEvent){event.preventDefault();setError('');if(password!==confirm){setError('Les deux mots de passe ne correspondent pas.');return;}if(requiresUsername&&!username.trim()){setError('Choisissez votre nom d’utilisateur unique.');return;}if(requiresUsername&&usernameAvailable===false){setError('Ce nom d’utilisateur n’est pas disponible.');return;}setBusy(true);try{const result=await apiRequest<{message?:string;username?:string|null}>('/auth/password-reset/complete',{method:'POST',body:JSON.stringify({token,password,username:username.trim()})});setDone(true);setMessage(result.message||'Identifiants modifiés.');if(result.username)setUsername(result.username);}catch(e){setError(e instanceof Error?e.message:'Réinitialisation impossible.');}finally{setBusy(false);}}
  if(!token)return <main className="login"><section className="login-card"><div className="brand">KHE <span>Booth</span></div><h1>Lien invalide</h1><p className="muted">Demandez un nouveau lien sécurisé.</p><Link href="/forgot-password" className="button">Demander un nouveau lien</Link></section></main>;
  if(!contextReady)return <main className="login"><section className="login-card"><div className="brand">KHE <span>Booth</span></div><p className="muted">Vérification de votre accès…</p></section></main>;
  return <main className="login"><section className="login-card"><div className="brand">KHE <span>Booth</span></div><div className="eyebrow" style={{marginTop:22}}>ACTIVATION SÉCURISÉE</div><h1>{requiresUsername?'Créez vos identifiants':'Nouveau mot de passe'}</h1>{done?<><div className="success">{message}</div>{username?<p className="muted">Votre nom d’utilisateur : <strong style={{color:'#d2ad4f'}}>{username}</strong></p>:null}<p className="muted">Toutes les anciennes sessions web ont été invalidées. Vous pouvez vous connecter avec votre e-mail ou votre nom d’utilisateur.</p><Link href="/login" className="button" style={{display:'block',textAlign:'center'}}>Se connecter</Link></>:<form className="form" onSubmit={submit}>{requiresUsername?<div className="field"><label htmlFor="username">Nom d’utilisateur unique *</label><input id="username" required minLength={3} maxLength={32} autoComplete="username" value={username} onChange={(e)=>{setUsername(e.target.value.toLowerCase());setUsernameAvailable(null);setAvailability('');}} onBlur={()=>void checkUsername()} placeholder="ex. kurtis.events"/><p className="muted" style={{fontSize:12}}>3 à 32 caractères : lettres, chiffres, point, tiret ou underscore. Une fois pris, ce nom n’est plus disponible pour un autre compte.</p>{availability?<div className={usernameAvailable?'success':'error'}>{availability}</div>:null}</div>:null}<p className="muted">Utilisez au moins 10 caractères avec des lettres et des chiffres.</p><SecurePasswordField label="Nouveau mot de passe" name="password" autoComplete="new-password" required value={password} onChange={setPassword}/><SecurePasswordField label="Confirmer le mot de passe" name="confirm" autoComplete="new-password" required value={confirm} onChange={setConfirm}/>{error?<div className="error">{error}</div>:null}<button className="button" disabled={busy}>{busy?'Sécurisation…':requiresUsername?'Activer mon accès KHE BOOTH':'Enregistrer le nouveau mot de passe'}</button></form>}</section></main>;
}

export default function ResetPasswordPage(){
  return <Suspense fallback={<main className="login"><section className="login-card"><div className="brand">KHE <span>Booth</span></div><p className="muted">Chargement sécurisé…</p></section></main>}><ResetPasswordForm/></Suspense>;
}