'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { PortalShell } from '@/components/portal-shell';
import { apiRequest, getAccessToken } from '@/lib/api';

type Daily={day:string;visits:number;checkouts:number;payments:number;revenueCents:number};
type Campaign={id:string;name:string;planCode?:string|null;segment:string;discountPercent:number;startsAt:string;endsAt:string;active:boolean;automatic:boolean;reason?:string|null};
type Automation={enabled:boolean;maxDiscountPercent:number;minCheckoutSample:number;lowConversionThresholdPercent:number;campaignDurationDays:number;cooldownDays:number;targetDiscovery:boolean;targetPaymentPending:boolean;ownerReportsEnabled:boolean};
type Dashboard={days:number;summary:{visits:number;planSelections:number;checkoutStarts:number;payments:number;downloads:number;revenueCents:number;conversionPercent:number;visitToPaymentPercent:number};daily:Daily[];planPerformance:Array<{planCode?:string|null;selections:number;checkouts:number;payments:number;revenueCents:number}>;campaigns:Campaign[];automation:Automation};
type ReportFormat='pdf'|'jpeg'|'docx'|'xlsx';
type ViewMode='ANALYSE'|'REPORTS';
const API_BASE=(process.env.NEXT_PUBLIC_API_URL||'https://khebooth-api.vercel.app/api').replace(/\/$/,'');
const EMPTY:Dashboard={days:30,summary:{visits:0,planSelections:0,checkoutStarts:0,payments:0,downloads:0,revenueCents:0,conversionPercent:0,visitToPaymentPercent:0},daily:[],planPerformance:[],campaigns:[],automation:{enabled:true,maxDiscountPercent:15,minCheckoutSample:20,lowConversionThresholdPercent:10,campaignDurationDays:7,cooldownDays:21,targetDiscovery:true,targetPaymentPending:true,ownerReportsEnabled:true}};

function Curve({daily}:{daily:Daily[]}){const source=daily.length?daily:[{day:'',visits:0,checkouts:0,payments:0,revenueCents:0},{day:'',visits:0,checkouts:0,payments:0,revenueCents:0}];const points=useMemo(()=>{const max=Math.max(1,...source.map((d)=>d.visits));return source.map((d,i)=>`${source.length<=1?0:(i/(source.length-1))*100},${100-(d.visits/max)*82}`).join(' ');},[source]);const checkout=useMemo(()=>{const max=Math.max(1,...source.map((d)=>d.checkouts));return source.map((d,i)=>`${source.length<=1?0:(i/(source.length-1))*100},${100-(d.checkouts/max)*82}`).join(' ');},[source]);return <div className="card"><h3>Évolution quotidienne</h3><svg viewBox="0 0 100 100" role="img" aria-label="Courbe des visites et checkouts" style={{width:'100%',height:280,background:'linear-gradient(145deg,#0c1118,#121922)',border:'1px solid #2e3946',borderRadius:16}}><line x1="0" y1="100" x2="100" y2="100" stroke="#3e4957" strokeWidth="0.5"/><polyline points={points} fill="none" stroke="#ff7181" strokeWidth="2.5" vectorEffect="non-scaling-stroke"/><polyline points={checkout} fill="none" stroke="#e0bd62" strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg><p className="muted"><strong style={{color:'#ff7181'}}>■ Visites</strong> · <strong style={{color:'#e0bd62'}}>■ Checkouts</strong></p></div>;}

function ReportPreview({data}:{data:Dashboard}){const s=data.summary;return <section className="card" style={{overflow:'hidden',padding:0}}><div style={{padding:'26px 26px 22px',background:'radial-gradient(circle at 85% 0%,rgba(210,173,79,.22),transparent 33%),linear-gradient(145deg,#090b0f,#151920)',borderBottom:'1px solid #343a43'}}><div className="eyebrow" style={{color:'#d2ad4f'}}>KHE BOOTH • RAPPORT CONFIDENTIEL</div><h2 style={{fontSize:'clamp(28px,5vw,48px)',maxWidth:760,margin:'10px 0'}}>Marketing & Analytics</h2><p className="muted" style={{maxWidth:780}}>Aperçu du rapport généré pour les {data.days} derniers jours. Les mêmes chiffres sont exportés dans les quatre formats.</p></div><div style={{padding:24}}><div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))'}}>{[['Visites',s.visits],['Paiements',s.payments],['Conversion',`${s.conversionPercent}%`],['Revenus',`CHF ${(s.revenueCents/100).toFixed(2)}`]].map(([label,value])=><div key={String(label)} style={{padding:16,borderRadius:14,background:'#11161d',border:'1px solid #2f3741'}}><div className="eyebrow">{label}</div><div style={{fontSize:26,fontWeight:950,color:'#e4c76e',marginTop:6}}>{value}</div></div>)}</div><div style={{marginTop:18,overflowX:'auto'}}><table className="table"><thead><tr><th>Offre</th><th>Choix</th><th>Checkouts</th><th>Paiements</th><th>Revenus</th></tr></thead><tbody>{data.planPerformance.length?data.planPerformance.map((p)=><tr key={p.planCode||'none'}><td>{p.planCode||'—'}</td><td>{p.selections}</td><td>{p.checkouts}</td><td>{p.payments}</td><td>CHF {(p.revenueCents/100).toFixed(2)}</td></tr>):<tr><td colSpan={5} className="muted">Les performances par offre apparaîtront ici dès que des données seront disponibles.</td></tr>}</tbody></table></div></div></section>;}

export default function MarketingPage(){
  const[data,setData]=useState<Dashboard>(EMPTY);const[days,setDays]=useState(30);const[view,setView]=useState<ViewMode>('ANALYSE');const[message,setMessage]=useState('');const[loading,setLoading]=useState(true);const[degraded,setDegraded]=useState(false);const[busy,setBusy]=useState(false);const[downloadBusy,setDownloadBusy]=useState<ReportFormat|null>(null);const[name,setName]=useState('Campagne manuelle KHE');const[planCode,setPlanCode]=useState('PRO');const[discount,setDiscount]=useState(10);const[duration,setDuration]=useState(7);
  const load=useCallback(async()=>{setLoading(true);try{const next=await apiRequest<Dashboard>(`/marketing/dashboard?days=${days}`);setData(next);setDegraded(false);setMessage('');}catch(e){setData((current)=>({...current,days}));setDegraded(true);setMessage(e instanceof Error?e.message:'Chargement Analytics impossible');}finally{setLoading(false);}},[days]);useEffect(()=>{void load();},[load]);
  async function saveAutomation(){setBusy(true);try{await apiRequest('/marketing/automation',{method:'PATCH',body:JSON.stringify(data.automation)});setMessage('✓ Règles marketing enregistrées.');await load();}catch(e){setMessage(e instanceof Error?e.message:'Erreur');}finally{setBusy(false);}}
  async function evaluate(){setBusy(true);try{const result=await apiRequest<{reason?:string}>('/marketing/automation/evaluate',{method:'POST'});setMessage(`Analyse automatique terminée : ${result.reason||'ok'}.`);await load();}catch(e){setMessage(e instanceof Error?e.message:'Erreur');}finally{setBusy(false);}}
  async function createCampaign(event:FormEvent){event.preventDefault();setBusy(true);try{const startsAt=new Date();const endsAt=new Date(Date.now()+duration*86400000);await apiRequest('/marketing/campaigns',{method:'POST',body:JSON.stringify({name,planCode,segment:'ALL',discountPercent:discount,startsAt:startsAt.toISOString(),endsAt:endsAt.toISOString(),messageTitle:`Offre KHE Booth -${discount}%`,messageBody:`Promotion limitée de ${discount}% pendant ${duration} jours.`})});setMessage('✓ Campagne manuelle créée.');await load();}catch(e){setMessage(e instanceof Error?e.message:'Erreur');}finally{setBusy(false);}}
  async function toggleCampaign(c:Campaign){try{await apiRequest(`/marketing/campaigns/${c.id}`,{method:'PATCH',body:JSON.stringify({active:!c.active,discountPercent:c.discountPercent})});await load();}catch(e){setMessage(e instanceof Error?e.message:'Modification impossible');}}
  async function downloadReport(format:ReportFormat){const token=getAccessToken();if(!token){setMessage('Reconnectez-vous pour télécharger le rapport.');return;}setDownloadBusy(format);setMessage('');try{const response=await fetch(`${API_BASE}/marketing/report/${format}?days=${days}`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error(`Export ${format.toUpperCase()} impossible (HTTP ${response.status}).`);const blob=await response.blob();const disposition=response.headers.get('content-disposition')||'';const match=disposition.match(/filename="?([^";]+)"?/i);const fallback=`khe-booth-rapport-${days}j.${format==='jpeg'?'jpg':format}`;const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=match?.[1]||fallback;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);setMessage(`✓ Rapport ${format==='docx'?'Word':format==='xlsx'?'Excel':format.toUpperCase()} téléchargé.`);}catch(e){setMessage(e instanceof Error?e.message:'Téléchargement impossible.');}finally{setDownloadBusy(null);}}
  const s=data.summary;
  const tabStyle=(active:boolean)=>({border:'1px solid '+(active?'#d2ad4f':'#35404d'),background:active?'linear-gradient(135deg,#d2ad4f,#9e7929)':'#111820',color:active?'#0c0c0c':'#f4f6f8',borderRadius:14,padding:'12px 18px',fontWeight:950,cursor:'pointer' as const,boxShadow:active?'0 10px 26px rgba(210,173,79,.18)':'none'});
  return <PortalShell>
    <div className="page-header"><div><div className="eyebrow">MARKETING & ANALYTICS</div><h1>{view==='ANALYSE'?'Analyse comportementale & performance':'Rapports KHE BOOTH'}</h1><p className="muted">{view==='ANALYSE'?'Visites, choix d’offre, checkouts, paiements, téléchargements, campagnes et revenus restent visibles même si une synchronisation échoue.':'Consultez un aperçu puis exportez vos indicateurs dans le format adapté à votre usage professionnel.'}</p></div><div className="toolbar"><select value={days} onChange={(e)=>setDays(Number(e.target.value))}><option value={7}>7 jours</option><option value={30}>30 jours</option><option value={90}>90 jours</option><option value={365}>1 an</option></select><button className="button secondary" onClick={()=>void load()}>{loading?'Actualisation…':'↻ Actualiser'}</button></div></div>
    <div style={{display:'flex',gap:10,flexWrap:'wrap',marginBottom:18}}><button type="button" onClick={()=>setView('ANALYSE')} style={tabStyle(view==='ANALYSE')}>▥ Analyse</button><button type="button" onClick={()=>setView('REPORTS')} style={tabStyle(view==='REPORTS')}>▣ Rapports & téléchargements</button></div>
    {degraded?<div className="portal-error-state" style={{marginBottom:16}}><div className="eyebrow">CONNEXION ANALYTICS À RÉTABLIR</div><h2>Le tableau reste disponible.</h2><p>La dernière requête API n’a pas abouti. Les indicateurs restent affichés au lieu de laisser une page vide. Utilisez « Actualiser » après le rétablissement.</p>{message?<code style={{fontSize:11,color:'#e7cc88',overflowWrap:'anywhere'}}>{message}</code>:null}</div>:null}

    {view==='REPORTS'?<>
      <div className="grid two" style={{alignItems:'stretch'}}><section className="card" style={{background:'linear-gradient(145deg,#101720,#15120b)',border:'1px solid rgba(210,173,79,.34)'}}><div className="eyebrow" style={{color:'#d2ad4f'}}>CENTRE D’EXPORT</div><h2 style={{marginBottom:8}}>Télécharger ce rapport</h2><p className="muted">Période sélectionnée : <strong>{days} jours</strong>. Le rapport contient la synthèse, les conversions, les revenus, les performances par offre et le détail quotidien.</p><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:10,marginTop:18}}>{([['pdf','PDF','Document prêt à imprimer'],['jpeg','JPEG','Visuel partageable'],['docx','Word','Rapport éditable'],['xlsx','Excel','Données et tableaux']] as Array<[ReportFormat,string,string]>).map(([format,label,description])=><button key={format} type="button" className="button secondary" disabled={Boolean(downloadBusy)||degraded} onClick={()=>void downloadReport(format)} style={{minHeight:86,textAlign:'left',display:'grid',alignContent:'center',gap:4,borderColor:format==='pdf'?'#b31520':format==='jpeg'?'#d2ad4f':'#3c4857'}}><strong style={{fontSize:18}}>{downloadBusy===format?'Préparation…':label}</strong><span style={{fontSize:11,opacity:.7}}>{description}</span></button>)}</div></section><section className="card"><div className="eyebrow">AUTOMATISATION</div><h2>Rapport dirigeant</h2><p className="muted">Les rapports automatiques KHE utilisent les mêmes données validées. Le propriétaire reçoit les alertes et retrouve ici les exports à la demande.</p><div style={{display:'grid',gap:10,marginTop:18}}><div style={{padding:14,border:'1px solid #303945',borderRadius:13}}><strong>Format de travail</strong><p className="muted" style={{marginBottom:0}}>Excel pour l’analyse, Word pour l’édition, PDF pour l’archivage, JPEG pour un résumé visuel.</p></div><div style={{padding:14,border:'1px solid #303945',borderRadius:13}}><strong>Données toujours recalculées</strong><p className="muted" style={{marginBottom:0}}>Chaque téléchargement régénère le rapport avec les chiffres de la période sélectionnée.</p></div></div></section></div><div style={{height:16}}/><ReportPreview data={data}/>
    </>:<>
      <div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))'}}>{[['Visites',s.visits],['Choix d’offre',s.planSelections],['Checkouts',s.checkoutStarts],['Paiements',s.payments],['Conversion',`${s.conversionPercent}%`],['Revenus',`CHF ${(s.revenueCents/100).toFixed(2)}`],['Téléchargements',s.downloads]].map(([label,value])=><div className="card" key={String(label)}><div className="eyebrow">{label}</div><div style={{fontSize:30,fontWeight:900,marginTop:8}}>{value}</div></div>)}</div>
      <div style={{height:16}}/><Curve daily={data.daily}/><div style={{height:16}}/>
      <div className="grid two"><section className="card"><h2>Entonnoir de conversion</h2><div style={{display:'grid',gap:9}}>{[['Visites',s.visits],['Offres sélectionnées',s.planSelections],['Checkout démarré',s.checkoutStarts],['Paiement confirmé',s.payments]].map(([label,value],i)=><div key={String(label)} style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',background:i===3?'linear-gradient(135deg,rgba(51,150,91,.18),#111a17)':'linear-gradient(135deg,rgba(214,175,82,.09),#111820)',color:'#f5f7f9',border:`1px solid ${i===3?'rgba(89,194,128,.28)':'#303a47'}`,borderRadius:12,padding:'13px 14px',width:`${Math.max(58,100-i*10)}%`,maxWidth:'100%'}}><strong>{label}</strong><span style={{fontWeight:950,color:i===3?'#91e4b4':'#e4c76e'}}>{value}</span></div>)}</div></section><section className="card"><h2>Performance par offre</h2><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Offre</th><th>Choix</th><th>Checkout</th><th>Paiements</th><th>Revenus</th></tr></thead><tbody>{data.planPerformance.length?data.planPerformance.map((p)=><tr key={p.planCode||'none'}><td>{p.planCode||'—'}</td><td>{p.selections}</td><td>{p.checkouts}</td><td>{p.payments}</td><td>CHF {(p.revenueCents/100).toFixed(2)}</td></tr>):<tr><td colSpan={5} className="muted">Aucune performance enregistrée pour cette période.</td></tr>}</tbody></table></div></section></div>
      <div style={{height:16}}/><div className="grid two"><section className="card" style={{display:'grid',gap:12}}><h2>Robot marketing</h2><label className="team-permission-option"><span>Automatisation active<small style={{display:'block',marginTop:3,color:'#8f9bab'}}>Autoriser KHE à analyser les performances et déclencher les règles configurées.</small></span><input type="checkbox" checked={data.automation.enabled} onChange={(e)=>setData({...data,automation:{...data.automation,enabled:e.target.checked}})}/></label><label>Remise maximum %<input type="number" min="0" max="30" value={data.automation.maxDiscountPercent} onChange={(e)=>setData({...data,automation:{...data.automation,maxDiscountPercent:Number(e.target.value)}})}/></label><label>Échantillon minimum de checkouts<input type="number" min="5" value={data.automation.minCheckoutSample} onChange={(e)=>setData({...data,automation:{...data.automation,minCheckoutSample:Number(e.target.value)}})}/></label><label>Seuil de conversion faible %<input type="number" min="1" max="80" value={data.automation.lowConversionThresholdPercent} onChange={(e)=>setData({...data,automation:{...data.automation,lowConversionThresholdPercent:Number(e.target.value)}})}/></label><label>Durée campagne auto (jours)<input type="number" min="1" max="30" value={data.automation.campaignDurationDays} onChange={(e)=>setData({...data,automation:{...data.automation,campaignDurationDays:Number(e.target.value)}})}/></label><label>Cooldown entre campagnes (jours)<input type="number" min="1" max="90" value={data.automation.cooldownDays} onChange={(e)=>setData({...data,automation:{...data.automation,cooldownDays:Number(e.target.value)}})}/></label><div className="toolbar"><button className="button" disabled={busy||degraded} onClick={()=>void saveAutomation()}>Enregistrer les règles</button><button className="button secondary" disabled={busy||degraded} onClick={()=>void evaluate()}>Analyser maintenant</button></div></section><form className="card" onSubmit={createCampaign} style={{display:'grid',gap:12}}><h2>Campagne manuelle</h2><label>Nom<input value={name} onChange={(e)=>setName(e.target.value)}/></label><label>Offre<select value={planCode} onChange={(e)=>setPlanCode(e.target.value)}><option>STARTER</option><option>PRO</option><option>BUSINESS</option><option>ENTERPRISE</option></select></label><label>Remise %<input type="number" min="0" max="30" value={discount} onChange={(e)=>setDiscount(Number(e.target.value))}/></label><label>Durée (jours)<input type="number" min="1" max="30" value={duration} onChange={(e)=>setDuration(Number(e.target.value))}/></label><button className="button" disabled={busy||degraded}>Créer la campagne</button></form></div>
      <div style={{height:16}}/><section className="card"><h2>Historique des campagnes</h2><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Campagne</th><th>Offre</th><th>Remise</th><th>Mode</th><th>Période</th><th>Statut</th><th>Action</th></tr></thead><tbody>{data.campaigns.length?data.campaigns.map((c)=><tr key={c.id}><td><strong>{c.name}</strong>{c.reason?<div className="muted" style={{fontSize:11,maxWidth:340}}>{c.reason}</div>:null}</td><td>{c.planCode||'Toutes'}</td><td>{c.discountPercent}%</td><td>{c.automatic?'Robot':'Manuel'}</td><td>{new Date(c.startsAt).toLocaleDateString()} → {new Date(c.endsAt).toLocaleDateString()}</td><td>{c.active?'Active':'Arrêtée'}</td><td><button className="button secondary compact" disabled={degraded} onClick={()=>void toggleCampaign(c)}>{c.active?'Suspendre':'Réactiver'}</button></td></tr>):<tr><td colSpan={7} className="muted">Aucune campagne enregistrée.</td></tr>}</tbody></table></div></section>
    </>}
    {!degraded&&message?<p className="card" style={{marginTop:16}}>{message}</p>:null}
  </PortalShell>;
}
