'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { PortalShell } from '@/components/portal-shell';
import { apiRequest, getAccessToken } from '@/lib/api';

type Daily={day:string;visits:number;checkouts:number;payments:number;revenueCents:number};
type Campaign={id:string;name:string;planCode?:string|null;segment:string;discountPercent:number;startsAt:string;endsAt:string;active:boolean;automatic:boolean;reason?:string|null};
type Automation={enabled:boolean;maxDiscountPercent:number;minCheckoutSample:number;lowConversionThresholdPercent:number;campaignDurationDays:number;cooldownDays:number;targetDiscovery:boolean;targetPaymentPending:boolean;ownerReportsEnabled:boolean};
type Dashboard={days:number;summary:{visits:number;planSelections:number;checkoutStarts:number;payments:number;downloads:number;revenueCents:number;conversionPercent:number;visitToPaymentPercent:number};daily:Daily[];planPerformance:Array<{planCode?:string|null;selections:number;checkouts:number;payments:number;revenueCents:number}>;campaigns:Campaign[];automation:Automation};
const API_BASE=(process.env.NEXT_PUBLIC_API_URL||'https://khebooth-api.vercel.app/api').replace(/\/$/,'');
const EMPTY:Dashboard={days:30,summary:{visits:0,planSelections:0,checkoutStarts:0,payments:0,downloads:0,revenueCents:0,conversionPercent:0,visitToPaymentPercent:0},daily:[],planPerformance:[],campaigns:[],automation:{enabled:true,maxDiscountPercent:15,minCheckoutSample:20,lowConversionThresholdPercent:10,campaignDurationDays:7,cooldownDays:21,targetDiscovery:true,targetPaymentPending:true,ownerReportsEnabled:true}};

function Curve({daily}:{daily:Daily[]}){const source=daily.length?daily:[{day:'',visits:0,checkouts:0,payments:0,revenueCents:0},{day:'',visits:0,checkouts:0,payments:0,revenueCents:0}];const points=useMemo(()=>{const max=Math.max(1,...source.map((d)=>d.visits));return source.map((d,i)=>`${source.length<=1?0:(i/(source.length-1))*100},${100-(d.visits/max)*82}`).join(' ');},[source]);const checkout=useMemo(()=>{const max=Math.max(1,...source.map((d)=>d.checkouts));return source.map((d,i)=>`${source.length<=1?0:(i/(source.length-1))*100},${100-(d.checkouts/max)*82}`).join(' ');},[source]);return <div className="card"><h3>Évolution quotidienne</h3><svg viewBox="0 0 100 100" role="img" aria-label="Courbe des visites et checkouts" style={{width:'100%',height:280,background:'linear-gradient(145deg,#0c1118,#121922)',border:'1px solid #2e3946',borderRadius:16}}><line x1="0" y1="100" x2="100" y2="100" stroke="#3e4957" strokeWidth="0.5"/><polyline points={points} fill="none" stroke="#ff7181" strokeWidth="2.5" vectorEffect="non-scaling-stroke"/><polyline points={checkout} fill="none" stroke="#e0bd62" strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg><p className="muted"><strong style={{color:'#ff7181'}}>■ Visites</strong> · <strong style={{color:'#e0bd62'}}>■ Checkouts</strong></p></div>;}

export default function MarketingPage(){
  const[data,setData]=useState<Dashboard>(EMPTY);const[days,setDays]=useState(30);const[message,setMessage]=useState('');const[loading,setLoading]=useState(true);const[degraded,setDegraded]=useState(false);const[busy,setBusy]=useState(false);const[name,setName]=useState('Campagne manuelle KHE');const[planCode,setPlanCode]=useState('PRO');const[discount,setDiscount]=useState(10);const[duration,setDuration]=useState(7);
  const load=useCallback(async()=>{setLoading(true);try{const next=await apiRequest<Dashboard>(`/marketing/dashboard?days=${days}`);setData(next);setDegraded(false);setMessage('');}catch(e){setData((current)=>({...current,days}));setDegraded(true);setMessage(e instanceof Error?e.message:'Chargement Analytics impossible');}finally{setLoading(false);}},[days]);useEffect(()=>{void load();},[load]);
  async function saveAutomation(){setBusy(true);try{await apiRequest('/marketing/automation',{method:'PATCH',body:JSON.stringify(data.automation)});setMessage('✓ Règles marketing enregistrées.');await load();}catch(e){setMessage(e instanceof Error?e.message:'Erreur');}finally{setBusy(false);}}
  async function evaluate(){setBusy(true);try{const result=await apiRequest<{reason?:string}>('/marketing/automation/evaluate',{method:'POST'});setMessage(`Analyse automatique terminée : ${result.reason||'ok'}.`);await load();}catch(e){setMessage(e instanceof Error?e.message:'Erreur');}finally{setBusy(false);}}
  async function createCampaign(event:FormEvent){event.preventDefault();setBusy(true);try{const startsAt=new Date();const endsAt=new Date(Date.now()+duration*86400000);await apiRequest('/marketing/campaigns',{method:'POST',body:JSON.stringify({name,planCode,segment:'ALL',discountPercent:discount,startsAt:startsAt.toISOString(),endsAt:endsAt.toISOString(),messageTitle:`Offre KHE Booth -${discount}%`,messageBody:`Promotion limitée de ${discount}% pendant ${duration} jours.`})});setMessage('✓ Campagne manuelle créée.');await load();}catch(e){setMessage(e instanceof Error?e.message:'Erreur');}finally{setBusy(false);}}
  async function toggleCampaign(c:Campaign){try{await apiRequest(`/marketing/campaigns/${c.id}`,{method:'PATCH',body:JSON.stringify({active:!c.active,discountPercent:c.discountPercent})});await load();}catch(e){setMessage(e instanceof Error?e.message:'Modification impossible');}}
  async function downloadPdf(){const token=getAccessToken();if(!token)return;const response=await fetch(`${API_BASE}/marketing/report.pdf?days=${days}`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok){setMessage('Téléchargement PDF impossible.');return;}const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`khe-marketing-${new Date().toISOString().slice(0,10)}.pdf`;a.click();URL.revokeObjectURL(url);}
  const s=data.summary;
  return <PortalShell>
    <div className="page-header"><div><div className="eyebrow">MARKETING & ANALYTICS</div><h1>Analyse comportementale & performance</h1><p className="muted">Visites, choix d’offre, checkouts, paiements, téléchargements, campagnes et revenus restent visibles même si une synchronisation échoue.</p></div><div className="toolbar"><select value={days} onChange={(e)=>setDays(Number(e.target.value))}><option value={7}>7 jours</option><option value={30}>30 jours</option><option value={90}>90 jours</option><option value={365}>1 an</option></select><button className="button secondary" onClick={()=>void load()}>{loading?'Actualisation…':'↻ Actualiser'}</button><button className="button secondary" onClick={()=>void downloadPdf()}>Télécharger PDF</button></div></div>
    {degraded?<div className="portal-error-state" style={{marginBottom:16}}><div className="eyebrow">CONNEXION ANALYTICS À RÉTABLIR</div><h2>Le tableau reste disponible.</h2><p>La dernière requête API n’a pas abouti. Les indicateurs restent affichés au lieu de laisser une page vide. Utilisez « Actualiser » après le rétablissement.</p>{message?<code style={{fontSize:11,color:'#e7cc88',overflowWrap:'anywhere'}}>{message}</code>:null}</div>:null}
    <div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))'}}>{[['Visites',s.visits],['Choix d’offre',s.planSelections],['Checkouts',s.checkoutStarts],['Paiements',s.payments],['Conversion',`${s.conversionPercent}%`],['Revenus',`CHF ${(s.revenueCents/100).toFixed(2)}`],['Téléchargements',s.downloads]].map(([label,value])=><div className="card" key={String(label)}><div className="eyebrow">{label}</div><div style={{fontSize:30,fontWeight:900,marginTop:8}}>{value}</div></div>)}</div>
    <div style={{height:16}}/><Curve daily={data.daily}/><div style={{height:16}}/>
    <div className="grid two"><section className="card"><h2>Entonnoir de conversion</h2><div style={{display:'grid',gap:9}}>{[['Visites',s.visits],['Offres sélectionnées',s.planSelections],['Checkout démarré',s.checkoutStarts],['Paiement confirmé',s.payments]].map(([label,value],i)=><div key={String(label)} style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',background:i===3?'linear-gradient(135deg,rgba(51,150,91,.18),#111a17)':'linear-gradient(135deg,rgba(214,175,82,.09),#111820)',color:'#f5f7f9',border:`1px solid ${i===3?'rgba(89,194,128,.28)':'#303a47'}`,borderRadius:12,padding:'13px 14px',width:`${Math.max(58,100-i*10)}%`,maxWidth:'100%'}}><strong>{label}</strong><span style={{fontWeight:950,color:i===3?'#91e4b4':'#e4c76e'}}>{value}</span></div>)}</div></section><section className="card"><h2>Performance par offre</h2><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Offre</th><th>Choix</th><th>Checkout</th><th>Paiements</th><th>Revenus</th></tr></thead><tbody>{data.planPerformance.length?data.planPerformance.map((p)=><tr key={p.planCode||'none'}><td>{p.planCode||'—'}</td><td>{p.selections}</td><td>{p.checkouts}</td><td>{p.payments}</td><td>CHF {(p.revenueCents/100).toFixed(2)}</td></tr>):<tr><td colSpan={5} className="muted">Aucune performance enregistrée pour cette période.</td></tr>}</tbody></table></div></section></div>
    <div style={{height:16}}/><div className="grid two"><section className="card" style={{display:'grid',gap:12}}><h2>Robot marketing</h2><label className="team-permission-option"><span>Automatisation active<small style={{display:'block',marginTop:3,color:'#8f9bab'}}>Autoriser KHE à analyser les performances et déclencher les règles configurées.</small></span><input type="checkbox" checked={data.automation.enabled} onChange={(e)=>setData({...data,automation:{...data.automation,enabled:e.target.checked}})}/></label><label>Remise maximum %<input type="number" min="0" max="30" value={data.automation.maxDiscountPercent} onChange={(e)=>setData({...data,automation:{...data.automation,maxDiscountPercent:Number(e.target.value)}})}/></label><label>Échantillon minimum de checkouts<input type="number" min="5" value={data.automation.minCheckoutSample} onChange={(e)=>setData({...data,automation:{...data.automation,minCheckoutSample:Number(e.target.value)}})}/></label><label>Seuil de conversion faible %<input type="number" min="1" max="80" value={data.automation.lowConversionThresholdPercent} onChange={(e)=>setData({...data,automation:{...data.automation,lowConversionThresholdPercent:Number(e.target.value)}})}/></label><label>Durée campagne auto (jours)<input type="number" min="1" max="30" value={data.automation.campaignDurationDays} onChange={(e)=>setData({...data,automation:{...data.automation,campaignDurationDays:Number(e.target.value)}})}/></label><label>Cooldown entre campagnes (jours)<input type="number" min="1" max="90" value={data.automation.cooldownDays} onChange={(e)=>setData({...data,automation:{...data.automation,cooldownDays:Number(e.target.value)}})}/></label><div className="toolbar"><button className="button" disabled={busy||degraded} onClick={()=>void saveAutomation()}>Enregistrer les règles</button><button className="button secondary" disabled={busy||degraded} onClick={()=>void evaluate()}>Analyser maintenant</button></div></section><form className="card" onSubmit={createCampaign} style={{display:'grid',gap:12}}><h2>Campagne manuelle</h2><label>Nom<input value={name} onChange={(e)=>setName(e.target.value)}/></label><label>Offre<select value={planCode} onChange={(e)=>setPlanCode(e.target.value)}><option>STARTER</option><option>PRO</option><option>BUSINESS</option><option>ENTERPRISE</option></select></label><label>Remise %<input type="number" min="0" max="30" value={discount} onChange={(e)=>setDiscount(Number(e.target.value))}/></label><label>Durée (jours)<input type="number" min="1" max="30" value={duration} onChange={(e)=>setDuration(Number(e.target.value))}/></label><button className="button" disabled={busy||degraded}>Créer la campagne</button></form></div>
    <div style={{height:16}}/><section className="card"><h2>Historique des campagnes</h2><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Campagne</th><th>Offre</th><th>Remise</th><th>Mode</th><th>Période</th><th>Statut</th><th>Action</th></tr></thead><tbody>{data.campaigns.length?data.campaigns.map((c)=><tr key={c.id}><td><strong>{c.name}</strong>{c.reason?<div className="muted" style={{fontSize:11,maxWidth:340}}>{c.reason}</div>:null}</td><td>{c.planCode||'Toutes'}</td><td>{c.discountPercent}%</td><td>{c.automatic?'Robot':'Manuel'}</td><td>{new Date(c.startsAt).toLocaleDateString()} → {new Date(c.endsAt).toLocaleDateString()}</td><td>{c.active?'Active':'Arrêtée'}</td><td><button className="button secondary compact" disabled={degraded} onClick={()=>void toggleCampaign(c)}>{c.active?'Suspendre':'Réactiver'}</button></td></tr>):<tr><td colSpan={7} className="muted">Aucune campagne enregistrée.</td></tr>}</tbody></table></div></section>
    {!degraded&&message?<p className="card" style={{marginTop:16}}>{message}</p>:null}
  </PortalShell>;
}
