import { BadRequestException, Injectable, NotFoundException, UnauthorizedException } from '@nestjs/common';
import { createHmac, timingSafeEqual } from 'node:crypto';
import { PrismaService } from '../prisma/prisma.service';

type EmailSettings={organizationId:string;enabled:boolean;senderName:string;replyTo:string|null;assignedUserId:string|null;maxEmailsPer7Days:number;timezone:string;sendWindowStartHour:number;sendWindowEndHour:number;consentVersion:string};
type Scenario={id:string;organizationId:string;code:string;name:string;enabled:boolean;segment:string;scheduleHours:unknown;subjectTemplate:string;bodyTemplate:string;ctaLabel:string;ctaPath:string};
type DueJourney={id:string;organizationId:string;clientId:string;scenarioCode:string;journeyKey:string;context:unknown;lastStep:number;email:string;name:string;marketingEmailsEnabled:boolean;marketingConsentAt:Date|null;marketingUnsubscribedAt:Date|null;archivedAt:Date|null;lastMarketingEmailAt:Date|null;enabled:boolean;senderName:string;replyTo:string|null;maxEmailsPer7Days:number;timezone:string;sendWindowStartHour:number;sendWindowEndHour:number;consentVersion:string;scenarioEnabled:boolean;scheduleHours:unknown;subjectTemplate:string;bodyTemplate:string;ctaLabel:string;ctaPath:string};

@Injectable()
export class EmailMarketingService{
  constructor(private readonly prisma:PrismaService){}

  private origin(){return (process.env.WEB_ORIGIN||'https://khebooth-rdvo.vercel.app').split(',')[0].trim().replace(/\/$/,'');}
  private consentVersion(){return 'marketing-v1';}
  private schedule(value:unknown){const raw=Array.isArray(value)?value:[];return raw.map(Number).filter((v)=>Number.isFinite(v)&&v>=1&&v<=2160).map(Math.round).slice(0,8);}
  private escape(value:string){return value.replace(/[&<>"']/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]||char));}
  private render(template:string,values:Record<string,string>){return template.replace(/\{\{(\w+)\}\}/g,(_,key:string)=>values[key]??'');}
  private token(clientId:string){const secret=(process.env.MARKETING_UNSUBSCRIBE_SECRET||process.env.JWT_SECRET||'').trim();if(!secret)throw new Error('Marketing unsubscribe secret is not configured');return createHmac('sha256',secret).update(clientId).digest('hex');}
  private tokenValid(clientId:string,value:string){try{const expected=this.token(clientId);const a=Buffer.from(expected);const b=Buffer.from(String(value||''));return a.length===b.length&&timingSafeEqual(a,b);}catch{return false;}}

  private async ensureSettings(organizationId:string){await this.prisma.$executeRaw`INSERT INTO "MarketingEmailSettings" ("organizationId") VALUES (${organizationId}::uuid) ON CONFLICT ("organizationId") DO NOTHING`;}

  async settings(organizationId:string){
    await this.ensureSettings(organizationId);
    const settings=await this.prisma.$queryRaw<EmailSettings[]>`SELECT "organizationId",enabled,"senderName","replyTo","assignedUserId","maxEmailsPer7Days",timezone,"sendWindowStartHour","sendWindowEndHour","consentVersion" FROM "MarketingEmailSettings" WHERE "organizationId"=${organizationId}::uuid LIMIT 1`;
    const team=await this.prisma.$queryRaw<Array<{id:string;email:string;firstName:string|null;lastName:string|null;role:string}>>`SELECT id,email,"firstName","lastName",role::text AS role FROM "User" WHERE "organizationId"=${organizationId}::uuid AND "isActive"=TRUE ORDER BY role,email`;
    return{...(settings[0]??null),team};
  }

  async updateSettings(organizationId:string,userId:string,body:Record<string,unknown>){
    await this.ensureSettings(organizationId);
    const max=Math.max(1,Math.min(10,Math.trunc(Number(body.maxEmailsPer7Days??3))));const start=Math.max(0,Math.min(23,Math.trunc(Number(body.sendWindowStartHour??8))));const end=Math.max(1,Math.min(24,Math.trunc(Number(body.sendWindowEndHour??19))));if(start>=end)throw new BadRequestException('La fin de la plage d’envoi doit être après son début.');
    const assignedUserId=body.assignedUserId?String(body.assignedUserId):null;if(assignedUserId){const users=await this.prisma.$queryRaw<Array<{id:string}>>`SELECT id FROM "User" WHERE id=${assignedUserId}::uuid AND "organizationId"=${organizationId}::uuid AND "isActive"=TRUE LIMIT 1`;if(!users[0])throw new BadRequestException('Le membre assigné est invalide ou inactif.');}
    const senderName=String(body.senderName??'KHE BOOTH').trim().slice(0,120)||'KHE BOOTH';const replyTo=body.replyTo?String(body.replyTo).trim().toLowerCase():null;if(replyTo&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(replyTo))throw new BadRequestException('Adresse Reply-To invalide.');const timezone=String(body.timezone??'Europe/Zurich').trim().slice(0,80)||'Europe/Zurich';
    await this.prisma.$executeRaw`UPDATE "MarketingEmailSettings" SET enabled=${body.enabled!==false},"senderName"=${senderName},"replyTo"=${replyTo},"assignedUserId"=${assignedUserId}::uuid,"maxEmailsPer7Days"=${max},timezone=${timezone},"sendWindowStartHour"=${start},"sendWindowEndHour"=${end},"updatedAt"=CURRENT_TIMESTAMP WHERE "organizationId"=${organizationId}::uuid`;
    await this.prisma.auditLog.create({data:{organizationId,userId,action:'MARKETING_EMAIL_SETTINGS_UPDATED',entityType:'MarketingEmailSettings',entityId:organizationId,metadata:{assignedUserId,maxEmailsPer7Days:max,sendWindowStartHour:start,sendWindowEndHour:end}}});return this.settings(organizationId);
  }

  async scenarios(organizationId:string){return this.prisma.$queryRaw<Scenario[]>`SELECT id,"organizationId",code,name,enabled,segment,"scheduleHours","subjectTemplate","bodyTemplate","ctaLabel","ctaPath" FROM "MarketingEmailScenario" WHERE "organizationId"=${organizationId}::uuid ORDER BY name`;}

  async updateScenario(organizationId:string,userId:string,codeValue:string,body:Record<string,unknown>){
    const code=codeValue.trim().toUpperCase();const current=(await this.prisma.$queryRaw<Scenario[]>`SELECT id,"organizationId",code,name,enabled,segment,"scheduleHours","subjectTemplate","bodyTemplate","ctaLabel","ctaPath" FROM "MarketingEmailScenario" WHERE "organizationId"=${organizationId}::uuid AND code=${code} LIMIT 1`)[0];if(!current)throw new NotFoundException('Scénario e-mail introuvable.');
    const schedule=this.schedule(body.scheduleHours??current.scheduleHours);if(schedule.length===0)throw new BadRequestException('Ajoutez au moins un délai d’envoi valide.');const subject=String(body.subjectTemplate??current.subjectTemplate).trim().slice(0,240);const content=String(body.bodyTemplate??current.bodyTemplate).trim().slice(0,8000);const ctaLabel=String(body.ctaLabel??current.ctaLabel).trim().slice(0,100);const ctaPath=String(body.ctaPath??current.ctaPath).trim().slice(0,500);if(!subject||!content||!ctaLabel||!ctaPath.startsWith('/'))throw new BadRequestException('Sujet, contenu et CTA valides sont obligatoires.');
    await this.prisma.$executeRaw`UPDATE "MarketingEmailScenario" SET enabled=${body.enabled!==false},"scheduleHours"=${JSON.stringify(schedule)}::jsonb,"subjectTemplate"=${subject},"bodyTemplate"=${content},"ctaLabel"=${ctaLabel},"ctaPath"=${ctaPath},"updatedAt"=CURRENT_TIMESTAMP WHERE id=${current.id}::uuid`;
    await this.prisma.auditLog.create({data:{organizationId,userId,action:'MARKETING_EMAIL_SCENARIO_UPDATED',entityType:'MarketingEmailScenario',entityId:current.id,metadata:{code,scheduleHours:schedule}}});return(this.scenarios(organizationId)).then((items)=>items.find((item)=>item.code===code));
  }

  async captureCheckoutLead(organizationId:string,clientId:string,emailValue:string,optIn:boolean,planCode:string){
    const email=emailValue.trim().toLowerCase();if(!email.includes('@'))return;
    if(optIn){await this.ensureSettings(organizationId);const settings=(await this.prisma.$queryRaw<EmailSettings[]>`SELECT "organizationId",enabled,"senderName","replyTo","assignedUserId","maxEmailsPer7Days",timezone,"sendWindowStartHour","sendWindowEndHour","consentVersion" FROM "MarketingEmailSettings" WHERE "organizationId"=${organizationId}::uuid LIMIT 1`)[0];await this.prisma.$executeRaw`UPDATE "Client" SET email=${email},"emailSource"='PROMOTIONAL_CHECKOUT',"emailLastCapturedAt"=CURRENT_TIMESTAMP,"marketingEmailsEnabled"=TRUE,"marketingConsentAt"=CURRENT_TIMESTAMP,"marketingConsentSource"='PROMOTIONAL_CHECKOUT_OPT_IN',"marketingConsentVersion"=${settings?.consentVersion??this.consentVersion()},"marketingUnsubscribedAt"=NULL,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${clientId}::uuid AND "organizationId"=${organizationId}::uuid`;}
    else{await this.prisma.$executeRaw`UPDATE "Client" SET email=${email},"emailSource"='PROMOTIONAL_CHECKOUT',"emailLastCapturedAt"=CURRENT_TIMESTAMP,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${clientId}::uuid AND "organizationId"=${organizationId}::uuid`;}
    await this.prisma.auditLog.create({data:{organizationId,userId:null,action:'CLIENT_EMAIL_CAPTURED',entityType:'Client',entityId:clientId,metadata:{source:'PROMOTIONAL_CHECKOUT',marketingOptIn:optIn,planCode}}});
  }

  private async eligible(clientId:string){const rows=await this.prisma.$queryRaw<Array<{organizationId:string;marketingEmailsEnabled:boolean;marketingConsentAt:Date|null;marketingUnsubscribedAt:Date|null;archivedAt:Date|null}>>`SELECT "organizationId","marketingEmailsEnabled","marketingConsentAt","marketingUnsubscribedAt","archivedAt" FROM "Client" WHERE id=${clientId}::uuid LIMIT 1`;const c=rows[0];return c&&c.marketingEmailsEnabled&&Boolean(c.marketingConsentAt)&&!c.marketingUnsubscribedAt&&!c.archivedAt?c:null;}

  async startJourney(organizationId:string,clientId:string,scenarioCode:string,journeyKey:string,context:Record<string,unknown>={}){
    const eligible=await this.eligible(clientId);if(!eligible||eligible.organizationId!==organizationId)return{started:false,reason:'NO_MARKETING_CONSENT'};const scenario=(await this.prisma.$queryRaw<Scenario[]>`SELECT id,"organizationId",code,name,enabled,segment,"scheduleHours","subjectTemplate","bodyTemplate","ctaLabel","ctaPath" FROM "MarketingEmailScenario" WHERE "organizationId"=${organizationId}::uuid AND code=${scenarioCode} LIMIT 1`)[0];if(!scenario||!scenario.enabled)return{started:false,reason:'SCENARIO_DISABLED'};const schedule=this.schedule(scenario.scheduleHours);if(!schedule.length)return{started:false,reason:'EMPTY_SCHEDULE'};const nextDueAt=new Date(Date.now()+schedule[0]*3600000);await this.prisma.$executeRaw`INSERT INTO "MarketingEmailJourney" (id,"organizationId","clientId","scenarioCode","journeyKey",source,context,"startedAt","lastStep","nextDueAt","updatedAt") VALUES(gen_random_uuid(),${organizationId}::uuid,${clientId}::uuid,${scenarioCode},${journeyKey},${String(context.source??'AUTOMATION')},${JSON.stringify(context)}::jsonb,CURRENT_TIMESTAMP,-1,${nextDueAt},CURRENT_TIMESTAMP) ON CONFLICT ("organizationId","clientId","scenarioCode","journeyKey") DO UPDATE SET context=EXCLUDED.context,"cancelledAt"=NULL,"completedAt"=NULL,"nextDueAt"=CASE WHEN "MarketingEmailJourney"."lastStep"<0 THEN EXCLUDED."nextDueAt" ELSE "MarketingEmailJourney"."nextDueAt" END,"updatedAt"=CURRENT_TIMESTAMP`;return{started:true,nextDueAt};
  }

  startCartRecovery(organizationId:string,clientId:string,planCode:string,journeyKey:string){return this.startJourney(organizationId,clientId,'CART_RECOVERY',journeyKey,{source:'PROMOTIONAL_CHECKOUT',plan:planCode});}
  startDiscoveryNurture(organizationId:string,clientId:string,planCode:string){return this.startJourney(organizationId,clientId,'DISCOVERY_NURTURE',`discovery-${planCode}`,{source:'PROMOTIONAL_SITE',plan:planCode});}
  startExpiredWinback(organizationId:string,clientId:string,previousPlan:string){return this.startJourney(organizationId,clientId,'EXPIRED_WINBACK',`expired-${Date.now()}`,{source:'SUBSCRIPTION_LIFECYCLE',plan:previousPlan});}
  async completePurchase(clientId:string){await this.prisma.$executeRaw`UPDATE "MarketingEmailJourney" SET "cancelledAt"=CURRENT_TIMESTAMP,"nextDueAt"=NULL,"updatedAt"=CURRENT_TIMESTAMP WHERE "clientId"=${clientId}::uuid AND "scenarioCode"='CART_RECOVERY' AND "completedAt" IS NULL AND "cancelledAt" IS NULL`;return{cancelled:true};}

  private inWindow(timezone:string,start:number,end:number){try{const parts=new Intl.DateTimeFormat('en-US',{timeZone:timezone,hour:'2-digit',hour12:false}).formatToParts(new Date());const hour=Number(parts.find((part)=>part.type==='hour')?.value??-1);return hour>=start&&hour<end;}catch{return true;}}

  private async send(row:DueJourney){
    const key=process.env.RESEND_API_KEY?.trim();const from=process.env.KHE_EMAIL_FROM?.trim();if(!key||!from)throw new Error('EMAIL_PROVIDER_NOT_CONFIGURED');
    const context=row.context&&typeof row.context==='object'&&!Array.isArray(row.context)?row.context as Record<string,unknown>:{};const plan=String(context.plan??'KHE BOOTH');const firstName=row.name.trim().split(/\s+/)[0]||row.name;const values={name:firstName,plan};const subject=this.render(row.subjectTemplate,values);const body=this.render(row.bodyTemplate,values);const ctaUrl=`${this.origin()}${row.ctaPath}${row.ctaPath.includes('?')?'&':'?'}utm_source=khe_email&utm_medium=automation&utm_campaign=${encodeURIComponent(row.scenarioCode)}`;const unsubscribeUrl=`${this.origin()}/unsubscribe?client=${encodeURIComponent(row.clientId)}&token=${encodeURIComponent(this.token(row.clientId))}`;
    const html=`<div style="font-family:Arial,sans-serif;background:#f5f5f5;padding:26px"><div style="max-width:640px;margin:auto;background:#fff;border-radius:18px;padding:28px;color:#171717"><div style="font-weight:900;letter-spacing:3px;color:#b58a27">${this.escape(row.senderName)}</div><h2 style="margin:18px 0 10px">${this.escape(subject)}</h2><p style="line-height:1.7;white-space:pre-line">${this.escape(body)}</p><p style="margin:24px 0"><a href="${this.escape(ctaUrl)}" style="display:inline-block;background:#111;color:#fff;text-decoration:none;border-radius:10px;padding:13px 18px;font-weight:800">${this.escape(row.ctaLabel)}</a></p><hr style="border:0;border-top:1px solid #eee;margin:24px 0"><p style="font-size:11px;color:#777;line-height:1.5">Vous recevez cet e-mail parce que vous avez accepté les communications marketing KHE BOOTH. <a href="${this.escape(unsubscribeUrl)}">Se désabonner</a>.</p></div></div>`;
    const payload:Record<string,unknown>={from,to:[row.email],subject,html};if(row.replyTo)payload.reply_to=row.replyTo;const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json() as {id?:string;message?:string};if(!response.ok)throw new Error(data.message||`RESEND_HTTP_${response.status}`);return{providerMessageId:data.id??null,subject,body};
  }

  async process(secret:string|undefined){
    const expected=process.env.CRON_SECRET?.trim();if(!expected||secret!==expected)throw new UnauthorizedException('Invalid cron authorization');
    const due=await this.prisma.$queryRaw<DueJourney[]>`
      SELECT j.id,j."organizationId",j."clientId",j."scenarioCode",j."journeyKey",j.context,j."lastStep",c.email,c.name,c."marketingEmailsEnabled",c."marketingConsentAt",c."marketingUnsubscribedAt",c."archivedAt",c."lastMarketingEmailAt",s.enabled,s."senderName",s."replyTo",s."maxEmailsPer7Days",s.timezone,s."sendWindowStartHour",s."sendWindowEndHour",s."consentVersion",sc.enabled AS "scenarioEnabled",sc."scheduleHours",sc."subjectTemplate",sc."bodyTemplate",sc."ctaLabel",sc."ctaPath"
      FROM "MarketingEmailJourney" j JOIN "Client" c ON c.id=j."clientId" JOIN "MarketingEmailSettings" s ON s."organizationId"=j."organizationId" JOIN "MarketingEmailScenario" sc ON sc."organizationId"=j."organizationId" AND sc.code=j."scenarioCode"
      WHERE j."nextDueAt" IS NOT NULL AND j."nextDueAt"<=CURRENT_TIMESTAMP AND j."completedAt" IS NULL AND j."cancelledAt" IS NULL AND c.email IS NOT NULL
      ORDER BY j."nextDueAt" ASC LIMIT 100`;
    let sent=0,failed=0,skipped=0;
    for(const row of due){
      if(!row.enabled||!row.scenarioEnabled||!row.marketingEmailsEnabled||!row.marketingConsentAt||row.marketingUnsubscribedAt||row.archivedAt){await this.prisma.$executeRaw`UPDATE "MarketingEmailJourney" SET "cancelledAt"=CURRENT_TIMESTAMP,"nextDueAt"=NULL,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${row.id}::uuid`;skipped++;continue;}
      if(!this.inWindow(row.timezone,row.sendWindowStartHour,row.sendWindowEndHour)){continue;}
      const recent=(await this.prisma.$queryRaw<Array<{count:bigint}>>`SELECT COUNT(*)::bigint AS count FROM "MarketingEmailDelivery" WHERE "clientId"=${row.clientId}::uuid AND status='SENT' AND "sentAt">=CURRENT_TIMESTAMP-INTERVAL '7 days'`)[0];if(Number(recent?.count??0)>=row.maxEmailsPer7Days){await this.prisma.$executeRaw`UPDATE "MarketingEmailJourney" SET "nextDueAt"=CURRENT_TIMESTAMP+INTERVAL '24 hours',"updatedAt"=CURRENT_TIMESTAMP WHERE id=${row.id}::uuid`;skipped++;continue;}
      const schedule=this.schedule(row.scheduleHours);const step=row.lastStep+1;if(step>=schedule.length){await this.prisma.$executeRaw`UPDATE "MarketingEmailJourney" SET "completedAt"=CURRENT_TIMESTAMP,"nextDueAt"=NULL,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${row.id}::uuid`;continue;}
      try{const result=await this.send(row);await this.prisma.$transaction(async tx=>{await tx.$executeRaw`INSERT INTO "MarketingEmailDelivery" (id,"organizationId","clientId","journeyId","scenarioCode",step,subject,body,status,"providerMessageId","sentAt","failedAt",error,"createdAt") VALUES(gen_random_uuid(),${row.organizationId}::uuid,${row.clientId}::uuid,${row.id}::uuid,${row.scenarioCode},${step},${result.subject},${result.body},'SENT',${result.providerMessageId},CURRENT_TIMESTAMP,NULL,NULL,CURRENT_TIMESTAMP) ON CONFLICT ("journeyId",step) WHERE "journeyId" IS NOT NULL DO UPDATE SET subject=EXCLUDED.subject,body=EXCLUDED.body,status='SENT',"providerMessageId"=EXCLUDED."providerMessageId","sentAt"=CURRENT_TIMESTAMP,"failedAt"=NULL,error=NULL`;const nextStep=step+1;const nextDue=nextStep<schedule.length?new Date(Date.now()+Math.max(1,schedule[nextStep]-schedule[step])*3600000):null;await tx.$executeRaw`UPDATE "MarketingEmailJourney" SET "lastStep"=${step},"lastSentAt"=CURRENT_TIMESTAMP,"nextDueAt"=${nextDue},"completedAt"=${nextDue?null:new Date()},"updatedAt"=CURRENT_TIMESTAMP WHERE id=${row.id}::uuid`;await tx.$executeRaw`UPDATE "Client" SET "lastMarketingEmailAt"=CURRENT_TIMESTAMP,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${row.clientId}::uuid`;});sent++;}
      catch(error){const message=error instanceof Error?error.message:'EMAIL_SEND_FAILED';await this.prisma.$executeRaw`INSERT INTO "MarketingEmailDelivery" (id,"organizationId","clientId","journeyId","scenarioCode",step,subject,body,status,"failedAt",error,"createdAt") VALUES(gen_random_uuid(),${row.organizationId}::uuid,${row.clientId}::uuid,${row.id}::uuid,${row.scenarioCode},${step},${row.subjectTemplate},${row.bodyTemplate},'FAILED',CURRENT_TIMESTAMP,${message.slice(0,1000)},CURRENT_TIMESTAMP) ON CONFLICT ("journeyId",step) WHERE "journeyId" IS NOT NULL DO UPDATE SET status='FAILED',"failedAt"=CURRENT_TIMESTAMP,error=EXCLUDED.error`;await this.prisma.$executeRaw`UPDATE "MarketingEmailJourney" SET "nextDueAt"=CURRENT_TIMESTAMP+INTERVAL '2 hours',"updatedAt"=CURRENT_TIMESTAMP WHERE id=${row.id}::uuid`;failed++;}
    }
    return{ok:true,checked:due.length,sent,failed,skipped};
  }

  async unsubscribe(clientId:string,token:string){if(!this.tokenValid(clientId,token))throw new BadRequestException('Lien de désabonnement invalide.');const rows=await this.prisma.$queryRaw<Array<{organizationId:string}>>`UPDATE "Client" SET "marketingEmailsEnabled"=FALSE,"marketingUnsubscribedAt"=CURRENT_TIMESTAMP,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${clientId}::uuid RETURNING "organizationId"`;if(!rows[0])throw new NotFoundException('Client introuvable.');await this.prisma.$executeRaw`UPDATE "MarketingEmailJourney" SET "cancelledAt"=CURRENT_TIMESTAMP,"nextDueAt"=NULL,"updatedAt"=CURRENT_TIMESTAMP WHERE "clientId"=${clientId}::uuid AND "completedAt" IS NULL AND "cancelledAt" IS NULL`;return{unsubscribed:true,message:'Vous êtes désabonné des e-mails marketing KHE BOOTH. Les e-mails transactionnels et de sécurité restent inchangés.'};}

  async clientHistory(organizationId:string,clientId:string){const client=(await this.prisma.$queryRaw<Array<{id:string;name:string;email:string|null;marketingEmailsEnabled:boolean;marketingConsentAt:Date|null;marketingConsentSource:string|null;marketingUnsubscribedAt:Date|null;lastMarketingEmailAt:Date|null}>>`SELECT id,name,email,"marketingEmailsEnabled","marketingConsentAt","marketingConsentSource","marketingUnsubscribedAt","lastMarketingEmailAt" FROM "Client" WHERE id=${clientId}::uuid AND "organizationId"=${organizationId}::uuid LIMIT 1`)[0];if(!client)throw new NotFoundException('Client introuvable.');const deliveries=await this.prisma.$queryRaw<Array<{id:string;scenarioCode:string;step:number;subject:string;status:string;providerMessageId:string|null;sentAt:Date|null;failedAt:Date|null;error:string|null;createdAt:Date}>>`SELECT id,"scenarioCode",step,subject,status,"providerMessageId","sentAt","failedAt",error,"createdAt" FROM "MarketingEmailDelivery" WHERE "organizationId"=${organizationId}::uuid AND "clientId"=${clientId}::uuid ORDER BY "createdAt" DESC LIMIT 100`;return{client,deliveries};}

  async summary(organizationId:string){await this.ensureSettings(organizationId);const clients=(await this.prisma.$queryRaw<Array<{total:bigint;consented:bigint;unsubscribed:bigint}>>`SELECT COUNT(*)::bigint AS total,COUNT(*) FILTER(WHERE "marketingEmailsEnabled"=TRUE AND "marketingConsentAt" IS NOT NULL AND "marketingUnsubscribedAt" IS NULL)::bigint AS consented,COUNT(*) FILTER(WHERE "marketingUnsubscribedAt" IS NOT NULL)::bigint AS unsubscribed FROM "Client" WHERE "organizationId"=${organizationId}::uuid AND "archivedAt" IS NULL`)[0];const deliveries=(await this.prisma.$queryRaw<Array<{sent:bigint;failed:bigint;queued:bigint}>>`SELECT COUNT(*) FILTER(WHERE status='SENT')::bigint AS sent,COUNT(*) FILTER(WHERE status='FAILED')::bigint AS failed,COUNT(*) FILTER(WHERE status='QUEUED')::bigint AS queued FROM "MarketingEmailDelivery" WHERE "organizationId"=${organizationId}::uuid AND "createdAt">=CURRENT_TIMESTAMP-INTERVAL '30 days'`)[0];const activeJourneys=(await this.prisma.$queryRaw<Array<{count:bigint}>>`SELECT COUNT(*)::bigint AS count FROM "MarketingEmailJourney" WHERE "organizationId"=${organizationId}::uuid AND "completedAt" IS NULL AND "cancelledAt" IS NULL`)[0];return{clients:{total:Number(clients?.total??0),consented:Number(clients?.consented??0),unsubscribed:Number(clients?.unsubscribed??0)},deliveries30Days:{sent:Number(deliveries?.sent??0),failed:Number(deliveries?.failed??0),queued:Number(deliveries?.queued??0)},activeJourneys:Number(activeJourneys?.count??0)};}
}
