import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import QRCode from 'react-native-qrcode-svg';
import type { StationExperienceApi } from '../api/station-api';
import { createEventShare, type EventShareContract } from './event-share-client';

export function EventGuestQrPanel({api,stationToken,eventName}:{api:StationExperienceApi;stationToken:string;eventName:string}){
  const[share,setShare]=useState<EventShareContract|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
  async function load(){setLoading(true);setError('');try{setShare(await createEventShare(api,stationToken));}catch(cause){setShare(null);setError(cause instanceof Error?cause.message:'QR événement indisponible.');}finally{setLoading(false);}}
  useEffect(()=>{void load();},[api,stationToken,eventName]);
  return <View style={styles.card}><View style={styles.copy}><Text style={styles.eyebrow}>QR INVITÉ PERMANENT</Text><Text style={styles.title}>Galerie de l’événement</Text><Text style={styles.help}>Laissez ce QR affiché pendant la prestation. Les invités retrouvent tous les Moments synchronisés de « {eventName} » avec le même lien, même lorsque de nouvelles photos et vidéos arrivent.</Text><View style={styles.secure}><Text style={styles.secureText}>✓ lien opaque • révocable • médias privés • galerie actualisée</Text></View>{error?<Text style={styles.error}>{error}</Text>:null}<Pressable disabled={loading} style={styles.refresh} onPress={()=>void load()}><Text style={styles.refreshText}>↻ VÉRIFIER LE QR</Text></Pressable></View><View style={styles.qrShell}>{loading?<ActivityIndicator color="#d2ad4f"/>:share?<QRCode value={share.shareUrl} size={196} backgroundColor="#ffffff" color="#111111"/>:<Text style={styles.qrError}>QR indisponible</Text>}</View></View>;
}
const styles=StyleSheet.create({card:{backgroundColor:'#fff',borderRadius:20,padding:16,borderWidth:1,borderColor:'#dec675',flexDirection:'row',gap:16,alignItems:'center',flexWrap:'wrap'},copy:{flex:1,minWidth:230,gap:6},eyebrow:{color:'#b31520',fontSize:10,fontWeight:'900',letterSpacing:1.6},title:{fontSize:22,fontWeight:'900',color:'#111'},help:{fontSize:12,lineHeight:18,color:'#635b51'},secure:{alignSelf:'flex-start',backgroundColor:'#e8f6ed',borderRadius:999,paddingHorizontal:10,paddingVertical:6},secureText:{color:'#185a32',fontSize:9,fontWeight:'900'},qrShell:{width:220,height:220,borderRadius:18,backgroundColor:'#fff',borderWidth:1,borderColor:'#ddd',alignItems:'center',justifyContent:'center',padding:12},qrError:{color:'#7a2028',fontWeight:'900'},refresh:{alignSelf:'flex-start',marginTop:4,borderWidth:1,borderColor:'#111',borderRadius:10,paddingHorizontal:11,paddingVertical:8},refreshText:{fontSize:9,fontWeight:'900',color:'#111'},error:{color:'#9c2530',fontSize:11,fontWeight:'800'}});
