import type { CaptureDurationSeconds, RemoteCaptureCommand, StationControlContract, VisualEffect } from '@khe/contracts';
import { CAPTURE_DURATIONS, VISUAL_EFFECTS } from '@khe/contracts';
import { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import type { StationExperienceApi } from '../api/station-api';
import { SharingLivePreview } from '../live/live-preview';
import { DEFAULT_STATION_CONTROL_PREFERENCES, updateStationControlPreferencesFromSharing, type CaptureAspectRatio, type CaptureCountdownSeconds, type CaptureKind, type StationControlPreferences } from '../station/control-preferences-client';
import { hasPendingCommand, preferencesFromControl, REMOTE_CONTROL_RETRY_MS, SHARING_STATUS_POLL_MS } from '../station/remote-control-performance';

interface Props{eventName:string;api:StationExperienceApi;stationToken:string;}
const GOLD='#d7b24c',RED='#b31520';
const effectLabels:Record<VisualEffect,string>={NONE:'Normal',WARM:'Chaud',COOL:'Froid',GOLD:'Doré',PARTY:'Party'};
function formatDuration(total:number){const m=Math.floor(total/60).toString().padStart(2,'0');const s=(total%60).toString().padStart(2,'0');return`${m}:${s}`;}

export function RemoteControlPanel({eventName,api,stationToken}:Props){
  const[control,setControl]=useState<StationControlContract|null>(null);const[prefs,setPrefs]=useState<StationControlPreferences|null>(null);const[displaySeconds,setDisplaySeconds]=useState(0);const[lastRefreshAt,setLastRefreshAt]=useState(0);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const lastServerSeconds=useRef(0);const prefsRef=useRef<StationControlPreferences>(DEFAULT_STATION_CONTROL_PREFERENCES);
  useEffect(()=>{let cancelled=false;let timer:ReturnType<typeof setTimeout>|null=null;const refresh=async()=>{let delay=SHARING_STATUS_POLL_MS;try{const c=await api.control(stationToken);const p=preferencesFromControl(c,prefsRef.current);if(cancelled)return;prefsRef.current=p;setControl(c);setPrefs(p);lastServerSeconds.current=c.elapsedSeconds;setDisplaySeconds(c.elapsedSeconds);setLastRefreshAt(Date.now());setMessage(current=>/Internal server error|Régie distante indisponible/i.test(current)?'':current);}catch(error){delay=REMOTE_CONTROL_RETRY_MS;if(!cancelled)setMessage(error instanceof Error?error.message:'Régie distante indisponible.');}finally{if(!cancelled)timer=setTimeout(()=>void refresh(),delay);}};void refresh();return()=>{cancelled=true;if(timer)clearTimeout(timer);};},[api,stationToken]);
  useEffect(()=>{if(control?.runtimeState!=='RECORDING'){setDisplaySeconds(control?.elapsedSeconds??0);return;}const timer=setInterval(()=>setDisplaySeconds(current=>Math.min(control.maxDurationSeconds,Math.max(current+1,lastServerSeconds.current))),1000);return()=>clearInterval(timer);},[control?.runtimeState,control?.elapsedSeconds,control?.maxDurationSeconds]);

  const status=control?.sharingConnectionStatus??'DISCONNECTED';const captureOnline=Boolean(control?.captureSeenAt&&Date.now()-new Date(control.captureSeenAt).getTime()<5000);const connected=status==='ACCEPTED'&&captureOnline;const pending=Boolean(control&&hasPendingCommand(control));const active=Boolean(control&&(pending||['COUNTDOWN','RECORDING','PAUSED','SAVING'].includes(control.runtimeState)));const paused=control?.runtimeState==='PAUSED';
  async function requestConnection(){setBusy(true);setMessage('Demande de connexion envoyée…');try{setControl(await api.requestControlConnection(stationToken));setMessage('Validez la demande sur CAPTURE.');}catch(error){setMessage(error instanceof Error?error.message:'Connexion impossible.');}finally{setBusy(false);}}
  async function disconnect(){setBusy(true);try{setControl(await api.disconnectControlConnection(stationToken));setMessage('SHARING est déconnectée de CAPTURE.');}catch(error){setMessage(error instanceof Error?error.message:'Déconnexion impossible.');}finally{setBusy(false);}}
  async function command(name:Exclude<RemoteCaptureCommand,'NONE'>){if(!connected)return;setBusy(true);try{setControl(await api.updateControlCommand(stationToken,{command:name}));setMessage(name==='START'?(prefs?.captureKind==='PHOTO'?'Commande PHOTO envoyée.':'Enregistrement demandé à CAPTURE.'):`Commande ${name} envoyée.`);}catch(error){setMessage(error instanceof Error?error.message:'Commande impossible.');}finally{setBusy(false);}}
  async function preference(patch:Partial<Pick<StationControlPreferences,'captureKind'|'aspectRatio'|'countdownSeconds'>>){if(!connected)return;setBusy(true);try{setPrefs(await updateStationControlPreferencesFromSharing(api,stationToken,patch));setMessage('Réglage CAPTURE synchronisé.');}catch(error){setMessage(error instanceof Error?error.message:'Réglage impossible.');}finally{setBusy(false);}}
  async function selectDuration(seconds:CaptureDurationSeconds){if(!connected)return;setBusy(true);try{setControl(await api.updateControlCommand(stationToken,{maxDurationSeconds:seconds}));setMessage(`Durée réglée à ${seconds} s.`);}catch(error){setMessage(error instanceof Error?error.message:'Durée impossible à modifier.');}finally{setBusy(false);}}
  async function selectEffect(effect:VisualEffect){if(!connected)return;setBusy(true);try{setControl(await api.updateControlCommand(stationToken,{selectedEffect:effect}));setMessage(`Effet ${effectLabels[effect]} synchronisé.`);}catch(error){setMessage(error instanceof Error?error.message:'Effet impossible à modifier.');}finally{setBusy(false);}}

  if(!control||!prefs)return <View style={styles.loading}><ActivityIndicator color={GOLD}/><Text style={styles.light}>Initialisation de la régie SHARING…</Text></View>;
  return <View style={styles.container}>
    <View style={styles.header}><View style={{flex:1}}><Text style={styles.eyebrow}>RÉGIE SHARING</Text><Text style={styles.title}>{eventName}</Text></View><View style={[styles.badge,connected&&styles.badgeOk]}><Text style={styles.badgeText}>{connected?'● CONNECTÉ':status==='PENDING'?'◌ EN ATTENTE':'○ DÉCONNECTÉ'}</Text></View></View>
    {!connected?<View style={styles.connectionCard}><Text style={styles.connectionTitle}>{status==='PENDING'?'Autorisation CAPTURE en attente':'Connecter la régie à CAPTURE'}</Text><Text style={styles.help}>{status==='PENDING'?'Acceptez la fenêtre sur la tablette CAPTURE.':'La tablette CAPTURE garde le dernier mot avant toute commande distante.'}</Text><View style={styles.row}><Pressable disabled={busy} style={styles.primary} onPress={()=>void requestConnection()}><Text style={styles.primaryText}>{status==='PENDING'?'RENVOYER':'CONNECTER'}</Text></Pressable>{status==='PENDING'?<Pressable disabled={busy} style={styles.secondary} onPress={()=>void disconnect()}><Text style={styles.secondaryText}>Annuler</Text></Pressable>:null}</View></View>:<View style={styles.connectedCard}><Text style={styles.ok}>✓ CAPTURE CONNECTÉE</Text><Text style={styles.help}>Dernier échange : {Math.max(0,Math.round((Date.now()-lastRefreshAt)/1000))} s</Text><Pressable disabled={busy} style={styles.smallDanger} onPress={()=>void disconnect()}><Text style={styles.smallDangerText}>Déconnecter</Text></Pressable></View>}

    <Text style={styles.section}>FLUX CAMÉRA PROPRE · SANS COMMANDES CAPTURE</Text>{connected?<SharingLivePreview api={api} stationToken={stationToken}/>:<View style={styles.preview}><Text style={styles.light}>Le flux caméra propre démarre après l’autorisation CAPTURE.</Text></View>}

    <View style={styles.statusCard}><Text style={styles.statusLabel}>ÉTAT CAPTURE</Text><Text style={styles.statusValue}>{control.runtimeState}</Text><Text style={styles.timer}>{formatDuration(displaySeconds)} / {formatDuration(control.maxDurationSeconds)}</Text><Text style={styles.help}>Mode {prefs.captureKind} • {prefs.aspectRatio} • décompte {prefs.countdownSeconds}s • commande #{control.commandVersion} / acquittée #{control.acknowledgedVersion}</Text></View>

    <Text style={styles.section}>MODE DE CAPTURE</Text><View style={styles.wrap}>{(['PHOTO','VIDEO'] as CaptureKind[]).map(value=><Chip key={value} label={value==='PHOTO'?'📷 PHOTO':'🎥 VIDÉO'} active={prefs.captureKind===value} disabled={!connected||busy||active} onPress={()=>void preference({captureKind:value})}/>)}</View>
    <Text style={styles.section}>FORMAT</Text><View style={styles.wrap}>{(['9:16','1:1'] as CaptureAspectRatio[]).map(value=><Chip key={value} label={value} active={prefs.aspectRatio===value} disabled={!connected||busy||active} onPress={()=>void preference({aspectRatio:value})}/>)}</View>
    <Text style={styles.section}>DÉCOMPTE</Text><View style={styles.wrap}>{([0,3,5,10] as CaptureCountdownSeconds[]).map(value=><Chip key={value} label={value===0?'Sans délai':`${value}s`} active={prefs.countdownSeconds===value} disabled={!connected||busy||active} onPress={()=>void preference({countdownSeconds:value})}/>)}</View>

    {prefs.captureKind==='VIDEO'?<><Text style={styles.section}>DURÉE MAXIMUM</Text><View style={styles.wrap}>{CAPTURE_DURATIONS.map(value=><Chip key={value} label={`${value}s`} active={control.maxDurationSeconds===value} disabled={!connected||busy||active} onPress={()=>void selectDuration(value)}/>)}</View></>:null}
    <Text style={styles.section}>EFFET VISUEL</Text><View style={styles.wrap}>{VISUAL_EFFECTS.map(value=><Chip key={value} label={effectLabels[value]} active={control.selectedEffect===value} disabled={!connected||busy||active} onPress={()=>void selectEffect(value)}/>)}</View>

    <View style={styles.commandRow}><Pressable disabled={!connected||busy||active} style={[styles.captureButton,(!connected||busy||active)&&styles.disabled]} onPress={()=>void command('START')}><Text style={styles.captureText}>{prefs.captureKind==='PHOTO'?'📷 PRENDRE LA PHOTO':'● DÉMARRER REC'}</Text></Pressable>{prefs.captureKind==='VIDEO'?<><Pressable disabled={!connected||busy||pending||(!paused&&control.runtimeState!=='RECORDING')} style={[styles.commandButton,(!connected||busy||pending||(!paused&&control.runtimeState!=='RECORDING'))&&styles.disabled]} onPress={()=>void command(paused?'RESUME':'PAUSE')}><Text style={styles.commandText}>{paused?'▶ REPRENDRE':'Ⅱ PAUSE'}</Text></Pressable><Pressable disabled={!connected||busy||pending||!active} style={[styles.stopButton,(!connected||busy||pending||!active)&&styles.disabled]} onPress={()=>void command('STOP')}><Text style={styles.commandText}>■ STOP</Text></Pressable></>:null}</View>
    {message?<Text style={styles.message}>{message}</Text>:null}
  </View>;
}

function Chip({label,active,disabled,onPress}:{label:string;active:boolean;disabled:boolean;onPress:()=>void}){return <Pressable disabled={disabled} style={[styles.chip,active&&styles.chipActive,disabled&&styles.disabled]} onPress={onPress}><Text style={[styles.chipText,active&&styles.chipTextActive]}>{label}</Text></Pressable>;}
const styles=StyleSheet.create({container:{backgroundColor:'#0d0d0f',borderRadius:22,padding:16,gap:12,borderWidth:1,borderColor:'#342b18'},loading:{backgroundColor:'#111',borderRadius:18,padding:18,alignItems:'center',gap:8},light:{color:'#ddd'},header:{flexDirection:'row',alignItems:'center',gap:10},eyebrow:{color:GOLD,fontSize:10,fontWeight:'900',letterSpacing:1.7},title:{color:'#fff',fontSize:24,fontWeight:'900',marginTop:3},badge:{backgroundColor:'#333',borderRadius:999,paddingHorizontal:10,paddingVertical:7},badgeOk:{backgroundColor:'#183b27'},badgeText:{color:'#fff',fontSize:9,fontWeight:'900'},connectionCard:{backgroundColor:'#18181d',borderRadius:16,padding:14,gap:9},connectionTitle:{color:'#fff',fontSize:17,fontWeight:'900'},help:{color:'#aaa',fontSize:11,lineHeight:17},row:{flexDirection:'row',gap:8},primary:{backgroundColor:RED,borderRadius:11,padding:12,alignItems:'center',flex:1},primaryText:{color:'#fff',fontWeight:'900'},secondary:{borderWidth:1,borderColor:'#666',borderRadius:11,padding:12,alignItems:'center'},secondaryText:{color:'#fff',fontWeight:'900'},connectedCard:{backgroundColor:'#14291d',borderRadius:16,padding:14,gap:5},ok:{color:'#aeeac1',fontWeight:'900'},smallDanger:{alignSelf:'flex-start',marginTop:5,borderWidth:1,borderColor:'#90545a',borderRadius:9,paddingHorizontal:10,paddingVertical:7},smallDangerText:{color:'#ffd4d8',fontSize:10,fontWeight:'900'},section:{color:GOLD,fontSize:10,fontWeight:'900',letterSpacing:1.3,marginTop:4},preview:{minHeight:150,borderRadius:16,backgroundColor:'#151515',alignItems:'center',justifyContent:'center',padding:16},statusCard:{backgroundColor:'#17171b',borderRadius:16,padding:14,gap:5},statusLabel:{color:'#aaa',fontSize:9,fontWeight:'900'},statusValue:{color:'#fff',fontSize:22,fontWeight:'900'},timer:{color:GOLD,fontSize:28,fontWeight:'900'},wrap:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{borderWidth:1,borderColor:'#555',borderRadius:999,paddingHorizontal:12,paddingVertical:9},chipActive:{backgroundColor:GOLD,borderColor:GOLD},chipText:{color:'#ddd',fontSize:10,fontWeight:'900'},chipTextActive:{color:'#111'},disabled:{opacity:.4},commandRow:{gap:8,marginTop:4},captureButton:{backgroundColor:RED,borderRadius:14,padding:15,alignItems:'center'},captureText:{color:'#fff',fontSize:14,fontWeight:'900'},commandButton:{backgroundColor:'#313136',borderRadius:12,padding:13,alignItems:'center'},stopButton:{backgroundColor:'#6f1520',borderRadius:12,padding:13,alignItems:'center'},commandText:{color:'#fff',fontWeight:'900'},message:{color:'#f0d997',fontSize:11,lineHeight:17,fontWeight:'700'}});
