import * as SecureStore from 'expo-secure-store';
import { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import type { StationExperienceApi } from '../api/station-api';
import type { LocalStore } from '../offline/local-store';
import { StationLinkHealth } from '../station/station-link-health';
import { CreativeStudio, type CreativePlan } from '../studio/creative-studio';
import { EventGuestQrPanel } from './event-guest-qr-panel';
import { RemoteControlPanel } from './remote-control-panel';
import { SharingBillingCenter } from './sharing-billing-center';
import { SharingEventManager } from './sharing-event-manager';
import { SharingMediaGallery } from './sharing-media-gallery';
import { SharingTrashPanel } from './sharing-trash-panel';
import { SlideToConnect } from './slide-to-connect';

const CREATIVE_PLAN_KEY='khe.creative.plan.v1';
interface Props{eventName:string;api:StationExperienceApi;stationToken:string;store:LocalStore;}
export function SharingStationPanel({eventName,api,stationToken,store}:Props){
  const[ready,setReady]=useState(false);const[checking,setChecking]=useState(true);const[error,setError]=useState('');const[optionalWarning,setOptionalWarning]=useState('');const[flowMessage,setFlowMessage]=useState('');const[designEvent,setDesignEvent]=useState<{id:string;name:string}|null>(null);const[activeEventId,setActiveEventId]=useState<string|null>(null);const[activeEventName,setActiveEventName]=useState(eventName);const[healthOpen,setHealthOpen]=useState(false);const designSavedRef=useRef(false);const checkingRef=useRef(false);
  async function initialize(){if(checkingRef.current)return;checkingRef.current=true;setChecking(true);setError('');setOptionalWarning('');try{const manifest=await api.manifest(stationToken);await store.init();setActiveEventId(manifest.event.id);setActiveEventName(manifest.event.name);setReady(true);const optional=await Promise.allSettled([api.control(stationToken),api.listMedia(stationToken),api.clientWorkspace(stationToken)]);const rejected=optional.filter(result=>result.status==='rejected') as PromiseRejectedResult[];if(rejected.length)setOptionalWarning('La régie de base est disponible. Certains services secondaires se reconnectent en arrière-plan.');}catch(cause){setReady(false);setError(cause instanceof Error?cause.message:'Impossible de valider la session SHARING.');}finally{checkingRef.current=false;setChecking(false);}}
  useEffect(()=>{void initialize();},[api,stationToken,store]);useEffect(()=>{setActiveEventName(eventName);},[eventName]);
  async function startDesign(eventId:string,eventTitle:string){setFlowMessage(`Événement « ${eventTitle} » créé. Préparez maintenant son design.`);await SecureStore.deleteItemAsync(CREATIVE_PLAN_KEY).catch(()=>undefined);designSavedRef.current=false;setDesignEvent({id:eventId,name:eventTitle});}
  async function publishDesign(plan:CreativePlan){const pending=designEvent;if(!pending)return;const workspace=await api.markClientEventDesignReady(stationToken,pending.id,plan as unknown as Record<string,unknown>);designSavedRef.current=true;setFlowMessage(`✓ Design « ${pending.name} » enregistré. Les stations vont basculer automatiquement.`);return workspace;}
  async function closeDesign(){const pending=designEvent;if(!pending)return;if(designSavedRef.current){setDesignEvent(null);return;}const raw=await SecureStore.getItemAsync(CREATIVE_PLAN_KEY);if(!raw){setDesignEvent(null);setFlowMessage(`« ${pending.name} » reste en brouillon.`);return;}try{const plan=JSON.parse(raw) as CreativePlan;await publishDesign({...plan,background:plan.background?{...plan.background,localUri:null}:null});}catch(cause){setFlowMessage(cause instanceof Error?cause.message:'Impossible de valider le design.');}finally{setDesignEvent(null);}}
  if(designEvent)return <CreativeStudio api={api} stationToken={stationToken} eventId={designEvent.id} onSaved={publishDesign} onClose={()=>void closeDesign()}/>;
  if(healthOpen&&activeEventId)return <StationLinkHealth mode="SHARING" eventId={activeEventId} eventName={activeEventName} api={api} stationToken={stationToken} store={store} onClose={()=>setHealthOpen(false)}/>;
  if(!ready)return <View style={styles.statusCard}><Text style={styles.eyebrow}>RÉGIE SHARING</Text><Text style={styles.title}>{checking?'Connexion à KHE Booth…':'Session SHARING indisponible'}</Text>{checking?<ActivityIndicator color="#d2ad4f"/>:null}<Text style={styles.help}>{checking?'Vérification de la session événement…':error}</Text>{!checking?<Pressable style={styles.retry} onPress={()=>void initialize()}><Text style={styles.retryText}>RÉESSAYER</Text></Pressable>:null}</View>;
  return <View style={styles.readyShell}><SlideToConnect api={api} stationToken={stationToken}/>{optionalWarning?<View style={styles.warning}><Text style={styles.warningText}>{optionalWarning}</Text></View>:null}<Pressable style={styles.healthButton} onPress={()=>setHealthOpen(true)}><View><Text style={styles.healthEyebrow}>KHE LINK HEALTH</Text><Text style={styles.healthTitle}>⇄ Vérifier CAPTURE ↔ SHARING</Text></View><Text style={styles.healthArrow}>›</Text></Pressable>{flowMessage?<View style={styles.flowBanner}><Text style={styles.flowText}>{flowMessage}</Text></View>:null}<SharingEventManager api={api} stationToken={stationToken} onCreated={(id,name)=>void startDesign(id,name)} onReady={name=>setFlowMessage(`✓ « ${name} » est prêt. Bascule automatique en cours.`)} onSelected={(_id,name)=>setFlowMessage(`✓ « ${name} » sélectionné. Attente de la confirmation de bascule des deux tablettes.`)}/><EventGuestQrPanel api={api} stationToken={stationToken} eventName={activeEventName}/><RemoteControlPanel eventName={activeEventName} api={api} stationToken={stationToken}/><SharingBillingCenter api={api} stationToken={stationToken}/><SharingTrashPanel api={api} stationToken={stationToken}/>{activeEventId?<SharingMediaGallery eventId={activeEventId} eventName={activeEventName} api={api} stationToken={stationToken} store={store}/>:null}</View>;
}
const styles=StyleSheet.create({readyShell:{gap:14},healthButton:{backgroundColor:'#111113',borderWidth:1,borderColor:'#d2ad4f',borderRadius:16,padding:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},healthEyebrow:{color:'#d2ad4f',fontSize:9,fontWeight:'900',letterSpacing:1.5},healthTitle:{color:'#fff',fontSize:15,fontWeight:'900',marginTop:3},healthArrow:{color:'#d2ad4f',fontSize:28},warning:{backgroundColor:'#fff3d6',borderRadius:13,padding:11,borderWidth:1,borderColor:'#d4b666'},warningText:{color:'#66511d',fontSize:11,lineHeight:17,fontWeight:'700'},flowBanner:{backgroundColor:'#e8f6ed',borderWidth:1,borderColor:'#9bc8aa',borderRadius:14,padding:12},flowText:{color:'#185a32',fontSize:12,lineHeight:18,fontWeight:'800'},statusCard:{marginTop:16,backgroundColor:'#111113',borderRadius:22,padding:22,gap:14},eyebrow:{color:'#d2ad4f',fontSize:11,letterSpacing:2,fontWeight:'900'},title:{color:'#fff',fontSize:24,fontWeight:'900'},help:{color:'#c4bfba',lineHeight:20},retry:{backgroundColor:'#b31520',borderRadius:14,padding:14,alignItems:'center'},retryText:{color:'#fff',fontWeight:'900'}});
