import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import type { ClientWorkspaceContract, StationExperienceApi } from '../api/station-api';

function parseLocalDateTime(value:string):string|null{
  const normalized=value.trim().replace('T',' ');const match=normalized.match(/^(\d{4})-(\d{2})-(\d{2})\s+(\d{2}):(\d{2})$/);if(!match)return null;
  const date=new Date(Number(match[1]),Number(match[2])-1,Number(match[3]),Number(match[4]),Number(match[5]),0,0);return Number.isNaN(date.getTime())?null:date.toISOString();
}
function localExample(offsetHours:number){const d=new Date(Date.now()+offsetHours*60*60*1000);const pad=(n:number)=>String(n).padStart(2,'0');return`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;}

export function SharingEventManager({api,stationToken,onCreated}:{api:StationExperienceApi;stationToken:string;onCreated:(eventId:string,eventName:string)=>void}){
  const[open,setOpen]=useState(false);const[name,setName]=useState('');const[description,setDescription]=useState('');const[startsAt,setStartsAt]=useState('');const[endsAt,setEndsAt]=useState('');const[workspace,setWorkspace]=useState<ClientWorkspaceContract|null>(null);const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);
  const refresh=()=>api.clientWorkspace(stationToken).then(setWorkspace).catch(()=>undefined);
  useEffect(()=>{void refresh();},[api,stationToken]);
  async function create(){
    const startIso=parseLocalDateTime(startsAt);const endIso=parseLocalDateTime(endsAt);setMessage('');
    if(!name.trim()||!description.trim()||!startsAt.trim()||!endsAt.trim()){setMessage('Nom, description, début et fin sont obligatoires.');return;}
    if(!startIso||!endIso){setMessage('Utilisez le format AAAA-MM-JJ HH:MM pour le début et la fin.');return;}
    if(new Date(endIso)<=new Date(startIso)){setMessage('La fin doit être après le début.');return;}
    setBusy(true);
    try{const result=await api.createClientEvent(stationToken,{name:name.trim(),description:description.trim(),startsAt:startIso,endsAt:endIso});setMessage(`✓ « ${result.event.name} » créé. Ouverture automatique du Studio créatif…`);setName('');setDescription('');setStartsAt('');setEndsAt('');setOpen(false);await refresh();onCreated(result.event.id,result.event.name);}catch(error){setMessage(error instanceof Error?error.message:'Impossible de créer l’événement.');}finally{setBusy(false);}
  }
  return <View style={styles.shell}><View style={styles.header}><View style={{flex:1}}><Text style={styles.eyebrow}>RÉGIE CLIENT • ÉVÉNEMENTS</Text><Text style={styles.title}>Mes événements</Text><Text style={styles.help}>Créez ici vos événements sans accéder au portail KHE Booth. Ils apparaissent automatiquement dans l’administration KHE.</Text></View><View style={styles.plan}><Text style={styles.planText}>{workspace?.plan||'…'}</Text></View></View>
    {!open?<Pressable style={styles.createButton} onPress={()=>{setOpen(true);if(!startsAt)setStartsAt(localExample(1));if(!endsAt)setEndsAt(localExample(5));}}><Text style={styles.createText}>＋ CRÉER UN ÉVÉNEMENT</Text></Pressable>:<View style={styles.form}><Text style={styles.required}>Tous les champs marqués * sont obligatoires.</Text><Text style={styles.label}>Nom *</Text><TextInput style={styles.input} value={name} onChangeText={setName} maxLength={180} placeholder="Mariage Sandrine & Heinz"/><Text style={styles.label}>Description *</Text><TextInput style={[styles.input,styles.multiline]} value={description} onChangeText={setDescription} multiline maxLength={4000} placeholder="Décrivez l’événement, l’ambiance et les besoins…"/><View style={styles.two}><View style={{flex:1}}><Text style={styles.label}>Début *</Text><TextInput style={styles.input} value={startsAt} onChangeText={setStartsAt} autoCapitalize="none" placeholder="2026-08-22 18:00"/></View><View style={{flex:1}}><Text style={styles.label}>Fin *</Text><TextInput style={styles.input} value={endsAt} onChangeText={setEndsAt} autoCapitalize="none" placeholder="2026-08-23 02:00"/></View></View><Text style={styles.format}>Format local : AAAA-MM-JJ HH:MM</Text><View style={styles.actions}><Pressable style={styles.cancel} onPress={()=>setOpen(false)}><Text style={styles.cancelText}>Annuler</Text></Pressable><Pressable disabled={busy} style={[styles.submit,busy&&styles.disabled]} onPress={()=>void create()}><Text style={styles.submitText}>{busy?'Création…':'Créer → Studio créatif'}</Text></Pressable></View></View>}
    {message?<Text style={styles.message}>{message}</Text>:null}
    {workspace?.events?.length?<View style={styles.list}><Text style={styles.listTitle}>ÉVÉNEMENTS DU CLIENT</Text>{workspace.events.slice(0,5).map((event)=><View key={event.id} style={styles.eventRow}><View style={{flex:1}}><Text style={styles.eventName}>{event.name}</Text><Text style={styles.eventDates}>{new Date(event.startsAt).toLocaleString()} → {event.endsAt?new Date(event.endsAt).toLocaleString():'—'}</Text></View><Text style={[styles.status,event.status==='COMPLETED'&&styles.completed]}>{event.status}</Text></View>)}</View>:null}
  </View>;
}

const KHE_RED='#b31520';const KHE_GOLD='#d2ad4f';
const styles=StyleSheet.create({shell:{backgroundColor:'#fff8e8',borderRadius:20,borderWidth:1,borderColor:'#ead397',padding:16,gap:13},header:{flexDirection:'row',gap:10,alignItems:'flex-start'},eyebrow:{color:KHE_RED,fontSize:10,letterSpacing:1.6,fontWeight:'900'},title:{fontSize:22,fontWeight:'900',color:'#111',marginTop:3},help:{color:'#6f6458',lineHeight:18,fontSize:12,marginTop:4},plan:{backgroundColor:'#111',borderRadius:999,paddingHorizontal:10,paddingVertical:6},planText:{color:KHE_GOLD,fontSize:10,fontWeight:'900'},createButton:{backgroundColor:KHE_RED,borderRadius:14,padding:14,alignItems:'center'},createText:{color:'#fff',fontWeight:'900',letterSpacing:.4},form:{gap:8,backgroundColor:'#fff',borderRadius:16,padding:14},required:{fontSize:11,color:'#7b342f',fontWeight:'800'},label:{fontSize:10,fontWeight:'900',letterSpacing:.6,color:'#4a4038'},input:{borderWidth:1,borderColor:'#ddd1c1',borderRadius:12,paddingHorizontal:12,paddingVertical:11,color:'#111',backgroundColor:'#fff'},multiline:{minHeight:90,textAlignVertical:'top'},two:{flexDirection:'row',gap:9},format:{fontSize:10,color:'#796e62'},actions:{flexDirection:'row',gap:9,marginTop:4},cancel:{flex:1,borderWidth:1,borderColor:'#bbb',borderRadius:12,padding:12,alignItems:'center'},cancelText:{fontWeight:'900'},submit:{flex:2,backgroundColor:'#111',borderRadius:12,padding:12,alignItems:'center'},submitText:{color:'#fff',fontWeight:'900'},disabled:{opacity:.5},message:{fontSize:12,lineHeight:18,color:'#4b4036'},list:{gap:7,borderTopWidth:1,borderTopColor:'#e7d7ba',paddingTop:10},listTitle:{fontSize:9,letterSpacing:1.4,fontWeight:'900',color:'#74664f'},eventRow:{flexDirection:'row',gap:9,alignItems:'center',paddingVertical:7},eventName:{fontWeight:'900',color:'#111'},eventDates:{fontSize:10,color:'#7b7064',marginTop:2},status:{fontSize:9,fontWeight:'900',color:KHE_RED},completed:{color:'#666'}});
