import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import type { ClientEventContract, ClientWorkspaceContract, StationExperienceApi } from '../api/station-api';
import { selectClientEvent } from '../station/client-event-selection-client';

function parseLocalDateTime(value:string):string|null{const normalized=value.trim().replace('T',' ');const match=normalized.match(/^(\d{4})-(\d{2})-(\d{2})\s+(\d{2}):(\d{2})$/);if(!match)return null;const date=new Date(Number(match[1]),Number(match[2])-1,Number(match[3]),Number(match[4]),Number(match[5]),0,0);return Number.isNaN(date.getTime())?null:date.toISOString();}
function localExample(offsetHours:number){const d=new Date(Date.now()+offsetHours*3600000);const pad=(n:number)=>String(n).padStart(2,'0');return`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;}

interface Props{api:StationExperienceApi;stationToken:string;onCreated:(eventId:string,eventName:string)=>void;onReady?:(eventName:string)=>void;onSelected?:(eventId:string,eventName:string)=>void;}

export function SharingEventManager({api,stationToken,onCreated,onReady,onSelected}:Props){
  const[open,setOpen]=useState(false);const[name,setName]=useState('');const[description,setDescription]=useState('');const[startsAt,setStartsAt]=useState('');const[endsAt,setEndsAt]=useState('');const[workspace,setWorkspace]=useState<ClientWorkspaceContract|null>(null);const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);const[selectingId,setSelectingId]=useState<string|null>(null);
  async function refresh(){try{setWorkspace(await api.clientWorkspace(stationToken));}catch{}}
  useEffect(()=>{void refresh();},[api,stationToken]);

  async function create(){const startIso=parseLocalDateTime(startsAt);const endIso=parseLocalDateTime(endsAt);setMessage('');if(!name.trim()||!description.trim()||!startsAt.trim()||!endsAt.trim()){setMessage('Nom, description, début et fin sont obligatoires.');return;}if(!startIso||!endIso){setMessage('Utilisez le format AAAA-MM-JJ HH:MM.');return;}if(new Date(endIso)<=new Date(startIso)){setMessage('La fin doit être après le début.');return;}setBusy(true);try{const result=await api.createClientEvent(stationToken,{name:name.trim(),description:description.trim(),startsAt:startIso,endsAt:endIso});setName('');setDescription('');setStartsAt('');setEndsAt('');setOpen(false);await refresh();if(result.nextStep==='STUDIO'){setMessage(`✓ « ${result.event.name} » créé. Préparez son design.`);onCreated(result.event.id,result.event.name);}else{setMessage(`✓ « ${result.event.name} » créé et prêt. Les stations vont basculer automatiquement.`);onReady?.(result.event.name);}}catch(error){setMessage(error instanceof Error?error.message:'Impossible de créer l’événement.');}finally{setBusy(false);}}

  async function select(event:ClientEventContract){if(event.id===workspace?.selectedEvent?.id)return;setSelectingId(event.id);setMessage('');try{const next=await selectClientEvent(api,stationToken,event.id);setWorkspace(next);setMessage(`✓ « ${event.name} » sélectionné. CAPTURE et SHARING basculent automatiquement avec le bon design.`);onSelected?.(event.id,event.name);}catch(error){setMessage(error instanceof Error?error.message:'Impossible d’ouvrir cet événement.');}finally{setSelectingId(null);}}

  const studioAllowed=Boolean(workspace?.entitlements?.STUDIO_BASIC);
  return <View style={styles.shell}>
    <View style={styles.header}><View style={{flex:1}}><Text style={styles.eyebrow}>RÉGIE CLIENT • ÉVÉNEMENTS</Text><Text style={styles.title}>Mes événements</Text><Text style={styles.help}>Créez, préparez et sélectionnez une prestation directement depuis SHARING. Chaque événement conserve désormais son propre design.</Text></View><View style={styles.plan}><Text style={styles.planText}>{workspace?.plan||'…'}</Text></View></View>
    {!open?<Pressable style={styles.createButton} onPress={()=>{setOpen(true);if(!startsAt)setStartsAt(localExample(1));if(!endsAt)setEndsAt(localExample(5));}}><Text style={styles.createText}>＋ CRÉER UN ÉVÉNEMENT</Text></Pressable>:<View style={styles.form}><Text style={styles.label}>Nom *</Text><TextInput style={styles.input} value={name} onChangeText={setName} maxLength={180} placeholder="Nom de la prestation"/><Text style={styles.label}>Description *</Text><TextInput style={[styles.input,styles.multiline]} value={description} onChangeText={setDescription} multiline maxLength={4000} placeholder="Ambiance et besoins…"/><View style={styles.two}><View style={{flex:1}}><Text style={styles.label}>Début *</Text><TextInput style={styles.input} value={startsAt} onChangeText={setStartsAt} autoCapitalize="none" placeholder="2026-08-22 18:00"/></View><View style={{flex:1}}><Text style={styles.label}>Fin *</Text><TextInput style={styles.input} value={endsAt} onChangeText={setEndsAt} autoCapitalize="none" placeholder="2026-08-23 02:00"/></View></View><View style={styles.actions}><Pressable style={styles.cancel} onPress={()=>setOpen(false)}><Text style={styles.cancelText}>Annuler</Text></Pressable><Pressable disabled={busy} style={[styles.submit,busy&&styles.disabled]} onPress={()=>void create()}><Text style={styles.submitText}>{busy?'Création…':studioAllowed?'Créer → Studio':'Créer → Prêt'}</Text></Pressable></View></View>}
    {!studioAllowed&&workspace?<View style={styles.locked}><Text style={styles.lockedTitle}>Design par défaut KHE</Text><Text style={styles.help}>Votre offre actuelle crée l’événement avec un design KHE prêt à l’emploi.</Text></View>:null}
    {message?<Text style={styles.message}>{message}</Text>:null}
    {workspace?.events?.length?<View style={styles.list}><Text style={styles.listTitle}>ÉVÉNEMENTS DU CLIENT</Text>{workspace.events.slice(0,12).map((event)=>{const selected=workspace.selectedEvent?.id===event.id;const disabled=['COMPLETED','ARCHIVED'].includes(event.status)||selectingId!==null;return <View key={event.id} style={[styles.eventRow,selected&&styles.eventSelected]}><View style={{flex:1}}><Text style={styles.eventName}>{event.name}</Text><Text style={styles.eventDates}>{new Date(event.startsAt).toLocaleString()} → {event.endsAt?new Date(event.endsAt).toLocaleString():'—'}</Text><Text style={styles.status}>{event.status}</Text></View><Pressable disabled={disabled||selected} onPress={()=>void select(event)} style={[styles.openButton,(disabled||selected)&&styles.disabled]}><Text style={styles.openText}>{selected?'ACTIF':selectingId===event.id?'OUVERTURE…':'OUVRIR'}</Text></Pressable></View>;})}</View>:null}
  </View>;
}

const RED='#b31520',GOLD='#d2ad4f';
const styles=StyleSheet.create({shell:{backgroundColor:'#fff8e8',borderRadius:20,borderWidth:1,borderColor:'#ead397',padding:16,gap:13},header:{flexDirection:'row',gap:10,alignItems:'flex-start'},eyebrow:{color:RED,fontSize:10,letterSpacing:1.6,fontWeight:'900'},title:{fontSize:22,fontWeight:'900',color:'#111',marginTop:3},help:{color:'#6f6458',lineHeight:18,fontSize:12,marginTop:4},plan:{backgroundColor:'#111',borderRadius:999,paddingHorizontal:10,paddingVertical:6},planText:{color:GOLD,fontSize:10,fontWeight:'900'},createButton:{backgroundColor:RED,borderRadius:14,padding:14,alignItems:'center'},createText:{color:'#fff',fontWeight:'900'},form:{gap:8,backgroundColor:'#fff',borderRadius:16,padding:14},label:{fontSize:10,fontWeight:'900',color:'#4a4038'},input:{borderWidth:1,borderColor:'#ddd1c1',borderRadius:12,paddingHorizontal:12,paddingVertical:11,color:'#111',backgroundColor:'#fff'},multiline:{minHeight:90,textAlignVertical:'top'},two:{flexDirection:'row',gap:9},actions:{flexDirection:'row',gap:9,marginTop:4},cancel:{flex:1,borderWidth:1,borderColor:'#bbb',borderRadius:12,padding:12,alignItems:'center'},cancelText:{fontWeight:'900'},submit:{flex:2,backgroundColor:'#111',borderRadius:12,padding:12,alignItems:'center'},submitText:{color:'#fff',fontWeight:'900'},disabled:{opacity:.45},locked:{borderRadius:14,borderWidth:1,borderColor:'#dbc8a7',padding:12,backgroundColor:'#f7f1e6'},lockedTitle:{fontWeight:'900',color:'#5d4b2b'},message:{fontSize:12,lineHeight:18,color:'#4b4036',fontWeight:'700'},list:{gap:7,borderTopWidth:1,borderTopColor:'#e7d7ba',paddingTop:10},listTitle:{fontSize:9,letterSpacing:1.4,fontWeight:'900',color:'#74664f'},eventRow:{flexDirection:'row',gap:9,alignItems:'center',padding:10,borderRadius:12,backgroundColor:'#fff'},eventSelected:{borderWidth:1,borderColor:GOLD},eventName:{fontWeight:'900',color:'#111'},eventDates:{fontSize:10,color:'#7b7064',marginTop:2},status:{fontSize:9,fontWeight:'900',color:RED,marginTop:3},openButton:{backgroundColor:'#111',borderRadius:10,paddingHorizontal:12,paddingVertical:9},openText:{color:'#fff',fontWeight:'900',fontSize:10}});
