import { useEffect, useMemo, useRef, useState } from 'react';
import { Animated, PanResponder, StyleSheet, Text, View } from 'react-native';
import type { StationExperienceApi } from '../api/station-api';

type Status='DISCONNECTED'|'PENDING'|'ACCEPTED'|'REJECTED';
const HANDLE=62;

export function SlideToConnect({api,stationToken}:{api:StationExperienceApi;stationToken:string}){
  const x=useRef(new Animated.Value(0)).current;const[width,setWidth]=useState(0);const[status,setStatus]=useState<Status>('DISCONNECTED');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const statusRef=useRef<Status>('DISCONNECTED');
  const maxX=Math.max(0,width-HANDLE-8);
  function updateStatus(next:Status){statusRef.current=next;setStatus(next);if(next==='ACCEPTED')Animated.spring(x,{toValue:maxX,useNativeDriver:true,tension:65,friction:9}).start();else if(next!=='PENDING')Animated.spring(x,{toValue:0,useNativeDriver:true,tension:65,friction:9}).start();}
  useEffect(()=>{let cancelled=false;let timer:ReturnType<typeof setTimeout>|null=null;const poll=async()=>{let delay=1500;try{const control=await api.control(stationToken);if(cancelled)return;const next=(control.sharingConnectionStatus??'DISCONNECTED') as Status;updateStatus(next);if(next==='PENDING')setMessage('Demande envoyée. Acceptez maintenant sur la tablette CAPTURE.');else if(next==='ACCEPTED')setMessage('✓ CAPTURE et SHARING sont connectées.');else if(next==='REJECTED')setMessage('Connexion refusée sur CAPTURE. Glissez à nouveau pour renvoyer la demande.');else setMessage('');}catch(error){delay=5000;if(!cancelled)setMessage(error instanceof Error?`État de liaison indisponible : ${error.message}`:'État de liaison indisponible.');}finally{if(!cancelled)timer=setTimeout(()=>void poll(),delay);}};void poll();return()=>{cancelled=true;if(timer)clearTimeout(timer);};},[api,stationToken,maxX,x]);
  async function requestConnection(){if(busy||statusRef.current==='ACCEPTED')return;setBusy(true);setMessage('Envoi de la demande à CAPTURE…');try{const control=await api.requestControlConnection(stationToken);updateStatus((control.sharingConnectionStatus??'PENDING') as Status);setMessage('Demande envoyée. Acceptez la connexion sur CAPTURE.');}catch(error){updateStatus('DISCONNECTED');setMessage(error instanceof Error?error.message:'Impossible d’envoyer la demande de connexion.');}finally{setBusy(false);}}
  const pan=useMemo(()=>PanResponder.create({onStartShouldSetPanResponder:()=>statusRef.current!=='ACCEPTED'&&!busy,onMoveShouldSetPanResponder:(_event,gesture)=>Math.abs(gesture.dx)>5,onPanResponderMove:(_event,gesture)=>{if(statusRef.current==='PENDING')return;x.setValue(Math.max(0,Math.min(maxX,gesture.dx)));},onPanResponderRelease:(_event,gesture)=>{if(statusRef.current==='PENDING'){Animated.spring(x,{toValue:maxX*.55,useNativeDriver:true}).start();return;}if(maxX>0&&gesture.dx>=maxX*.68){Animated.spring(x,{toValue:maxX,useNativeDriver:true}).start();void requestConnection();}else Animated.spring(x,{toValue:0,useNativeDriver:true}).start();},onPanResponderTerminate:()=>{if(statusRef.current!=='ACCEPTED')Animated.spring(x,{toValue:0,useNativeDriver:true}).start();}}),[busy,maxX,x]);
  const label=status==='ACCEPTED'?'TABLETTES CONNECTÉES':status==='PENDING'?'EN ATTENTE DE CAPTURE':'GLISSEZ L’ÉTOILE VERS LA DROITE';
  return <View style={styles.card}><Text style={styles.eyebrow}>CONNEXION CAPTURE ↔ SHARING</Text><Text style={styles.title}>Relier les deux tablettes</Text><Text style={styles.help}>Glissez l’étoile dorée vers la droite. Une confirmation apparaîtra immédiatement sur CAPTURE.</Text><View style={[styles.track,status==='ACCEPTED'&&styles.trackAccepted]} onLayout={event=>setWidth(event.nativeEvent.layout.width)}><Text style={styles.trackLabel}>{busy?'CONNEXION…':label}</Text><Animated.View {...pan.panHandlers} style={[styles.handle,{transform:[{translateX:x}]}]}><Text style={styles.star}>★</Text></Animated.View></View>{message?<Text style={[styles.message,status==='ACCEPTED'&&styles.success]}>{message}</Text>:null}</View>;
}

const GOLD='#d2ad4f';
const styles=StyleSheet.create({card:{backgroundColor:'#111113',borderWidth:1,borderColor:'#4b4230',borderRadius:20,padding:16,gap:8},eyebrow:{color:GOLD,fontSize:9,fontWeight:'900',letterSpacing:1.7},title:{color:'#fff',fontSize:21,fontWeight:'900'},help:{color:'#bbb4aa',fontSize:12,lineHeight:18},track:{height:70,borderRadius:35,backgroundColor:'#27231c',borderWidth:1,borderColor:'#756236',justifyContent:'center',overflow:'hidden',marginTop:5,paddingHorizontal:70},trackAccepted:{backgroundColor:'#173324',borderColor:'#55bd7c'},trackLabel:{color:'#dfd5c1',fontSize:10,fontWeight:'900',letterSpacing:.7,textAlign:'center'},handle:{position:'absolute',left:4,top:4,width:62,height:62,borderRadius:31,backgroundColor:GOLD,alignItems:'center',justifyContent:'center',borderWidth:2,borderColor:'#ffe79d',shadowColor:'#d2ad4f',shadowOpacity:.6,shadowRadius:10,elevation:7},star:{fontSize:29,color:'#111'},message:{color:'#e4c873',fontSize:11,lineHeight:16},success:{color:'#7be0a1'}});
