import { BadRequestException, ForbiddenException, Injectable } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import type { AuthenticatedUser } from '../auth/auth.types';
import { SocialCredentialCipher } from './social-credential-cipher';

export type SocialDeveloperProvider='META'|'WHATSAPP'|'TIKTOK'|'X'|'TELEGRAM'|'YOUTUBE';
type CredentialRow={provider:SocialDeveloperProvider;credentialsCiphertext:string;configuredFields:string[];configuredByUserId:string|null;status:string;updatedAt:Date};
export const SOCIAL_DEVELOPER_DEFINITIONS:Record<SocialDeveloperProvider,{label:string;fields:string[];env:Record<string,string>;callbacks?:string[]}>= {
  META:{label:'Meta / Facebook / Instagram',fields:['appId','appSecret','configId'],env:{appId:'META_APP_ID',appSecret:'META_APP_SECRET',configId:'META_BUSINESS_LOGIN_CONFIG_ID'},callbacks:['facebook','instagram']},
  WHATSAPP:{label:'WhatsApp Cloud API',fields:['accessToken','phoneNumberId'],env:{accessToken:'META_WHATSAPP_ACCESS_TOKEN',phoneNumberId:'META_WHATSAPP_PHONE_NUMBER_ID'}},
  TIKTOK:{label:'TikTok',fields:['clientKey','clientSecret'],env:{clientKey:'TIKTOK_CLIENT_KEY',clientSecret:'TIKTOK_CLIENT_SECRET'},callbacks:['tiktok']},
  X:{label:'X',fields:['clientId','clientSecret'],env:{clientId:'X_CLIENT_ID',clientSecret:'X_CLIENT_SECRET'},callbacks:['x']},
  TELEGRAM:{label:'Telegram',fields:['botToken','targetChatId'],env:{botToken:'TELEGRAM_BOT_TOKEN',targetChatId:'TELEGRAM_TARGET_CHAT_ID'}},
  YOUTUBE:{label:'YouTube / Google',fields:['clientId','clientSecret'],env:{clientId:'GOOGLE_OAUTH_CLIENT_ID',clientSecret:'GOOGLE_OAUTH_CLIENT_SECRET'},callbacks:['youtube']},
};
@Injectable()
export class SocialDeveloperCredentialService{
  constructor(private readonly prisma:PrismaService,private readonly cipher:SocialCredentialCipher){}
  private row(org:string,provider:SocialDeveloperProvider){return this.prisma.$queryRaw<CredentialRow[]>`SELECT provider,"credentialsCiphertext","configuredFields","configuredByUserId",status,"updatedAt" FROM "SocialDeveloperCredential" WHERE "organizationId"=${org}::uuid AND provider=${provider} LIMIT 1`.then(rows=>rows[0]??null);}
  private decode(row:CredentialRow|null):Record<string,string>{if(!row||row.status!=='ACTIVE')return{};const raw=this.cipher.decrypt(row.credentialsCiphertext);if(!raw)return{};try{const parsed=JSON.parse(raw) as Record<string,unknown>;return Object.fromEntries(Object.entries(parsed).filter(([,v])=>typeof v==='string'&&v.trim()).map(([k,v])=>[k,String(v).trim()]));}catch{return{};}}
  private assertProvider(value:string):SocialDeveloperProvider{const provider=String(value||'').toUpperCase() as SocialDeveloperProvider;if(!(provider in SOCIAL_DEVELOPER_DEFINITIONS))throw new BadRequestException('Fournisseur développeur social inconnu');return provider;}
  private requireOwner(user:AuthenticatedUser){if(user.role!=='OWNER')throw new ForbiddenException('Seul OWNER peut modifier les secrets développeur sociaux');}
  private callbackOrigin(){const explicit=process.env.SOCIAL_OAUTH_CALLBACK_ORIGIN?.trim();if(explicit)return explicit.replace(/\/$/,'');const vercel=process.env.VERCEL_PROJECT_PRODUCTION_URL?.trim();if(vercel)return`https://${vercel.replace(/^https?:\/\//,'').replace(/\/$/,'')}`;return'http://localhost:3001';}
  private async summaries(org:string){const rows=await this.prisma.$queryRaw<CredentialRow[]>`SELECT provider,"credentialsCiphertext","configuredFields","configuredByUserId",status,"updatedAt" FROM "SocialDeveloperCredential" WHERE "organizationId"=${org}::uuid`;const map=new Map(rows.map(r=>[r.provider,r]));return Object.entries(SOCIAL_DEVELOPER_DEFINITIONS).map(([key,d])=>{const provider=key as SocialDeveloperProvider;const row=map.get(provider);const envFields=d.fields.filter(f=>Boolean(process.env[d.env[f]]?.trim()));const dbFields=row?.status==='ACTIVE'?row.configuredFields:[];const configuredFields=[...new Set([...envFields,...dbFields])];return{provider,label:d.label,configured:d.fields.every(f=>configuredFields.includes(f)),configuredFields,requiredFields:d.fields,source:dbFields.length?'KHE_ENCRYPTED':envFields.length?'SERVER_ENV':'NONE',updatedAt:row?.updatedAt??null,configuredByUserId:row?.configuredByUserId??null,callbacks:(d.callbacks??[]).map(p=>`${this.callbackOrigin()}/api/stations/social/oauth/${p}/callback`)};});}
  list(user:AuthenticatedUser){return this.summaries(user.organizationId);}
  summaryForOrganization(org:string){return this.summaries(org);}
  async save(user:AuthenticatedUser,value:string,body:Record<string,unknown>){this.requireOwner(user);const provider=this.assertProvider(value);const d=SOCIAL_DEVELOPER_DEFINITIONS[provider];const existing=await this.row(user.organizationId,provider);const merged=this.decode(existing);for(const field of d.fields){const v=body[field];if(typeof v==='string'&&v.trim())merged[field]=v.trim();}const missing=d.fields.filter(f=>!merged[f]);if(missing.length)throw new BadRequestException(`Champs requis manquants : ${missing.join(', ')}`);const encrypted=this.cipher.encrypt(JSON.stringify(merged));if(!encrypted)throw new BadRequestException('Configuration vide');await this.prisma.$executeRaw`INSERT INTO "SocialDeveloperCredential" ("organizationId",provider,"credentialsCiphertext","configuredFields","configuredByUserId",status) VALUES (${user.organizationId}::uuid,${provider},${encrypted},${d.fields}::text[],${user.id}::uuid,'ACTIVE') ON CONFLICT ("organizationId",provider) DO UPDATE SET "credentialsCiphertext"=EXCLUDED."credentialsCiphertext","configuredFields"=EXCLUDED."configuredFields","configuredByUserId"=EXCLUDED."configuredByUserId",status='ACTIVE',"updatedAt"=CURRENT_TIMESTAMP`;await this.prisma.auditLog.create({data:{organizationId:user.organizationId,userId:user.id,action:'SOCIAL_DEVELOPER_CREDENTIAL_UPDATED',entityType:'SocialDeveloperCredential',metadata:{provider,fields:d.fields}}});return{provider,configured:true,configuredFields:d.fields};}
  async remove(user:AuthenticatedUser,value:string){this.requireOwner(user);const provider=this.assertProvider(value);await this.prisma.$executeRaw`DELETE FROM "SocialDeveloperCredential" WHERE "organizationId"=${user.organizationId}::uuid AND provider=${provider}`;await this.prisma.auditLog.create({data:{organizationId:user.organizationId,userId:user.id,action:'SOCIAL_DEVELOPER_CREDENTIAL_REMOVED',entityType:'SocialDeveloperCredential',metadata:{provider}}});return{provider,configured:false};}
  async value(org:string,provider:SocialDeveloperProvider,field:string,envName:string):Promise<string>{const row=await this.row(org,provider);const db=this.decode(row)[field];const value=db||process.env[envName]?.trim();if(!value)throw new BadRequestException(`Configuration développeur incomplète : ${provider}.${field}`);return value;}
}
