'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { PortalShell } from '@/components/portal-shell';
import { apiRequest } from '@/lib/api';

type Shift={id:string;startsAt:string;endsAt:string;status:string;source:string;note?:string|null;confirmationStatus:string;respondedAt?:string|null;responseNote?:string|null;languages:string[];skills:string[];availabilityConflict:boolean};
type Availability={id:string;startsAt:string;endsAt:string;status:string;note?:string|null};
type Notice={id:string;kind:string;title:string;body:string;actionUrl?:string|null;readAt?:string|null;createdAt:string};
type Mine={summary:{upcoming:number;pending:number;accepted:number;conflicts:number;unreadNotices:number};shifts:Shift[];availability:Availability[];notices:Notice[]};

function when(value:string){return new Date(value).toLocaleString('fr-CH',{weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});}
function toIso(value:string){const d=new Date(value);return Number.isFinite(d.getTime())?d.toISOString():'';}
function statusLabel(value:string){return value==='ACCEPTED'?'Accepté':value==='DECLINED'?'Refusé':'Confirmation attendue';}

export default function AgentWorkforcePage(){
  const[data,setData]=useState<Mine|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState('');const[message,setMessage]=useState('');const[notes,setNotes]=useState<Record<string,string>>({});const[availability,setAvailability]=useState({startsAt:'',endsAt:'',note:''});
  const load=useCallback(async(quiet=false)=>{if(!quiet)setLoading(true);try{setData(await apiRequest<Mine>('/operations/workforce/agent/me'));if(!quiet)setMessage('');}catch(e){if(!quiet)setMessage(e instanceof Error?e.message:'Planning indisponible');}finally{if(!quiet)setLoading(false);}},[]);
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(true),60000);return()=>window.clearInterval(timer);},[load]);
  const upcoming=useMemo(()=>data?.shifts.filter(s=>s.status==='PLANNED'&&new Date(s.endsAt)>new Date())??[],[data]);
  async function respond(id:string,response:'ACCEPTED'|'DECLINED'){setBusy(id);try{await apiRequest(`/operations/workforce/agent/shifts/${id}/respond`,{method:'POST',body:JSON.stringify({response,note:notes[id]||''})});setMessage(response==='ACCEPTED'?'✓ Shift confirmé.':'✓ Indisponibilité signalée pour ce shift. Le manager décidera du remplacement.');await load(true);}catch(e){setMessage(e instanceof Error?e.message:'Réponse impossible');}finally{setBusy('');}}
  async function addAvailability(){if(!availability.startsAt||!availability.endsAt){setMessage('Renseignez le début et la fin de votre indisponibilité.');return;}setBusy('availability');try{const result=await apiRequest<{conflictingShifts:number}>('/operations/workforce/agent/availability',{method:'POST',body:JSON.stringify({startsAt:toIso(availability.startsAt),endsAt:toIso(availability.endsAt),note:availability.note})});setAvailability({startsAt:'',endsAt:'',note:''});setMessage(result.conflictingShifts?`✓ Indisponibilité enregistrée. ${result.conflictingShifts} shift(s) existant(s) ont été signalés au manager, sans annulation automatique.`:'✓ Indisponibilité enregistrée.');await load(true);}catch(e){setMessage(e instanceof Error?e.message:'Impossible d’enregistrer l’indisponibilité');}finally{setBusy('');}}
  async function cancelAvailability(id:string){try{await apiRequest(`/operations/workforce/agent/availability/${id}/cancel`,{method:'PATCH'});setMessage('✓ Indisponibilité annulée.');await load(true);}catch(e){setMessage(e instanceof Error?e.message:'Action impossible');}}
  async function markRead(id:string){try{await apiRequest(`/operations/workforce/agent/notices/${id}/read`,{method:'POST'});await load(true);}catch{}}

  return <PortalShell><div className="page-header"><div><div className="eyebrow">KHE • AGENT WORKFORCE</div><h1>Mon planning</h1><p className="muted">Consultez vos shifts, confirmez votre présence et signalez vos indisponibilités. Un refus ne modifie pas automatiquement votre planning : le manager valide tout remplacement.</p><div style={{display:'flex',gap:12,flexWrap:'wrap',marginTop:8}}><Link href="/dashboard">← Dashboard</Link><Link href="/help">Aide / Messagerie</Link></div></div><button className="button secondary" onClick={()=>void load()}>{loading?'Chargement…':'↻ Actualiser'}</button></div>
  {message?<p className={message.startsWith('✓')?'success':'error'}>{message}</p>:null}
  {!data?null:<>
    <div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',marginBottom:16}}>{[['Shifts à venir',data.summary.upcoming],['À confirmer',data.summary.pending],['Acceptés',data.summary.accepted],['Conflits disponibilité',data.summary.conflicts],['Rappels non lus',data.summary.unreadNotices]].map(([label,value])=><div className="card" key={String(label)}><div className="eyebrow">{label}</div><div style={{fontSize:28,fontWeight:950,marginTop:8}}>{value}</div></div>)}</div>

    {data.notices.length?<section className="card" style={{marginBottom:16}}><div className="eyebrow">RAPPELS PRIVÉS</div><h2>Notifications de planning</h2>{data.notices.slice(0,8).map(n=><button key={n.id} onClick={()=>void markRead(n.id)} style={{width:'100%',textAlign:'left',background:'transparent',border:0,borderBottom:'1px solid #27303a',padding:'10px 0',color:'inherit',opacity:n.readAt?0.72:1,cursor:'pointer'}}><strong>{n.readAt?'':'● '}{n.title}</strong><div className="muted" style={{fontSize:12,marginTop:3}}>{n.body}</div><div className="muted" style={{fontSize:10,marginTop:3}}>{when(n.createdAt)}</div></button>)}</section>:null}

    <section className="card"><div className="eyebrow">SHIFTS</div><h2>Mes prochains services</h2>{upcoming.length?upcoming.map(s=><div key={s.id} style={{padding:'14px 0',borderBottom:'1px solid #27303a'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><strong>{when(s.startsAt)} → {when(s.endsAt)}</strong><div className="muted" style={{fontSize:12,marginTop:3}}>{s.skills.length?`Compétences : ${s.skills.join(', ')}`:'Couverture générale'} · {s.languages.length?`Langues : ${s.languages.join(', ')}`:'Langue non spécifiée'}</div>{s.availabilityConflict?<div style={{color:'#ff9aa4',fontWeight:800,fontSize:12,marginTop:4}}>⚠ Ce shift chevauche une indisponibilité déclarée.</div>:null}</div><span style={{fontWeight:900,color:s.confirmationStatus==='ACCEPTED'?'#78d59c':s.confirmationStatus==='DECLINED'?'#ff9aa4':'#f5c76b'}}>{statusLabel(s.confirmationStatus)}</span></div><input className="input" value={notes[s.id]??''} onChange={e=>setNotes({...notes,[s.id]:e.target.value})} placeholder="Commentaire opérationnel facultatif" style={{marginTop:10}}/><div className="muted" style={{fontSize:10,marginTop:4}}>Évitez d’inscrire des informations médicales ou personnelles sensibles. Le commentaire n’est pas utilisé pour classer les agents.</div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:10}}><button className="button" disabled={busy===s.id} onClick={()=>void respond(s.id,'ACCEPTED')}>Je confirme</button><button className="button secondary" disabled={busy===s.id} onClick={()=>void respond(s.id,'DECLINED')}>Je ne suis pas disponible</button></div></div>):<p className="muted">Aucun shift planifié sur les 30 prochains jours.</p>}</section>

    <div className="grid two" style={{alignItems:'start',marginTop:16}}><section className="card"><div className="eyebrow">INDISPONIBILITÉ</div><h2>Déclarer une période</h2><div className="grid two"><label>Début<input className="input" type="datetime-local" value={availability.startsAt} onChange={e=>setAvailability({...availability,startsAt:e.target.value})}/></label><label>Fin<input className="input" type="datetime-local" value={availability.endsAt} onChange={e=>setAvailability({...availability,endsAt:e.target.value})}/></label></div><label>Note opérationnelle facultative<input className="input" value={availability.note} onChange={e=>setAvailability({...availability,note:e.target.value})} placeholder="Ex. déjà engagé sur un autre événement"/></label><p className="muted" style={{fontSize:11}}>N’indiquez pas de diagnostic, donnée médicale ou autre information sensible. KHE utilise seulement les dates pour éviter les conflits de planning.</p><button className="button" disabled={busy==='availability'} onClick={()=>void addAvailability()}>{busy==='availability'?'Enregistrement…':'Enregistrer l’indisponibilité'}</button></section><section className="card"><div className="eyebrow">PÉRIODES ACTIVES</div><h2>Mes indisponibilités</h2>{data.availability.length?data.availability.map(a=><div key={a.id} style={{padding:'10px 0',borderBottom:'1px solid #27303a'}}><strong>{when(a.startsAt)} → {when(a.endsAt)}</strong>{a.note?<div className="muted" style={{fontSize:12}}>{a.note}</div>:null}<button className="button secondary" style={{marginTop:7}} onClick={()=>void cancelAvailability(a.id)}>Annuler cette indisponibilité</button></div>):<p className="muted">Aucune indisponibilité active.</p>}</section></div>
  </>}
  </PortalShell>;
}
