'use client';

import { useParams } from 'next/navigation';
import { ChangeEvent, useCallback, useEffect, useMemo, useState } from 'react';

const configuredApiUrl=process.env.NEXT_PUBLIC_API_URL?.trim();
const API_URL=configuredApiUrl?configuredApiUrl.replace(/\/$/,''):process.env.NODE_ENV==='production'?'https://khebooth-api.vercel.app/api':'http://localhost:3001/api';

type DocumentRow={id:string;documentType:string;originalFileName:string;status:string;uploadedAt:string;verifiedAt?:string|null;rejectionReason?:string|null;verificationCycle:number};
type StatusPayload={client:{name:string;email?:string|null};subscription:{active:boolean;plan:string;status:string;paymentStatus:string;endsAt?:string|null};cycle:number;status:string;dueAt?:string|null;lastVerifiedAt?:string|null;documents:DocumentRow[];requirements:{identity:{received:boolean;status:string};proofOfAddress:{received:boolean;status:string}};humanReviewRequired:boolean;contractResignRequired:boolean;message:string};

async function request<T>(path:string,init:RequestInit={}):Promise<T>{const headers=new Headers(init.headers);if(init.body)headers.set('Content-Type','application/json');const response=await fetch(`${API_URL}${path}`,{...init,headers,cache:'no-store'});if(!response.ok){let message=`Erreur (${response.status})`;try{const data=await response.json() as {message?:string|string[]};message=Array.isArray(data.message)?data.message.join(', '):data.message||message;}catch{}throw new Error(message);}return response.json() as Promise<T>;}

function statusTone(status:string){if(status==='VERIFIED')return'#8fe0aa';if(status==='REJECTED'||status==='CHANGES_REQUESTED'||status==='OVERDUE')return'#ff9f9f';return'#e9c86c';}
function docLabel(type:string){if(type==='PROOF_OF_ADDRESS')return'Preuve de domicile';if(type==='IDENTITY_CARD')return'Carte d’identité';if(type==='PASSPORT')return'Passeport';return type;}

export default function EnterpriseReverificationPage(){
  const params=useParams<{token:string}>();const token=String(params?.token||'');
  const[data,setData]=useState<StatusPayload|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');const[identityType,setIdentityType]=useState('PASSPORT');
  const load=useCallback(async()=>{if(!token)return;setError('');try{setData(await request<StatusPayload>(`/enterprise/onboarding/${encodeURIComponent(token)}/reverification-status`));}catch(caught){setError(caught instanceof Error?caught.message:'Lien de vérification indisponible.');}},[token]);
  useEffect(()=>{void load();},[load]);

  async function upload(documentType:string,file:File){setBusy(true);setError('');setMessage('');try{const ticket=await request<{pathname:string;uploadUrl:string}>(`/enterprise/onboarding/${encodeURIComponent(token)}/documents/upload`,{method:'POST',body:JSON.stringify({documentType,contentType:file.type,byteSize:file.size,originalFileName:file.name})});const uploaded=await fetch(ticket.uploadUrl,{method:'PUT',headers:{'Content-Type':file.type},body:file});if(!uploaded.ok)throw new Error(`Transmission impossible (${uploaded.status})`);await request(`/enterprise/onboarding/${encodeURIComponent(token)}/documents/confirm`,{method:'POST',body:JSON.stringify({pathname:ticket.pathname,documentType,originalFileName:file.name})});setMessage('Document reçu. Il est maintenant dans la file de vérification KHE.');await load();}catch(caught){setError(caught instanceof Error?caught.message:'Transmission impossible.');}finally{setBusy(false);}}

  const currentDocs=useMemo(()=>data?.documents||[],[data]);
  if(!data&&!error)return <main style={styles.page}><section style={styles.card}><strong>KHE BOOTH Enterprise</strong><p>Chargement de votre vérification annuelle…</p></section></main>;
  if(!data)return <main style={styles.page}><section style={styles.card}><h1>KHE BOOTH Enterprise</h1><p style={styles.error}>{error||'Lien invalide ou expiré.'}</p></section></main>;
  const done=data.status==='VERIFIED';const disabled=busy||done||!data.subscription.active;
  return <main style={styles.page}>
    <section style={styles.hero}><div><div style={styles.kicker}>KHE BOOTH • SÉCURITÉ ENTERPRISE</div><h1 style={{fontSize:'clamp(30px,5vw,50px)',margin:'8px 0'}}>Vérification annuelle</h1><p style={styles.lead}>Deux justificatifs seulement. Votre formulaire, votre contrat et vos paramètres restent enregistrés.</p></div><span style={{...styles.status,color:statusTone(data.status)}}>{data.status}</span></section>
    {error?<div style={{...styles.card,...styles.error}}>{error}</div>:null}{message?<div style={{...styles.card,color:'#9ee5b6'}}>{message}</div>:null}

    <section style={styles.card}><div style={styles.summary}><div><small>CLIENT</small><strong>{data.client.name}</strong></div><div><small>CYCLE</small><strong>Année {Math.max(1,data.cycle)}</strong></div><div><small>ÉCHÉANCE</small><strong>{data.dueAt?new Date(data.dueAt).toLocaleDateString('fr-CH'):'—'}</strong></div></div><p style={{marginBottom:0,color:'#c8cdd4'}}>{data.message}</p></section>

    {!data.subscription.active?<section style={{...styles.card,borderColor:'#7b5623'}}><div style={styles.kicker}>ABONNEMENT</div><h2>Votre abonnement Enterprise n’est plus actif</h2><p style={styles.lead}>Les avantages payants sont suspendus et le compte est revenu au niveau gratuit. Renouvelez votre abonnement avant de poursuivre cette procédure.</p><a style={styles.primary as any} href="/subscribe">Voir les offres KHE BOOTH</a></section>:null}

    <section style={styles.card}><div style={styles.kicker}>01 • IDENTITÉ</div><h2>Pièce d’identité ou passeport valable</h2><div style={styles.row}><select value={identityType} onChange={(e)=>setIdentityType(e.target.value)} disabled={disabled} style={styles.input}><option value="PASSPORT">Passeport</option><option value="IDENTITY_CARD">Carte d’identité</option></select><input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,application/pdf,image/jpeg,image/png,image/webp" disabled={disabled} onChange={(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(file)void upload(identityType,file);}}/></div><Requirement label="Identité" received={data.requirements.identity.received} status={data.requirements.identity.status}/></section>

    <section style={styles.card}><div style={styles.kicker}>02 • DOMICILE</div><h2>Preuve de domicile récente</h2><p style={styles.lead}>Utilisez un document récent et lisible indiquant votre nom et votre adresse actuelle.</p><input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,application/pdf,image/jpeg,image/png,image/webp" disabled={disabled} onChange={(event)=>{const file=event.target.files?.[0];if(file)void upload('PROOF_OF_ADDRESS',file);}}/><Requirement label="Domicile" received={data.requirements.proofOfAddress.received} status={data.requirements.proofOfAddress.status}/></section>

    <section style={styles.card}><div style={styles.kicker}>SUIVI</div><h2>Documents de cette vérification</h2>{currentDocs.length===0?<p style={styles.lead}>Aucun nouveau justificatif transmis pour ce cycle.</p>:<div style={{display:'grid',gap:9}}>{currentDocs.map(doc=><div key={doc.id} style={styles.doc}><div><strong>{docLabel(doc.documentType)}</strong><div style={{fontSize:12,color:'#969eaa'}}>{doc.originalFileName} · {new Date(doc.uploadedAt).toLocaleDateString('fr-CH')}</div>{doc.rejectionReason?<div style={{marginTop:5,color:'#ff9f9f',fontSize:12}}>{doc.rejectionReason}</div>:null}</div><span style={{fontWeight:900,color:statusTone(doc.status)}}>{doc.status}</span></div>)}</div>}</section>

    <section style={styles.card}><div style={styles.kicker}>CONFIDENTIALITÉ</div><p style={{margin:0,color:'#aeb5bf',lineHeight:1.65}}>Les justificatifs sont transmis dans un stockage privé. Leur examen est réservé au OWNER KHE BOOTH ou à un agent disposant explicitement du droit de vérification Enterprise. Une fois les deux documents validés, la re-vérification annuelle se termine automatiquement.</p></section>
  </main>;
}

function Requirement({label,received,status}:{label:string;received:boolean;status:string}){return <div style={{...styles.requirement,borderColor:received?'rgba(143,224,170,.35)':'rgba(233,200,108,.3)'}}><span>{received?'✓':'○'} {label}</span><strong style={{color:statusTone(status)}}>{status}</strong></div>;}

const styles:Record<string,React.CSSProperties>={page:{minHeight:'100vh',background:'radial-gradient(circle at 12% 0%,#34270d 0,#0b0d11 36%,#060709 100%)',color:'#f5f6f8',padding:'32px 16px 80px',fontFamily:'Arial,sans-serif'},hero:{maxWidth:900,margin:'0 auto 16px',padding:'26px',border:'1px solid rgba(215,180,90,.38)',borderRadius:24,background:'linear-gradient(145deg,rgba(24,28,34,.97),rgba(18,15,8,.97))',display:'flex',justifyContent:'space-between',alignItems:'flex-start',gap:20,flexWrap:'wrap'},card:{maxWidth:900,margin:'14px auto',padding:'23px',border:'1px solid #2b3038',borderRadius:20,background:'rgba(16,19,24,.97)',boxSizing:'border-box'},kicker:{fontSize:11,fontWeight:900,letterSpacing:1.8,color:'#d7b45a'},lead:{color:'#aeb5bf',lineHeight:1.6},status:{padding:'9px 13px',border:'1px solid #5c4b25',background:'#211c10',borderRadius:999,fontSize:12,fontWeight:900},summary:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:12},row:{display:'grid',gridTemplateColumns:'minmax(160px,240px) 1fr',gap:16,alignItems:'center'},input:{width:'100%',padding:'12px 13px',background:'#090b0e',border:'1px solid #343a44',borderRadius:11,color:'#fff'},requirement:{marginTop:16,padding:'12px 14px',border:'1px solid',borderRadius:12,display:'flex',justifyContent:'space-between',gap:14,background:'#0b0d11'},doc:{padding:'12px 14px',border:'1px solid #2b3038',borderRadius:12,display:'flex',justifyContent:'space-between',gap:15,alignItems:'center',background:'#0b0d11'},primary:{display:'inline-block',padding:'12px 18px',borderRadius:11,background:'#d7b45a',color:'#111',fontWeight:900,textDecoration:'none'},error:{color:'#ffaaaa'}};
