'use client';

import { useCallback, useEffect, useState } from 'react';
import { PortalShell } from '@/components/portal-shell';
import { apiRequest, getSessionUser } from '@/lib/api';

type TeamMember={id:string;email:string;firstName?:string|null;lastName?:string|null;role:string};
type Settings={organizationId:string;enabled:boolean;senderName:string;replyTo:string|null;assignedUserId:string|null;maxEmailsPer7Days:number;timezone:string;sendWindowStartHour:number;sendWindowEndHour:number;consentVersion:string;team:TeamMember[]};
type Scenario={id:string;code:string;name:string;enabled:boolean;segment:string;scheduleHours:number[];subjectTemplate:string;bodyTemplate:string;ctaLabel:string;ctaPath:string};
type Summary={clients:{total:number;consented:number;unsubscribed:number};deliveries30Days:{sent:number;failed:number;queued:number};activeJourneys:number};

export default function EmailingPage(){
  const[settings,setSettings]=useState<Settings|null>(null);const[scenarios,setScenarios]=useState<Scenario[]>([]);const[summary,setSummary]=useState<Summary|null>(null);const[message,setMessage]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const isOwner=getSessionUser()?.role==='OWNER';
  const load=useCallback(async()=>{setError('');try{const[s,c,m]=await Promise.all([apiRequest<Settings>('/marketing/email/settings'),apiRequest<Scenario[]>('/marketing/email/scenarios'),apiRequest<Summary>('/marketing/email/summary')]);setSettings(s);setScenarios(c);setSummary(m);}catch(e){setError(e instanceof Error?e.message:'E-mailing indisponible');}},[]);useEffect(()=>{void load();},[load]);
  async function saveSettings(){if(!settings)return;setBusy(true);setError('');try{await apiRequest('/marketing/email/settings',{method:'PATCH',body:JSON.stringify(settings)});setMessage('✓ Paramètres e-mail enregistrés.');await load();}catch(e){setError(e instanceof Error?e.message:'Enregistrement impossible');}finally{setBusy(false);}}
  function patchScenario(code:string,patch:Partial<Scenario>){setScenarios((current)=>current.map((item)=>item.code===code?{...item,...patch}:item));}
  async function saveScenario(s:Scenario){setBusy(true);setError('');try{await apiRequest(`/marketing/email/scenarios/${encodeURIComponent(s.code)}`,{method:'PATCH',body:JSON.stringify({enabled:s.enabled,scheduleHours:s.scheduleHours,subjectTemplate:s.subjectTemplate,bodyTemplate:s.bodyTemplate,ctaLabel:s.ctaLabel,ctaPath:s.ctaPath})});setMessage(`✓ Scénario « ${s.name} » enregistré.`);await load();}catch(e){setError(e instanceof Error?e.message:'Scénario impossible à enregistrer');}finally{setBusy(false);}}
  if(!settings)return <PortalShell><div className="portal-error-state"><div className="eyebrow">E-MAILING KHE BOOTH</div><h2>Chargement de l’automatisation</h2><p>{error||'Chargement…'}</p></div></PortalShell>;
  return <PortalShell>
    <div className="page-header"><div><div className="eyebrow">MARKETING • E-MAILING AUTOMATIQUE</div><h1>Relances, nurturing et historique</h1><p className="muted">KHE BOOTH collecte les coordonnées depuis le site et les profils synchronisés. Les e-mails promotionnels ne partent que lorsqu’un consentement marketing est enregistré.</p></div><button className="button secondary" type="button" onClick={()=>void load()}>↻ Actualiser</button></div>
    {error?<div className="error">{error}</div>:null}{message?<div className="success">{message}</div>:null}
    {summary?<div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',marginBottom:18}}>{[['Clients CRM',summary.clients.total],['Consentements actifs',summary.clients.consented],['Désabonnés',summary.clients.unsubscribed],['E-mails envoyés · 30 j',summary.deliveries30Days.sent],['Échecs · 30 j',summary.deliveries30Days.failed],['Parcours actifs',summary.activeJourneys]].map(([label,value])=><div className="card" key={String(label)}><div className="eyebrow">{label}</div><div style={{fontSize:28,fontWeight:900,marginTop:8}}>{value}</div></div>)}</div>:null}
    <section className="card" style={{marginBottom:18}}><div className="portal-section-title"><div className="eyebrow">PARAMÈTRES GÉNÉRAUX</div><h2>Automatisation e-mail</h2><p>Le OWNER définit la fréquence, la plage horaire et le membre chargé du suivi.</p></div><div className="grid two"><label>Automatisation<select disabled={!isOwner} value={settings.enabled?'on':'off'} onChange={(e)=>setSettings({...settings,enabled:e.target.value==='on'})}><option value="on">Activée</option><option value="off">Désactivée</option></select></label><label>Membre assigné<select disabled={!isOwner} value={settings.assignedUserId||''} onChange={(e)=>setSettings({...settings,assignedUserId:e.target.value||null})}><option value="">Non assigné</option>{settings.team.map((member)=><option key={member.id} value={member.id}>{[member.firstName,member.lastName].filter(Boolean).join(' ')||member.email} · {member.role}</option>)}</select></label><label>Nom expéditeur<input disabled={!isOwner} value={settings.senderName} onChange={(e)=>setSettings({...settings,senderName:e.target.value})}/></label><label>Reply-To<input disabled={!isOwner} type="email" value={settings.replyTo||''} onChange={(e)=>setSettings({...settings,replyTo:e.target.value||null})}/></label><label>Maximum d’e-mails / 7 jours<input disabled={!isOwner} type="number" min={1} max={10} value={settings.maxEmailsPer7Days} onChange={(e)=>setSettings({...settings,maxEmailsPer7Days:Number(e.target.value)})}/></label><label>Fuseau horaire<input disabled={!isOwner} value={settings.timezone} onChange={(e)=>setSettings({...settings,timezone:e.target.value})}/></label><label>Début des envois<input disabled={!isOwner} type="number" min={0} max={23} value={settings.sendWindowStartHour} onChange={(e)=>setSettings({...settings,sendWindowStartHour:Number(e.target.value)})}/></label><label>Fin des envois<input disabled={!isOwner} type="number" min={1} max={24} value={settings.sendWindowEndHour} onChange={(e)=>setSettings({...settings,sendWindowEndHour:Number(e.target.value)})}/></label></div>{isOwner?<button className="button" disabled={busy} onClick={()=>void saveSettings()}>{busy?'Enregistrement…':'Enregistrer les paramètres'}</button>:<p className="muted">Seul le OWNER peut modifier les paramètres généraux et l’assignation.</p>}</section>
    <div className="portal-section-title"><div className="eyebrow">SCÉNARIOS AUTOMATIQUES</div><h2>Messages qui poussent à l’action</h2><p>Les délais sont exprimés en heures après le déclencheur. Panier : 1 h, 24 h, 72 h par défaut.</p></div>
    <div className="grid two">{scenarios.map((scenario)=><section className="card" key={scenario.code}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><div><div className="eyebrow">{scenario.code}</div><h3>{scenario.name}</h3></div><label><input type="checkbox" checked={scenario.enabled} onChange={(e)=>patchScenario(scenario.code,{enabled:e.target.checked})}/> Actif</label></div><label>Délais d’envoi (heures)<input value={scenario.scheduleHours.join(', ')} onChange={(e)=>patchScenario(scenario.code,{scheduleHours:e.target.value.split(',').map((v)=>Number(v.trim())).filter((v)=>Number.isFinite(v)&&v>0)})}/></label><label>Sujet<input value={scenario.subjectTemplate} onChange={(e)=>patchScenario(scenario.code,{subjectTemplate:e.target.value})}/></label><label>Message<textarea rows={6} value={scenario.bodyTemplate} onChange={(e)=>patchScenario(scenario.code,{bodyTemplate:e.target.value})}/></label><div className="grid two"><label>Bouton CTA<input value={scenario.ctaLabel} onChange={(e)=>patchScenario(scenario.code,{ctaLabel:e.target.value})}/></label><label>Lien interne<input value={scenario.ctaPath} onChange={(e)=>patchScenario(scenario.code,{ctaPath:e.target.value})}/></label></div><p className="muted" style={{fontSize:12}}>Variables disponibles : <code>{'{{name}}'}</code> et <code>{'{{plan}}'}</code>.</p><button className="button secondary" disabled={busy} onClick={()=>void saveScenario(scenario)}>Enregistrer ce scénario</button></section>)}</div>
  </PortalShell>;
}
