'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { PortalShell } from '@/components/portal-shell';
import { apiRequest } from '@/lib/api';

type Proposal={id:string;status:string;horizonDays:number;forecastTimezone:string;startsAt:string;endsAt:string;sampleSize:number;requiredAgentSlots:number;proposedAgentSlots:number;uncoveredAgentSlots:number;coveragePct:number;note?:string|null;optimizerVersion:string;approvedAt?:string|null;appliedAt?:string|null;rejectedAt?:string|null;createdAt:string;updatedAt:string};
type Agent={id:string;email:string;firstName?:string|null;lastName?:string|null;name:string;role:string;skills:string[];languages:string[]};
type Shift={id:string;proposalId:string;userId:string;startsAt:string;endsAt:string;enabled:boolean;score:number;reason:string;languages:string[];skills:string[];slotCount:number;plannedMinutes:number;agentEmail:string;agentFirstName?:string|null;agentLastName?:string|null;agentName:string};
type Detail={proposal:Proposal;shifts:Shift[];agents:Agent[]};
type ProposalList=Proposal&{enabledShifts:number};

function localInput(value:string){const d=new Date(value);if(!Number.isFinite(d.getTime()))return'';const offset=d.getTimezoneOffset();return new Date(d.getTime()-offset*60000).toISOString().slice(0,16);}
function iso(value:string){const d=new Date(value);return Number.isFinite(d.getTime())?d.toISOString():'';}
function when(value:string,zone:string){return new Date(value).toLocaleString('fr-CH',{timeZone:zone,weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});}
function statusLabel(value:string){return({DRAFT:'Brouillon',APPROVED:'Validé',APPLIED:'Appliqué',REJECTED:'Rejeté',EXPIRED:'Remplacé'} as Record<string,string>)[value]??value;}
function statusColor(value:string){return value==='APPLIED'?'#78d59c':value==='APPROVED'?'#85b8ff':value==='DRAFT'?'#f5c76b':value==='REJECTED'?'#ff9aa4':'#9ba7b4';}

export default function WorkforceOptimizerPage(){
  const[items,setItems]=useState<ProposalList[]>([]);const[detail,setDetail]=useState<Detail|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[message,setMessage]=useState('');const[days,setDays]=useState(7);const[maxHours,setMaxHours]=useState(8);const[note,setNote]=useState('');
  const loadList=useCallback(async(selectLatest=true)=>{setLoading(true);try{const list=await apiRequest<ProposalList[]>('/operations/workforce/optimizer/proposals');setItems(list);if(selectLatest&&list[0]){const next=await apiRequest<Detail>(`/operations/workforce/optimizer/proposals/${list[0].id}`);setDetail(next);}else if(!list.length)setDetail(null);setMessage('');}catch(e){setMessage(e instanceof Error?e.message:'Impossible de charger le planificateur KHE.');}finally{setLoading(false);}},[]);
  useEffect(()=>{void loadList();},[loadList]);
  const selected=detail?.proposal;
  const enabled=useMemo(()=>detail?.shifts.filter(s=>s.enabled)??[],[detail]);
  const hours=useMemo(()=>enabled.reduce((n,s)=>n+s.plannedMinutes,0)/60,[enabled]);

  async function open(id:string){setLoading(true);try{setDetail(await apiRequest<Detail>(`/operations/workforce/optimizer/proposals/${id}`));setMessage('');}catch(e){setMessage(e instanceof Error?e.message:'Impossible de charger la proposition.');}finally{setLoading(false);}}
  async function generate(){setSaving(true);try{const next=await apiRequest<Detail>('/operations/workforce/optimizer/proposals',{method:'POST',body:JSON.stringify({days,maxHoursPerAgentDay:maxHours,note})});setDetail(next);setMessage('✓ KHE a généré un nouveau brouillon. Aucun shift réel n’a encore été créé.');await loadList(false);}catch(e){setMessage(e instanceof Error?e.message:'Génération impossible');}finally{setSaving(false);}}
  function patchLocal(id:string,patch:Partial<Shift>){setDetail(current=>current?{...current,shifts:current.shifts.map(s=>s.id===id?{...s,...patch}:s)}:current);}
  async function saveShift(shift:Shift){if(!detail)return;setSaving(true);try{const next=await apiRequest<Detail>(`/operations/workforce/optimizer/proposals/${detail.proposal.id}/shifts/${shift.id}`,{method:'PATCH',body:JSON.stringify({agentId:shift.userId,startsAt:shift.startsAt,endsAt:shift.endsAt,enabled:shift.enabled})});setDetail(next);setMessage('✓ Proposition mise à jour.');await loadList(false);}catch(e){setMessage(e instanceof Error?e.message:'Modification impossible');}finally{setSaving(false);}}
  async function action(name:'approve'|'reopen'|'apply'|'reject'){if(!detail)return;setSaving(true);try{const next=await apiRequest<Detail>(`/operations/workforce/optimizer/proposals/${detail.proposal.id}/${name}`,{method:'POST'});setDetail(next);setMessage(name==='approve'?'✓ Planning validé. Il n’est toujours pas appliqué.':name==='apply'?'✓ Planning appliqué : les shifts sélectionnés sont maintenant réels.':name==='reopen'?'✓ Planning rouvert en brouillon.':'✓ Proposition rejetée.');await loadList(false);}catch(e){setMessage(e instanceof Error?e.message:'Action impossible');}finally{setSaving(false);}}

  return <PortalShell><div className="page-header"><div><div className="eyebrow">KHE • WORKFORCE OPTIMIZER</div><h1>Planning optimal proposé par KHE</h1><p className="muted">KHE transforme les prévisions d’effectifs en propositions de shifts. Vous gardez le contrôle : génération → modification → validation → application.</p><div style={{display:'flex',gap:12,flexWrap:'wrap',marginTop:8}}><Link href="/operations/workforce">← Workforce Intelligence</Link><Link href="/operations/routing">Routing & SLA</Link></div></div><button className="button secondary" onClick={()=>void loadList(false)}>{loading?'Chargement…':'↻ Actualiser'}</button></div>
  {message?<p className={message.startsWith('✓')?'success':'error'}>{message}</p>:null}
  <section className="card" style={{border:'1px solid rgba(210,173,79,.45)',marginBottom:16}}><div className="eyebrow">GARDE-FOU OWNER</div><h2>Aucune modification automatique du planning</h2><p>KHE peut calculer et préremplir le meilleur planning, mais <strong>aucun shift n’est créé</strong> tant qu’un OWNER/ADMIN n’a pas validé la proposition puis cliqué séparément sur <strong>Appliquer au planning</strong>.</p></section>
  <div className="grid two" style={{alignItems:'start'}}><section className="card"><div className="eyebrow">NOUVELLE PROPOSITION</div><h2>Générer avec KHE</h2><label>Horizon<select className="input" value={days} onChange={e=>setDays(Number(e.target.value))}><option value={1}>24 heures</option><option value={3}>3 jours</option><option value={7}>7 jours</option><option value={14}>14 jours</option></select></label><label>Maximum proposé par agent / jour<select className="input" value={maxHours} onChange={e=>setMaxHours(Number(e.target.value))}>{[4,6,8,10,12].map(h=><option key={h} value={h}>{h} h</option>)}</select></label><label>Note<input className="input" value={note} onChange={e=>setNote(e.target.value)} placeholder="Ex. semaine événement / haute saison"/></label><button className="button" disabled={saving} onClick={()=>void generate()}>{saving?'Calcul…':'Générer le planning optimal'}</button></section><section className="card"><div className="eyebrow">HISTORIQUE</div><h2>Propositions récentes</h2>{items.length?items.slice(0,10).map(p=><button key={p.id} className="button secondary" style={{width:'100%',textAlign:'left',marginBottom:7,borderColor:detail?.proposal.id===p.id?'#d2ad4f':undefined}} onClick={()=>void open(p.id)}><strong style={{color:statusColor(p.status)}}>{statusLabel(p.status)}</strong> · {new Date(p.createdAt).toLocaleString('fr-CH')}<br/><span className="muted" style={{fontSize:11}}>{p.coveragePct}% couverture · {p.enabledShifts} shift(s)</span></button>):<p className="muted">Aucune proposition enregistrée.</p>}</section></div>
  {!detail?null:<><section className="card" style={{marginTop:16}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'flex-start',flexWrap:'wrap'}}><div><div className="eyebrow">PROPOSITION ACTIVE</div><h2 style={{marginBottom:4}}>Planning {detail.proposal.horizonDays} jour(s)</h2><div style={{fontWeight:900,color:statusColor(detail.proposal.status)}}>{statusLabel(detail.proposal.status)}</div></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{detail.proposal.status==='DRAFT'?<><button className="button" disabled={saving} onClick={()=>void action('approve')}>Valider le planning</button><button className="button secondary" disabled={saving} onClick={()=>void action('reject')}>Rejeter</button></>:null}{detail.proposal.status==='APPROVED'?<><button className="button" disabled={saving} onClick={()=>void action('apply')}>Appliquer au planning</button><button className="button secondary" disabled={saving} onClick={()=>void action('reopen')}>Modifier encore</button><button className="button secondary" disabled={saving} onClick={()=>void action('reject')}>Rejeter</button></>:null}</div></div><div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(145px,1fr))',marginTop:16}}>{[['Couverture',`${detail.proposal.coveragePct}%`],['Besoin à couvrir',detail.proposal.requiredAgentSlots],['Créneaux couverts',detail.proposal.proposedAgentSlots],['Reste non couvert',detail.proposal.uncoveredAgentSlots],['Shifts sélectionnés',enabled.length],['Heures proposées',hours.toFixed(1)],['Échantillon',detail.proposal.sampleSize]].map(([label,value])=><div key={String(label)} style={{padding:10,border:'1px solid #29313b',borderRadius:12}}><div className="eyebrow">{label}</div><div style={{fontSize:22,fontWeight:950,marginTop:6}}>{value}</div></div>)}</div>{detail.proposal.uncoveredAgentSlots>0?<p style={{color:'#f5c76b',fontWeight:800,marginTop:12}}>⚠ KHE n’a pas trouvé assez de capacité compatible pour couvrir {detail.proposal.uncoveredAgentSlots} créneau(x)-agent. Vous pouvez ajouter ou modifier des shifts avant validation.</p>:<p className="success" style={{marginTop:12}}>✓ La proposition couvre le déficit prévu sur l’horizon calculé.</p>}</section>
    <section className="card" style={{marginTop:16}}><div className="eyebrow">SHIFTS PROPOSÉS</div><h2>Contrôler et modifier avant validation</h2>{detail.shifts.length?<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:1150}}><thead><tr>{['Actif','Agent','Début','Fin','Durée','Langues','Compétences','Score','Raison',''].map(h=><th key={h} style={{textAlign:'left',padding:8,borderBottom:'1px solid #303945'}}>{h}</th>)}</tr></thead><tbody>{detail.shifts.map(s=><tr key={s.id} style={{opacity:s.enabled?1:.55}}><td style={{padding:8}}><input type="checkbox" disabled={detail.proposal.status!=='DRAFT'} checked={s.enabled} onChange={e=>patchLocal(s.id,{enabled:e.target.checked})}/></td><td style={{padding:8}}><select className="input" disabled={detail.proposal.status!=='DRAFT'} value={s.userId} onChange={e=>patchLocal(s.id,{userId:e.target.value})}>{detail.agents.map(a=><option key={a.id} value={a.id}>{a.name} · {a.role} · {a.languages.join('/')}</option>)}</select></td><td style={{padding:8}}><input className="input" type="datetime-local" disabled={detail.proposal.status!=='DRAFT'} value={localInput(s.startsAt)} onChange={e=>patchLocal(s.id,{startsAt:iso(e.target.value)})}/></td><td style={{padding:8}}><input className="input" type="datetime-local" disabled={detail.proposal.status!=='DRAFT'} value={localInput(s.endsAt)} onChange={e=>patchLocal(s.id,{endsAt:iso(e.target.value)})}/></td><td style={{padding:8}}>{(s.plannedMinutes/60).toFixed(1)} h</td><td style={{padding:8}}>{s.languages.join(', ')||'—'}</td><td style={{padding:8}}>{s.skills.join(', ')||'Général'}</td><td style={{padding:8,fontWeight:900}}>{s.score}</td><td style={{padding:8,fontSize:11}}>{s.reason}</td><td style={{padding:8}}>{detail.proposal.status==='DRAFT'?<button className="button secondary" disabled={saving} onClick={()=>void saveShift(s)}>Enregistrer</button>:null}</td></tr>)}</tbody></table></div>:<p className="muted">KHE n’a proposé aucun shift supplémentaire : soit la couverture est déjà suffisante, soit aucun agent admissible n’est disponible dans les contraintes sélectionnées.</p>}</section>
    <section className="card" style={{marginTop:16}}><div className="eyebrow">PÉRIODE CALCULÉE</div><p>{when(detail.proposal.startsAt,detail.proposal.forecastTimezone)} → {when(detail.proposal.endsAt,detail.proposal.forecastTimezone)} · fuseau {detail.proposal.forecastTimezone}</p><p className="muted">Version moteur : {detail.proposal.optimizerVersion}. Une proposition validée peut être rouverte avant application. Si le planning réel change entre validation et application, KHE bloque l’application en cas de conflit et demande une nouvelle vérification.</p></section></>}
  </PortalShell>;
}
