'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { PortalShell } from '@/components/portal-shell';
import { apiRequest } from '@/lib/api';

type Item={id:string;status:string;conversationId:string;subject:string;priority:string;routingTopic:string;requestedLanguage:string;lastMessageAt:string;suggestedAgentName?:string|null;selectedAgentName?:string|null;reason?:string|null;agentNote?:string|null;managerNote?:string|null};
type Batch={id:string;status:string;trigger:string;openConversationCount:number;shiftStartsAt:string;shiftEndsAt:string;preparedAt:string;items:Item[]};
type Mine={summary:{batches:number;pending:number;applied:number};batches:Batch[]};
function when(value:string){return new Date(value).toLocaleString('fr-CH',{weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});}
function statusLabel(v:string){return v==='APPLIED'?'Transféré':v==='SKIPPED'?'Conservé':v==='STALE'?'Déjà traité':'À valider';}

export default function MyHandoverPage(){
  const[data,setData]=useState<Mine|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState('');const[message,setMessage]=useState('');const[notes,setNotes]=useState<Record<string,string>>({});
  const load=useCallback(async(quiet=false)=>{if(!quiet)setLoading(true);try{setData(await apiRequest<Mine>('/operations/workforce/handover/me'));if(!quiet)setMessage('');}catch(e){if(!quiet)setMessage(e instanceof Error?e.message:'Passage de relais indisponible');}finally{if(!quiet)setLoading(false);}},[]);
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(true),30000);return()=>window.clearInterval(timer);},[load]);
  async function saveNote(item:Item){setBusy(item.id);try{const value=notes[item.id]??item.agentNote??'';await apiRequest(`/operations/workforce/handover/items/${item.id}/note`,{method:'PATCH',body:JSON.stringify({note:value})});setMessage('✓ Note de relais enregistrée.');await load(true);}catch(e){setMessage(e instanceof Error?e.message:'Note impossible à enregistrer');}finally{setBusy('');}}
  return <PortalShell><div className="page-header"><div><div className="eyebrow">KHE • SHIFT HANDOVER</div><h1>Mes passages de relais</h1><p className="muted">Après votre fin de shift, KHE prépare les conversations encore ouvertes. Vous pouvez ajouter un contexte opérationnel ; seul un OWNER/ADMIN valide le transfert vers un autre agent.</p><div style={{display:'flex',gap:12,flexWrap:'wrap',marginTop:8}}><Link href="/operations/workforce/live">← Live Shift</Link><Link href="/operations/workforce/me">Mon planning</Link><Link href="/help">Support</Link></div></div><button className="button secondary" onClick={()=>void load()}>{loading?'Chargement…':'↻ Actualiser'}</button></div>
  {message?<p className={message.startsWith('✓')?'success':'error'}>{message}</p>:null}
  {!data?null:<><div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',marginBottom:16}}>{[['Relais récents',data.summary.batches],['À valider',data.summary.pending],['Transférés',data.summary.applied]].map(([label,value])=><div className="card" key={String(label)}><div className="eyebrow">{label}</div><div style={{fontSize:28,fontWeight:950,marginTop:8}}>{value}</div></div>)}</div>
  {data.batches.length?data.batches.map(batch=><section className="card" key={batch.id} style={{marginBottom:16}}><div style={{display:'flex',justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><div><div className="eyebrow">SHIFT TERMINÉ</div><h2 style={{marginBottom:4}}>{when(batch.shiftStartsAt)} → {when(batch.shiftEndsAt)}</h2><div className="muted" style={{fontSize:11}}>{batch.openConversationCount} conversation(s) · {batch.status}</div></div></div>{batch.items.length?batch.items.map(item=><div key={item.id} style={{padding:'14px 0',borderBottom:'1px solid #27303a'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><strong>{item.subject}</strong><div className="muted" style={{fontSize:11,marginTop:3}}>{item.priority} · {item.routingTopic} · {item.requestedLanguage} · dernière activité {when(item.lastMessageAt)}</div></div><span style={{fontWeight:900,color:item.status==='APPLIED'?'#78d59c':item.status==='PENDING'?'#f5c76b':'#9aa5b1'}}>{statusLabel(item.status)}</span></div>{item.status==='PENDING'?<><div className="muted" style={{fontSize:11,marginTop:7}}>Suggestion actuelle : <strong>{item.suggestedAgentName||'aucun agent actif disponible'}</strong>{item.reason?` · ${item.reason}`:''}</div><textarea className="input" rows={2} value={notes[item.id]??item.agentNote??''} onChange={e=>setNotes({...notes,[item.id]:e.target.value})} placeholder="Contexte opérationnel utile au prochain agent" style={{marginTop:9}}/><div className="muted" style={{fontSize:10,marginTop:4}}>N’inscrivez pas de donnée médicale, familiale ou autre information sensible. La note n’entre pas dans le classement des agents.</div><button className="button secondary" disabled={busy===item.id} onClick={()=>void saveNote(item)} style={{marginTop:8}}>{busy===item.id?'Enregistrement…':'Enregistrer la note'}</button></>:<div className="muted" style={{fontSize:11,marginTop:7}}>{item.status==='APPLIED'?`Repris par ${item.selectedAgentName||'un autre agent'}`:'Aucun transfert appliqué'}{item.agentNote?` · Note : ${item.agentNote}`:''}</div>}</div>):<p className="muted">Aucune conversation n’était ouverte à la fin de ce shift.</p>}</section>):<section className="card"><p className="muted">Aucun passage de relais récent.</p></section>}</>}
  </PortalShell>;
}
