'use client';

import { FormEvent, useEffect, useState } from 'react';
import { PortalShell } from '@/components/portal-shell';
import { apiRequest } from '@/lib/api';

type Client={id:string;name:string;firstName?:string;lastName?:string;email?:string|null;subscriptionPlan?:string;subscriptionStatus?:string;paymentStatus?:string};

export default function CommunicationsPage(){
  const [clients,setClients]=useState<Client[]>([]);const [clientId,setClientId]=useState('');const [kind,setKind]=useState('MANUAL');const [title,setTitle]=useState('');const [body,setBody]=useState('');const [actionUrl,setActionUrl]=useState('');const [emailRequested,setEmailRequested]=useState(true);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  useEffect(()=>{apiRequest<Client[]>('/clients').then((items)=>{setClients(items);if(items[0])setClientId(items[0].id);}).catch((e)=>setMessage(e instanceof Error?e.message:'Chargement impossible'));},[]);
  async function submit(event:FormEvent){event.preventDefault();if(!clientId)return;setBusy(true);setMessage('Envoi…');try{await apiRequest(`/commerce/admin/clients/${clientId}/messages`,{method:'POST',body:JSON.stringify({kind,title,body,actionUrl:actionUrl||null,emailRequested})});setMessage('✓ Message enregistré dans KHE Booth et e-mail demandé selon les préférences du client.');setTitle('');setBody('');setActionUrl('');}catch(e){setMessage(e instanceof Error?e.message:'Envoi impossible');}finally{setBusy(false);}}
  const selected=clients.find((client)=>client.id===clientId);
  return <PortalShell><div className="page-header"><div><div className="eyebrow">AUTOMATISATION & MANUEL</div><h1>Communications clients</h1><p className="muted">L’automatisation KHE continue de gérer mises à jour, maintenance, paiement et incitations. Utilisez cette page uniquement lorsque vous souhaitez ajouter un message vous-même.</p></div></div><div className="grid two"><form className="card" onSubmit={submit} style={{display:'grid',gap:14}}><label>Client<select value={clientId} onChange={(e)=>setClientId(e.target.value)}>{clients.map((client)=><option key={client.id} value={client.id}>{[client.firstName,client.lastName].filter(Boolean).join(' ')||client.name} · {client.email||'sans e-mail'}</option>)}</select></label><label>Type<select value={kind} onChange={(e)=>setKind(e.target.value)}><option value="MANUAL">Information</option><option value="PROMO">Promotion</option><option value="UPDATE">Mise à jour</option><option value="MAINTENANCE">Maintenance</option><option value="PAYMENT">Paiement</option><option value="SUBSCRIPTION">Abonnement</option></select></label><label>Titre<input required value={title} onChange={(e)=>setTitle(e.target.value)}/></label><label>Message<textarea required rows={7} value={body} onChange={(e)=>setBody(e.target.value)}/></label><label>Lien d’action facultatif<input value={actionUrl} onChange={(e)=>setActionUrl(e.target.value)} placeholder="https://…"/></label><label><input type="checkbox" checked={emailRequested} onChange={(e)=>setEmailRequested(e.target.checked)}/> Envoyer aussi par e-mail si le canal e-mail est configuré et autorisé</label><button className="button" disabled={busy||!clientId}>{busy?'Envoi…':'Envoyer le message'}</button>{message?<p>{message}</p>:null}</form><section className="card"><h2>Client sélectionné</h2>{selected?<><p><strong>{[selected.firstName,selected.lastName].filter(Boolean).join(' ')||selected.name}</strong></p><p>{selected.email||'E-mail non renseigné'}</p><div className="subscription-editor"><div className="eyebrow">ABONNEMENT</div><p>Niveau : <strong>{selected.subscriptionPlan||'DISCOVERY'}</strong></p><p>Statut : <strong>{selected.subscriptionStatus||'PROSPECT'}</strong></p><p>Paiement : <strong>{selected.paymentStatus||'UNPAID'}</strong></p></div></>:<p>Aucun client.</p>}<hr/><h3>Messages gérés automatiquement</h3><ul><li>Activation et KHE ID après paiement</li><li>Paiement échoué / à régulariser</li><li>Incitation à évoluer depuis Découverte</li><li>Nouvelle version de l’application</li><li>Maintenance ou indisponibilité temporaire</li><li>Fin ou réactivation d’abonnement</li></ul></section></div></PortalShell>;
}
