'use client';

import Link from 'next/link';
import { useCallback,useEffect,useMemo,useState } from 'react';
import { PortalShell } from '@/components/portal-shell';
import { apiRequest } from '@/lib/api';

type BriefItem={id:string;conversationId:string;subject:string;conversationStatus:string;priority:string;routingTopic:string;requestedLanguage:string;lastMessageAt:string;riskLevel:string;nextSlaDueAt?:string|null;suggestedUserId?:string|null;suggestedAgentName?:string|null;score?:number|null;reason?:string|null;agentNote?:string|null};
type Brief={id:string;status:string;agentName:string;shiftStartsAt:string;shiftEndsAt:string;openConversationCount:number;urgentSlaCount:number;missingNoteCount:number;candidateCoverageCount:number;incomingAgentCount:number;preparedAt:string;lastRefreshedAt:string;items:BriefItem[]};
type Data={summary:{briefs:number;open:number;urgent:number;missingNotes:number};briefs:Brief[]};
function when(v?:string|null){return v?new Date(v).toLocaleString('fr-CH',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';}
function riskLabel(v:string){return v==='OVERDUE'?'SLA dépassé':v==='URGENT'?'Urgent':v==='WATCH'?'À surveiller':'Normal';}
function riskColor(v:string){return v==='OVERDUE'?'#ff6b78':v==='URGENT'?'#ff9aa4':v==='WATCH'?'#f5c76b':'#78d59c';}
export default function ShiftBriefPage(){
  const[data,setData]=useState<Data|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState('');const[message,setMessage]=useState('');const[notes,setNotes]=useState<Record<string,string>>({});
  const load=useCallback(async(quiet=false)=>{if(!quiet)setLoading(true);try{const d=await apiRequest<Data>('/operations/workforce/brief/me');setData(d);const next:Record<string,string>={};d.briefs.forEach(b=>b.items.forEach(i=>next[i.id]=i.agentNote??''));setNotes(next);if(!quiet)setMessage('');}catch(e){if(!quiet)setMessage(e instanceof Error?e.message:'Brief indisponible');}finally{if(!quiet)setLoading(false);}},[]);
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(true),30000);return()=>window.clearInterval(timer);},[load]);
  const current=useMemo(()=>data?.briefs.find(b=>['OPEN','READY'].includes(b.status))??data?.briefs[0]??null,[data]);
  async function refresh(){setBusy('refresh');try{await apiRequest('/operations/workforce/brief/refresh',{method:'POST'});setMessage('✓ Brief actualisé.');await load(true);}catch(e){setMessage(e instanceof Error?e.message:'Le brief ne peut pas encore être préparé');}finally{setBusy('');}}
  async function saveNote(id:string){setBusy(id);try{await apiRequest(`/operations/workforce/brief/items/${id}/note`,{method:'PATCH',body:JSON.stringify({note:notes[id]??''})});setMessage('✓ Note de relais enregistrée.');await load(true);}catch(e){setMessage(e instanceof Error?e.message:'Enregistrement impossible');}finally{setBusy('');}}
  return <PortalShell><div className="page-header"><div><div className="eyebrow">KHE • SHIFT BRIEF</div><h1>Préparer ma fin de shift</h1><p className="muted">KHE rassemble les conversations encore ouvertes, les risques SLA et la couverture du prochain shift. Rien n’est transféré ici : vous préparez seulement le contexte pour le relais.</p><div style={{display:'flex',gap:12,flexWrap:'wrap',marginTop:8}}><Link href="/operations/workforce/live">← Live Shift</Link><Link href="/operations/workforce/handover/me">Relais après shift</Link><Link href="/help">Messagerie</Link></div></div><button className="button secondary" disabled={busy==='refresh'} onClick={()=>void refresh()}>{busy==='refresh'?'Actualisation…':'↻ Actualiser le brief'}</button></div>
  {message?<p className={message.startsWith('✓')?'success':'error'}>{message}</p>:null}
  {!data?null:<><div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',marginBottom:16}}>{[['Briefs actifs',data.summary.open],['SLA urgents',data.summary.urgent],['Notes manquantes',data.summary.missingNotes],['Briefs récents',data.summary.briefs]].map(([label,value])=><div className="card" key={String(label)}><div className="eyebrow">{label}</div><div style={{fontSize:28,fontWeight:950,marginTop:8}}>{value}</div></div>)}</div>
  {!current?<section className="card"><h2>Aucun brief actif</h2><p className="muted">Le brief apparaît automatiquement dans la fenêtre configurée avant la fin d’un shift actif.</p></section>:<><section className="card" style={{marginBottom:16}}><div className="eyebrow">COUVERTURE DE SORTIE</div><h2>{when(current.shiftStartsAt)} → {when(current.shiftEndsAt)}</h2><div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))'}}>{[['Conversations ouvertes',current.openConversationCount],['SLA urgents',current.urgentSlaCount],['Notes manquantes',current.missingNoteCount],['Conversations couvertes',`${current.candidateCoverageCount}/${current.openConversationCount}`],['Agents entrants',current.incomingAgentCount]].map(([label,value])=><div key={String(label)}><div className="muted" style={{fontSize:11}}>{label}</div><strong style={{fontSize:20}}>{value}</strong></div>)}</div><p className="muted" style={{fontSize:11,marginTop:10}}>Dernière analyse : {when(current.lastRefreshedAt)}. Les suggestions sont indicatives et seront revalidées après la fin du shift avant tout transfert.</p></section>
  <section className="card"><div className="eyebrow">CONVERSATIONS À PRÉPARER</div><h2>Priorités avant la sortie</h2>{current.items.length?current.items.map(i=><div key={i.id} style={{padding:'14px 0',borderBottom:'1px solid #27303a'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><strong>{i.subject}</strong><div className="muted" style={{fontSize:11,marginTop:3}}>{i.priority} · {i.routingTopic} · {i.requestedLanguage} · dernier message {when(i.lastMessageAt)}</div></div><span style={{fontWeight:900,color:riskColor(i.riskLevel)}}>{riskLabel(i.riskLevel)}</span></div>{i.nextSlaDueAt?<div style={{fontSize:12,marginTop:6}}>Échéance SLA : <strong>{when(i.nextSlaDueAt)}</strong></div>:null}<div style={{fontSize:12,marginTop:6}}><strong>Relève pressentie :</strong> {i.suggestedAgentName??'Aucune relève confirmée'}{i.reason?<span className="muted"> · {i.reason}</span>:null}</div><textarea className="input" rows={3} value={notes[i.id]??''} onChange={e=>setNotes({...notes,[i.id]:e.target.value})} placeholder="Contexte utile pour le prochain agent : action en cours, prochaine étape, point à vérifier…" style={{marginTop:10}}/><div className="muted" style={{fontSize:10,marginTop:4}}>N’inscrivez pas de données médicales, familiales ou personnelles sensibles. Cette note n’est pas utilisée pour évaluer votre performance.</div><button className="button secondary" style={{marginTop:8}} disabled={busy===i.id} onClick={()=>void saveNote(i.id)}>{busy===i.id?'Enregistrement…':'Enregistrer la note'}</button></div>):<p className="muted">Aucune conversation ouverte à préparer.</p>}</section></>}
  </>}
  </PortalShell>;
}
