import { BadRequestException, ForbiddenException, Injectable, NotFoundException, ServiceUnavailableException } from '@nestjs/common';
import { createHash, randomBytes } from 'node:crypto';
import { head, issueSignedToken, presignUrl } from '@vercel/blob';
import { PrismaService } from '../prisma/prisma.service';

const CONTRACT_TOKEN_TTL_MS=15*60*1000;
const MAX_MANUAL_CONTRACT_BYTES=20*1024*1024;
const MANUAL_TYPES=new Set(['application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']);
const SUPPORTED_LANGUAGES=new Set(['fr','en','de','it','es','pt','nl','pl','ro','cs','sv','da','fi','el']);
const EU_EEA=new Set(['AT','BE','BG','HR','CY','CZ','DE','DK','EE','ES','FI','FR','GR','HU','IE','IS','IT','LI','LT','LU','LV','MT','NL','NO','PL','PT','RO','SE','SI','SK']);

function sha(value:string){return createHash('sha256').update(value).digest('hex');}
function safe(value:unknown,max=4000){return String(value??'').trim().slice(0,max);}
function cc(value:unknown){return safe(value,2).toUpperCase();}
function canonical(value:unknown){return JSON.stringify(value);}
function language(value:unknown){const normalized=safe(value,5).toLowerCase().split('-')[0];return SUPPORTED_LANGUAGES.has(normalized)?normalized:'en';}
function defaultLanguageForCountry(countryCode:string){
  const code=cc(countryCode);if(code==='FR'||code==='MC')return'fr';if(['DE','AT'].includes(code))return'de';if(code==='IT')return'it';if(code==='ES')return'es';if(['PT','BR'].includes(code))return'pt';if(code==='NL')return'nl';if(code==='PL')return'pl';if(code==='RO')return'ro';if(code==='CZ')return'cs';if(code==='SE')return'sv';if(code==='DK')return'da';if(code==='FI')return'fi';if(code==='GR'||code==='CY')return'el';if(code==='CH')return'fr';return'en';
}
function jurisdiction(countryCode:string){const code=cc(countryCode);if(code==='CH')return'SWITZERLAND';if(EU_EEA.has(code))return'EU_EEA';if(code==='GB')return'UNITED_KINGDOM';if(code==='US')return'UNITED_STATES';if(code==='CA')return'CANADA';return'GLOBAL';}
function extension(contentType:string){if(contentType==='application/pdf')return'pdf';if(contentType.includes('wordprocessingml'))return'docx';if(contentType.includes('spreadsheetml'))return'xlsx';return'bin';}

@Injectable()
export class EnterpriseContractService{
  constructor(private readonly prisma:PrismaService){}

  private async rootOwner(organizationId:string,role:string){const rows=await this.prisma.$queryRaw<Array<{tenantKind:string}>>`SELECT "tenantKind" FROM "Organization" WHERE id=${organizationId}::uuid LIMIT 1`;if(role!=='OWNER'||rows[0]?.tenantKind!=='KHE_ROOT')throw new ForbiddenException('Only the KHE root owner can manage contract templates');}

  private async tokenContext(rawToken:string){
    const tokenHash=sha(safe(rawToken,300));const rows=await this.prisma.$queryRaw<any[]>`
      SELECT t."organizationId",t."clientId",t."expiresAt",t."revokedAt",c.name,c.email,c."subscriptionPlan",c."paymentStatus",
             o."preferredLanguage",o."countryCode",o."desiredUsers",o.status AS "onboardingStatus"
      FROM "EnterpriseOnboardingToken" t
      JOIN "Client" c ON c.id=t."clientId"
      JOIN "EnterpriseOnboarding" o ON o."clientId"=c.id
      WHERE t."tokenHash"=${tokenHash} LIMIT 1`;
    const row=rows[0];if(!row||row.revokedAt||new Date(row.expiresAt).getTime()<Date.now())throw new BadRequestException('Lien Enterprise invalide ou expiré.');
    await this.prisma.$executeRaw`UPDATE "EnterpriseOnboardingToken" SET "lastUsedAt"=CURRENT_TIMESTAMP WHERE "tokenHash"=${tokenHash}`;
    return row;
  }

  private async templateFor(organizationId:string,countryCode:string){
    const code=cc(countryCode);const area=jurisdiction(code);const exact=await this.prisma.$queryRaw<any[]>`
      SELECT * FROM "EnterpriseContractTemplate" WHERE "organizationId"=${organizationId}::uuid AND active=TRUE AND "countryCodes" @> ${JSON.stringify([code])}::jsonb ORDER BY "legalReviewRequired" ASC,version DESC LIMIT 1`;
    if(exact[0])return exact[0];const regional=await this.prisma.$queryRaw<any[]>`
      SELECT * FROM "EnterpriseContractTemplate" WHERE "organizationId"=${organizationId}::uuid AND active=TRUE AND jurisdiction=${area} ORDER BY version DESC LIMIT 1`;
    if(regional[0])return regional[0];const global=await this.prisma.$queryRaw<any[]>`SELECT * FROM "EnterpriseContractTemplate" WHERE "organizationId"=${organizationId}::uuid AND active=TRUE AND code='GLOBAL_ANNUAL' LIMIT 1`;if(!global[0])throw new ServiceUnavailableException('Enterprise contract template is not configured');return global[0];
  }

  private localized(template:any,preferredLanguage:string){
    const lang=language(preferredLanguage||template.defaultLanguage);const translations=template.translations&&typeof template.translations==='object'?template.translations:{};const localized=translations[lang]??translations[template.defaultLanguage]??{};return{language:lang,title:safe(localized.title||template.name,240),sections:Array.isArray(localized.sections)?localized.sections:(Array.isArray(template.sections)?template.sections:[]),translationReviewed:Boolean(localized.sections)||lang===template.defaultLanguage};
  }

  async setPreferredLanguage(token:string,value:string){const context=await this.tokenContext(token);const lang=language(value||defaultLanguageForCountry(context.countryCode));await this.prisma.$executeRaw`UPDATE "EnterpriseOnboarding" SET "preferredLanguage"=${lang},"updatedAt"=CURRENT_TIMESTAMP WHERE "clientId"=${context.clientId}::uuid`;const contracts=await this.prisma.$queryRaw<Array<{id:string;status:string;language:string}>>`SELECT id,status,language FROM "EnterpriseContract" WHERE "clientId"=${context.clientId}::uuid AND status NOT IN ('VOID','SUPERSEDED') ORDER BY "createdAt" DESC LIMIT 1`;const current=contracts[0];if(current&&current.status!=='SIGNED'&&current.language!==lang)await this.prisma.$executeRaw`UPDATE "EnterpriseContract" SET status='SUPERSEDED',"updatedAt"=CURRENT_TIMESTAMP WHERE id=${current.id}::uuid`;return{preferredLanguage:lang};}

  async ensureForClient(organizationId:string,clientId:string){
    const existing=await this.prisma.$queryRaw<any[]>`SELECT * FROM "EnterpriseContract" WHERE "organizationId"=${organizationId}::uuid AND "clientId"=${clientId}::uuid AND status NOT IN ('VOID','SUPERSEDED') ORDER BY "createdAt" DESC LIMIT 1`;
    if(existing[0])return existing[0];
    const clients=await this.prisma.$queryRaw<any[]>`SELECT id,name,email,phone,"companyName","subscriptionPlan","paymentStatus" FROM "Client" WHERE id=${clientId}::uuid AND "organizationId"=${organizationId}::uuid LIMIT 1`;const client=clients[0];if(!client)throw new NotFoundException('Client not found');if(client.subscriptionPlan!=='ENTERPRISE'||client.paymentStatus!=='PAID')throw new BadRequestException('Enterprise payment must be validated before contract generation');
    const onboardingRows=await this.prisma.$queryRaw<any[]>`SELECT * FROM "EnterpriseOnboarding" WHERE "clientId"=${clientId}::uuid LIMIT 1`;const onboarding=onboardingRows[0];if(!onboarding)throw new BadRequestException('Enterprise onboarding is not initialized');
    const profileRows=await this.prisma.$queryRaw<any[]>`SELECT * FROM "ClientProfileSnapshot" WHERE "clientId"=${clientId}::uuid LIMIT 1`;const profile=profileRows[0]??{};
    const quoteRows=await this.prisma.$queryRaw<any[]>`SELECT * FROM "EnterpriseQuote" WHERE "clientId"=${clientId}::uuid AND status IN ('SENT','ACCEPTED') ORDER BY "createdAt" DESC LIMIT 1`;const quote=quoteRows[0];if(!quote)throw new BadRequestException('A sent Enterprise quote is required before contract generation');
    const countryCode=cc(onboarding.countryCode||profile.countryCode);const template=await this.templateFor(organizationId,countryCode);const preferred=language(onboarding.preferredLanguage||defaultLanguageForCountry(countryCode));const localized=this.localized(template,preferred);const annualCents=Number(quote.annualCents||Number(quote.monthlyCents||0)*12);const contractNumber=`KHE-CON-${new Date().getFullYear()}-${randomBytes(4).toString('hex').toUpperCase()}`;
    const snapshot={brand:{name:'KHE BOOTH',legalEntity:'Kurtis Hypnotic Events'},contractNumber,countryCode,jurisdiction:jurisdiction(countryCode),language:localized.language,generatedAt:new Date().toISOString(),termMonths:12,client:{id:client.id,name:client.name,email:client.email,phone:profile.phone||client.phone||'',company:profile.company||client.companyName||'',role:profile.role||'',address:profile.address||'',city:profile.city||'',country:profile.country||'',representativeName:(onboarding.answers||{}).representativeName||profile.displayName||client.name,representativeRole:(onboarding.answers||{}).representativeRole||profile.role||''},quote:{id:quote.id,quoteNumber:quote.quoteNumber,currency:quote.currency,userCount:quote.userCount,annualCents,setupFeeCents:quote.setupFeeCents,discountCents:quote.discountCents,features:quote.features,customItems:quote.customItems,notes:quote.notes,billingCadence:quote.billingCadence||'ANNUAL'},template:{id:template.id,code:template.code,name:template.name,title:localized.title,version:template.version,sections:localized.sections,layout:template.layout,signaturePolicy:template.signaturePolicy,governingLaw:template.governingLaw,venue:template.venue,sourceReferences:template.sourceReferences,legalReviewRequired:template.legalReviewRequired,translationReviewed:localized.translationReviewed}};
    const contentHash=sha(canonical(snapshot));const rows=await this.prisma.$queryRaw<any[]>`
      INSERT INTO "EnterpriseContract" (id,"organizationId","clientId","quoteId","templateId","contractNumber","countryCode",jurisdiction,language,"templateVersion","termMonths",status,"contractSnapshot","contentHash","signaturePolicy")
      VALUES (gen_random_uuid(),${organizationId}::uuid,${clientId}::uuid,${quote.id}::uuid,${template.id}::uuid,${contractNumber},${countryCode},${jurisdiction(countryCode)},${localized.language},${template.version},12,'DRAFT',${JSON.stringify(snapshot)}::jsonb,${contentHash},${template.signaturePolicy}) RETURNING *`;
    return rows[0];
  }

  async publicContract(token:string,preferredLanguage?:string){const context=await this.tokenContext(token);if(preferredLanguage)await this.setPreferredLanguage(token,preferredLanguage);const contract=await this.ensureForClient(context.organizationId,context.clientId);if(contract.status==='DRAFT')await this.prisma.$executeRaw`UPDATE "EnterpriseContract" SET status='VIEWED',"viewedAt"=CURRENT_TIMESTAMP,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${contract.id}::uuid`;return{contract:{...contract,status:contract.status==='DRAFT'?'VIEWED':contract.status},client:{name:context.name,email:context.email},canSignNatively:contract.signaturePolicy==='NATIVE_EVIDENCE',requiresQualifiedProvider:['ADVANCED_REQUIRED','QUALIFIED_REQUIRED'].includes(contract.signaturePolicy)};}

  async signNative(token:string,payload:Record<string,unknown>,requestContext:{ipAddress?:string|null;userAgent?:string|null}={}){
    const context=await this.tokenContext(token);const contract=await this.ensureForClient(context.organizationId,context.clientId);if(contract.status==='SIGNED')return contract;if(contract.signaturePolicy!=='NATIVE_EVIDENCE')throw new BadRequestException('Ce contrat exige un niveau de signature supérieur. Une signature qualifiée/avancée doit être utilisée via un fournisseur approprié.');
    if(payload.acceptContract!==true||payload.authorityConfirmed!==true)throw new BadRequestException('Vous devez accepter le contrat et confirmer votre pouvoir de signature.');const signerName=safe(payload.signerName,200);if(signerName.length<3)throw new BadRequestException('Nom du signataire requis');const method=safe(payload.method,20).toUpperCase();if(!['TYPED','DRAWN'].includes(method))throw new BadRequestException('Méthode de signature non supportée');const signatureMaterial=safe(payload.signatureData,20000);if(method==='DRAWN'&&signatureMaterial.length<20)throw new BadRequestException('Signature dessinée incomplète');const signedAt=new Date();const signatureHash=sha([contract.contentHash,method,signerName,signatureMaterial,signedAt.toISOString(),requestContext.ipAddress||'',requestContext.userAgent||''].join('|'));const evidence={acceptedContract:true,authorityConfirmed:true,signatureDataHash:signatureMaterial?sha(signatureMaterial):null,contentHash:contract.contentHash,signedAt:signedAt.toISOString()};
    const rows=await this.prisma.$queryRaw<any[]>`
      UPDATE "EnterpriseContract" SET status='SIGNED',"signatureMethod"=${method},"signerName"=${signerName},"signerEmail"=${context.email||null},"signerIp"=${requestContext.ipAddress||null},"signerUserAgent"=${requestContext.userAgent||null},"signatureHash"=${signatureHash},"signatureEvidence"=${JSON.stringify(evidence)}::jsonb,"signedAt"=${signedAt},"updatedAt"=CURRENT_TIMESTAMP WHERE id=${contract.id}::uuid RETURNING *`;
    await this.prisma.$executeRaw`UPDATE "EnterpriseQuote" SET status='ACCEPTED',"acceptedAt"=COALESCE("acceptedAt",CURRENT_TIMESTAMP),"updatedAt"=CURRENT_TIMESTAMP WHERE id=${contract.quoteId}::uuid`;
    await this.prisma.auditLog.create({data:{organizationId:context.organizationId,userId:null,action:'ENTERPRISE_CONTRACT_SIGNED',entityType:'Client',entityId:context.clientId,metadata:{contractId:contract.id,contractNumber:contract.contractNumber,signatureMethod:method,signatureHash,contentHash:contract.contentHash,signerName,signerEmail:context.email??null,ipAddress:requestContext.ipAddress??null}}});return rows[0];
  }

  async prepareManualSignedUpload(token:string,payload:Record<string,unknown>){const context=await this.tokenContext(token);const contract=await this.ensureForClient(context.organizationId,context.clientId);if(contract.status==='SIGNED')throw new BadRequestException('Contract already signed');const contentType=safe(payload.contentType,150).toLowerCase();const byteSize=Number(payload.byteSize||0);const originalFileName=safe(payload.originalFileName,260)||`signed-contract.${extension(contentType)}`;if(!MANUAL_TYPES.has(contentType))throw new BadRequestException('Signed contract must be PDF, Word or Excel');if(!Number.isInteger(byteSize)||byteSize<=0||byteSize>MAX_MANUAL_CONTRACT_BYTES)throw new BadRequestException('Signed contract must be 20 MB or less');const pathname=`organizations/${context.organizationId}/enterprise/${context.clientId}/contracts/${contract.id}/manual-${Date.now()}-${randomBytes(4).toString('hex')}.${extension(contentType)}`;const validUntil=Date.now()+CONTRACT_TOKEN_TTL_MS;try{const signed=await issueSignedToken({pathname,operations:['put'],validUntil,maximumSizeInBytes:byteSize,allowedContentTypes:[contentType]});const {presignedUrl}=await presignUrl(signed,{access:'private',pathname,operation:'put',validUntil,maximumSizeInBytes:byteSize,allowedContentTypes:[contentType],allowOverwrite:false});return{contractId:contract.id,pathname,uploadUrl:presignedUrl,expiresAt:new Date(validUntil),contentType,byteSize,originalFileName};}catch(error){throw new ServiceUnavailableException(error instanceof Error?error.message:'Contract storage unavailable');}}

  async confirmManualSignedUpload(token:string,payload:Record<string,unknown>,requestContext:{ipAddress?:string|null;userAgent?:string|null}={}){const context=await this.tokenContext(token);const contract=await this.ensureForClient(context.organizationId,context.clientId);const pathname=safe(payload.pathname,1000);const prefix=`organizations/${context.organizationId}/enterprise/${context.clientId}/contracts/${contract.id}/`;if(!pathname.startsWith(prefix))throw new BadRequestException('Invalid contract document path');const blob=await head(pathname);if(!MANUAL_TYPES.has(blob.contentType||'')||blob.size<=0||blob.size>MAX_MANUAL_CONTRACT_BYTES)throw new BadRequestException('Invalid signed contract document');const filename=safe(payload.originalFileName,260)||`signed-contract.${extension(blob.contentType||'')}`;const signedAt=new Date();const signatureHash=sha([contract.contentHash,pathname,String(blob.size),signedAt.toISOString()].join('|'));await this.prisma.$transaction(async tx=>{await tx.$executeRaw`INSERT INTO "EnterpriseContractAttachment" (id,"organizationId","clientId","contractId",kind,pathname,"originalFileName","contentType","byteSize") VALUES (gen_random_uuid(),${context.organizationId}::uuid,${context.clientId}::uuid,${contract.id}::uuid,'SIGNED_MANUAL',${pathname},${filename},${blob.contentType||'application/octet-stream'},${blob.size})`;await tx.$executeRaw`UPDATE "EnterpriseContract" SET status='SIGNED',"signatureMethod"='MANUAL_UPLOAD',"signerName"=${safe(payload.signerName,200)||context.name},"signerEmail"=${context.email||null},"signerIp"=${requestContext.ipAddress||null},"signerUserAgent"=${requestContext.userAgent||null},"signatureHash"=${signatureHash},"signatureEvidence"=${JSON.stringify({contentHash:contract.contentHash,manualDocumentPath:pathname,byteSize:blob.size})}::jsonb,"signedAt"=${signedAt},"updatedAt"=CURRENT_TIMESTAMP WHERE id=${contract.id}::uuid`;await tx.$executeRaw`UPDATE "EnterpriseQuote" SET status='ACCEPTED',"acceptedAt"=COALESCE("acceptedAt",CURRENT_TIMESTAMP),"updatedAt"=CURRENT_TIMESTAMP WHERE id=${contract.quoteId}::uuid`;});await this.prisma.auditLog.create({data:{organizationId:context.organizationId,userId:null,action:'ENTERPRISE_CONTRACT_SIGNED_MANUALLY',entityType:'Client',entityId:context.clientId,metadata:{contractId:contract.id,contractNumber:contract.contractNumber,signatureHash,pathname}}});return this.publicContract(token);}

  async adminContracts(organizationId:string,role:string,clientId:string){if(!['OWNER','ADMIN'].includes(role))throw new ForbiddenException('KHE staff access required');const clients=await this.prisma.$queryRaw<any[]>`SELECT id FROM "Client" WHERE id=${clientId}::uuid AND "organizationId"=${organizationId}::uuid LIMIT 1`;if(!clients[0])throw new NotFoundException('Client not found');return this.prisma.$queryRaw<any[]>`SELECT * FROM "EnterpriseContract" WHERE "clientId"=${clientId}::uuid ORDER BY "createdAt" DESC`;}

  async templates(organizationId:string,role:string){await this.rootOwner(organizationId,role);return this.prisma.$queryRaw<any[]>`SELECT * FROM "EnterpriseContractTemplate" WHERE "organizationId"=${organizationId}::uuid ORDER BY jurisdiction,code,version DESC`;}

  async updateTemplate(organizationId:string,userId:string,role:string,id:string,payload:Record<string,unknown>){await this.rootOwner(organizationId,role);const name=safe(payload.name,200);const sections=Array.isArray(payload.sections)?payload.sections:[];const translations=payload.translations&&typeof payload.translations==='object'?payload.translations:{};const layout=payload.layout&&typeof payload.layout==='object'?payload.layout:{};const signaturePolicy=safe(payload.signaturePolicy,40).toUpperCase();if(!name||sections.length===0||!['NATIVE_EVIDENCE','ADVANCED_REQUIRED','QUALIFIED_REQUIRED','MANUAL_SIGNATURE'].includes(signaturePolicy))throw new BadRequestException('Invalid contract template');const rows=await this.prisma.$queryRaw<any[]>`UPDATE "EnterpriseContractTemplate" SET name=${name},sections=${JSON.stringify(sections)}::jsonb,translations=${JSON.stringify(translations)}::jsonb,layout=${JSON.stringify(layout)}::jsonb,"signaturePolicy"=${signaturePolicy},"governingLaw"=${safe(payload.governingLaw,1000)},venue=${safe(payload.venue,1000)},"sourceReferences"=${JSON.stringify(Array.isArray(payload.sourceReferences)?payload.sourceReferences:[])}::jsonb,"legalReviewRequired"=${payload.legalReviewRequired===true},active=${payload.active!==false},version=version+1,"updatedByUserId"=${userId}::uuid,"updatedAt"=CURRENT_TIMESTAMP WHERE id=${id}::uuid AND "organizationId"=${organizationId}::uuid RETURNING *`;if(!rows[0])throw new NotFoundException('Contract template not found');await this.prisma.auditLog.create({data:{organizationId,userId,action:'ENTERPRISE_CONTRACT_TEMPLATE_UPDATED',entityType:'EnterpriseContractTemplate',entityId:id,metadata:{version:rows[0].version,signaturePolicy}}});return rows[0];}

  async signedForAccess(organizationId:string,clientId:string){const rows=await this.prisma.$queryRaw<Array<{id:string;contractNumber:string;signedAt:Date|null;status:string}>>`SELECT id,"contractNumber","signedAt",status FROM "EnterpriseContract" WHERE "organizationId"=${organizationId}::uuid AND "clientId"=${clientId}::uuid AND status='SIGNED' ORDER BY "signedAt" DESC LIMIT 1`;return rows[0]??null;}
}
