import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { AlignmentType, BorderStyle, Document, HeadingLevel, Packer, Paragraph, Table, TableCell, TableRow, TextRun, WidthType } from 'docx';
import { PrismaService } from '../prisma/prisma.service';
import { EnterpriseContractService } from './enterprise-contract.service';

type ExcelModule=typeof import('@excel.js/exceljs');
const nativeImport=new Function('specifier','return import(specifier)') as (specifier:string)=>Promise<ExcelModule>;

function plain(value:unknown){return String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7E]/g,'?');}
function esc(value:string){return plain(value).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');}
function money(cents:number,currency:string){try{return new Intl.NumberFormat('fr-CH',{style:'currency',currency}).format(cents/100);}catch{return`${(cents/100).toFixed(2)} ${currency}`;}}
function snapshot(row:any){return row.contractSnapshot&&typeof row.contractSnapshot==='object'?row.contractSnapshot:{};}
function commitmentMonths(row:any,s:any){return Number(row.termMonths||s.termMonths||s.quote?.contractTermMonths||12);}

function buildPdf(lines:string[]):Buffer{
  const perPage=38;const pages:Array<string[]>=[];for(let i=0;i<lines.length;i+=perPage)pages.push(lines.slice(i,i+perPage));if(!pages.length)pages.push(['KHE BOOTH']);const pageCount=pages.length;const fontNormal=3+pageCount*2;const fontBold=fontNormal+1;const objects=new Map<number,string>();objects.set(1,'<< /Type /Catalog /Pages 2 0 R >>');objects.set(2,`<< /Type /Pages /Count ${pageCount} /Kids [${pages.map((_,i)=>`${3+i*2} 0 R`).join(' ')}] >>`);
  pages.forEach((pageLines,index)=>{const pageId=3+index*2;const contentId=pageId+1;const body:string[]=['BT','/F2 17 Tf','0.70 0.52 0.12 rg','48 800 Td','(KHE BOOTH) Tj','0 0 0 rg','/F1 10 Tf','0 -25 Td'];pageLines.forEach((line,i)=>{if(i>0)body.push('0 -17 Td');const bold=/^(CONTRAT|CLIENT|OFFRE|SIGNATURE|[0-9]+\.)/.test(plain(line).toUpperCase());body.push(bold?'/F2 10 Tf':'/F1 10 Tf');body.push(`(${esc(line)}) Tj`);});body.push('/F1 8 Tf','0 -30 Td',`(Page ${index+1}/${pageCount} - KHE BOOTH Enterprise) Tj`,'ET');const stream=body.join('\n');objects.set(pageId,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${fontNormal} 0 R /F2 ${fontBold} 0 R >> >> /Contents ${contentId} 0 R >>`);objects.set(contentId,`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`);});objects.set(fontNormal,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');objects.set(fontBold,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>');let output='%PDF-1.4\n';const offsets:number[]=[0];for(let id=1;id<=fontBold;id++){offsets[id]=Buffer.byteLength(output);output+=`${id} 0 obj\n${objects.get(id)}\nendobj\n`;}const xref=Buffer.byteLength(output);output+=`xref\n0 ${fontBold+1}\n0000000000 65535 f \n`;for(let id=1;id<=fontBold;id++)output+=`${String(offsets[id]).padStart(10,'0')} 00000 n \n`;output+=`trailer\n<< /Size ${fontBold+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(output,'ascii');
}

@Injectable()
export class EnterpriseContractExportService{
  constructor(private readonly prisma:PrismaService,private readonly contracts:EnterpriseContractService){}

  private async publicModel(token:string){const data=await this.contracts.publicContract(token);return data.contract;}
  private async adminModel(organizationId:string,role:string,clientId:string,contractId:string){if(!['OWNER','ADMIN'].includes(role))throw new ForbiddenException('KHE staff access required');const rows=await this.prisma.$queryRaw<any[]>`SELECT c.* FROM "EnterpriseContract" c JOIN "Client" cl ON cl.id=c."clientId" WHERE c.id=${contractId}::uuid AND c."clientId"=${clientId}::uuid AND c."organizationId"=${organizationId}::uuid AND cl."organizationId"=${organizationId}::uuid LIMIT 1`;if(!rows[0])throw new NotFoundException('Contract not found');return rows[0];}

  async publicExport(token:string,format:string){return this.generate(await this.publicModel(token),format);}
  async adminExport(organizationId:string,role:string,clientId:string,contractId:string,format:string){return this.generate(await this.adminModel(organizationId,role,clientId,contractId),format);}

  private async generate(row:any,format:string){const normalized=format.toLowerCase();if(!['pdf','docx','xlsx'].includes(normalized))throw new BadRequestException('Unsupported contract export format');const filename=`${String(row.contractNumber||'KHE-CONTRACT').replace(/[^A-Za-z0-9_-]/g,'-')}${row.status==='SIGNED'?'-signed':''}`;if(normalized==='pdf')return{buffer:this.pdf(row),contentType:'application/pdf',filename:`${filename}.pdf`};if(normalized==='docx')return{buffer:await this.docx(row),contentType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',filename:`${filename}.docx`};return{buffer:await this.xlsx(row),contentType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',filename:`${filename}.xlsx`};}

  private lines(row:any){const s=snapshot(row);const client=s.client??{};const quote=s.quote??{};const template=s.template??{};const months=commitmentMonths(row,s);const sections=Array.isArray(template.sections)?template.sections:[];const lines=[String(template.title||template.name||'KHE BOOTH Enterprise Agreement'),'',`Contract: ${row.contractNumber}`,`Language: ${row.language||s.language||''}`,`Jurisdiction: ${row.jurisdiction||s.jurisdiction||''}`,'',`CLIENT: ${client.company||client.name||''}`,`Representative: ${client.representativeName||client.name||''}${client.representativeRole?` - ${client.representativeRole}`:''}`,`E-mail: ${client.email||''}`,`Address: ${[client.address,client.city,client.country].filter(Boolean).join(', ')}`,'',`OFFRE: ${quote.quoteNumber||''}`,`Users: ${quote.userCount||''}`,`Annual fee: ${money(Number(quote.annualCents||0),quote.currency||'CHF')}`,`Setup fee: ${money(Number(quote.setupFeeCents||0),quote.currency||'CHF')}`,`Commitment term: ${months} months`,''];for(const section of sections){lines.push(String(section.title||section.key||''),String(section.body||''),'');}lines.push('SIGNATURE',`Status: ${row.status}`,`Method: ${row.signatureMethod||'Not signed'}`,`Signer: ${row.signerName||''}`,`Signed at: ${row.signedAt?new Date(row.signedAt).toISOString():''}`,`Contract content hash: ${row.contentHash}`,`Signature evidence hash: ${row.signatureHash||''}`,'','KHE BOOTH / Kurtis Hypnotic Events');return lines;}

  private pdf(row:any){return buildPdf(this.lines(row));}

  private async docx(row:any){const s=snapshot(row);const client=s.client??{};const quote=s.quote??{};const template=s.template??{};const months=commitmentMonths(row,s);const sections=Array.isArray(template.sections)?template.sections:[];const border={style:BorderStyle.SINGLE,size:4,color:'D7B55B'};const infoRows=[['Contrat',row.contractNumber],['Client',client.company||client.name],['Représentant',client.representativeName||client.name],['E-mail',client.email],['Pays',client.country||row.countryCode],['Langue',row.language],['Durée',`${months} mois`],['Utilisateurs',String(quote.userCount||'')],['Montant annuel',money(Number(quote.annualCents||0),quote.currency||'CHF')],['Mise en place',money(Number(quote.setupFeeCents||0),quote.currency||'CHF')]].map(([a,b])=>new TableRow({children:[new TableCell({borders:{top:border,bottom:border,left:border,right:border},children:[new Paragraph({children:[new TextRun({text:String(a),bold:true})]})]}),new TableCell({borders:{top:border,bottom:border,left:border,right:border},children:[new Paragraph(String(b||''))]})]}));const children=[new Paragraph({children:[new TextRun({text:'KHE BOOTH',bold:true,size:36})],alignment:AlignmentType.CENTER}),new Paragraph({text:String(template.title||template.name||'Enterprise Agreement'),heading:HeadingLevel.TITLE,alignment:AlignmentType.CENTER}),new Paragraph({text:'Kurtis Hypnotic Events',alignment:AlignmentType.CENTER}),new Paragraph(''),new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:infoRows}),new Paragraph(''),...sections.flatMap((section:any)=>[new Paragraph({text:String(section.title||section.key||''),heading:HeadingLevel.HEADING_2}),new Paragraph(String(section.body||''))]),new Paragraph({text:'Signature',heading:HeadingLevel.HEADING_2}),new Paragraph(`Statut : ${row.status}`),new Paragraph(`Méthode : ${row.signatureMethod||'Non signé'}`),new Paragraph(`Signataire : ${row.signerName||''}`),new Paragraph(`Date : ${row.signedAt?new Date(row.signedAt).toLocaleString('fr-CH'):''}`),new Paragraph(`Empreinte du contrat : ${row.contentHash}`),new Paragraph(`Empreinte de signature : ${row.signatureHash||''}`),new Paragraph({text:'KHE BOOTH • Kurtis Hypnotic Events • Contrat Enterprise',alignment:AlignmentType.CENTER})];const document=new Document({sections:[{children}]});return Buffer.from(await Packer.toBuffer(document));}

  private async xlsx(row:any){const s=snapshot(row);const client=s.client??{};const quote=s.quote??{};const template=s.template??{};const months=commitmentMonths(row,s);const ExcelJS=await nativeImport('@excel.js/exceljs');const workbook=new ExcelJS.Workbook();workbook.creator='KHE Booth';workbook.company='Kurtis Hypnotic Events';const cover=workbook.addWorksheet('Contrat');cover.columns=[{width:32},{width:75}];cover.addRow(['KHE BOOTH','ENTERPRISE']);cover.getRow(1).font={bold:true,size:18};[['Contrat',row.contractNumber],['Client',client.company||client.name],['Représentant',client.representativeName||client.name],['E-mail',client.email],['Pays',client.country||row.countryCode],['Langue',row.language],['Durée',`${months} mois`],['Utilisateurs',quote.userCount],['Montant annuel',money(Number(quote.annualCents||0),quote.currency||'CHF')],['Mise en place',money(Number(quote.setupFeeCents||0),quote.currency||'CHF')],['Statut',row.status],['Méthode signature',row.signatureMethod||''],['Signataire',row.signerName||''],['Date signature',row.signedAt?new Date(row.signedAt).toISOString():''],['Hash contrat',row.contentHash],['Hash signature',row.signatureHash||'']].forEach(values=>cover.addRow(values));const clauses=workbook.addWorksheet('Clauses');clauses.columns=[{header:'Section',key:'section',width:38},{header:'Texte contractuel',key:'body',width:100}];clauses.getRow(1).font={bold:true};(Array.isArray(template.sections)?template.sections:[]).forEach((section:any)=>clauses.addRow({section:String(section.title||section.key||''),body:String(section.body||'')}));const trace=workbook.addWorksheet('Preuve signature');trace.columns=[{width:32},{width:100}];[['Contract content hash',row.contentHash],['Signature hash',row.signatureHash||''],['Signature method',row.signatureMethod||''],['Signer',row.signerName||''],['Signer e-mail',row.signerEmail||''],['Signed at',row.signedAt?new Date(row.signedAt).toISOString():'' ],['Evidence',JSON.stringify(row.signatureEvidence||{})]].forEach(values=>trace.addRow(values));return Buffer.from(await workbook.xlsx.writeBuffer());}
}
