import { BadRequestException, ForbiddenException, Injectable, NotFoundException, ServiceUnavailableException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

@Injectable()
export class EnterpriseQuoteCheckoutService{
  constructor(private readonly prisma:PrismaService){}

  private async ensureRoot(organizationId:string,role:string){const rows=await this.prisma.$queryRaw<Array<{tenantKind:string}>>`SELECT "tenantKind" FROM "Organization" WHERE id=${organizationId}::uuid LIMIT 1`;if(!['OWNER','ADMIN'].includes(role)||rows[0]?.tenantKind!=='KHE_ROOT')throw new ForbiddenException('KHE root access required');}

  async send(organizationId:string,userId:string,role:string,clientId:string,quoteId:string){
    await this.ensureRoot(organizationId,role);
    const clients=await this.prisma.$queryRaw<Array<{id:string;name:string;email:string|null}>>`SELECT id,name,email FROM "Client" WHERE id=${clientId}::uuid AND "organizationId"=${organizationId}::uuid LIMIT 1`;
    const client=clients[0];if(!client)throw new NotFoundException('Client not found');if(!client.email)throw new BadRequestException('Client email is required');
    const quotes=await this.prisma.$queryRaw<Array<{id:string;quoteNumber:string;currency:string;userCount:number;monthlyCents:number;annualCents:number;contractTermMonths:number;billingCadence:string;totalContractCents:number;setupFeeCents:number;discountCents:number;status:string;validUntil:Date|null}>>`
      SELECT id,"quoteNumber",currency,"userCount","monthlyCents","annualCents","contractTermMonths","billingCadence","totalContractCents","setupFeeCents","discountCents",status,"validUntil" FROM "EnterpriseQuote" WHERE id=${quoteId}::uuid AND "clientId"=${clientId}::uuid AND "organizationId"=${organizationId}::uuid LIMIT 1`;
    const quote=quotes[0];if(!quote)throw new NotFoundException('Enterprise quote not found');if(!['DRAFT','SENT'].includes(quote.status))throw new BadRequestException('Only a draft or sent quote can be checked out');if(quote.validUntil&&new Date(quote.validUntil).getTime()<Date.now())throw new BadRequestException('This Enterprise quote is expired');
    if(![12,24,36,48,60].includes(Number(quote.contractTermMonths)))throw new BadRequestException('Invalid Enterprise commitment term');
    const annual=Math.max(0,Number(quote.annualCents||quote.monthlyCents*12));const firstAnnualInvoice=Math.max(0,annual-Math.min(Math.max(0,quote.discountCents),annual));if(firstAnnualInvoice<=0)throw new BadRequestException('A positive annual amount is required before sending the payment link');
    const secret=process.env.STRIPE_SECRET_KEY?.trim();if(!secret)throw new ServiceUnavailableException('Stripe is not configured');
    const origin=(process.env.WEB_ORIGIN||'https://khebooth.vercel.app').split(',')[0].trim().replace(/\/$/,'');const params=new URLSearchParams();
    params.set('mode','subscription');params.set('success_url',`${origin}/subscribe/success?session_id={CHECKOUT_SESSION_ID}`);params.set('cancel_url',`${origin}/enterprise`);params.set('customer_email',client.email);params.append('payment_method_types[]','card');params.set('billing_address_collection','required');params.set('tax_id_collection[enabled]','true');params.set('automatic_tax[enabled]','true');
    const meta:Record<string,string>={clientId:client.id,planCode:'ENTERPRISE',quoteId:quote.id,quoteNumber:quote.quoteNumber,amountCents:String(firstAnnualInvoice+Math.max(0,quote.setupFeeCents)),annualCents:String(annual),contractTermMonths:String(quote.contractTermMonths),billingCadence:'ANNUAL',totalContractCents:String(quote.totalContractCents||annual*(quote.contractTermMonths/12)+quote.setupFeeCents-quote.discountCents),currency:quote.currency};
    for(const [key,value] of Object.entries(meta)){params.set(`metadata[${key}]`,value);params.set(`subscription_data[metadata][${key}]`,value);}
    params.set('line_items[0][quantity]','1');params.set('line_items[0][price_data][currency]',quote.currency.toLowerCase());params.set('line_items[0][price_data][unit_amount]',String(firstAnnualInvoice));params.set('line_items[0][price_data][recurring][interval]','year');params.set('line_items[0][price_data][recurring][interval_count]','1');params.set('line_items[0][price_data][product_data][name]',`KHE BOOTH Enterprise · ${quote.quoteNumber} · engagement ${quote.contractTermMonths} mois · ${quote.userCount} utilisateur(s)`);
    if(quote.setupFeeCents>0){params.set('line_items[1][quantity]','1');params.set('line_items[1][price_data][currency]',quote.currency.toLowerCase());params.set('line_items[1][price_data][unit_amount]',String(quote.setupFeeCents));params.set('line_items[1][price_data][product_data][name]','KHE BOOTH Enterprise · Mise en place');}
    const response=await fetch('https://api.stripe.com/v1/checkout/sessions',{method:'POST',headers:{Authorization:`Bearer ${secret}`,'Content-Type':'application/x-www-form-urlencoded'},body:params.toString()});const data=await response.json() as{id?:string;url?:string;error?:{message?:string}};if(!response.ok||!data.url)throw new ServiceUnavailableException(data.error?.message||'Unable to create Enterprise checkout');
    await this.prisma.$transaction(async tx=>{await tx.$executeRaw`UPDATE "EnterpriseQuote" SET status='SENT',"billingCadence"='ANNUAL',"updatedAt"=CURRENT_TIMESTAMP WHERE id=${quote.id}::uuid`;await tx.$executeRaw`UPDATE "Client" SET "subscriptionPlan"='ENTERPRISE',"subscriptionStatus"='PAYMENT_PENDING',"paymentStatus"='PENDING',"updatedAt"=CURRENT_TIMESTAMP WHERE id=${client.id}::uuid`;await tx.auditLog.create({data:{organizationId,userId,action:'ENTERPRISE_QUOTE_SENT',entityType:'Client',entityId:client.id,metadata:{quoteId:quote.id,quoteNumber:quote.quoteNumber,userCount:quote.userCount,annualCents:annual,monthlyEquivalentCents:quote.monthlyCents,contractTermMonths:quote.contractTermMonths,totalContractCents:quote.totalContractCents,setupFeeCents:quote.setupFeeCents,currency:quote.currency,checkoutSessionId:data.id}}});});
    await this.sendEmail(client.email,client.name,quote.quoteNumber,data.url,annual,quote.setupFeeCents,quote.currency,quote.userCount,quote.contractTermMonths,quote.totalContractCents||annual*(quote.contractTermMonths/12)+quote.setupFeeCents-quote.discountCents);
    return{sent:true,quoteNumber:quote.quoteNumber,checkoutUrl:data.url,sessionId:data.id,billingCadence:'ANNUAL',contractTermMonths:quote.contractTermMonths};
  }

  private async sendEmail(to:string,name:string,quoteNumber:string,url:string,annual:number,setup:number,currency:string,userCount:number,termMonths:number,totalContract:number){const key=process.env.RESEND_API_KEY?.trim();const from=process.env.KHE_EMAIL_FROM?.trim();if(!key||!from)return;const money=(amount:number)=>new Intl.NumberFormat('fr-CH',{style:'currency',currency}).format(amount/100);const monthlyEquivalent=Math.round(annual/12);await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({from,to:[to],subject:`Votre devis Enterprise KHE BOOTH ${quoteNumber}`,html:`<div style="font-family:Arial,sans-serif;max-width:640px;margin:auto"><h2 style="color:#b58a27">KHE BOOTH Enterprise</h2><p>Bonjour ${name},</p><p>Votre devis <strong>${quoteNumber}</strong> est prêt pour ${userCount} utilisateur(s).</p><p>Engagement : <strong>${termMonths} mois</strong><br/>Facturation : <strong>${money(annual)}/an</strong> (équivalent indicatif ${money(monthlyEquivalent)}/mois)<br/>Valeur contractuelle : <strong>${money(totalContract)}</strong>${setup>0?`<br/>Mise en place incluse dans le devis : <strong>${money(setup)}</strong>`:''}</p><p><a href="${url}" style="display:inline-block;background:#111;color:#fff;padding:13px 20px;border-radius:10px;text-decoration:none">Consulter et payer de manière sécurisée</a></p><p style="font-size:12px;color:#666">Après validation du paiement, KHE BOOTH vous transmettra le dossier Enterprise. La signature du contrat par le client est obligatoire avant tout accès à la plateforme.</p></div>`})});}
}
