import { BadRequestException, Injectable } from '@nestjs/common';
import { AlignmentType, Document, HeadingLevel, Packer, Paragraph, Table, TableCell, TableRow, TextRun, WidthType } from 'docx';
import { EnterpriseOnboardingService } from './enterprise-onboarding.service';

type ExcelModule=typeof import('@excel.js/exceljs');
const nativeImport=new Function('specifier','return import(specifier)') as (specifier:string)=>Promise<ExcelModule>;

function plain(value:unknown){return String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7E]/g,'?');}
function pdfEscape(value:string){return plain(value).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');}
function buildPdf(lines:string[]):Buffer{
  const perPage=42;const pages:Array<string[]>=[];for(let i=0;i<lines.length;i+=perPage)pages.push(lines.slice(i,i+perPage));if(!pages.length)pages.push(['KHE BOOTH ENTERPRISE']);
  const pageCount=pages.length;const fontId=3+pageCount*2;const objects=new Map<number,string>();
  objects.set(1,'<< /Type /Catalog /Pages 2 0 R >>');
  const kids=pages.map((_,i)=>`${3+i*2} 0 R`).join(' ');objects.set(2,`<< /Type /Pages /Count ${pageCount} /Kids [${kids}] >>`);
  pages.forEach((pageLines,i)=>{const pageId=3+i*2;const contentId=pageId+1;const stream=['BT','/F1 11 Tf','48 795 Td',...pageLines.flatMap((line,index)=>index===0?[`(${pdfEscape(line)}) Tj`]:['0 -17 Td',`(${pdfEscape(line)}) Tj`]),'ET'].join('\n');objects.set(pageId,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${fontId} 0 R >> >> /Contents ${contentId} 0 R >>`);objects.set(contentId,`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`);});
  objects.set(fontId,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');
  let output='%PDF-1.4\n';const offsets:number[]=[0];for(let id=1;id<=fontId;id++){offsets[id]=Buffer.byteLength(output);output+=`${id} 0 obj\n${objects.get(id)}\nendobj\n`;}
  const xref=Buffer.byteLength(output);output+=`xref\n0 ${fontId+1}\n0000000000 65535 f \n`;for(let id=1;id<=fontId;id++)output+=`${String(offsets[id]).padStart(10,'0')} 00000 n \n`;output+=`trailer\n<< /Size ${fontId+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(output,'ascii');
}

@Injectable()
export class EnterpriseFormExportService{
  constructor(private readonly onboarding:EnterpriseOnboardingService){}

  private async model(token:string){const data=await this.onboarding.publicForm(token);const fields=Array.isArray(data.template.fields)?data.template.fields as Array<Record<string,unknown>>:[];const answers=(data.onboarding.answers&&typeof data.onboarding.answers==='object'?data.onboarding.answers:{}) as Record<string,unknown>;return{data,fields,answers};}

  async generate(token:string,format:string){const normalized=format.toLowerCase();if(!['pdf','docx','xlsx'].includes(normalized))throw new BadRequestException('Unsupported form export format');const model=await this.model(token);const base=`khe-enterprise-${model.data.onboarding.countryCode||'international'}-${new Date().toISOString().slice(0,10)}`;if(normalized==='pdf')return{buffer:this.pdf(model),contentType:'application/pdf',filename:`${base}.pdf`};if(normalized==='docx')return{buffer:await this.docx(model),contentType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',filename:`${base}.docx`};return{buffer:await this.xlsx(model),contentType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',filename:`${base}.xlsx`};}

  private pdf(model:Awaited<ReturnType<EnterpriseFormExportService['model']>>){const {data,fields,answers}=model;const lines=[`KHE BOOTH ENTERPRISE - ${data.template.name}`,'',`Client: ${data.client.name}`,`E-mail: ${data.client.email||''}`,`Pays: ${data.onboarding.countryCode||'A completer'}`,`Utilisateurs prevus: ${data.onboarding.desiredUsers}`,'','FORMULAIRE'];for(const field of fields){const key=String(field.key??'');const label=String(field.label??key);lines.push('',`${label}:`,String(answers[key]??'________________________________________'));}lines.push('','CONFIDENTIALITE',data.template.privacyNotice,'','Pieces a remettre via le portail securise: piece identite/passeport valide + preuve de domicile.','Validation finale: agent KHE puis OWNER KHE BOOTH.');return buildPdf(lines);}

  private async docx(model:Awaited<ReturnType<EnterpriseFormExportService['model']>>){const {data,fields,answers}=model;const rows=fields.map((field)=>{const key=String(field.key??'');return new TableRow({children:[new TableCell({children:[new Paragraph({children:[new TextRun({text:String(field.label??key),bold:true})]})]}),new TableCell({children:[new Paragraph(String(answers[key]??''))]})]});});const document=new Document({sections:[{children:[new Paragraph({text:'KHE BOOTH',heading:HeadingLevel.TITLE,alignment:AlignmentType.CENTER}),new Paragraph({text:data.template.name,heading:HeadingLevel.HEADING_1,alignment:AlignmentType.CENTER}),new Paragraph(`Client : ${data.client.name}`),new Paragraph(`E-mail : ${data.client.email||''}`),new Paragraph(`Pays : ${data.onboarding.countryCode||'À compléter'}`),new Paragraph(`Nombre d’utilisateurs prévu : ${data.onboarding.desiredUsers}`),new Paragraph({text:'Informations Enterprise',heading:HeadingLevel.HEADING_2}),new Table({width:{size:100,type:WidthType.PERCENTAGE},rows}),new Paragraph({text:'Confidentialité et vérification',heading:HeadingLevel.HEADING_2}),new Paragraph(data.template.privacyNotice),new Paragraph('Pièces à transmettre via le portail sécurisé KHE Booth : pièce d’identité ou passeport valide et preuve de domicile.'),new Paragraph('Le dossier est revu par un agent KHE puis approuvé par le OWNER avant ouverture de l’accès.'),new Paragraph({text:'Kurtis Hypnotic Events • KHE Booth • Document confidentiel',alignment:AlignmentType.CENTER})]}]});return Buffer.from(await Packer.toBuffer(document));}

  private async xlsx(model:Awaited<ReturnType<EnterpriseFormExportService['model']>>){const {data,fields,answers}=model;const ExcelJS=await nativeImport('@excel.js/exceljs');const workbook=new ExcelJS.Workbook();workbook.creator='KHE Booth';workbook.company='Kurtis Hypnotic Events';const sheet=workbook.addWorksheet('Formulaire Enterprise',{views:[{state:'frozen',ySplit:1}]});sheet.columns=[{header:'Champ',key:'field',width:42},{header:'Réponse',key:'value',width:60},{header:'Obligatoire',key:'required',width:16}];sheet.getRow(1).font={bold:true};sheet.addRow({field:'Client',value:data.client.name,required:'—'});sheet.addRow({field:'E-mail',value:data.client.email||'',required:'—'});sheet.addRow({field:'Pays',value:data.onboarding.countryCode||'',required:'Oui'});sheet.addRow({field:'Nombre d’utilisateurs prévu',value:data.onboarding.desiredUsers,required:'Oui'});fields.forEach((field)=>{const key=String(field.key??'');sheet.addRow({field:String(field.label??key),value:String(answers[key]??''),required:field.required===true?'Oui':'Non'});});const privacy=workbook.addWorksheet('Confidentialité');privacy.getColumn(1).width=110;privacy.addRow(['KHE BOOTH Enterprise']);privacy.addRow([data.template.privacyNotice]);privacy.addRow(['Pièces à transmettre via le portail sécurisé : pièce d’identité ou passeport valide + preuve de domicile.']);privacy.addRow(['Validation par agent KHE puis approbation OWNER avant accès plateforme.']);const buffer=await workbook.xlsx.writeBuffer();return Buffer.from(buffer);}
}
