import { BadRequestException, ForbiddenException, Injectable, NotFoundException, ServiceUnavailableException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

@Injectable()
export class EnterpriseQuoteCheckoutService{
  constructor(private readonly prisma:PrismaService){}

  private async ensureRoot(organizationId:string,role:string){const rows=await this.prisma.$queryRaw<Array<{tenantKind:string}>>`SELECT "tenantKind" FROM "Organization" WHERE id=${organizationId}::uuid LIMIT 1`;if(!['OWNER','ADMIN'].includes(role)||rows[0]?.tenantKind!=='KHE_ROOT')throw new ForbiddenException('KHE root access required');}

  async send(organizationId:string,userId:string,role:string,clientId:string,quoteId:string){
    await this.ensureRoot(organizationId,role);
    const clients=await this.prisma.$queryRaw<Array<{id:string;name:string;email:string|null}>>`SELECT id,name,email FROM "Client" WHERE id=${clientId}::uuid AND "organizationId"=${organizationId}::uuid LIMIT 1`;
    const client=clients[0];if(!client)throw new NotFoundException('Client not found');if(!client.email)throw new BadRequestException('Client email is required');
    const quotes=await this.prisma.$queryRaw<Array<{id:string;quoteNumber:string;currency:string;userCount:number;monthlyCents:number;setupFeeCents:number;discountCents:number;status:string;validUntil:Date|null}>>`
      SELECT id,"quoteNumber",currency,"userCount","monthlyCents","setupFeeCents","discountCents",status,"validUntil" FROM "EnterpriseQuote" WHERE id=${quoteId}::uuid AND "clientId"=${clientId}::uuid AND "organizationId"=${organizationId}::uuid LIMIT 1`;
    const quote=quotes[0];if(!quote)throw new NotFoundException('Enterprise quote not found');if(!['DRAFT','SENT'].includes(quote.status))throw new BadRequestException('Only a draft or sent quote can be checked out');if(quote.validUntil&&new Date(quote.validUntil).getTime()<Date.now())throw new BadRequestException('This Enterprise quote is expired');
    const monthly=Math.max(0,quote.monthlyCents-quote.discountCents);if(monthly<=0)throw new BadRequestException('A positive monthly amount is required before sending the payment link');
    const secret=process.env.STRIPE_SECRET_KEY?.trim();if(!secret)throw new ServiceUnavailableException('Stripe is not configured');
    const origin=(process.env.WEB_ORIGIN||'https://khebooth.vercel.app').split(',')[0].trim().replace(/\/$/,'');const params=new URLSearchParams();
    params.set('mode','subscription');params.set('success_url',`${origin}/subscribe/success?session_id={CHECKOUT_SESSION_ID}`);params.set('cancel_url',`${origin}/subscribe?plan=ENTERPRISE`);params.set('customer_email',client.email);params.append('payment_method_types[]','card');
    params.set('metadata[clientId]',client.id);params.set('metadata[planCode]','ENTERPRISE');params.set('metadata[quoteId]',quote.id);params.set('metadata[quoteNumber]',quote.quoteNumber);params.set('metadata[amountCents]',String(monthly+Math.max(0,quote.setupFeeCents)));params.set('metadata[currency]',quote.currency);
    params.set('subscription_data[metadata][clientId]',client.id);params.set('subscription_data[metadata][planCode]','ENTERPRISE');params.set('subscription_data[metadata][quoteId]',quote.id);params.set('subscription_data[metadata][quoteNumber]',quote.quoteNumber);
    params.set('line_items[0][quantity]','1');params.set('line_items[0][price_data][currency]',quote.currency.toLowerCase());params.set('line_items[0][price_data][unit_amount]',String(monthly));params.set('line_items[0][price_data][recurring][interval]','month');params.set('line_items[0][price_data][product_data][name]',`KHE Booth Enterprise · ${quote.quoteNumber} · ${quote.userCount} utilisateur(s)`);
    if(quote.setupFeeCents>0){params.set('line_items[1][quantity]','1');params.set('line_items[1][price_data][currency]',quote.currency.toLowerCase());params.set('line_items[1][price_data][unit_amount]',String(quote.setupFeeCents));params.set('line_items[1][price_data][product_data][name]','KHE Booth Enterprise · Mise en place');}
    const response=await fetch('https://api.stripe.com/v1/checkout/sessions',{method:'POST',headers:{Authorization:`Bearer ${secret}`,'Content-Type':'application/x-www-form-urlencoded'},body:params.toString()});const data=await response.json() as{id?:string;url?:string;error?:{message?:string}};if(!response.ok||!data.url)throw new ServiceUnavailableException(data.error?.message||'Unable to create Enterprise checkout');
    await this.prisma.$transaction(async tx=>{await tx.$executeRaw`UPDATE "EnterpriseQuote" SET status='SENT',"updatedAt"=CURRENT_TIMESTAMP WHERE id=${quote.id}::uuid`;await tx.$executeRaw`UPDATE "Client" SET "subscriptionPlan"='ENTERPRISE',"subscriptionStatus"='PAYMENT_PENDING',"paymentStatus"='PENDING',"updatedAt"=CURRENT_TIMESTAMP WHERE id=${client.id}::uuid`;await tx.auditLog.create({data:{organizationId,userId,action:'ENTERPRISE_QUOTE_SENT',entityType:'Client',entityId:client.id,metadata:{quoteId:quote.id,quoteNumber:quote.quoteNumber,userCount:quote.userCount,monthlyCents:monthly,setupFeeCents:quote.setupFeeCents,currency:quote.currency,checkoutSessionId:data.id}}});});
    await this.sendEmail(client.email,client.name,quote.quoteNumber,data.url,monthly,quote.setupFeeCents,quote.currency,quote.userCount);
    return{sent:true,quoteNumber:quote.quoteNumber,checkoutUrl:data.url,sessionId:data.id};
  }

  private async sendEmail(to:string,name:string,quoteNumber:string,url:string,monthly:number,setup:number,currency:string,userCount:number){const key=process.env.RESEND_API_KEY?.trim();const from=process.env.KHE_EMAIL_FROM?.trim();if(!key||!from)return;const money=(amount:number)=>new Intl.NumberFormat('fr-CH',{style:'currency',currency}).format(amount/100);await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({from,to:[to],subject:`Votre devis Enterprise KHE BOOTH ${quoteNumber}`,html:`<div style="font-family:Arial,sans-serif;max-width:640px;margin:auto"><h2 style="color:#b58a27">KHE BOOTH Enterprise</h2><p>Bonjour ${name},</p><p>Votre devis <strong>${quoteNumber}</strong> est prêt pour ${userCount} utilisateur(s).</p><p>Abonnement : <strong>${money(monthly)}/mois</strong>${setup>0?`<br/>Mise en place : <strong>${money(setup)}</strong>`:''}</p><p><a href="${url}" style="display:inline-block;background:#111;color:#fff;padding:13px 20px;border-radius:10px;text-decoration:none">Consulter et payer de manière sécurisée</a></p><p style="font-size:12px;color:#666">Après validation du paiement, KHE BOOTH vous transmettra automatiquement le formulaire d’identification Enterprise. L’accès plateforme restera soumis à la vérification KHE et à l’approbation finale du OWNER.</p></div>`})});}
}
