import { BadRequestException, ForbiddenException, Injectable, NotFoundException, UnauthorizedException } from '@nestjs/common';
import { createHash } from 'node:crypto';
import { issueSignedToken, presignUrl } from '@vercel/blob';
import { PrismaService } from '../prisma/prisma.service';

const DOWNLOAD_TTL_MS=15*60*1000;
function safe(value:unknown,max=4000){return String(value??'').trim().slice(0,max);}
function hash(value:string){return createHash('sha256').update(value).digest('hex');}

@Injectable()
export class EnterpriseVerificationService{
  constructor(private readonly prisma:PrismaService){}

  private async ensureRoot(organizationId:string){const rows=await this.prisma.$queryRaw<Array<{tenantKind:string}>>`SELECT "tenantKind" FROM "Organization" WHERE id=${organizationId}::uuid LIMIT 1`;if(rows[0]?.tenantKind!=='KHE_ROOT')throw new ForbiddenException('KHE root access required');}

  async documentTicket(organizationId:string,clientId:string,documentId:string){await this.ensureRoot(organizationId);const rows=await this.prisma.$queryRaw<any[]>`SELECT d.pathname,d."deletedAt",d."contentType",d."originalFileName" FROM "EnterpriseVerificationDocument" d JOIN "Client" c ON c.id=d."clientId" WHERE d.id=${documentId}::uuid AND d."clientId"=${clientId}::uuid AND d."organizationId"=${organizationId}::uuid AND c."organizationId"=${organizationId}::uuid LIMIT 1`;const doc=rows[0];if(!doc||doc.deletedAt)throw new NotFoundException('Document not found');const validUntil=Date.now()+DOWNLOAD_TTL_MS;const token=await issueSignedToken({pathname:doc.pathname,operations:['get'],validUntil});const {presignedUrl}=await presignUrl(token,{access:'private',pathname:doc.pathname,operation:'get',validUntil});return{downloadUrl:presignedUrl,expiresAt:new Date(validUntil),contentType:doc.contentType,originalFileName:doc.originalFileName};}

  async reviewDocument(organizationId:string,userId:string,clientId:string,documentId:string,payload:Record<string,unknown>){await this.ensureRoot(organizationId);const decision=safe(payload.decision,20).toUpperCase();if(!['VERIFIED','REJECTED'].includes(decision))throw new BadRequestException('Decision must be VERIFIED or REJECTED');const reason=safe(payload.reason,1200)||null;if(decision==='REJECTED'&&!reason)throw new BadRequestException('A reason is required when rejecting a document');const retentionDeleteAt=decision==='VERIFIED'?new Date(Date.now()+7*24*60*60*1000):null;const rows=await this.prisma.$queryRaw<any[]>`UPDATE "EnterpriseVerificationDocument" SET status=${decision},"verifiedAt"=CASE WHEN ${decision}='VERIFIED' THEN CURRENT_TIMESTAMP ELSE NULL END,"verifiedByUserId"=${userId}::uuid,"rejectionReason"=${reason},"retentionDeleteAt"=${retentionDeleteAt},"updatedAt"=CURRENT_TIMESTAMP WHERE id=${documentId}::uuid AND "clientId"=${clientId}::uuid AND "organizationId"=${organizationId}::uuid AND "documentType" IN ('IDENTITY_CARD','PASSPORT','PROOF_OF_ADDRESS') RETURNING *`;if(!rows[0])throw new NotFoundException('Verification document not found');
    if(decision==='REJECTED')await this.prisma.$executeRaw`UPDATE "EnterpriseOnboarding" SET status='CHANGES_REQUESTED',"reviewNotes"=${reason},"updatedAt"=CURRENT_TIMESTAMP WHERE "clientId"=${clientId}::uuid AND status<>'REJECTED'`;
    await this.prisma.auditLog.create({data:{organizationId,userId,action:`ENTERPRISE_DOCUMENT_HUMAN_${decision}`,entityType:'Client',entityId:clientId,metadata:{documentId,documentType:rows[0].documentType,reason,automaticNextStep:true}}});
    const onboarding=await this.prisma.$queryRaw<any[]>`SELECT status,"reviewNotes","updatedAt" FROM "EnterpriseOnboarding" WHERE "clientId"=${clientId}::uuid LIMIT 1`;return{document:rows[0],onboarding:onboarding[0]??null,automaticApproval:decision==='VERIFIED'&&onboarding[0]?.status==='APPROVED'};
  }

  async queue(organizationId:string){await this.ensureRoot(organizationId);const settings=await this.settings(organizationId);return this.prisma.$queryRaw<any[]>`
    SELECT c.id AS "clientId",c.name,c.email,o.status,o."submittedAt",o."reviewStartedAt",o."desiredUsers",o."updatedAt",
      COUNT(d.id) FILTER (WHERE d."documentType" IN ('IDENTITY_CARD','PASSPORT','PROOF_OF_ADDRESS') AND d.status IN ('RECEIVED','UNDER_REVIEW'))::int AS "pendingDocuments",
      COUNT(d.id) FILTER (WHERE d."documentType" IN ('IDENTITY_CARD','PASSPORT') AND d.status='VERIFIED')::int AS "verifiedIdentity",
      COUNT(d.id) FILTER (WHERE d."documentType"='PROOF_OF_ADDRESS' AND d.status='VERIFIED')::int AS "verifiedAddress",
      EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP-COALESCE(o."reviewStartedAt",o."submittedAt",o."updatedAt")))/3600 AS "waitingHours"
    FROM "Client" c JOIN "EnterpriseOnboarding" o ON o."clientId"=c.id LEFT JOIN "EnterpriseVerificationDocument" d ON d."clientId"=c.id AND d."deletedAt" IS NULL
    WHERE c."organizationId"=${organizationId}::uuid AND c."subscriptionPlan"='ENTERPRISE' AND c."paymentStatus"='PAID' AND o.status IN ('IDENTITY_PENDING','UNDER_REVIEW','CHANGES_REQUESTED','VERIFIED')
    GROUP BY c.id,c.name,c.email,o.status,o."submittedAt",o."reviewStartedAt",o."desiredUsers",o."updatedAt"
    ORDER BY CASE WHEN EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP-COALESCE(o."reviewStartedAt",o."submittedAt",o."updatedAt")))/3600 >= ${settings.documentReviewEscalationHours} THEN 0 WHEN EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP-COALESCE(o."reviewStartedAt",o."submittedAt",o."updatedAt")))/3600 >= ${settings.documentReviewTargetHours} THEN 1 ELSE 2 END, COALESCE(o."reviewStartedAt",o."submittedAt",o."updatedAt") ASC`;
  }

  async settings(organizationId:string){await this.ensureRoot(organizationId);const rows=await this.prisma.$queryRaw<any[]>`SELECT * FROM "EnterpriseWorkflowSettings" WHERE "organizationId"=${organizationId}::uuid LIMIT 1`;return rows[0]??{organizationId,documentReviewTargetHours:24,documentReviewEscalationHours:36,autoApproveAfterVerifiedDocuments:true,paidWaitingPortalEnabled:true,ownerKycOverrideEnabled:true};}

  async updateSettings(organizationId:string,userId:string,payload:Record<string,unknown>){await this.ensureRoot(organizationId);const target=Math.max(1,Math.min(168,Math.round(Number(payload.documentReviewTargetHours??24))));const escalation=Math.max(target,Math.min(336,Math.round(Number(payload.documentReviewEscalationHours??Math.max(36,target)))));const rows=await this.prisma.$queryRaw<any[]>`INSERT INTO "EnterpriseWorkflowSettings" ("organizationId","documentReviewTargetHours","documentReviewEscalationHours","autoApproveAfterVerifiedDocuments","paidWaitingPortalEnabled","ownerKycOverrideEnabled","updatedAt") VALUES (${organizationId}::uuid,${target},${escalation},${payload.autoApproveAfterVerifiedDocuments!==false},${payload.paidWaitingPortalEnabled!==false},${payload.ownerKycOverrideEnabled!==false},CURRENT_TIMESTAMP) ON CONFLICT ("organizationId") DO UPDATE SET "documentReviewTargetHours"=EXCLUDED."documentReviewTargetHours","documentReviewEscalationHours"=EXCLUDED."documentReviewEscalationHours","autoApproveAfterVerifiedDocuments"=EXCLUDED."autoApproveAfterVerifiedDocuments","paidWaitingPortalEnabled"=EXCLUDED."paidWaitingPortalEnabled","ownerKycOverrideEnabled"=EXCLUDED."ownerKycOverrideEnabled","updatedAt"=CURRENT_TIMESTAMP RETURNING *`;await this.prisma.auditLog.create({data:{organizationId,userId,action:'ENTERPRISE_WORKFLOW_SETTINGS_UPDATED',entityType:'Organization',entityId:organizationId,metadata:{targetHours:target,escalationHours:escalation}}});return rows[0];}

  private async tokenContext(rawToken:string){const tokenHash=hash(safe(rawToken,300));const rows=await this.prisma.$queryRaw<any[]>`SELECT t."organizationId",t."clientId",t."expiresAt",t."revokedAt",c.name,c.email,c."paymentStatus",c."subscriptionPlan",o.status,o."submittedAt",o."reviewStartedAt",o."updatedAt" FROM "EnterpriseOnboardingToken" t JOIN "Client" c ON c.id=t."clientId" JOIN "EnterpriseOnboarding" o ON o."clientId"=c.id WHERE t."tokenHash"=${tokenHash} LIMIT 1`;const row=rows[0];if(!row||row.revokedAt||new Date(row.expiresAt).getTime()<Date.now())throw new UnauthorizedException('Lien Enterprise invalide ou expiré');return row;}

  async publicStatus(rawToken:string){const row=await this.tokenContext(rawToken);const settings=await this.settings(row.organizationId);const contracts=await this.prisma.$queryRaw<any[]>`SELECT "contractNumber",status,"signedAt" FROM "EnterpriseContract" WHERE "clientId"=${row.clientId}::uuid AND status<>'SUPERSEDED' ORDER BY "createdAt" DESC LIMIT 1`;const docs=await this.prisma.$queryRaw<any[]>`SELECT "documentType",status,"uploadedAt","verifiedAt","rejectionReason" FROM "EnterpriseVerificationDocument" WHERE "clientId"=${row.clientId}::uuid AND "deletedAt" IS NULL ORDER BY "uploadedAt" DESC`;const reference=row.reviewStartedAt||row.submittedAt||row.updatedAt;const waitingHours=reference?Math.max(0,(Date.now()-new Date(reference).getTime())/3600000):0;const reviewPending=['IDENTITY_PENDING','UNDER_REVIEW','CHANGES_REQUESTED','VERIFIED'].includes(row.status);return{paymentValidated:row.paymentStatus==='PAID',contract:contracts[0]??null,onboardingStatus:row.status,documents:docs,review:{pending:reviewPending,targetHours:settings.documentReviewTargetHours,escalationHours:settings.documentReviewEscalationHours,waitingHours:Math.round(waitingHours*10)/10,priority:waitingHours>=settings.documentReviewEscalationHours?'URGENT':waitingHours>=settings.documentReviewTargetHours?'PRIORITY':'NORMAL',message:reviewPending?waitingHours>=settings.documentReviewTargetHours?'Votre dossier est prioritaire. L’équipe KHE a été relancée automatiquement.':'Vos documents sont dans la file de vérification KHE.':'Aucune vérification manuelle n’est actuellement en attente.'},waitingPortalEnabled:settings.paidWaitingPortalEnabled,fullPlatformAccessAutomatic:false,ownerControlsActivation:true};}

  async processSla(secret:string|undefined){const expected=process.env.CRON_SECRET?.trim();if(!expected||secret!==expected)throw new UnauthorizedException('Invalid cron authorization');const roots=await this.prisma.$queryRaw<Array<{organizationId:string;documentReviewTargetHours:number;documentReviewEscalationHours:number}>>`SELECT "organizationId","documentReviewTargetHours","documentReviewEscalationHours" FROM "EnterpriseWorkflowSettings"`;let notified=0;let escalated=0;for(const root of roots){const candidates=await this.prisma.$queryRaw<any[]>`SELECT c.id,c.name,c.email,o.status,COALESCE(o."reviewStartedAt",o."submittedAt",o."updatedAt") AS "waitingSince",EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP-COALESCE(o."reviewStartedAt",o."submittedAt",o."updatedAt")))/3600 AS hours FROM "Client" c JOIN "EnterpriseOnboarding" o ON o."clientId"=c.id WHERE c."organizationId"=${root.organizationId}::uuid AND c."subscriptionPlan"='ENTERPRISE' AND c."paymentStatus"='PAID' AND o.status IN ('IDENTITY_PENDING','UNDER_REVIEW','VERIFIED') AND COALESCE(o."reviewStartedAt",o."submittedAt",o."updatedAt") IS NOT NULL`;
      for(const item of candidates){const hours=Number(item.hours||0);if(hours<root.documentReviewTargetHours)continue;const urgent=hours>=root.documentReviewEscalationHours;const action=urgent?'ENTERPRISE_DOCUMENT_REVIEW_ESCALATED':'ENTERPRISE_DOCUMENT_REVIEW_SLA_ALERT';const recent=await this.prisma.$queryRaw<Array<{id:string}>>`SELECT id FROM "AuditLog" WHERE "organizationId"=${root.organizationId}::uuid AND "entityId"=${item.id}::text AND action=${action} AND "createdAt">CURRENT_TIMESTAMP-INTERVAL '12 hours' LIMIT 1`;if(recent[0])continue;await this.prisma.$transaction(async tx=>{await tx.appNotification.create({data:{organizationId:root.organizationId,kind:'SYSTEM',title:urgent?'Dossier Enterprise urgent':'Dossier Enterprise à vérifier',body:`${item.name} attend la validation documentaire depuis ${Math.round(hours)} h.`,actionUrl:`/clients?client=${item.id}`}});await tx.auditLog.create({data:{organizationId:root.organizationId,userId:null,action,entityType:'Client',entityId:item.id,metadata:{waitingHours:Math.round(hours),targetHours:root.documentReviewTargetHours,escalationHours:root.documentReviewEscalationHours}}});});if(urgent)escalated++;else notified++;if(item.email)await this.sendClientDelayEmail(item.email,item.name,urgent).catch(()=>undefined);}
    }return{ok:true,notified,escalated};}

  private async sendClientDelayEmail(to:string,name:string,urgent:boolean){const key=process.env.RESEND_API_KEY?.trim();const from=process.env.KHE_EMAIL_FROM?.trim();if(!key||!from)return;await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({from,to:[to],subject:'Mise à jour de votre dossier KHE BOOTH Enterprise',html:`<div style="font-family:Arial,sans-serif;max-width:640px;margin:auto"><h2 style="color:#b58a27">KHE BOOTH Enterprise</h2><p>Bonjour ${name},</p><p>Votre paiement et votre dossier sont bien enregistrés. ${urgent?'Votre vérification documentaire a été escaladée en priorité auprès de notre équipe.':'La vérification de vos documents prend un peu plus de temps que notre objectif habituel.'}</p><p>Vous n’avez rien à renvoyer si les documents apparaissent déjà comme reçus. Vous pouvez suivre l’avancement depuis votre lien Enterprise et contacter l’assistance KHE à tout moment.</p><p>Merci pour votre patience.</p></div>`})});}
}
