'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { PortalShell } from '@/components/portal-shell';
import { apiRequest } from '@/lib/api';

type PaidCampaign={id:string;channel:string;name:string;objective:string;audience:Record<string,unknown>;creative:Record<string,unknown>;budgetCurrency:string;proposedBudgetCents:number;status:string;analysis?:string|null;projectedRevenueCents?:number|null;projectedRoas?:number|null;spentCents:number;attributedRevenueCents:number;createdAt:string};
type Strategy={id:string;periodType:string;periodStart:string;periodEnd:string;summary:string;analysis:Record<string,unknown>;recommendations:string[];projections:Record<string,number>;urgent:boolean;createdAt:string};
type Overview={days:number;summary:{visits:number;checkoutStarts:number;payments:number;revenueCents:number;conversionPercent:number};stripe:{dashboardUrl:string;accountLabel:string;sourceOfTruth:string};paidMarketing:{campaigns:PaidCampaign[];spendCents:number;attributedRevenueCents:number;grossProfitCents:number;roas:number|null;roiPercent:number|null;paymentGate:string};strategies:Strategy[];connectors:Record<string,{connected:boolean;spendEnabled:boolean}>;tenancy:{tenantKind:string;managedByOrganizationId:string|null}};

const EMPTY:Overview={days:30,summary:{visits:0,checkoutStarts:0,payments:0,revenueCents:0,conversionPercent:0},stripe:{dashboardUrl:'https://dashboard.stripe.com/',accountLabel:'KHE Booth',sourceOfTruth:'Stripe Billing'},paidMarketing:{campaigns:[],spendCents:0,attributedRevenueCents:0,grossProfitCents:0,roas:null,roiPercent:null,paymentGate:'OWNER_APPROVAL_REQUIRED'},strategies:[],connectors:{},tenancy:{tenantKind:'UNKNOWN',managedByOrganizationId:null}};
const CHANNELS=['GOOGLE','YOUTUBE','INSTAGRAM','FACEBOOK','TIKTOK','X'] as const;
const PERIODS=[['WEEKLY','Hebdomadaire'],['MONTHLY','Mensuel'],['QUARTERLY','Trimestriel'],['SEMIANNUAL','Semestriel'],['ANNUAL','Annuel']] as const;

function money(cents:number,currency='CHF'){return new Intl.NumberFormat('fr-CH',{style:'currency',currency}).format((cents||0)/100);}
function statusStyle(status:string){const ok=['APPROVED','ACTIVE','COMPLETED'].includes(status);const wait=['READY_FOR_APPROVAL','DRAFT'].includes(status);return{display:'inline-flex',padding:'5px 9px',borderRadius:999,fontSize:10,fontWeight:900,background:ok?'rgba(53,169,97,.15)':wait?'rgba(210,173,79,.15)':'rgba(179,21,32,.12)',color:ok?'#78d59c':wait?'#e4c76e':'#ff9aa4',border:`1px solid ${ok?'rgba(83,190,123,.3)':wait?'rgba(210,173,79,.32)':'rgba(207,72,86,.28)'}`};}

export default function GrowthPage(){
  const[data,setData]=useState<Overview>(EMPTY);const[loading,setLoading]=useState(true);const[message,setMessage]=useState('');const[days,setDays]=useState(30);const[budget,setBudget]=useState(30000);const[offer,setOffer]=useState('PRO');const[selected,setSelected]=useState<string[]>([...CHANNELS]);const[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{setLoading(true);try{setData(await apiRequest<Overview>(`/marketing/growth/overview?days=${days}`));setMessage('');}catch(e){setMessage(e instanceof Error?e.message:'Impossible de charger Growth Lab.');}finally{setLoading(false);}},[days]);
  useEffect(()=>{void load();},[load]);
  const totals=useMemo(()=>({proposed:data.paidMarketing.campaigns.filter(c=>['READY_FOR_APPROVAL','APPROVED'].includes(c.status)).reduce((s,c)=>s+c.proposedBudgetCents,0),active:data.paidMarketing.campaigns.filter(c=>c.status==='ACTIVE').length}),[data.paidMarketing.campaigns]);
  async function strategy(period:string){setBusy(true);try{await apiRequest(`/marketing/growth/strategy/${period}`,{method:'POST'});setMessage(`✓ Plan ${period.toLowerCase()} régénéré.`);await load();}catch(e){setMessage(e instanceof Error?e.message:'Analyse impossible.');}finally{setBusy(false);}}
  async function drafts(){setBusy(true);try{const result=await apiRequest<{created:PaidCampaign[];paymentExecuted:boolean;providerLaunchExecuted:boolean}>('/marketing/growth/paid-campaigns/drafts',{method:'POST',body:JSON.stringify({channels:selected,totalBudgetCents:budget,offer,country:'CH',days})});setMessage(`✓ ${result.created.length} campagne(s) préparée(s). Aucun paiement et aucun lancement n’ont été effectués.`);await load();}catch(e){setMessage(e instanceof Error?e.message:'Création impossible.');}finally{setBusy(false);}}
  async function approve(id:string,approved:boolean){setBusy(true);try{const result=await apiRequest<{paymentExecuted:boolean;providerLaunchExecuted:boolean}>(`/marketing/growth/paid-campaigns/${id}/approval`,{method:'POST',body:JSON.stringify({approved})});setMessage(approved?'✓ Campagne approuvée pour préparation fournisseur. Aucun paiement effectué.':'Campagne rejetée.');if(result.paymentExecuted||result.providerLaunchExecuted)setMessage('Sécurité KHE : état inattendu détecté. Aucun débit ne doit être déclenché depuis cette étape.');await load();}catch(e){setMessage(e instanceof Error?e.message:'Validation impossible.');}finally{setBusy(false);}}
  return <PortalShell>
    <div className="page-header"><div><div className="eyebrow">MARKETING & ANALYTICS • GROWTH LAB</div><h1>Stripe, réseaux sociaux & campagnes</h1><p className="muted">Analyse financière, recommandations KHE et préparation des campagnes payantes avec validation propriétaire obligatoire avant toute dépense.</p></div><div className="toolbar"><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 jours</option><option value={30}>30 jours</option><option value={90}>90 jours</option><option value={365}>1 an</option></select><button className="button secondary" onClick={()=>void load()}>{loading?'Actualisation…':'↻ Actualiser'}</button></div></div>

    <section className="card" style={{background:'linear-gradient(145deg,#0c1118,#17130d)',border:'1px solid rgba(210,173,79,.4)',marginBottom:16}}><div style={{display:'flex',justifyContent:'space-between',gap:18,alignItems:'center',flexWrap:'wrap'}}><div><div className="eyebrow" style={{color:'#d2ad4f'}}>STRIPE ASSOCIÉ</div><h2 style={{margin:'6px 0'}}>Tableau de bord Stripe</h2><p className="muted" style={{margin:0}}>Source de vérité : {data.stripe.sourceOfTruth}. Ouvrez Stripe pour les réglages avancés, taxes, moyens de paiement et facturation.</p></div><a className="button" href={data.stripe.dashboardUrl} target="_blank" rel="noreferrer">Ouvrir Stripe Dashboard ↗</a></div></section>

    <div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(165px,1fr))',marginBottom:16}}>{[
      ['Revenus suivis',money(data.summary.revenueCents)],['Dépenses pub',money(data.paidMarketing.spendCents)],['Revenus attribués',money(data.paidMarketing.attributedRevenueCents)],['Bénéfice attribué',money(data.paidMarketing.grossProfitCents)],['ROAS',data.paidMarketing.roas===null?'—':`${data.paidMarketing.roas}×`],['ROI',data.paidMarketing.roiPercent===null?'—':`${data.paidMarketing.roiPercent}%`],['Budget en attente',money(totals.proposed)],['Campagnes actives',totals.active]
    ].map(([label,value])=><div className="card" key={String(label)}><div className="eyebrow">{label}</div><div style={{fontSize:26,fontWeight:950,marginTop:8,color:'#e4c76e'}}>{value}</div></div>)}</div>

    <div className="grid two" style={{alignItems:'start',marginBottom:16}}><section className="card"><div className="eyebrow">ANALYSE AUTOMATIQUE KHE</div><h2>Plans marketing périodiques</h2><p className="muted">Chaque plan recalcule conversion, revenus, budget conseillé, impact projeté, ROAS et bénéfice potentiel. Les urgences génèrent une notification KHE.</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{PERIODS.map(([key,label])=><button key={key} className="button secondary" disabled={busy} onClick={()=>void strategy(key)}>{label}</button>)}</div></section><section className="card"><div className="eyebrow">CONNEXIONS PUBLICITAIRES</div><h2>État des canaux</h2><div style={{display:'grid',gap:8}}>{Object.entries(data.connectors).map(([name,state])=><div key={name} style={{display:'flex',justifyContent:'space-between',gap:12,padding:10,border:'1px solid #303945',borderRadius:12}}><strong style={{textTransform:'capitalize'}}>{name}</strong><span style={{color:state.connected?'#7bd59e':'#e4c76e',fontWeight:900,fontSize:11}}>{state.connected?'Connecté':'À connecter'} • Dépense bloquée</span></div>)}</div></section></div>

    <section className="card" style={{marginBottom:16}}><div className="eyebrow">GÉNÉRATEUR DE CAMPAGNES</div><h2>Préparer des publicités ciblées</h2><p className="muted">KHE peut préparer les audiences, formats et budgets par canal. Cette action ne lance rien et ne paie rien.</p><div className="grid two"><label>Offre<select value={offer} onChange={e=>setOffer(e.target.value)}><option value="STARTER">Starter</option><option value="PRO">Pro</option><option value="BUSINESS">Business</option><option value="ENTERPRISE">Enterprise</option></select></label><label>Budget total proposé (CHF)<input type="number" min={0} step={10} value={budget/100} onChange={e=>setBudget(Math.max(0,Math.round(Number(e.target.value||0)*100)))}/></label></div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}>{CHANNELS.map(channel=><button key={channel} type="button" onClick={()=>setSelected(current=>current.includes(channel)?current.filter(x=>x!==channel):[...current,channel])} className={selected.includes(channel)?'button':'button secondary'}>{channel}</button>)}</div><button className="button" disabled={busy||selected.length===0} style={{marginTop:14}} onClick={()=>void drafts()}>Préparer les campagnes sans paiement</button></section>

    <section className="card" style={{marginBottom:16}}><div className="eyebrow">VALIDATION PROPRIÉTAIRE</div><h2>Campagnes proposées</h2><p className="muted">Une approbation ici autorise uniquement la préparation fournisseur. Le paiement et le lancement restent deux étapes distinctes qui nécessiteront une confirmation explicite.</p><div style={{display:'grid',gap:10}}>{data.paidMarketing.campaigns.length?data.paidMarketing.campaigns.map(c=><div key={c.id} style={{padding:14,border:'1px solid #303945',borderRadius:14,background:'#111820'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><strong>{c.channel} • {c.name}</strong><div className="muted" style={{fontSize:12,marginTop:4}}>Budget {money(c.proposedBudgetCents,c.budgetCurrency)} • projection {money(c.projectedRevenueCents||0,c.budgetCurrency)} • ROAS {c.projectedRoas??'—'}×</div></div><span style={statusStyle(c.status)}>{c.status}</span></div>{c.analysis?<p className="muted" style={{fontSize:12}}>{c.analysis}</p>:null}{['DRAFT','READY_FOR_APPROVAL','APPROVED'].includes(c.status)?<div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="button" disabled={busy} onClick={()=>void approve(c.id,true)}>Approuver la proposition</button><button className="button secondary" disabled={busy} onClick={()=>void approve(c.id,false)}>Rejeter</button></div>:null}</div>):<p className="muted">Aucune campagne payante préparée pour le moment.</p>}</div></section>

    <section className="card"><div className="eyebrow">RÉFLEXIONS & CONCLUSIONS KHE</div><h2>Rapports stratégiques</h2><div style={{display:'grid',gap:12}}>{data.strategies.length?data.strategies.map(report=><article key={report.id} style={{padding:14,border:`1px solid ${report.urgent?'#b31520':'#303945'}`,borderRadius:14}}><div style={{display:'flex',justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><strong>{report.periodType} • {report.periodStart} → {report.periodEnd}</strong>{report.urgent?<span style={{color:'#ff8f98',fontWeight:900}}>URGENT</span>:null}</div><p>{report.summary}</p><ul>{(report.recommendations||[]).map((item,index)=><li key={index}>{item}</li>)}</ul></article>):<p className="muted">Générez votre première analyse hebdomadaire, mensuelle, trimestrielle, semestrielle ou annuelle.</p>}</div></section>
    {message?<p className="success" style={{marginTop:14}}>{message}</p>:null}
  </PortalShell>;
}
