'use client';
import { useEffect, useMemo, useState } from 'react';
import { PortalShell } from '@/components/portal-shell';
import { apiRequest } from '@/lib/api';

type Provider='META'|'WHATSAPP'|'TIKTOK'|'X'|'TELEGRAM'|'YOUTUBE';
type Status={provider:Provider;label:string;configured:boolean;configuredFields:string[];requiredFields:string[];source:'KHE_ENCRYPTED'|'SERVER_ENV'|'NONE';updatedAt:string|null;callbacks:string[]};
type Me={role:string};
const LABELS:Record<string,string>={appId:'App ID',appSecret:'App Secret',accessToken:'Access Token',phoneNumberId:'Phone Number ID',clientKey:'Client Key',clientSecret:'Client Secret',clientId:'Client ID',botToken:'Bot Token',targetChatId:'Target Chat ID'};
const HELP:Record<Provider,string>={META:'Une seule application Meta alimente Facebook et Instagram. Activez Facebook Login / Instagram API et ajoutez les deux callbacks affichés.',WHATSAPP:'Utilisez le token permanent Cloud API et le Phone Number ID du numéro WhatsApp Business.',TIKTOK:'Client Key + Client Secret de TikTok for Developers. Content Posting API / video.publish doit être approuvé pour publier.',X:'OAuth 2.0 Authorization Code + PKCE avec droits lecture/écriture et offline access.',TELEGRAM:'Token BotFather + identifiant du canal/groupe où le bot est déjà membre avec les droits requis.',YOUTUBE:'Client OAuth Web Google Cloud avec YouTube Data API activée et callback exact autorisé.'};
export default function SocialDeveloperPage(){const[me,setMe]=useState<Me|null>(null);const[items,setItems]=useState<Status[]>([]);const[forms,setForms]=useState<Record<string,Record<string,string>>>({});const[msg,setMsg]=useState('');const[busy,setBusy]=useState('');
 const load=async()=>{const [user,data]=await Promise.all([apiRequest<Me>('/auth/me'),apiRequest<Status[]>('/settings/social-developer')]);setMe(user);setItems(data);};useEffect(()=>{void load().catch(e=>setMsg(e instanceof Error?e.message:'Erreur'));},[]);
 const owner=me?.role==='OWNER';const callbacks=useMemo(()=>items.flatMap(i=>i.callbacks),[items]);
 function change(p:Provider,f:string,v:string){setForms(x=>({...x,[p]:{...(x[p]||{}),[f]:v}}));}
 async function save(item:Status){if(!owner)return;setBusy(item.provider);setMsg('Chiffrement et enregistrement…');try{await apiRequest(`/settings/social-developer/${item.provider}`,{method:'PATCH',body:JSON.stringify(forms[item.provider]||{})});setForms(x=>({...x,[item.provider]:{}}));await load();setMsg(`✓ ${item.label} enregistré dans le coffre KHE.`);}catch(e){setMsg(e instanceof Error?e.message:'Erreur');}finally{setBusy('');}}
 async function remove(item:Status){if(!owner||!confirm(`Supprimer la configuration développeur KHE pour ${item.label} ? Le fallback Vercel restera disponible s’il existe.`))return;setBusy(item.provider);try{await apiRequest(`/settings/social-developer/${item.provider}`,{method:'DELETE'});await load();setMsg(`✓ Configuration KHE supprimée pour ${item.label}.`);}catch(e){setMsg(e instanceof Error?e.message:'Erreur');}finally{setBusy('');}}
 return <PortalShell><div className="page-header"><div><div className="eyebrow">COFFRE SOCIAL KHE</div><h1>Connexions développeur</h1><p className="muted">Identifiants d’applications et tokens serveur chiffrés côté API. Les valeurs enregistrées ne sont jamais relues dans le navigateur.</p></div></div>
 {!owner?<section className="card"><h2>Lecture seule</h2><p className="muted">Seul OWNER peut enregistrer ou remplacer des secrets développeur. Vous pouvez consulter l’état de préparation.</p></section>:null}
 <div className="grid two" style={{alignItems:'start'}}>{items.map(item=><section className="card" key={item.provider} style={{display:'grid',gap:12}}><div><div className="eyebrow">{item.provider}</div><h2 style={{margin:'4px 0'}}>{item.label}</h2><p className="muted">{HELP[item.provider]}</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><span className={item.configured?'badge ok':'badge'}>{item.configured?'CONFIGURÉ':'À CONFIGURER'}</span><span className="badge">{item.source==='KHE_ENCRYPTED'?'COFFRE KHE':item.source==='SERVER_ENV'?'VERCEL ENV':'AUCUNE SOURCE'}</span></div>{item.requiredFields.map(field=><label key={field}>{LABELS[field]||field}<input type={/secret|token/i.test(field)?'password':'text'} autoComplete="off" value={forms[item.provider]?.[field]||''} placeholder={item.configuredFields.includes(field)?'Déjà configuré — laisser vide pour conserver':'À renseigner'} onChange={e=>change(item.provider,field,e.target.value)} disabled={!owner||busy===item.provider}/></label>)}{item.callbacks.length?<div><strong>Callback(s) à autoriser</strong>{item.callbacks.map(cb=><div key={cb} style={{fontFamily:'monospace',fontSize:11,overflowWrap:'anywhere',marginTop:6,padding:8,border:'1px solid rgba(255,255,255,.12)',borderRadius:8}}>{cb}</div>)}</div>:null}<div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{owner?<button className="button" type="button" onClick={()=>void save(item)} disabled={busy===item.provider}>{busy===item.provider?'Enregistrement…':'Enregistrer / remplacer'}</button>:null}{owner&&item.source==='KHE_ENCRYPTED'?<button className="button secondary" type="button" onClick={()=>void remove(item)} disabled={busy===item.provider}>Retirer du coffre KHE</button>:null}</div>{item.updatedAt?<p className="muted" style={{fontSize:11}}>Dernière mise à jour coffre : {new Date(item.updatedAt).toLocaleString('fr-CH')}</p>:null}</section>)}</div>
 {callbacks.length?<section className="card" style={{marginTop:18}}><div className="eyebrow">RÈGLE DE SÉCURITÉ</div><h2>Callbacks fixes</h2><p className="muted">Copiez exactement ces URL dans les portails développeur. KHE utilise ensuite un état OAuth à usage unique et stocke les jetons uniquement côté serveur.</p></section>:null}{msg?<p className={msg.startsWith('✓')?'success':'muted'}>{msg}</p>:null}</PortalShell>;
}
