'use client';

import Link from 'next/link';
import { useCallback,useEffect,useState } from 'react';
import { PortalShell } from '@/components/portal-shell';
import { apiRequest } from '@/lib/api';

type Policy={enabled:boolean;activationBeforeShiftEndMinutes:number;notifyManagers:boolean};
type RescueCase={id:string;status:string;riskLevel:string;nextSlaDueAt?:string|null;recommendedAction:string;suggestedUserId?:string|null;suggestedAgentName?:string|null;selectedUserId?:string|null;selectedAgentName?:string|null;reason?:string|null;decisionNote?:string|null;conversationId:string;subject:string;priority:string;routingTopic:string;requestedLanguage:string;escalationLevel:number;shiftEndsAt:string;fromAgentName:string};
type Team={policy:Policy;summary:{actionRequired:number;prepared:number;overdue:number;urgent:number;withoutCandidate:number;applied:number};cases:RescueCase[]};
type Candidate={id:string;name:string;coverageStatus:string;reason:string};
function when(v?:string|null){return v?new Date(v).toLocaleString('fr-CH',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';}
function actionLabel(v:string){return v==='HOLD'?'Conserver temporairement':v==='PREPARE_RELAY'?'Préparer une relève':'Escalader';}
function statusLabel(v:string){return v==='OPEN'?'À décider':v==='PREPARED'?'Relève préparée':v==='HOLD'?'Conservé':v==='ESCALATED'?'Escaladé':v==='APPLIED'?'Transféré':v==='STALE'?'Obsolète':'Clos';}

export default function SlaRescueTeamPage(){
  const[data,setData]=useState<Team|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[busy,setBusy]=useState('');const[message,setMessage]=useState('');const[candidates,setCandidates]=useState<Record<string,Candidate[]>>({});
  const load=useCallback(async(quiet=false)=>{if(!quiet)setLoading(true);try{setData(await apiRequest<Team>('/operations/workforce/rescue/team'));if(!quiet)setMessage('');}catch(e){if(!quiet)setMessage(e instanceof Error?e.message:'SLA Rescue indisponible');}finally{if(!quiet)setLoading(false);}},[]);
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(true),15000);return()=>window.clearInterval(timer);},[load]);
  const setPolicy=<K extends keyof Policy>(key:K,value:Policy[K])=>setData(d=>d?{...d,policy:{...d.policy,[key]:value}}:d);
  async function savePolicy(){if(!data)return;setSaving(true);try{await apiRequest('/operations/workforce/rescue/policy',{method:'PATCH',body:JSON.stringify(data.policy)});setMessage('✓ Politique SLA Rescue enregistrée.');await load(true);}catch(e){setMessage(e instanceof Error?e.message:'Enregistrement impossible');}finally{setSaving(false);}}
  async function act(id:string,action:'hold'|'escalate'|'apply-relay',body:Record<string,unknown>={}){setBusy(`${id}:${action}`);try{await apiRequest(`/operations/workforce/rescue/cases/${id}/${action}`,{method:'POST',body:JSON.stringify(body)});setMessage(action==='hold'?'✓ Le manager conserve temporairement ce dossier chez l’agent actuel.':action==='escalate'?'✓ Dossier escaladé. L’assignation reste inchangée.':'✓ Relève immédiate validée et appliquée.');await load(true);}catch(e){setMessage(e instanceof Error?e.message:'Action impossible');}finally{setBusy('');}}
  async function showCandidates(id:string){setBusy(`${id}:candidates`);try{const result=await apiRequest<{candidates:Candidate[]}>(`/operations/workforce/rescue/cases/${id}/candidates`);setCandidates(v=>({...v,[id]:result.candidates}));}catch(e){setMessage(e instanceof Error?e.message:'Relèves indisponibles');}finally{setBusy('');}}
  async function prepare(id:string,agentId:string){setBusy(`${id}:prepare`);try{await apiRequest(`/operations/workforce/rescue/cases/${id}/prepare-relay`,{method:'POST',body:JSON.stringify({agentId})});setMessage('✓ Relève préparée. Aucun transfert n’a encore été effectué.');setCandidates(v=>({...v,[id]:[]}));await load(true);}catch(e){setMessage(e instanceof Error?e.message:'Préparation impossible');}finally{setBusy('');}}
  return <PortalShell><div className="page-header"><div><div className="eyebrow">KHE • SLA RESCUE</div><h1>Protection SLA avant fin de shift</h1><p className="muted">KHE détecte les dossiers à risque et propose une action. Les transferts restent exclusivement validés par OWNER/ADMIN et aucune décision disciplinaire n’est automatisée.</p><div style={{display:'flex',gap:12,flexWrap:'wrap',marginTop:8}}><Link href="/operations/workforce/brief/team">← Shift Brief</Link><Link href="/operations/workforce/handover">Passages de relais</Link><Link href="/operations/routing">Routing & SLA</Link></div></div><button className="button secondary" onClick={()=>void load()}>{loading?'Chargement…':'↻ Actualiser'}</button></div>
  {message?<p className={message.startsWith('✓')?'success':'error'}>{message}</p>:null}
  {!data?null:<><div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(145px,1fr))',marginBottom:16}}>{[['À décider',data.summary.actionRequired],['Relèves préparées',data.summary.prepared],['SLA dépassés',data.summary.overdue],['SLA urgents',data.summary.urgent],['Sans relève',data.summary.withoutCandidate],['Transférés',data.summary.applied]].map(([label,value])=><div className="card" key={String(label)}><div className="eyebrow">{label}</div><div style={{fontSize:28,fontWeight:950,marginTop:8}}>{value}</div></div>)}</div>
  <div className="grid two" style={{alignItems:'start'}}><section className="card"><div className="eyebrow">CAS À SURVEILLER</div><h2>Décisions manager</h2>{data.cases.length?data.cases.map(c=><div key={c.id} style={{padding:'13px 0',borderBottom:'1px solid #27303a'}}><div style={{display:'flex',justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><strong>{c.subject}</strong><span style={{fontWeight:900,color:c.riskLevel==='OVERDUE'?'#ff9aa4':'#f5c76b'}}>{c.riskLevel}</span></div><div className="muted" style={{fontSize:11,marginTop:3}}>{c.fromAgentName} · fin {when(c.shiftEndsAt)} · SLA {when(c.nextSlaDueAt)} · {c.routingTopic}/{c.requestedLanguage}</div><div style={{fontSize:12,marginTop:7}}><strong>{statusLabel(c.status)}</strong> · recommandation KHE : {actionLabel(c.recommendedAction)}</div>{c.reason?<div className="muted" style={{fontSize:11,marginTop:3}}>{c.reason}</div>:null}{c.suggestedAgentName?<div className="muted" style={{fontSize:11,marginTop:3}}>Relève pressentie : {c.suggestedAgentName}</div>:null}{c.selectedAgentName?<div style={{fontSize:11,marginTop:3}}>Relève préparée : <strong>{c.selectedAgentName}</strong></div>:null}
  {['OPEN','PREPARED'].includes(c.status)?<div style={{display:'flex',gap:7,flexWrap:'wrap',marginTop:9}}><button className="button secondary" disabled={Boolean(busy)} onClick={()=>void act(c.id,'hold')}>Conserver ici</button><button className="button secondary" disabled={Boolean(busy)} onClick={()=>void showCandidates(c.id)}>Choisir une relève</button><button className="button secondary" disabled={Boolean(busy)} onClick={()=>void act(c.id,'escalate')}>Escalader</button>{c.status==='PREPARED'?<button className="button" disabled={Boolean(busy)} onClick={()=>void act(c.id,'apply-relay')}>Transférer maintenant</button>:null}</div>:null}
  {candidates[c.id]?.length?<div style={{marginTop:9,padding:9,border:'1px solid #27303a',borderRadius:8}}><strong style={{fontSize:12}}>Relèves compatibles</strong>{candidates[c.id].map(x=><div key={x.id} style={{display:'flex',justifyContent:'space-between',gap:8,alignItems:'center',padding:'8px 0',borderBottom:'1px solid #27303a'}}><div><strong>{x.name}</strong><div className="muted" style={{fontSize:10}}>{x.coverageStatus==='ACTIVE'?'déjà en service':'shift entrant'} · {x.reason}</div></div><button className="button secondary" disabled={Boolean(busy)} onClick={()=>void prepare(c.id,x.id)}>Préparer</button></div>)}</div>:null}</div>):<p className="muted">Aucun cas SLA Rescue récent.</p>}</section>
  <section className="card"><div className="eyebrow">POLITIQUE</div><h2>Détection SLA Rescue</h2><label style={{display:'flex',gap:8,alignItems:'center',marginBottom:12}}><input type="checkbox" checked={data.policy.enabled} onChange={e=>setPolicy('enabled',e.target.checked)}/> SLA Rescue actif</label><label>Fenêtre avant fin du shift (min)<input className="input" type="number" min={5} max={120} value={data.policy.activationBeforeShiftEndMinutes} onChange={e=>setPolicy('activationBeforeShiftEndMinutes',Number(e.target.value))}/></label><label style={{display:'flex',gap:8,alignItems:'center',marginTop:12}}><input type="checkbox" checked={data.policy.notifyManagers} onChange={e=>setPolicy('notifyManagers',e.target.checked)}/> Alerter les managers lors d’un nouveau risque</label><p className="muted" style={{fontSize:11,marginTop:12}}>Le moteur utilise uniquement l’état du dossier, le SLA, les compétences/langues, la capacité et les shifts. Il n’utilise ni refus passés, ni notes personnelles, ni données médicales ou caractéristiques protégées.</p><button className="button" disabled={saving} onClick={()=>void savePolicy()}>{saving?'Enregistrement…':'Enregistrer la politique'}</button></section></div></>}
  </PortalShell>;
}
