'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { PortalShell } from '@/components/portal-shell';
import { apiRequest } from '@/lib/api';

type Shift={id:string;startsAt:string;endsAt:string;status:string;confirmationStatus:string;liveStatus:string;actualStartedAt?:string|null;actualEndedAt?:string|null;pauseStartedAt?:string|null;pausedSeconds:number;skills:string[];languages:string[]};
type EventRow={id:string;shiftId:string;action:string;createdAt:string;metadata?:Record<string,unknown>};
type Policy={startEarlyMinutes:number;startGraceMinutes:number;noShowAlertMinutes:number;autoCloseMinutes:number;requireActiveShiftForRouting:boolean};
type Mine={policy:Policy;summary:{active:number;paused:number;scheduled:number;missed:number};activeShift?:Shift|null;shifts:Shift[];events:EventRow[]};

function when(value:string){return new Date(value).toLocaleString('fr-CH',{weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});}
function liveLabel(value:string){return value==='ACTIVE'?'En service':value==='PAUSED'?'En pause':value==='COMPLETED'?'Terminé':value==='MISSED'?'Non démarré':'Planifié';}

export default function LiveShiftPage(){
  const[data,setData]=useState<Mine|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState('');const[message,setMessage]=useState('');
  const load=useCallback(async(quiet=false)=>{if(!quiet)setLoading(true);try{setData(await apiRequest<Mine>('/operations/workforce/live/me'));if(!quiet)setMessage('');}catch(e){if(!quiet)setMessage(e instanceof Error?e.message:'Mode Live indisponible');}finally{if(!quiet)setLoading(false);}},[]);
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(true),30000);return()=>window.clearInterval(timer);},[load]);
  const candidate=useMemo(()=>data?.shifts.find(s=>s.status==='PLANNED'&&s.confirmationStatus==='ACCEPTED'&&['SCHEDULED','MISSED'].includes(s.liveStatus)&&new Date(s.endsAt)>new Date())??null,[data]);
  async function action(id:string,action:'start'|'pause'|'resume'|'end'){setBusy(action);try{await apiRequest(`/operations/workforce/live/shifts/${id}/${action}`,{method:'POST'});setMessage(action==='start'?'✓ Shift démarré. Le routing peut maintenant vous attribuer des tâches selon les règles actives.':action==='pause'?'✓ Pause activée. Les nouvelles assignations sont suspendues.':action==='resume'?'✓ Shift repris. Les nouvelles assignations peuvent reprendre.':'✓ Shift terminé. Si des conversations restent ouvertes, KHE a préparé un passage de relais à faire valider par un manager.');await load(true);}catch(e){setMessage(e instanceof Error?e.message:'Action impossible');}finally{setBusy('');}}
  return <PortalShell><div className="page-header"><div><div className="eyebrow">KHE • LIVE SHIFT</div><h1>Mon service en direct</h1><p className="muted">Démarrez votre shift, gérez vos pauses et terminez votre service. KHE synchronise votre état avec le routing, sans créer de sanction automatique en cas de retard ou d’absence.</p><div style={{display:'flex',gap:12,flexWrap:'wrap',marginTop:8}}><Link href="/operations/workforce/me">← Mon planning</Link><Link href="/operations/workforce/handover/me">Passage de relais</Link><Link href="/help">Aide / Messagerie</Link></div></div><button className="button secondary" onClick={()=>void load()}>{loading?'Chargement…':'↻ Actualiser'}</button></div>
  {message?<p className={message.startsWith('✓')?'success':'error'}>{message}</p>:null}
  {!data?null:<><div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',marginBottom:16}}>{[['Actifs',data.summary.active],['En pause',data.summary.paused],['Planifiés',data.summary.scheduled],['Non démarrés',data.summary.missed]].map(([label,value])=><div className="card" key={String(label)}><div className="eyebrow">{label}</div><div style={{fontSize:28,fontWeight:950,marginTop:8}}>{value}</div></div>)}</div>
  <section className="card" style={{marginBottom:16}}><div className="eyebrow">ÉTAT DU SERVICE</div><h2>{data.activeShift?liveLabel(data.activeShift.liveStatus):candidate?'Prêt à démarrer':'Aucun shift actif'}</h2>{data.activeShift?<><p><strong>{when(data.activeShift.startsAt)} → {when(data.activeShift.endsAt)}</strong></p><p className="muted">Pause cumulée : {Math.round((data.activeShift.pausedSeconds||0)/60)} min</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{data.activeShift.liveStatus==='ACTIVE'?<><button className="button secondary" disabled={Boolean(busy)} onClick={()=>void action(data.activeShift!.id,'pause')}>Mettre en pause</button><button className="button" disabled={Boolean(busy)} onClick={()=>void action(data.activeShift!.id,'end')}>Terminer le shift</button></>:<><button className="button" disabled={Boolean(busy)} onClick={()=>void action(data.activeShift!.id,'resume')}>Reprendre</button><button className="button secondary" disabled={Boolean(busy)} onClick={()=>void action(data.activeShift!.id,'end')}>Terminer le shift</button></>}</div></>:candidate?<><p><strong>{when(candidate.startsAt)} → {when(candidate.endsAt)}</strong></p><p className="muted">Vous pouvez démarrer au plus tôt {data.policy.startEarlyMinutes} min avant l’heure prévue. La marge de retard configurée est de {data.policy.startGraceMinutes} min.</p><button className="button" disabled={Boolean(busy)} onClick={()=>void action(candidate.id,'start')}>Commencer mon shift</button></>:<p className="muted">Aucun shift accepté à démarrer pour le moment.</p>}</section>
  <section className="card"><div className="eyebrow">HISTORIQUE LIVE</div><h2>Mes dernières actions</h2>{data.events.length?data.events.slice(0,20).map(e=><div key={e.id} style={{padding:'9px 0',borderBottom:'1px solid #27303a'}}><strong>{e.action}</strong><div className="muted" style={{fontSize:11}}>{when(e.createdAt)}</div></div>):<p className="muted">Aucune action Live enregistrée.</p>}</section></>}
  </PortalShell>;
}
