import * as SecureStore from 'expo-secure-store';
import type { ReactNode } from 'react';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { StartupIntro } from '../branding/startup-intro';
import { API_BASE_URL } from '../config';

export const APP_VERSION = '0.3.12';
export const LEGAL_CONTENT_REVISION = '2026-09-03.diagnostics.1';
const TERMS_ACCEPTED_KEY = 'khe.terms.accepted.revision.v3';
const PUBLIC_APP_CONFIG_URL = 'https://raw.githubusercontent.com/paokurtis-a11y/Khebooth/main/apps/mobile/app.json';
const STANDALONE_APK_URL = 'https://github.com/paokurtis-a11y/Khebooth/releases/download/android-latest/KHE-Booth-Android-Standalone.apk';
const LEGAL_POLICY_URL = 'https://khebooth.vercel.app/api/legal/policy';

const EU_EEA_REGIONS = new Set(['AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GR', 'HU', 'IE', 'IS', 'IT', 'LI', 'LT', 'LU', 'LV', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK']);

export interface ReleaseInfo { latestVersion:string; updateAvailable:boolean; releaseNotes?:string; installUrl?:string; }
export interface LegalPolicyProfile { region:'CH'|'EEA'|'UK'|'US'|'GLOBAL';label:string;jurisdictionLabel:string;countryCode:string;subdivisionCode:string|null;frameworks:string[];termsAddendum:string[];revision:string;lastReviewed:string;exactNationalProfile:boolean;detectedBy:'network'|'device-fallback'; }

function deviceRegion():string{const locale=Intl.DateTimeFormat().resolvedOptions().locale||'fr-CH';const region=locale.replace('_','-').split('-').find(part=>/^[A-Z]{2}$/.test(part));return region??'GLOBAL';}
function fallbackLegalProfile():LegalPolicyProfile{const countryCode=deviceRegion();if(countryCode==='CH')return{region:'CH',label:'Suisse',jurisdictionLabel:'Suisse',countryCode,subdivisionCode:null,frameworks:['LPD suisse (nLPD) et règles locales applicables'],termsAddendum:['En mode hors ligne, KHE Booth applique ce profil suisse de secours. Les dispositions impératives réellement applicables restent prioritaires.'],revision:'2026-08-22.FALLBACK.CH.1',lastReviewed:'2026-08-22',exactNationalProfile:true,detectedBy:'device-fallback'};if(EU_EEA_REGIONS.has(countryCode))return{region:'EEA',label:'Union européenne / EEE',jurisdictionLabel:countryCode,countryCode,subdivisionCode:null,frameworks:['RGPD (UE) 2016/679','règles nationales complémentaires applicables'],termsAddendum:['En mode hors ligne, KHE Booth applique ce profil EEE de secours. Les droits impératifs du pays concerné restent applicables.'],revision:'2026-08-22.FALLBACK.EEA.1',lastReviewed:'2026-08-22',exactNationalProfile:true,detectedBy:'device-fallback'};if(countryCode==='GB')return{region:'UK',label:'Royaume-Uni',jurisdictionLabel:'Royaume-Uni',countryCode,subdivisionCode:null,frameworks:['UK GDPR','Data Protection Act 2018'],termsAddendum:['En mode hors ligne, KHE Booth applique ce profil britannique de secours. Les droits impératifs applicables restent prioritaires.'],revision:'2026-08-22.FALLBACK.UK.1',lastReviewed:'2026-08-22',exactNationalProfile:true,detectedBy:'device-fallback'};if(countryCode==='US')return{region:'US',label:'États-Unis',jurisdictionLabel:'États-Unis',countryCode,subdivisionCode:null,frameworks:['lois fédérales applicables','lois étatiques applicables selon le contexte'],termsAddendum:['En mode hors ligne, KHE Booth ne peut pas déterminer l’État réseau. Les droits impératifs de l’État réellement applicable restent prioritaires.'],revision:'2026-08-22.FALLBACK.US.1',lastReviewed:'2026-08-22',exactNationalProfile:true,detectedBy:'device-fallback'};return{region:'GLOBAL',label:'Version internationale',jurisdictionLabel:countryCode==='GLOBAL'?'Localisation non déterminée':countryCode,countryCode,subdivisionCode:null,frameworks:['lois impératives applicables dans le pays de l’utilisateur ou de l’organisation'],termsAddendum:['En l’absence de localisation réseau disponible, les règles impératives de la juridiction réellement applicable restent prioritaires.'],revision:'2026-08-22.FALLBACK.GLOBAL.1',lastReviewed:'2026-08-22',exactNationalProfile:false,detectedBy:'device-fallback'};}
function validLegalProfile(value:unknown):value is Omit<LegalPolicyProfile,'detectedBy'>&{detectedBy?:string}{if(!value||typeof value!=='object')return false;const profile=value as Record<string,unknown>;return typeof profile.region==='string'&&typeof profile.label==='string'&&typeof profile.jurisdictionLabel==='string'&&typeof profile.countryCode==='string'&&Array.isArray(profile.frameworks)&&Array.isArray(profile.termsAddendum)&&typeof profile.revision==='string'&&typeof profile.lastReviewed==='string';}
export async function fetchLegalPolicyProfile():Promise<LegalPolicyProfile>{try{const response=await fetch(LEGAL_POLICY_URL,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`HTTP ${response.status}`);const payload=await response.json() as unknown;if(!validLegalProfile(payload))throw new Error('Profil juridique distant invalide');return{...payload,detectedBy:'network'} as LegalPolicyProfile;}catch{return fallbackLegalProfile();}}
function currentTermsRevision(profile:LegalPolicyProfile){return`khe-terms-${LEGAL_CONTENT_REVISION}-${profile.revision}-${profile.countryCode}-${profile.subdivisionCode??'all'}`;}
export async function hasAcceptedCurrentTerms(profile:LegalPolicyProfile){return(await SecureStore.getItemAsync(TERMS_ACCEPTED_KEY))===currentTermsRevision(profile);}
export async function acceptCurrentTerms(profile:LegalPolicyProfile){await SecureStore.setItemAsync(TERMS_ACCEPTED_KEY,currentTermsRevision(profile),{keychainAccessible:SecureStore.WHEN_UNLOCKED_THIS_DEVICE_ONLY});}
function compareVersions(a:string,b:string){const pa=a.split('.').map(value=>Number.parseInt(value,10)||0);const pb=b.split('.').map(value=>Number.parseInt(value,10)||0);const length=Math.max(pa.length,pb.length);for(let index=0;index<length;index+=1){const diff=(pa[index]??0)-(pb[index]??0);if(diff!==0)return diff;}return 0;}
async function fetchReleaseInfoFromGithub():Promise<ReleaseInfo>{const response=await fetch(PUBLIC_APP_CONFIG_URL);if(!response.ok)throw new Error(`GitHub HTTP ${response.status}`);const config=await response.json() as {expo?:{version?:string}};const latestVersion=config.expo?.version?.trim();if(!latestVersion)throw new Error('Version distante absente');return{latestVersion,updateAvailable:compareVersions(latestVersion,APP_VERSION)>0,releaseNotes:compareVersions(latestVersion,APP_VERSION)>0?'Une nouvelle version autonome de KHE Booth est disponible. Appuyez sur Télécharger pour installer l’APK validé.':undefined,installUrl:STANDALONE_APK_URL};}
export async function fetchReleaseInfo():Promise<ReleaseInfo>{try{const response=await fetch(`${API_BASE_URL}/mobile/version?current=${encodeURIComponent(APP_VERSION)}`);if(!response.ok)throw new Error(`HTTP ${response.status}`);return await response.json() as ReleaseInfo;}catch{try{return await fetchReleaseInfoFromGithub();}catch{return{latestVersion:APP_VERSION,updateAvailable:false,installUrl:STANDALONE_APK_URL};}}}

export function TermsContent({profile}:{profile:LegalPolicyProfile}){return <View style={styles.termsBody}><Text style={styles.heading}>Conditions générales d’utilisation — KHE Booth</Text><Text style={styles.revision}>Version de l’application : {APP_VERSION} • Révision KHE : {LEGAL_CONTENT_REVISION} • Révision juridique : {profile.revision} • Juridiction : {profile.jurisdictionLabel}</Text><View style={styles.regionCard}><Text style={styles.regionTitle}>Cadre local — {profile.jurisdictionLabel}</Text><Text style={styles.regionBody}>Cadres pris en compte : {profile.frameworks.join(' · ')}.</Text><Text style={styles.regionBody}>{profile.detectedBy==='network'?'Version sélectionnée automatiquement selon le pays et, lorsque disponible, la région ou l’État associés à la connexion.':'Mode hors ligne : profil de secours basé sur la région de l’appareil. La version réseau sera resynchronisée dès que possible.'}</Text></View>
<Text style={styles.subheading}>1. Objet</Text><Text style={styles.paragraph}>KHE Booth est une application destinée à la capture, la gestion, la synchronisation, la visualisation, l’impression et le partage de contenus photo/vidéo lors d’événements. Certaines fonctions peuvent fonctionner hors ligne et synchroniser les contenus ultérieurement.</Text>
<Text style={styles.subheading}>2. Utilisation autorisée et responsabilité de l’utilisateur</Text><Text style={styles.paragraph}>L’utilisateur est responsable de la manière dont il configure et utilise l’application, du matériel employé, des personnes filmées ou photographiées, des contenus enregistrés et des destinations de partage ou d’impression. Il doit respecter les règles applicables en matière de droit à l’image, de vie privée, de protection des données, de propriété intellectuelle, de sécurité et d’accès aux réseaux.</Text>
<Text style={styles.subheading}>3. Consentement des personnes filmées ou photographiées</Text><Text style={styles.paragraph}>Avant toute captation, impression ou diffusion, l’organisateur ou l’utilisateur doit obtenir les autorisations nécessaires des personnes concernées lorsque la loi, le règlement du lieu ou le contexte de l’événement l’exige. KHE ne collecte pas ce consentement à la place de l’utilisateur.</Text>
<Text style={styles.subheading}>4. Contenus et usages interdits</Text><Text style={styles.paragraph}>L’application ne doit pas être utilisée pour enregistrer, surveiller, imprimer, diffuser ou partager des contenus de manière illicite, trompeuse, abusive, intrusive ou contraire aux droits de tiers. Toute utilisation détournée reste sous la responsabilité de son auteur.</Text>
<Text style={styles.subheading}>5. Données, stockage local et synchronisation</Text><Text style={styles.paragraph}>Les contenus peuvent être conservés localement sur la tablette avant synchronisation. L’utilisateur doit vérifier l’espace disponible, l’état de synchronisation et ses sauvegardes avant de supprimer un média, réinitialiser une station ou modifier son environnement réseau.</Text>
<Text style={styles.subheading}>6. Diagnostic technique automatique</Text><Text style={styles.paragraph}>Lorsqu’une erreur ou un plantage survient, KHE Booth peut conserver hors ligne puis transmettre au support KHE un rapport technique comprenant la version de l’application, le mode et les identifiants techniques de la station, la source de l’erreur, une trace filtrée et son contexte d’exécution. Les mots de passe, jetons, clés, cookies et adresses e-mail sont masqués automatiquement. Aucun contenu photo, vidéo ou audio n’est joint au rapport. Ces informations servent exclusivement au support, à la sécurité et à l’amélioration de la fiabilité.</Text>
<Text style={styles.subheading}>7. Réseau, appareils et services tiers</Text><Text style={styles.paragraph}>Certaines fonctions dépendent d’Android, du matériel, du réseau Internet, d’une imprimante ou de services tiers. Leur disponibilité, leurs performances et leurs limites peuvent varier. KHE ne peut pas garantir qu’un service externe ou un composant matériel sera disponible sans interruption.</Text>
<Text style={styles.subheading}>8. Limitation de responsabilité</Text><Text style={styles.paragraph}>Dans la mesure permise par la loi applicable, KHE n’est pas responsable d’une mauvaise utilisation de l’application par ses utilisateurs, d’une captation, impression ou diffusion non autorisée, d’une suppression volontaire de contenu, d’une configuration incorrecte, d’un appareil insuffisamment sécurisé ou d’un usage contraire aux présentes conditions. Cette clause ne limite pas les responsabilités qui ne peuvent légalement être exclues.</Text>
<Text style={styles.subheading}>9. Sécurité et fonctions facultatives</Text><Text style={styles.paragraph}>Les options d’anti-veille, mot de passe KHE, biométrie ou verrouillage système sont proposées comme fonctions de confort et de sécurité. Sauf nécessité particulière indiquée dans l’application, elles sont facultatives et leur refus ne doit pas empêcher la capture normale des médias.</Text>
<Text style={styles.subheading}>10. Langue, région et localisation</Text><Text style={styles.paragraph}>Lorsque le réseau est disponible, KHE Booth sélectionne le profil juridique à partir du pays et, lorsque le fournisseur d’hébergement le permet, de la région ou de l’État associés à la connexion. Aucun accès GPS précis n’est nécessaire pour cette sélection juridique. La localisation réseau reste indicative et ne remplace pas la détermination du domicile, de la résidence ou de l’établissement juridiquement pertinent.</Text>
<Text style={styles.subheading}>11. Mises à jour juridiques et fonctionnelles</Text><Text style={styles.paragraph}>Les profils juridiques sont versionnés côté serveur et peuvent être mis à jour indépendamment d’une nouvelle version de l’application. Si la révision applicable change, KHE Booth peut demander une nouvelle acceptation. Les changements réglementaires détectés font l’objet d’une revue avant publication afin d’éviter qu’une interprétation automatisée incorrecte ne devienne immédiatement contractuelle.</Text>
<Text style={styles.subheading}>12. Dispositions locales — {profile.jurisdictionLabel}</Text>{profile.termsAddendum.map(body=><Text key={body} style={styles.paragraph}>{body}</Text>)}<Text style={styles.subheading}>13. Acceptation</Text><Text style={styles.paragraph}>En appuyant sur « J’accepte », l’utilisateur confirme avoir lu et compris les conditions affichées pour la juridiction détectée et accepter de les respecter.</Text></View>;}

export function TermsGate({children}:{children:ReactNode}){const[introDone,setIntroDone]=useState(false);const[checking,setChecking]=useState(true);const[accepted,setAccepted]=useState(false);const[profile,setProfile]=useState<LegalPolicyProfile|null>(null);useEffect(()=>{void fetchLegalPolicyProfile().then(async resolvedProfile=>{setProfile(resolvedProfile);setAccepted(await hasAcceptedCurrentTerms(resolvedProfile));setChecking(false);});},[]);if(!introDone)return<StartupIntro onDone={()=>setIntroDone(true)}/>;if(checking||!profile)return<View style={styles.center}><ActivityIndicator/><Text>Synchronisation des conditions applicables…</Text></View>;if(!accepted)return<View style={styles.page}><ScrollView contentContainerStyle={styles.scroll}><Text style={styles.brand}>KHE</Text><Text style={styles.slogan}>Votre événement, notre expertise !</Text><TermsContent profile={profile}/><Pressable style={styles.acceptButton} onPress={()=>void acceptCurrentTerms(profile).then(()=>setAccepted(true))}><Text style={styles.acceptText}>J’ACCEPTE ET JE CONTINUE</Text></Pressable><Text style={styles.required}>L’acceptation de la révision juridique affichée est nécessaire pour utiliser KHE Booth.</Text></ScrollView></View>;return<>{children}</>;}

export function AboutAndTerms({onClose}:{onClose:()=>void}){const[release,setRelease]=useState<ReleaseInfo>({latestVersion:APP_VERSION,updateAvailable:false});const[profile,setProfile]=useState<LegalPolicyProfile>(()=>fallbackLegalProfile());useEffect(()=>{void fetchReleaseInfo().then(setRelease);void fetchLegalPolicyProfile().then(setProfile);},[]);return<View style={styles.page}><ScrollView contentContainerStyle={styles.scroll}><View style={styles.headerRow}><View style={{flex:1}}><Text style={styles.brand}>KHE BOOTH</Text><Text style={styles.slogan}>Votre événement, notre expertise !</Text></View><Pressable onPress={onClose} style={styles.closeButton}><Text style={styles.closeText}>Fermer</Text></Pressable></View><View style={styles.versionCard}><Text style={styles.versionTitle}>Version installée</Text><Text style={styles.versionNumber}>{APP_VERSION}</Text><Text style={styles.versionStatus}>{release.updateAvailable?`Nouvelle version disponible : ${release.latestVersion}`:'Application à jour'}</Text><Text style={styles.releaseNotes}>Révision juridique active : {profile.revision}</Text><Text style={styles.releaseNotes}>Juridiction détectée : {profile.jurisdictionLabel}</Text>{release.releaseNotes?<Text style={styles.releaseNotes}>{release.releaseNotes}</Text>:null}</View><TermsContent profile={profile}/></ScrollView></View>;}

const styles=StyleSheet.create({page:{flex:1,backgroundColor:'#101010'},scroll:{padding:24,paddingBottom:60,gap:16},center:{flex:1,alignItems:'center',justifyContent:'center',gap:12,padding:24},brand:{color:'#fff',fontSize:28,fontWeight:'900',letterSpacing:4},slogan:{color:'#d6d6d6',fontSize:16,fontWeight:'700',marginTop:4},headerRow:{flexDirection:'row',alignItems:'center',gap:12},closeButton:{borderWidth:1,borderColor:'#555',borderRadius:12,paddingHorizontal:14,paddingVertical:10},closeText:{color:'#fff',fontWeight:'800'},termsBody:{backgroundColor:'#fff',borderRadius:22,padding:22,gap:9},heading:{fontSize:24,fontWeight:'900',color:'#111'},revision:{fontSize:11,lineHeight:16,color:'#666'},regionCard:{backgroundColor:'#f3f3f3',borderRadius:14,padding:14,gap:5},regionTitle:{fontSize:13,fontWeight:'900',color:'#111'},regionBody:{fontSize:11,lineHeight:17,color:'#555'},subheading:{marginTop:7,fontSize:15,fontWeight:'900',color:'#111'},paragraph:{fontSize:13,lineHeight:20,color:'#333'},acceptButton:{backgroundColor:'#fff',borderRadius:16,padding:17,alignItems:'center'},acceptText:{color:'#111',fontWeight:'900'},required:{color:'#aaa',textAlign:'center',fontSize:11},versionCard:{backgroundColor:'#1c1c1f',borderRadius:18,padding:18,gap:5},versionTitle:{color:'#aaa',fontSize:11,fontWeight:'800',textTransform:'uppercase'},versionNumber:{color:'#fff',fontSize:28,fontWeight:'900'},versionStatus:{color:'#fff',fontWeight:'800'},releaseNotes:{color:'#c9c9c9',lineHeight:18,marginTop:4}});
