'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { apiRequest, getSessionUser } from '@/lib/api';

type Profile={displayName?:string;firstName?:string;lastName?:string;company?:string;role?:string;email?:string;phone?:string;address?:string;city?:string;country?:string;countryCode?:string;birthDate?:string|null;bio?:string;avatarPath?:string|null;source?:string;syncedAt?:string};
type Doc={id:string;documentType:string;originalFileName:string;status:string;uploadedAt:string;verifiedAt?:string|null;rejectionReason?:string|null;retentionDeleteAt?:string|null};
type Quote={id:string;quoteNumber:string;currency:string;userCount:number;monthlyCents:number;setupFeeCents:number;discountCents:number;status:string;createdAt:string};
type Onboarding={status:string;countryCode:string;desiredUsers:number;answers:Record<string,unknown>;submittedAt?:string|null;reviewNotes?:string|null;rejectionReason?:string|null;ownerApprovedAt?:string|null};
type Report={client:{name:string;email?:string|null;subscriptionPlan:string;paymentStatus:string};profile:Profile|null;onboarding:Onboarding|null;template?:{name:string;jurisdiction:string;legalReviewRequired:boolean}|null;documents:Doc[];quotes:Quote[];accessGate:{canEnablePlatform:boolean}};
type Offer={id:string;name:string;description:string;currency:string;baseMonthlyCents:number;setupFeeCents:number;includedUsers:number;extraUserMonthlyCents:number;features:string[];active:boolean};

const statusLabels:Record<string,string>={PAYMENT_PENDING:'Paiement en attente',FORM_AVAILABLE:'Formulaire disponible',FORM_SUBMITTED:'Formulaire envoyé',IDENTITY_PENDING:'Justificatifs requis',UNDER_REVIEW:'Revue agent KHE',CHANGES_REQUESTED:'Complément demandé',VERIFIED:'Vérifié par agent',APPROVED:'Approuvé par OWNER',REJECTED:'Refusé'};
const money=(cents:number,currency='CHF')=>new Intl.NumberFormat('fr-CH',{style:'currency',currency}).format(cents/100);
const majorToCents=(value:string)=>Math.max(0,Math.round((Number(value.replace(',','.'))||0)*100));

export function ClientEnterpriseOnboardingPanel({clientId,plan}:{clientId:string;plan:string}){
  const[report,setReport]=useState<Report|null>(null);const[offers,setOffers]=useState<Offer[]>([]);const[avatar,setAvatar]=useState<string|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');const[selectedOffer,setSelectedOffer]=useState('');const[userCount,setUserCount]=useState(1);const[monthlyAmount,setMonthlyAmount]=useState('');const[setupAmount,setSetupAmount]=useState('');const[discountAmount,setDiscountAmount]=useState('0');const[quoteNotes,setQuoteNotes]=useState('');const role=getSessionUser()?.role||'';const isOwner=role==='OWNER';
  const load=useCallback(async()=>{if(plan!=='ENTERPRISE')return;setError('');try{const [next,offerRows]=await Promise.all([apiRequest<Report>(`/clients/${clientId}/enterprise-onboarding`),apiRequest<Offer[]>('/clients/enterprise/offers/catalog')]);setReport(next);setOffers(offerRows.filter(item=>item.active));setUserCount(next.onboarding?.desiredUsers||1);if(next.profile?.avatarPath){const ticket=await apiRequest<{downloadUrl:string|null}>(`/clients/${clientId}/profile-avatar`);setAvatar(ticket.downloadUrl);}else setAvatar(null);}catch(caught){setError(caught instanceof Error?caught.message:'Dossier Enterprise indisponible.');}},[clientId,plan]);
  useEffect(()=>{void load();},[load]);
  const offer=useMemo(()=>offers.find(item=>item.id===selectedOffer)??null,[offers,selectedOffer]);
  useEffect(()=>{if(!offer)return;const calculated=offer.baseMonthlyCents+Math.max(0,userCount-offer.includedUsers)*offer.extraUserMonthlyCents;setMonthlyAmount((calculated/100).toFixed(2));setSetupAmount((offer.setupFeeCents/100).toFixed(2));setDiscountAmount('0.00');},[offer,userCount]);
  if(plan!=='ENTERPRISE')return null;

  async function invite(){setBusy(true);setError('');setMessage('');try{await apiRequest(`/clients/${clientId}/enterprise-onboarding/invite`,{method:'POST'});setMessage('Lien sécurisé envoyé au client par e-mail.');await load();}catch(caught){setError(caught instanceof Error?caught.message:'Invitation impossible.');}finally{setBusy(false);}}
  async function review(action:string){const promptLabel=action==='REJECT'?'Motif du refus':action==='REQUEST_CHANGES'?'Complément demandé au client':'Note interne / commentaire';const notes=window.prompt(promptLabel,'')??'';if(action==='REJECT'&&!notes.trim())return;setBusy(true);setError('');setMessage('');try{const next=await apiRequest<Report>(`/clients/${clientId}/enterprise-onboarding/review`,{method:'PATCH',body:JSON.stringify({action,notes})});setReport(next);setMessage(action==='APPROVE'?'Dossier approuvé par le OWNER. L’accès peut maintenant être activé.':'Décision enregistrée.');}catch(caught){setError(caught instanceof Error?caught.message:'Décision impossible.');}finally{setBusy(false);}}
  async function reviewDoc(doc:Doc,decision:'VERIFIED'|'REJECTED'){const reason=decision==='REJECTED'?(window.prompt('Motif du rejet du document','')??''):'';if(decision==='REJECTED'&&!reason.trim())return;setBusy(true);try{await apiRequest(`/clients/${clientId}/enterprise-documents/${doc.id}`,{method:'PATCH',body:JSON.stringify({decision,reason})});await load();}catch(caught){setError(caught instanceof Error?caught.message:'Vérification impossible.');}finally{setBusy(false);}}
  async function openDoc(doc:Doc){try{const ticket=await apiRequest<{downloadUrl:string}>(`/clients/${clientId}/enterprise-documents/${doc.id}`);window.open(ticket.downloadUrl,'_blank','noopener,noreferrer');}catch(caught){setError(caught instanceof Error?caught.message:'Ouverture impossible.');}}
  async function quote(){if(!selectedOffer)return;setBusy(true);setError('');setMessage('');try{const created=await apiRequest<Quote>(`/clients/${clientId}/enterprise-quotes`,{method:'POST',body:JSON.stringify({offerTemplateId:selectedOffer,userCount,monthlyCents:majorToCents(monthlyAmount),setupFeeCents:majorToCents(setupAmount),discountCents:majorToCents(discountAmount),notes:quoteNotes})});setMessage(`Devis ${created.quoteNumber} créé. Vérifie-le puis utilise « Envoyer & paiement ».`);await load();}catch(caught){setError(caught instanceof Error?caught.message:'Devis impossible.');}finally{setBusy(false);}}
  async function sendQuote(item:Quote){if(!window.confirm(`Envoyer le devis ${item.quoteNumber} et son lien de paiement sécurisé au client ?`))return;setBusy(true);setError('');setMessage('');try{await apiRequest(`/clients/${clientId}/enterprise-quotes/${item.id}/send`,{method:'POST'});setMessage(`Devis ${item.quoteNumber} envoyé au client. Aucun paiement n’est exécuté par KHE : le client décide et paie lui-même sur Stripe.`);await load();}catch(caught){setError(caught instanceof Error?caught.message:'Envoi du devis impossible.');}finally{setBusy(false);}}

  const onboarding=report?.onboarding;return <section className="card" style={{marginTop:16,border:'1px solid rgba(210,173,79,.45)',background:'linear-gradient(145deg,#10151b,#17130b)'}}>
    <div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'flex-start',flexWrap:'wrap'}}><div><div className="eyebrow" style={{color:'#d2ad4f'}}>IDENTITÉ & ONBOARDING ENTERPRISE</div><h2 style={{margin:'6px 0'}}>Dossier de vérification</h2><p className="muted">Devis/paiement → formulaire pays → justificatifs → agent KHE → approbation OWNER → accès.</p></div><span style={{padding:'8px 12px',borderRadius:999,background:onboarding?.status==='APPROVED'?'#143621':'#2e2715',color:onboarding?.status==='APPROVED'?'#91e4ac':'#eed47c',fontWeight:900,fontSize:12}}>{statusLabels[onboarding?.status||'PAYMENT_PENDING']||onboarding?.status||'À démarrer'}</span></div>
    {error?<p className="error">{error}</p>:null}{message?<p className="success">{message}</p>:null}
    {report?<>
      <div style={{display:'grid',gridTemplateColumns:'minmax(160px,210px) 1fr',gap:18,marginTop:16,alignItems:'start'}}><div style={{border:'1px solid #343b45',borderRadius:16,padding:14,textAlign:'center',background:'#0d1116'}}>{avatar?<img src={avatar} alt="Profil client" style={{width:116,height:116,borderRadius:'50%',objectFit:'cover',border:'2px solid #d2ad4f'}}/>:<div style={{width:116,height:116,borderRadius:'50%',margin:'0 auto',display:'grid',placeItems:'center',background:'#252b33',fontSize:40}}>👤</div>}<div style={{fontWeight:950,marginTop:10}}>{report.profile?.displayName||report.client.name}</div><div className="muted" style={{fontSize:12,marginTop:4}}>{report.profile?.source?`Synchronisé depuis ${report.profile.source}`:'Profil KHE Client'}</div></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:10}}>{[['Entreprise',report.profile?.company],['Fonction',report.profile?.role],['E-mail',report.profile?.email||report.client.email],['Téléphone',report.profile?.phone],['Adresse',report.profile?.address],['Ville / pays',[report.profile?.city,report.profile?.country].filter(Boolean).join(' · ')],['Pays formulaire',onboarding?.countryCode],['Utilisateurs prévus',onboarding?.desiredUsers]].map(([label,value])=><div key={String(label)} style={{padding:12,border:'1px solid #303843',borderRadius:12}}><small className="eyebrow">{label}</small><div style={{fontWeight:800,marginTop:5}}>{String(value||'À compléter')}</div></div>)}</div></div>
      <div className="toolbar" style={{marginTop:16}}><button className="button" type="button" disabled={busy||report.client.paymentStatus!=='PAID'} onClick={()=>void invite()}>Envoyer / renouveler le lien du formulaire</button><button className="button secondary" type="button" disabled={busy} onClick={()=>void load()}>↻ Actualiser</button></div>

      <h3 style={{marginTop:24}}>Justificatifs</h3>{report.documents.length===0?<p className="muted">Aucun justificatif reçu.</p>:<div style={{display:'grid',gap:8}}>{report.documents.map(doc=><div key={doc.id} style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,border:'1px solid #303943',borderRadius:12,padding:'11px 13px',flexWrap:'wrap'}}><div><strong>{doc.originalFileName}</strong><div className="muted" style={{fontSize:12}}>{doc.documentType} · {new Date(doc.uploadedAt).toLocaleString('fr-CH')} · {doc.status}</div>{doc.retentionDeleteAt?<div className="muted" style={{fontSize:11}}>Suppression de la copie prévue : {new Date(doc.retentionDeleteAt).toLocaleDateString('fr-CH')}</div>:null}</div><div className="toolbar"><button className="button secondary compact" type="button" onClick={()=>void openDoc(doc)}>Voir</button>{doc.status!=='VERIFIED'?<button className="button compact" type="button" disabled={busy} onClick={()=>void reviewDoc(doc,'VERIFIED')}>Valider</button>:null}{doc.status!=='REJECTED'?<button className="button danger compact" type="button" disabled={busy} onClick={()=>void reviewDoc(doc,'REJECTED')}>Rejeter</button>:null}</div></div>)}</div>}

      <h3 style={{marginTop:24}}>Décision KHE</h3><div className="toolbar"><button className="button" type="button" disabled={busy||!onboarding||onboarding.status!=='UNDER_REVIEW'} onClick={()=>void review('VERIFY')}>Marquer vérifié par l’agent</button><button className="button secondary" type="button" disabled={busy||!onboarding} onClick={()=>void review('REQUEST_CHANGES')}>Demander un complément</button><button className="button danger" type="button" disabled={busy||!onboarding} onClick={()=>void review('REJECT')}>Refuser</button>{isOwner?<button className="button" type="button" disabled={busy||onboarding?.status!=='VERIFIED'} onClick={()=>void review('APPROVE')}>Approuver en tant que OWNER</button>:null}</div><p className="muted" style={{fontSize:12}}>Accès plateforme actuellement : <strong>{report.accessGate.canEnablePlatform?'AUTORISABLE PAR LE OWNER':'BLOQUÉ PAR LE CONTRÔLE KHE'}</strong>.</p>

      <h3 style={{marginTop:24}}>Offre et devis Enterprise</h3><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10,alignItems:'end'}}><div className="field" style={{gridColumn:'span 2'}}><label>Offre de départ</label><select value={selectedOffer} onChange={(e)=>setSelectedOffer(e.target.value)}><option value="">Choisir une offre…</option>{offers.map(item=><option key={item.id} value={item.id}>{item.name} · {money(item.baseMonthlyCents,item.currency)}/mois · {item.includedUsers} utilisateurs inclus</option>)}</select></div><div className="field"><label>Utilisateurs</label><input type="number" min={1} max={10000} value={userCount} onChange={(e)=>setUserCount(Math.max(1,Number(e.target.value)||1))}/></div><div className="field"><label>Mensuel proposé</label><input inputMode="decimal" value={monthlyAmount} onChange={(e)=>setMonthlyAmount(e.target.value)}/></div><div className="field"><label>Mise en place</label><input inputMode="decimal" value={setupAmount} onChange={(e)=>setSetupAmount(e.target.value)}/></div><div className="field"><label>Remise mensuelle</label><input inputMode="decimal" value={discountAmount} onChange={(e)=>setDiscountAmount(e.target.value)}/></div><div className="field" style={{gridColumn:'1 / -1'}}><label>Notes du devis</label><textarea rows={3} value={quoteNotes} onChange={(e)=>setQuoteNotes(e.target.value)} placeholder="SLA, options, déploiement, intégrations ou conditions particulières…"/></div><button className="button" type="button" disabled={busy||!selectedOffer} onClick={()=>void quote()}>Créer le devis sur mesure</button></div>
      {report.quotes.length?<div style={{overflowX:'auto',marginTop:12}}><table className="table"><thead><tr><th>Devis</th><th>Utilisateurs</th><th>Mensuel</th><th>Mise en place</th><th>Statut</th><th>Action</th></tr></thead><tbody>{report.quotes.map(item=><tr key={item.id}><td>{item.quoteNumber}</td><td>{item.userCount}</td><td>{money(Math.max(0,item.monthlyCents-item.discountCents),item.currency)}</td><td>{money(item.setupFeeCents,item.currency)}</td><td>{item.status}</td><td>{['DRAFT','SENT'].includes(item.status)?<button className="button secondary compact" type="button" disabled={busy} onClick={()=>void sendQuote(item)}>{item.status==='SENT'?'Renvoyer lien paiement':'Envoyer & paiement'}</button>:'—'}</td></tr>)}</tbody></table></div>:null}
    </>:null}
  </section>;
}
