'use client';

import { useCallback, useEffect, useState } from 'react';
import { apiRequest } from '@/lib/api';

type Step={key:string;label:string;status:'TODO'|'WAITING'|'IN_PROGRESS'|'DONE'|'BLOCKED'|'AVAILABLE';ownerCanAct:boolean;clientMustAct:boolean;detail:string};
type Journey={client:{name:string;paymentStatus:string};quote?:{quoteNumber:string;contractTermMonths:number;annualCents:number;totalContractCents:number;currency:string}|null;contract?:{contractNumber:string;status:string;signedAt?:string|null;termMonths:number}|null;accessEnabled:boolean;steps:Step[]};
const palette:Record<string,{bg:string;border:string;color:string;label:string}>={DONE:{bg:'#10291a',border:'#2f6d46',color:'#95e8b0',label:'VALIDÉ'},IN_PROGRESS:{bg:'#17233a',border:'#385f9d',color:'#a9c9ff',label:'EN COURS'},WAITING:{bg:'#2a2413',border:'#6b5625',color:'#efd77d',label:'EN ATTENTE'},AVAILABLE:{bg:'#2b1d0d',border:'#9a6d22',color:'#ffd477',label:'ACTION OWNER'},BLOCKED:{bg:'#281719',border:'#704049',color:'#ffaaaa',label:'BLOQUÉ'},TODO:{bg:'#191d22',border:'#39414b',color:'#c5cbd3',label:'À FAIRE'}};

export function ClientEnterpriseJourneyPanel({clientId,plan}:{clientId:string;plan:string}){
  const[data,setData]=useState<Journey|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
  const load=useCallback(async()=>{if(plan!=='ENTERPRISE')return;setLoading(true);setError('');try{setData(await apiRequest<Journey>(`/clients/${clientId}/enterprise-journey`));}catch(caught){setError(caught instanceof Error?caught.message:'Parcours Enterprise indisponible.');}finally{setLoading(false);}},[clientId,plan]);
  useEffect(()=>{void load();},[load]);if(plan!=='ENTERPRISE')return null;
  const completed=data?.steps.filter(step=>step.status==='DONE').length??0;const total=data?.steps.length??8;const progress=Math.round((completed/Math.max(1,total))*100);
  return <section className="card" style={{marginTop:16,border:'1px solid rgba(210,173,79,.42)',background:'linear-gradient(145deg,#10141a,#17130b)'}}>
    <div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',gap:16,flexWrap:'wrap'}}><div><div className="eyebrow" style={{color:'#d2ad4f'}}>SUIVI CLIENT ENTERPRISE</div><h2 style={{margin:'6px 0'}}>Parcours & accompagnement</h2><p className="muted" style={{maxWidth:760}}>Vue OWNER synchronisée du devis jusqu’à l’activation. Le contrat est la seule étape que KHE ne peut jamais valider à la place du client.</p></div><button className="button secondary" type="button" disabled={loading} onClick={()=>void load()}>↻ Actualiser</button></div>
    {error?<p className="error">{error}</p>:null}
    <div style={{marginTop:14,height:9,borderRadius:999,background:'#242a31',overflow:'hidden'}}><div style={{height:'100%',width:`${progress}%`,background:'linear-gradient(90deg,#8b651e,#e1c061)',transition:'width .35s ease'}}/></div><div className="muted" style={{fontSize:12,marginTop:6}}>{completed}/{total} étapes validées · {progress}%</div>
    <div style={{display:'grid',gap:10,marginTop:18}}>{data?.steps.map((step,index)=>{const p=palette[step.status]||palette.TODO;return <div key={step.key} style={{display:'grid',gridTemplateColumns:'48px minmax(0,1fr) auto',gap:12,alignItems:'center',padding:'13px 14px',border:`1px solid ${p.border}`,borderRadius:14,background:p.bg}}><div style={{width:38,height:38,borderRadius:'50%',display:'grid',placeItems:'center',fontWeight:950,border:`1px solid ${p.border}`,color:p.color}}>{step.status==='DONE'?'✓':String(index+1).padStart(2,'0')}</div><div><strong>{step.label}</strong><div className="muted" style={{fontSize:12,marginTop:4}}>{step.detail}</div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:6}}>{step.clientMustAct?<span style={{fontSize:10,fontWeight:900,color:'#f0d37a'}}>ACTION CLIENT</span>:null}{step.ownerCanAct?<span style={{fontSize:10,fontWeight:900,color:'#a9c9ff'}}>ACCOMPAGNEMENT KHE</span>:null}{step.key==='CONTRACT'?<span style={{fontSize:10,fontWeight:900,color:'#ffb5b5'}}>SIGNATURE CLIENT UNIQUEMENT</span>:null}</div></div><span style={{padding:'6px 9px',borderRadius:999,border:`1px solid ${p.border}`,color:p.color,fontSize:10,fontWeight:950,whiteSpace:'nowrap'}}>{p.label}</span></div>;})}</div>
    {data?.quote?<div style={{marginTop:16,padding:13,border:'1px solid #323945',borderRadius:13,display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',gap:10}}><div><small className="eyebrow">DEVIS</small><div style={{fontWeight:900}}>{data.quote.quoteNumber}</div></div><div><small className="eyebrow">ENGAGEMENT</small><div style={{fontWeight:900}}>{data.quote.contractTermMonths} mois</div></div><div><small className="eyebrow">FACTURATION</small><div style={{fontWeight:900}}>Annuelle</div></div><div><small className="eyebrow">ACCÈS</small><div style={{fontWeight:900,color:data.accessEnabled?'#91e4ac':'#e4c86e'}}>{data.accessEnabled?'ACTIF':'NON ACTIF'}</div></div></div>:null}
  </section>;
}
