'use client';

import { useCallback, useEffect, useState } from 'react';
import { apiRequest } from '@/lib/api';

type Template={id:string;code:string;name:string;jurisdiction:string;countryCodes:string[];fields:unknown[];identityRequirements:Record<string,unknown>;privacyNotice:string;retentionPolicy:Record<string,unknown>;legalReviewRequired:boolean;active:boolean;version:number};
type Offer={id:string;code:string;name:string;description:string;currency:string;baseMonthlyCents:number;setupFeeCents:number;includedUsers:number;extraUserMonthlyCents:number;features:string[];active:boolean};

export function EnterpriseFormConfigPanel(){
  const[templates,setTemplates]=useState<Template[]>([]);const[offers,setOffers]=useState<Offer[]>([]);const[selectedTemplate,setSelectedTemplate]=useState('');const[selectedOffer,setSelectedOffer]=useState('');const[templateDraft,setTemplateDraft]=useState('');const[offerDraft,setOfferDraft]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');
  const load=useCallback(async()=>{setError('');try{const[t,o]=await Promise.all([apiRequest<Template[]>('/clients/enterprise/forms/templates'),apiRequest<Offer[]>('/clients/enterprise/offers/catalog')]);setTemplates(t);setOffers(o);if(!selectedTemplate&&t[0]){setSelectedTemplate(t[0].id);setTemplateDraft(JSON.stringify(t[0],null,2));}if(!selectedOffer&&o[0]){setSelectedOffer(o[0].id);setOfferDraft(JSON.stringify(o[0],null,2));}}catch(caught){setError(caught instanceof Error?caught.message:'Configuration Enterprise indisponible.');}},[selectedTemplate,selectedOffer]);
  useEffect(()=>{void load();},[load]);

  function chooseTemplate(id:string){setSelectedTemplate(id);const item=templates.find(row=>row.id===id);setTemplateDraft(item?JSON.stringify(item,null,2):'');setMessage('');setError('');}
  function chooseOffer(id:string){setSelectedOffer(id);const item=offers.find(row=>row.id===id);setOfferDraft(item?JSON.stringify(item,null,2):'');setMessage('');setError('');}
  async function saveTemplate(){setBusy(true);setError('');setMessage('');try{const parsed=JSON.parse(templateDraft) as Template;const next=await apiRequest<Template>(`/clients/enterprise/forms/templates/${selectedTemplate}`,{method:'PATCH',body:JSON.stringify({name:parsed.name,fields:parsed.fields,identityRequirements:parsed.identityRequirements,privacyNotice:parsed.privacyNotice,retentionPolicy:parsed.retentionPolicy,legalReviewRequired:parsed.legalReviewRequired,active:parsed.active})});setMessage(`Formulaire ${next.name} enregistré · version ${next.version}.`);setSelectedTemplate(next.id);setTemplateDraft(JSON.stringify(next,null,2));await load();}catch(caught){setError(caught instanceof Error?caught.message:'Enregistrement du formulaire impossible.');}finally{setBusy(false);}}
  async function saveOffer(){setBusy(true);setError('');setMessage('');try{const parsed=JSON.parse(offerDraft) as Offer;const next=await apiRequest<Offer>(`/clients/enterprise/offers/catalog/${selectedOffer}`,{method:'PATCH',body:JSON.stringify({name:parsed.name,description:parsed.description,currency:parsed.currency,baseMonthlyCents:parsed.baseMonthlyCents,setupFeeCents:parsed.setupFeeCents,includedUsers:parsed.includedUsers,extraUserMonthlyCents:parsed.extraUserMonthlyCents,features:parsed.features,active:parsed.active})});setMessage(`Offre ${next.name} enregistrée.`);setSelectedOffer(next.id);setOfferDraft(JSON.stringify(next,null,2));await load();}catch(caught){setError(caught instanceof Error?caught.message:'Enregistrement de l’offre impossible.');}finally{setBusy(false);}}

  return <section className="card" style={{marginTop:16,border:'1px solid rgba(210,173,79,.42)',background:'linear-gradient(145deg,#10151b,#17130b)'}}>
    <div className="eyebrow" style={{color:'#d2ad4f'}}>PARAMÉTRAGE ENTERPRISE • OWNER</div><h2 style={{margin:'6px 0'}}>Formulaires pays & offres sur mesure</h2><p className="muted">Ces réglages déterminent ce que le client voit après paiement. Les modèles pays sont éditables pour permettre une validation juridique locale sans devoir modifier le code.</p>
    {error?<p className="error">{error}</p>:null}{message?<p className="success">{message}</p>:null}
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(340px,1fr))',gap:16}}>
      <div style={{padding:15,border:'1px solid #303944',borderRadius:15,background:'#0e1217'}}><h3>Formulaire et règles pays</h3><div className="field"><label>Modèle</label><select value={selectedTemplate} onChange={(e)=>chooseTemplate(e.target.value)}>{templates.map(item=><option key={item.id} value={item.id}>{item.name} · {item.jurisdiction} · v{item.version}</option>)}</select></div><p className="muted" style={{fontSize:12}}>Modifiez le JSON : <code>fields</code> contrôle les champs, <code>identityRequirements</code> les pièces demandées, <code>privacyNotice</code> le texte client et <code>retentionPolicy</code> la conservation. KHE conserve l’historique via le numéro de version.</p><textarea value={templateDraft} onChange={(e)=>setTemplateDraft(e.target.value)} spellCheck={false} style={{width:'100%',minHeight:430,boxSizing:'border-box',border:'1px solid #39414c',borderRadius:12,background:'#080b0f',color:'#dce2e9',fontFamily:'monospace',fontSize:12,padding:12}}/><div className="toolbar" style={{marginTop:10}}><button className="button" type="button" disabled={busy||!selectedTemplate} onClick={()=>void saveTemplate()}>Enregistrer le formulaire</button></div></div>
      <div style={{padding:15,border:'1px solid #303944',borderRadius:15,background:'#0e1217'}}><h3>Catalogue d’offres Enterprise</h3><div className="field"><label>Offre</label><select value={selectedOffer} onChange={(e)=>chooseOffer(e.target.value)}>{offers.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></div><p className="muted" style={{fontSize:12}}>Les montants sont stockés en centimes : <strong>14900 = CHF 149.00</strong>. Le devis calcule automatiquement les utilisateurs supplémentaires, puis tu peux le personnaliser dans le dossier client.</p><textarea value={offerDraft} onChange={(e)=>setOfferDraft(e.target.value)} spellCheck={false} style={{width:'100%',minHeight:430,boxSizing:'border-box',border:'1px solid #39414c',borderRadius:12,background:'#080b0f',color:'#dce2e9',fontFamily:'monospace',fontSize:12,padding:12}}/><div className="toolbar" style={{marginTop:10}}><button className="button" type="button" disabled={busy||!selectedOffer} onClick={()=>void saveOffer()}>Enregistrer l’offre</button></div></div>
    </div>
  </section>;
}
