'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { apiRequest } from '@/lib/api';

type Language = 'fr'|'en'|'de'|'it'|'es'|'pt';
type Level = 'PASS'|'WARN'|'BLOCK'|'INFO';
type Station = {id:string;mode:'CAPTURE'|'SHARING';deviceName:string|null;platform:string|null;lastSeenAt:string;ageSeconds:number;online:boolean;stale:boolean};
type Check = {id:string;level:Level;detail:string};
type Snapshot = {
  generatedAt:string;
  state:'READY'|'ATTENTION'|'BLOCKED';
  event:{id:string;name:string;status:string;startsAt:string;endsAt:string|null};
  stations:Station[];
  media:{queued:number;uploading:number;failed:number;synced:number;pending:number};
  remote:{runtimeState:string;captureSeenAt:string|null;sharingConnectionStatus:string}|null;
  checks:Check[];
  alerts:Array<{level:'warning'|'critical';code:string;message:string}>;
  recommendedAction:string;
};

type Copy={title:string;subtitle:string;refresh:string;updated:string;capture:string;sharing:string;online:string;quiet:string;offline:string;sync:string;synced:string;pending:string;failed:string;checks:string;unknown:string;tablet:string;emergency:string;emergencyText:string;choose:string;camera:string;share:string;print:string;network:string;station:string;syncIssue:string;other:string;send:string;sending:string;sent:string;agent:string;ready:string;attention:string;blocked:string;openHelp:string};
const COPY:Record<Language,Copy>={
fr:{title:'KHE Event Ready',subtitle:'État opérationnel réel de l’événement et des stations.',refresh:'Actualiser',updated:'Mis à jour',capture:'CAPTURE',sharing:'SHARING',online:'Connectée',quiet:'Silencieuse',offline:'Hors ligne',sync:'Synchronisation',synced:'synchronisés',pending:'en attente',failed:'en échec',checks:'Contrôles pré-événement',unknown:'À confirmer sur la tablette',tablet:'Ouvrez Event Ready sur la tablette pour transmettre ce contrôle matériel.',emergency:'Assistance événement en cours',emergencyText:'Priorité à la conservation des médias. Choisissez le problème : KHE transmettra le contexte à un agent.',choose:'Type de problème',camera:'Caméra / vidéo',share:'Partage / QR',print:'Impression',network:'Internet / réseau',station:'Station CAPTURE / SHARING',syncIssue:'Synchronisation',other:'Autre',send:'Demander une assistance prioritaire',sending:'Transmission…',sent:'Demande prioritaire transmise.',agent:'Un agent KHE reçoit le contexte de cet événement.',ready:'PRÊT',attention:'À VÉRIFIER',blocked:'ACTION REQUISE',openHelp:'Ouvrir la messagerie'},
en:{title:'KHE Event Ready',subtitle:'Live operational status for this event and its stations.',refresh:'Refresh',updated:'Updated',capture:'CAPTURE',sharing:'SHARING',online:'Online',quiet:'Quiet',offline:'Offline',sync:'Synchronization',synced:'synced',pending:'pending',failed:'failed',checks:'Pre-event checks',unknown:'Confirm on tablet',tablet:'Open Event Ready on the tablet to report this hardware check.',emergency:'Live event assistance',emergencyText:'Protect captured media first. Choose the issue and KHE will send the context to an agent.',choose:'Issue type',camera:'Camera / video',share:'Sharing / QR',print:'Printing',network:'Internet / network',station:'CAPTURE / SHARING station',syncIssue:'Synchronization',other:'Other',send:'Request priority assistance',sending:'Sending…',sent:'Priority request sent.',agent:'A KHE agent receives this event context.',ready:'READY',attention:'CHECK',blocked:'ACTION REQUIRED',openHelp:'Open messaging'},
de:{title:'KHE Event Ready',subtitle:'Live-Betriebsstatus für Event und Stationen.',refresh:'Aktualisieren',updated:'Aktualisiert',capture:'CAPTURE',sharing:'SHARING',online:'Verbunden',quiet:'Still',offline:'Offline',sync:'Synchronisierung',synced:'synchronisiert',pending:'ausstehend',failed:'fehlgeschlagen',checks:'Vorabprüfungen',unknown:'Am Tablet bestätigen',tablet:'Öffnen Sie Event Ready am Tablet, um diesen Hardware-Check zu melden.',emergency:'Hilfe beim laufenden Event',emergencyText:'Aufgenommene Medien zuerst schützen. Problem wählen; KHE sendet den Kontext an einen Agenten.',choose:'Problemtyp',camera:'Kamera / Video',share:'Sharing / QR',print:'Drucken',network:'Internet / Netzwerk',station:'CAPTURE / SHARING Station',syncIssue:'Synchronisierung',other:'Andere',send:'Prioritätshilfe anfordern',sending:'Senden…',sent:'Prioritätsanfrage gesendet.',agent:'Ein KHE-Agent erhält den Event-Kontext.',ready:'BEREIT',attention:'PRÜFEN',blocked:'AKTION ERFORDERLICH',openHelp:'Nachrichten öffnen'},
it:{title:'KHE Event Ready',subtitle:'Stato operativo reale dell’evento e delle stazioni.',refresh:'Aggiorna',updated:'Aggiornato',capture:'CAPTURE',sharing:'SHARING',online:'Connessa',quiet:'Silenziosa',offline:'Offline',sync:'Sincronizzazione',synced:'sincronizzati',pending:'in attesa',failed:'in errore',checks:'Controlli pre-evento',unknown:'Conferma sul tablet',tablet:'Apri Event Ready sul tablet per inviare questo controllo hardware.',emergency:'Assistenza evento in corso',emergencyText:'Proteggi prima i media acquisiti. Scegli il problema e KHE invierà il contesto a un agente.',choose:'Tipo di problema',camera:'Fotocamera / video',share:'Condivisione / QR',print:'Stampa',network:'Internet / rete',station:'Stazione CAPTURE / SHARING',syncIssue:'Sincronizzazione',other:'Altro',send:'Richiedi assistenza prioritaria',sending:'Invio…',sent:'Richiesta prioritaria inviata.',agent:'Un agente KHE riceve il contesto dell’evento.',ready:'PRONTO',attention:'CONTROLLARE',blocked:'AZIONE RICHIESTA',openHelp:'Apri messaggi'},
es:{title:'KHE Event Ready',subtitle:'Estado operativo real del evento y las estaciones.',refresh:'Actualizar',updated:'Actualizado',capture:'CAPTURE',sharing:'SHARING',online:'Conectada',quiet:'Sin actividad',offline:'Sin conexión',sync:'Sincronización',synced:'sincronizados',pending:'pendientes',failed:'con error',checks:'Comprobaciones previas',unknown:'Confirmar en tableta',tablet:'Abre Event Ready en la tableta para enviar esta comprobación de hardware.',emergency:'Asistencia durante el evento',emergencyText:'Protege primero los medios capturados. Elige el problema y KHE enviará el contexto a un agente.',choose:'Tipo de problema',camera:'Cámara / vídeo',share:'Compartir / QR',print:'Impresión',network:'Internet / red',station:'Estación CAPTURE / SHARING',syncIssue:'Sincronización',other:'Otro',send:'Solicitar asistencia prioritaria',sending:'Enviando…',sent:'Solicitud prioritaria enviada.',agent:'Un agente KHE recibe el contexto del evento.',ready:'LISTO',attention:'REVISAR',blocked:'ACCIÓN NECESARIA',openHelp:'Abrir mensajes'},
pt:{title:'KHE Event Ready',subtitle:'Estado operacional real do evento e das estações.',refresh:'Atualizar',updated:'Atualizado',capture:'CAPTURE',sharing:'SHARING',online:'Ligada',quiet:'Sem atividade',offline:'Offline',sync:'Sincronização',synced:'sincronizados',pending:'pendentes',failed:'com erro',checks:'Verificações pré-evento',unknown:'Confirmar no tablet',tablet:'Abra Event Ready no tablet para enviar esta verificação de hardware.',emergency:'Assistência durante o evento',emergencyText:'Proteja primeiro os conteúdos captados. Escolha o problema e KHE enviará o contexto a um agente.',choose:'Tipo de problema',camera:'Câmara / vídeo',share:'Partilha / QR',print:'Impressão',network:'Internet / rede',station:'Estação CAPTURE / SHARING',syncIssue:'Sincronização',other:'Outro',send:'Pedir assistência prioritária',sending:'A enviar…',sent:'Pedido prioritário enviado.',agent:'Um agente KHE recebe o contexto do evento.',ready:'PRONTO',attention:'VERIFICAR',blocked:'AÇÃO NECESSÁRIA',openHelp:'Abrir mensagens'}
};
function readLanguage():Language{if(typeof window==='undefined')return'fr';const v=localStorage.getItem('khe.web.language');return v&&v in COPY?v as Language:'fr';}
const levelSymbol:Record<Level,string>={PASS:'✓',WARN:'!',BLOCK:'×',INFO:'•'};
const levelStyle:Record<Level,{background:string;color:string;border:string}>={PASS:{background:'rgba(48,164,92,.12)',color:'#97e6b2',border:'rgba(90,205,126,.3)'},WARN:{background:'rgba(219,169,51,.12)',color:'#f0cf78',border:'rgba(219,169,51,.35)'},BLOCK:{background:'rgba(211,72,72,.12)',color:'#ffaaaa',border:'rgba(211,72,72,.35)'},INFO:{background:'rgba(255,255,255,.04)',color:'#b9c0c9',border:'rgba(255,255,255,.09)'}};
const checkNames:Record<string,string>={studio:'Studio',capture:'CAPTURE',sharing:'SHARING',sync:'Cloud Sync','station-link':'CAPTURE ↔ SHARING',camera:'Caméra',microphone:'Microphone',battery:'Batterie',storage:'Stockage',network:'Réseau',printer:'Imprimante','test-photo':'Test photo','test-video':'Test vidéo','guest-qr':'QR invité'};

export function EventReadyMonitor({eventId}:Readonly<{eventId:string}>){
 const[language,setLanguage]=useState<Language>('fr');const[snapshot,setSnapshot]=useState<Snapshot|null>(null);const[error,setError]=useState('');const[loading,setLoading]=useState(true);const[issue,setIssue]=useState('camera');const[sending,setSending]=useState(false);const[sent,setSent]=useState(false);const t=COPY[language];
 const load=useCallback(async()=>{try{setError('');setSnapshot(await apiRequest<Snapshot>(`/events/${eventId}/readiness`));}catch(e){setError(e instanceof Error?e.message:'Event Ready unavailable');}finally{setLoading(false);}},[eventId]);
 useEffect(()=>{setLanguage(readLanguage());const h=(event:Event)=>{const d=(event as CustomEvent<string>).detail;if(d&&d in COPY)setLanguage(d as Language);};window.addEventListener('khe-language-changed',h);void load();const timer=window.setInterval(()=>void load(),10_000);return()=>{window.removeEventListener('khe-language-changed',h);window.clearInterval(timer);};},[load]);
 const stations=useMemo(()=>({CAPTURE:snapshot?.stations.find(s=>s.mode==='CAPTURE'),SHARING:snapshot?.stations.find(s=>s.mode==='SHARING')}),[snapshot]);
 async function emergency(){if(!snapshot)return;setSending(true);setSent(false);try{const label:{[key:string]:string}={camera:'Caméra / vidéo',sharing:'Partage / QR',print:'Impression',network:'Internet / réseau',station:'Station CAPTURE / SHARING',sync:'Synchronisation',other:'Autre'};const message=`URGENCE ÉVÉNEMENT EN COURS — ${snapshot.event.name}\nType: ${label[issue]??issue}\nÉtat Event Ready: ${snapshot.state}\nStations: ${snapshot.stations.map(s=>`${s.mode} ${s.online?'ONLINE':s.stale?'STALE':'QUIET'} (${s.ageSeconds}s)`).join(', ')||'aucune'}\nSynchronisation: ${snapshot.media.pending} en attente, ${snapshot.media.failed} en échec.\nPriorité: préserver les médias capturés et rétablir la prestation.`;const conversation=await apiRequest<{id:string}>('/support/conversations',{method:'POST',body:JSON.stringify({message})});await apiRequest(`/support/conversations/${conversation.id}/request-agent`,{method:'POST'});setSent(true);}catch(e){setError(e instanceof Error?e.message:'Support unavailable');}finally{setSending(false);}}
 function StationCard({mode}:{mode:'CAPTURE'|'SHARING'}){const s=stations[mode];const state=!s?'offline':s.online?'online':s.stale?'offline':'quiet';const label=state==='online'?t.online:state==='quiet'?t.quiet:t.offline;return <article style={{padding:18,borderRadius:20,border:'1px solid rgba(255,255,255,.08)',background:'linear-gradient(145deg,rgba(255,255,255,.055),rgba(255,255,255,.018))'}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:10}}><strong>{mode==='CAPTURE'?t.capture:t.sharing}</strong><span style={{fontSize:12,fontWeight:800,color:state==='online'?'#91e7ad':state==='quiet'?'#f0cf78':'#ff9f9f'}}>● {label}</span></div><div className="muted" style={{marginTop:10}}>{s?(s.deviceName||s.platform||'KHE station'):'—'}</div>{s?<div className="muted" style={{fontSize:12,marginTop:4}}>{s.ageSeconds}s</div>:null}</article>}
 if(loading)return <section className="card"><div className="muted">KHE Event Ready…</div></section>;
 return <div style={{display:'grid',gap:18}}>
  <section className="card" style={{padding:24,border:'1px solid rgba(210,173,79,.28)',background:'radial-gradient(circle at 90% 0%,rgba(210,173,79,.13),transparent 35%),linear-gradient(145deg,#12171e,#0c1015)'}}>
   <div style={{display:'flex',alignItems:'flex-start',justifyContent:'space-between',gap:16,flexWrap:'wrap'}}><div><div className="muted" style={{fontSize:12,fontWeight:900,letterSpacing:'.13em'}}>OPERATIONS / EVENT READY</div><h2 style={{margin:'8px 0 5px',fontSize:26}}>{t.title}</h2><p className="muted" style={{margin:0}}>{t.subtitle}</p></div>{snapshot?<span style={{padding:'9px 13px',borderRadius:999,fontWeight:900,fontSize:12,...(snapshot.state==='READY'?levelStyle.PASS:snapshot.state==='ATTENTION'?levelStyle.WARN:levelStyle.BLOCK)}}>{snapshot.state==='READY'?t.ready:snapshot.state==='ATTENTION'?t.attention:t.blocked}</span>:null}</div>
   {error?<p className="error">{error}</p>:null}
   <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12,marginTop:20}}><StationCard mode="CAPTURE"/><StationCard mode="SHARING"/><article style={{padding:18,borderRadius:20,border:'1px solid rgba(255,255,255,.08)',background:'rgba(255,255,255,.025)'}}><strong>{t.sync}</strong><div style={{fontSize:26,fontWeight:900,marginTop:9}}>{snapshot?.media.pending??0}</div><div className="muted" style={{fontSize:12}}>{snapshot?.media.synced??0} {t.synced} · {snapshot?.media.failed??0} {t.failed}</div></article></div>
   <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,marginTop:18,flexWrap:'wrap'}}><span className="muted" style={{fontSize:12}}>{snapshot?`${t.updated} ${new Date(snapshot.generatedAt).toLocaleTimeString(language==='fr'?'fr-CH':language)}`:''}</span><button className="button secondary" onClick={()=>void load()}>{t.refresh}</button></div>
  </section>
  <section className="card"><h2 style={{marginTop:0}}>{t.checks}</h2><div style={{display:'grid',gap:9}}>{snapshot?.checks.map(check=>{const style=levelStyle[check.level];return <div key={check.id} style={{display:'grid',gridTemplateColumns:'34px minmax(120px,180px) 1fr',alignItems:'center',gap:10,padding:'11px 12px',borderRadius:15,border:`1px solid ${style.border}`,background:style.background}}><span style={{color:style.color,fontWeight:900,fontSize:18,textAlign:'center'}}>{levelSymbol[check.level]}</span><strong style={{fontSize:13}}>{checkNames[check.id]??check.id}</strong><span className="muted" style={{fontSize:13}}>{check.level==='INFO'?t.tablet:check.detail}</span></div>})}</div></section>
  <section className="card" style={{border:'1px solid rgba(229,78,78,.34)',background:'radial-gradient(circle at 0 0,rgba(229,78,78,.12),transparent 36%),#11151a'}}><div style={{display:'flex',justifyContent:'space-between',gap:18,alignItems:'flex-start',flexWrap:'wrap'}}><div style={{maxWidth:650}}><div style={{fontSize:12,fontWeight:900,letterSpacing:'.12em',color:'#ff9999'}}>KHE PRIORITY</div><h2 style={{margin:'7px 0'}}>{t.emergency}</h2><p className="muted">{t.emergencyText}</p></div><a className="button secondary" href="/help">{t.openHelp}</a></div><div style={{display:'flex',gap:10,flexWrap:'wrap',alignItems:'end'}}><label className="field" style={{minWidth:230,flex:'1 1 280px'}}><span>{t.choose}</span><select value={issue} onChange={e=>setIssue(e.target.value)}><option value="camera">{t.camera}</option><option value="sharing">{t.share}</option><option value="print">{t.print}</option><option value="network">{t.network}</option><option value="station">{t.station}</option><option value="sync">{t.syncIssue}</option><option value="other">{t.other}</option></select></label><button className="button danger" disabled={sending||!snapshot} onClick={()=>void emergency()}>{sending?t.sending:t.send}</button></div>{sent?<p className="success">{t.sent} {t.agent}</p>:null}</section>
 </div>;
}
