'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import type { MarketingLanguage } from '@/lib/marketing-i18n';

export type CampaignPlan={code:string;name:string;tagline:string;priceLabel:string;highlighted:boolean};
type Story={id:string;kicker:string;title:string;body:string;bullets:string[];cta:string;href:string;kind:'capture'|'sharing'|'agent'|'business'};

const COPY:Record<MarketingLanguage,{kicker:string;title:string;intro:string;open:string;stories:(plans:CampaignPlan[])=>Story[]}>= {
  fr:{kicker:'OFFRES & OPPORTUNITÉS KHE',title:'Une expérience qui évolue avec votre activité.',intro:'Découvrez automatiquement les offres, nouveautés et opportunités qui correspondent à l’univers CAPTURE & SHARING.',open:'Afficher',stories:(plans)=>[
    {id:'capture',kicker:'PHOTOBOOTH STATION',title:'Passez de la prise de vue au partage, sans interruption.',body:'CAPTURE enregistre pendant que SHARING remet les souvenirs aux invités. Le parcours reste fluide même pendant les événements les plus intenses.',bullets:['Deux stations synchronisées','QR invité sécurisé','Cloud et reprise hors connexion'],cta:'Découvrir les abonnements',href:'#tarifs',kind:'capture'},
    {id:'sharing',kicker:'PHOTBOOTH 360°',title:'Transformez chaque séquence 360° en contenu prêt à partager.',body:'Créez une expérience spectaculaire, appliquez votre univers de marque et facilitez la diffusion sur mobile dès la fin de la capture.',bullets:['Formats verticaux pour les réseaux','Personnalisation Studio','Partage rapide par QR'],cta:'Voir les fonctions',href:'#features',kind:'sharing'},
    {id:'agent',kicker:'REJOIGNEZ LE RÉSEAU KHE',title:'Devenez Agent KHE Booth.',body:'Accompagnez les clients, les photobooths Station et 360°, développez votre expertise événementielle et rejoignez un réseau piloté depuis KHE Booth.',bullets:['Formation et outils KHE','Missions et planning centralisés','Profil agent visible après validation'],cta:'Déposer ma candidature',href:'/become-agent',kind:'agent'},
    {id:'business',kicker:'OFFRE DU MOMENT',title:plans.find((plan)=>plan.highlighted)?.name||'KHE Booth Pro',body:plans.find((plan)=>plan.highlighted)?.tagline||'L’offre conçue pour les professionnels réguliers.',bullets:['CAPTURE & SHARING réunis','Marketing et analyses','Support prioritaire'],cta:`Choisir ${plans.find((plan)=>plan.highlighted)?.priceLabel||'mon offre'}`,href:`/subscribe?plan=${encodeURIComponent(plans.find((plan)=>plan.highlighted)?.code||'PRO')}`,kind:'business'},
  ]},
  en:{kicker:'KHE OFFERS & OPPORTUNITIES',title:'An experience that grows with your business.',intro:'Explore offers, updates and opportunities built around CAPTURE & SHARING.',open:'Show',stories:(plans)=>[
    {id:'capture',kicker:'PHOTOBOOTH STATION',title:'Move from capture to sharing without interruption.',body:'CAPTURE records while SHARING delivers memories to guests, even during demanding events.',bullets:['Two synced stations','Secure guest QR','Cloud and offline recovery'],cta:'Explore plans',href:'#tarifs',kind:'capture'},
    {id:'sharing',kicker:'360° PHOTOBOOTH',title:'Turn every 360° sequence into share-ready content.',body:'Create a striking branded experience and deliver it to mobile as soon as capture ends.',bullets:['Social-ready vertical formats','Studio customisation','Fast QR sharing'],cta:'Explore features',href:'#features',kind:'sharing'},
    {id:'agent',kicker:'JOIN THE KHE NETWORK',title:'Become a KHE Booth Agent.',body:'Support Station and 360° photobooth customers, grow your event expertise and join a network managed through KHE Booth.',bullets:['KHE training and tools','Centralised assignments','Validated agent profile'],cta:'Apply now',href:'/become-agent',kind:'agent'},
    {id:'business',kicker:'FEATURED PLAN',title:plans.find((plan)=>plan.highlighted)?.name||'KHE Booth Pro',body:plans.find((plan)=>plan.highlighted)?.tagline||'Built for regular event professionals.',bullets:['CAPTURE & SHARING','Marketing analytics','Priority support'],cta:`Choose ${plans.find((plan)=>plan.highlighted)?.priceLabel||'a plan'}`,href:`/subscribe?plan=${encodeURIComponent(plans.find((plan)=>plan.highlighted)?.code||'PRO')}`,kind:'business'},
  ]},
  de:{kicker:'KHE ANGEBOTE & CHANCEN',title:'Eine Erfahrung, die mit Ihrem Geschäft wächst.',intro:'Entdecken Sie Angebote, Updates und Chancen rund um CAPTURE & SHARING.',open:'Anzeigen',stories:(plans)=>[
    {id:'capture',kicker:'PHOTOBOOTH STATION',title:'Von der Aufnahme zur Freigabe ohne Unterbrechung.',body:'CAPTURE nimmt auf, während SHARING die Erinnerungen an Gäste verteilt.',bullets:['Zwei synchronisierte Stationen','Sicherer Gäste-QR','Cloud und Offline-Wiederaufnahme'],cta:'Tarife entdecken',href:'#tarifs',kind:'capture'},
    {id:'sharing',kicker:'360° PHOTOBOOTH',title:'Jede 360°-Sequenz wird sofort teilbar.',body:'Erstellen Sie ein markengerechtes Erlebnis und teilen Sie es direkt nach der Aufnahme mobil.',bullets:['Vertikale Social-Formate','Studio-Anpassung','Schnelles QR-Sharing'],cta:'Funktionen ansehen',href:'#features',kind:'sharing'},
    {id:'agent',kicker:'KHE NETZWERK',title:'Werden Sie KHE Booth Agent.',body:'Begleiten Sie Station- und 360°-Kunden und entwickeln Sie Ihre Event-Kompetenz im KHE Netzwerk.',bullets:['KHE Schulung und Tools','Zentrale Einsätze','Validiertes Agentenprofil'],cta:'Jetzt bewerben',href:'/become-agent',kind:'agent'},
    {id:'business',kicker:'EMPFOHLENER TARIF',title:plans.find((plan)=>plan.highlighted)?.name||'KHE Booth Pro',body:plans.find((plan)=>plan.highlighted)?.tagline||'Für regelmäßige Eventprofis.',bullets:['CAPTURE & SHARING','Marketing-Analysen','Prioritäts-Support'],cta:'Tarif wählen',href:`/subscribe?plan=${encodeURIComponent(plans.find((plan)=>plan.highlighted)?.code||'PRO')}`,kind:'business'},
  ]},
  it:{kicker:'OFFERTE & OPPORTUNITÀ KHE',title:'Un’esperienza che cresce con la tua attività.',intro:'Scopri offerte, aggiornamenti e opportunità CAPTURE & SHARING.',open:'Mostra',stories:(plans)=>[
    {id:'capture',kicker:'PHOTOBOOTH STATION',title:'Dalla cattura alla condivisione senza interruzioni.',body:'CAPTURE registra mentre SHARING consegna i ricordi agli ospiti.',bullets:['Due postazioni sincronizzate','QR ospite sicuro','Cloud e ripresa offline'],cta:'Scopri i piani',href:'#tarifs',kind:'capture'},
    {id:'sharing',kicker:'PHOTOBOOTH 360°',title:'Ogni sequenza 360° diventa pronta da condividere.',body:'Crea un’esperienza di marca e consegnala su mobile appena termina la cattura.',bullets:['Formati verticali social','Personalizzazione Studio','Condivisione QR rapida'],cta:'Vedi le funzioni',href:'#features',kind:'sharing'},
    {id:'agent',kicker:'RETE KHE',title:'Diventa Agente KHE Booth.',body:'Affianca i clienti Station e 360° e sviluppa la tua esperienza nel network KHE.',bullets:['Formazione e strumenti KHE','Missioni centralizzate','Profilo agente convalidato'],cta:'Candidati ora',href:'/become-agent',kind:'agent'},
    {id:'business',kicker:'PIANO IN EVIDENZA',title:plans.find((plan)=>plan.highlighted)?.name||'KHE Booth Pro',body:plans.find((plan)=>plan.highlighted)?.tagline||'Per professionisti degli eventi.',bullets:['CAPTURE & SHARING','Analisi marketing','Supporto prioritario'],cta:'Scegli il piano',href:`/subscribe?plan=${encodeURIComponent(plans.find((plan)=>plan.highlighted)?.code||'PRO')}`,kind:'business'},
  ]},
  es:{kicker:'OFERTAS Y OPORTUNIDADES KHE',title:'Una experiencia que crece con tu actividad.',intro:'Descubre ofertas, novedades y oportunidades CAPTURE & SHARING.',open:'Mostrar',stories:(plans)=>[
    {id:'capture',kicker:'PHOTOBOOTH STATION',title:'De la captura a la entrega sin interrupciones.',body:'CAPTURE graba mientras SHARING entrega los recuerdos a los invitados.',bullets:['Dos estaciones sincronizadas','QR seguro para invitados','Nube y recuperación sin conexión'],cta:'Explorar planes',href:'#tarifs',kind:'capture'},
    {id:'sharing',kicker:'PHOTOBOOTH 360°',title:'Cada secuencia 360° queda lista para compartir.',body:'Crea una experiencia de marca y entrégala en el móvil al terminar la captura.',bullets:['Formatos verticales sociales','Personalización Studio','Entrega rápida por QR'],cta:'Ver funciones',href:'#features',kind:'sharing'},
    {id:'agent',kicker:'RED KHE',title:'Conviértete en Agente KHE Booth.',body:'Ayuda a clientes Station y 360° y desarrolla tu experiencia en la red KHE.',bullets:['Formación y herramientas KHE','Misiones centralizadas','Perfil de agente validado'],cta:'Enviar candidatura',href:'/become-agent',kind:'agent'},
    {id:'business',kicker:'PLAN DESTACADO',title:plans.find((plan)=>plan.highlighted)?.name||'KHE Booth Pro',body:plans.find((plan)=>plan.highlighted)?.tagline||'Para profesionales habituales.',bullets:['CAPTURE & SHARING','Análisis de marketing','Soporte prioritario'],cta:'Elegir plan',href:`/subscribe?plan=${encodeURIComponent(plans.find((plan)=>plan.highlighted)?.code||'PRO')}`,kind:'business'},
  ]},
  pt:{kicker:'OFERTAS E OPORTUNIDADES KHE',title:'Uma experiência que cresce com a sua atividade.',intro:'Descubra ofertas, novidades e oportunidades CAPTURE & SHARING.',open:'Mostrar',stories:(plans)=>[
    {id:'capture',kicker:'PHOTOBOOTH STATION',title:'Da captura à partilha sem interrupções.',body:'CAPTURE grava enquanto SHARING entrega as recordações aos convidados.',bullets:['Duas estações sincronizadas','QR seguro para convidados','Cloud e recuperação offline'],cta:'Explorar planos',href:'#tarifs',kind:'capture'},
    {id:'sharing',kicker:'PHOTOBOOTH 360°',title:'Cada sequência 360° fica pronta a partilhar.',body:'Crie uma experiência de marca e entregue-a no telemóvel no fim da captura.',bullets:['Formatos sociais verticais','Personalização Studio','Partilha rápida por QR'],cta:'Ver funcionalidades',href:'#features',kind:'sharing'},
    {id:'agent',kicker:'REDE KHE',title:'Torne-se Agente KHE Booth.',body:'Apoie clientes Station e 360° e desenvolva a sua experiência na rede KHE.',bullets:['Formação e ferramentas KHE','Missões centralizadas','Perfil de agente validado'],cta:'Enviar candidatura',href:'/become-agent',kind:'agent'},
    {id:'business',kicker:'PLANO EM DESTAQUE',title:plans.find((plan)=>plan.highlighted)?.name||'KHE Booth Pro',body:plans.find((plan)=>plan.highlighted)?.tagline||'Para profissionais de eventos.',bullets:['CAPTURE & SHARING','Análise de marketing','Suporte prioritário'],cta:'Escolher plano',href:`/subscribe?plan=${encodeURIComponent(plans.find((plan)=>plan.highlighted)?.code||'PRO')}`,kind:'business'},
  ]},
};

function icon(kind:Story['kind']){
  const p={viewBox:'0 0 48 48',fill:'none',stroke:'currentColor',strokeWidth:1.8,strokeLinecap:'round' as const,strokeLinejoin:'round' as const};
  if(kind==='agent')return <svg {...p}><circle cx="24" cy="17" r="7"/><path d="M11 40c1.8-9 6.2-13.5 13-13.5S35.2 31 37 40"/><path d="m34 10 3 3 6-6"/></svg>;
  if(kind==='sharing')return <svg {...p}><circle cx="24" cy="24" r="17"/><path d="M7 24h34M24 7c6 5 9 10.6 9 17s-3 12-9 17c-6-5-9-10.6-9-17s3-12 9-17"/><circle cx="34" cy="14" r="4"/></svg>;
  if(kind==='business')return <svg {...p}><path d="M7 39h34M11 36V20h8v16M21 36V11h8v25M31 36V25h7v11"/><path d="m9 16 10-8 9 7 11-10"/></svg>;
  return <svg {...p}><rect x="8" y="8" width="32" height="32" rx="8"/><circle cx="24" cy="24" r="9"/><circle cx="24" cy="24" r="3"/><path d="M14 14h4"/></svg>;
}

export function MarketingCampaignShowcase({language,plans}:{language:MarketingLanguage;plans:CampaignPlan[]}){
  const copy=COPY[language];const stories=useMemo(()=>copy.stories(plans),[copy,plans]);const[active,setActive]=useState(0);
  useEffect(()=>{setActive(Math.floor(Math.random()*stories.length));},[stories.length]);
  useEffect(()=>{const timer=window.setInterval(()=>setActive((value)=>(value+1)%stories.length),7600);return()=>window.clearInterval(timer);},[stories.length]);
  const story=stories[active];
  return <section className="marketing-campaign-section" id="opportunites"><div className="section-heading centered"><div className="marketing-kicker"><span/> {copy.kicker}</div><h2>{copy.title}</h2><p>{copy.intro}</p></div><div className={`marketing-campaign-card is-${story.kind}`}><div className="campaign-visual" aria-hidden="true"><div className="campaign-icon">{icon(story.kind)}</div><div className="campaign-pulse campaign-pulse-one"/><div className="campaign-pulse campaign-pulse-two"/><span>CAPTURE</span><b>→</b><span>SHARING</span></div><div className="campaign-copy"><div className="marketing-kicker"><span/> {story.kicker}</div><h3>{story.title}</h3><p>{story.body}</p><ul>{story.bullets.map((bullet)=><li key={bullet}>{bullet}</li>)}</ul><Link className="marketing-cta" href={story.href}>{story.cta} →</Link></div></div><div className="campaign-switcher" role="tablist" aria-label={copy.kicker}>{stories.map((item,index)=><button key={item.id} type="button" role="tab" aria-selected={index===active} className={index===active?'active':''} onClick={()=>setActive(index)}><span>{String(index+1).padStart(2,'0')}</span><b>{item.kicker}</b><small>{copy.open}</small></button>)}</div></section>;
}
