'use client';

import { useEffect, useMemo, useState } from 'react';

type Language='fr'|'en'|'de'|'it'|'es'|'pt';
type Point={id:string;email:string;firstName?:string|null;lastName?:string|null;online:boolean;available:boolean;availability?:string|null;countryCode?:string|null;regionCode?:string|null;municipality?:string|null;latitude?:number|null;longitude?:number|null};
type CountryProps={ADMIN?:string;CONTINENT?:string;LABELRANK?:number;LABEL_X?:number;LABEL_Y?:number;NAME_FR?:string;NAME_EN?:string;NAME_DE?:string;NAME_IT?:string;NAME_ES?:string;NAME_PT?:string};
type Geometry={type:'Polygon'|'MultiPolygon';coordinates:number[][][]|number[][][][]};
type Country={type:'Feature';properties:CountryProps;geometry:Geometry};
type WorldData={type:'FeatureCollection';features:Country[]};
const WORLD_SOURCE='https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson';
const copy:Record<Language,{rotate:string;auto:string;stop:string;available:string;connected:string;offline:string;privacy:string;loading:string;unavailable:string;countries:string;zones:string}>={
fr:{rotate:'Rotation du globe',auto:'Rotation automatique',stop:'Arrêter la rotation',available:'disponible',connected:'connecté',offline:'hors ligne',privacy:'La position des agents est une estimation de zone, jamais un suivi GPS précis.',loading:'Chargement de la carte mondiale…',unavailable:'Carte détaillée temporairement indisponible',countries:'Pays',zones:'Zones'},
en:{rotate:'Globe rotation',auto:'Auto rotate',stop:'Stop rotation',available:'available',connected:'connected',offline:'offline',privacy:'Agent positions are approximate areas, never precise GPS tracking.',loading:'Loading world map…',unavailable:'Detailed map temporarily unavailable',countries:'Countries',zones:'Regions'},
de:{rotate:'Globus drehen',auto:'Automatisch drehen',stop:'Rotation stoppen',available:'verfügbar',connected:'verbunden',offline:'offline',privacy:'Agentenpositionen sind nur ungefähre Gebiete, niemals präzises GPS-Tracking.',loading:'Weltkarte wird geladen…',unavailable:'Detailkarte vorübergehend nicht verfügbar',countries:'Länder',zones:'Regionen'},
it:{rotate:'Rotazione del globo',auto:'Rotazione automatica',stop:'Ferma rotazione',available:'disponibile',connected:'connesso',offline:'offline',privacy:'Le posizioni degli agenti sono zone approssimative, mai tracciamento GPS preciso.',loading:'Caricamento mappa mondiale…',unavailable:'Mappa dettagliata temporaneamente non disponibile',countries:'Paesi',zones:'Zone'},
es:{rotate:'Rotación del globo',auto:'Rotación automática',stop:'Detener rotación',available:'disponible',connected:'conectado',offline:'sin conexión',privacy:'Las posiciones de los agentes son zonas aproximadas, nunca seguimiento GPS preciso.',loading:'Cargando mapa mundial…',unavailable:'Mapa detallado temporalmente no disponible',countries:'Países',zones:'Zonas'},
pt:{rotate:'Rotação do globo',auto:'Rotação automática',stop:'Parar rotação',available:'disponível',connected:'ligado',offline:'offline',privacy:'As posições dos agentes são zonas aproximadas, nunca seguimento GPS preciso.',loading:'A carregar mapa mundial…',unavailable:'Mapa detalhado temporariamente indisponível',countries:'Países',zones:'Zonas'},
};
const CONTINENTS=[['Europe',15,52],['Africa',20,5],['Asia',88,47],['North America',-105,49],['South America',-60,-20],['Oceania',137,-24],['Antarctica',15,-75]] as const;
const ZONES=[['Europe occidentale',5,48],['Afrique de l’Ouest',-4,10],['Afrique centrale',20,0],['Amérique du Nord',-105,39],['Amérique latine',-70,-8],['Moyen-Orient',44,28],['Asie du Sud',78,21],['Asie de l’Est',112,34],['Océanie',145,-29]] as const;
function readLanguage():Language{if(typeof window==='undefined')return'fr';const value=window.localStorage.getItem('khe.web.language');return value&&value in copy?value as Language:'fr';}
function rings(geometry:Geometry):number[][][]{return geometry.type==='Polygon'?geometry.coordinates as number[][][]:(geometry.coordinates as number[][][][]).flat();}
function localizedCountry(p:CountryProps,language:Language){const key=(`NAME_${language.toUpperCase()}`) as keyof CountryProps;return String(p[key]||p.NAME_EN||p.ADMIN||'');}

export function OperationsGlobe({agents}:{agents:Point[]}){
  const[rotation,setRotation]=useState(0);const[playing,setPlaying]=useState(true);const[world,setWorld]=useState<WorldData|null>(null);const[worldError,setWorldError]=useState(false);const[language,setLanguage]=useState<Language>('fr');
  const size=520,c=size/2,r=218,t=copy[language];
  useEffect(()=>{setLanguage(readLanguage());const handler=(event:Event)=>{const detail=(event as CustomEvent<string>).detail;if(detail&&detail in copy)setLanguage(detail as Language);};window.addEventListener('khe-language-changed',handler);return()=>window.removeEventListener('khe-language-changed',handler);},[]);
  useEffect(()=>{let active=true;fetch(WORLD_SOURCE,{cache:'force-cache'}).then(response=>{if(!response.ok)throw new Error('world map');return response.json() as Promise<WorldData>;}).then(data=>{if(active)setWorld(data);}).catch(()=>{if(active)setWorldError(true);});return()=>{active=false;};},[]);
  useEffect(()=>{if(!playing)return;const timer=window.setInterval(()=>setRotation(value=>{const next=value+.55;return next>180?-180:next;}),90);return()=>window.clearInterval(timer);},[playing]);
  const project=(lon:number,lat:number)=>{const phi=lat*Math.PI/180;const lambda=(lon-rotation)*Math.PI/180;const visibility=Math.cos(phi)*Math.cos(lambda);return{visible:visibility>=-.015,x:c+r*Math.cos(phi)*Math.sin(lambda),y:c-r*Math.sin(phi),depth:Math.max(0,visibility)};};
  const countryShapes=useMemo(()=>{if(!world)return[];return world.features.map((country,index)=>{const paths:string[]=[];for(const ring of rings(country.geometry)){let current='';let visibleCount=0;for(const pair of ring){const p=project(pair[0],pair[1]);if(p.visible){current+=`${visibleCount?'L':'M'}${p.x.toFixed(1)},${p.y.toFixed(1)}`;visibleCount++;}else if(visibleCount>2){paths.push(current);current='';visibleCount=0;}else{current='';visibleCount=0;}}if(visibleCount>2)paths.push(current);}return{country,index,paths};}).filter(item=>item.paths.length);},[world,rotation]);
  const labels=useMemo(()=>{if(!world)return[];return world.features.map(country=>{const p=country.properties;if(!Number.isFinite(p.LABEL_X)||!Number.isFinite(p.LABEL_Y))return null;const q=project(Number(p.LABEL_X),Number(p.LABEL_Y));if(!q.visible)return null;return{name:localizedCountry(p,language),rank:Number(p.LABELRANK||9),x:q.x,y:q.y,depth:q.depth};}).filter(Boolean).sort((a,b)=>(a!.rank-b!.rank)||((b!.depth)-(a!.depth))).slice(0,18) as Array<{name:string;rank:number;x:number;y:number;depth:number}>;},[world,rotation,language]);
  const points=useMemo(()=>agents.filter(a=>Number.isFinite(Number(a.latitude))&&Number.isFinite(Number(a.longitude))).map(agent=>({agent,...project(Number(agent.longitude),Number(agent.latitude))})).filter(point=>point.visible),[agents,rotation]);
  const hidden=agents.filter(a=>!Number.isFinite(Number(a.latitude))||!Number.isFinite(Number(a.longitude)));
  const continentLabels=CONTINENTS.map(([name,lon,lat])=>({name,...project(lon,lat)})).filter(x=>x.visible&&x.depth>.24);
  const zoneLabels=ZONES.map(([name,lon,lat])=>({name,...project(lon,lat)})).filter(x=>x.visible&&x.depth>.34);
  return <div className="operations-globe">
    <div className="globe-stage"><div className="globe-halo"/><svg viewBox={`0 0 ${size} ${size}`} width="100%" className="world-globe" role="img" aria-label="Globe terrestre des agents KHE">
      <defs><radialGradient id="ocean" cx="37%" cy="30%"><stop offset="0" stopColor="#203446"/><stop offset=".55" stopColor="#0f1b26"/><stop offset="1" stopColor="#05090d"/></radialGradient><radialGradient id="shine" cx="28%" cy="20%"><stop offset="0" stopColor="rgba(255,255,255,.24)"/><stop offset=".55" stopColor="rgba(255,255,255,.02)"/><stop offset="1" stopColor="rgba(255,255,255,0)"/></radialGradient><clipPath id="earth-clip"><circle cx={c} cy={c} r={r}/></clipPath><filter id="agent-glow"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>
      <circle cx={c} cy={c} r={r} fill="url(#ocean)" stroke="rgba(218,177,76,.72)" strokeWidth="2.4"/>
      <g clipPath="url(#earth-clip)"><g className="geo-grid" fill="none" stroke="rgba(143,166,187,.13)" strokeWidth=".8"><ellipse cx={c} cy={c} rx={r*.72} ry={r}/><ellipse cx={c} cy={c} rx={r*.36} ry={r}/><line x1={c-r} y1={c} x2={c+r} y2={c}/><ellipse cx={c} cy={c-r*.49} rx={r*.87} ry={r*.25}/><ellipse cx={c} cy={c+r*.49} rx={r*.87} ry={r*.25}/></g>
        {countryShapes.map(({country,index,paths})=>paths.map((d,i)=><path key={`${index}-${i}`} d={d} className={`country continent-${(country.properties.CONTINENT||'other').replace(/\s+/g,'-').toLowerCase()}`}/>))}
        {zoneLabels.map(zone=><text key={zone.name} x={zone.x} y={zone.y} textAnchor="middle" className="zone-label">{zone.name}</text>)}
        {continentLabels.map(continent=><text key={continent.name} x={continent.x} y={continent.y} textAnchor="middle" className="continent-label">{continent.name}</text>)}
        {labels.map(label=><text key={`${label.name}-${label.x}`} x={label.x} y={label.y} textAnchor="middle" className={`country-label rank-${Math.min(5,label.rank)}`}>{label.name}</text>)}
        {points.map(({agent,x,y,depth})=><g key={agent.id} transform={`translate(${x} ${y})`} opacity={.45+.55*depth} filter="url(#agent-glow)"><circle r={agent.available?7:agent.online?5.5:4.5} fill={agent.available?'#6fe09a':agent.online?'#e0b94d':'#7c8794'} stroke="#fff" strokeWidth="1.25"><title>{[agent.firstName,agent.lastName].filter(Boolean).join(' ')||agent.email} · {[agent.municipality,agent.regionCode,agent.countryCode].filter(Boolean).join(' · ')} · {agent.available?t.available:agent.online?t.connected:t.offline}</title></circle>{agent.available?<circle r="12" fill="none" stroke="rgba(111,224,154,.5)" strokeWidth="1.2"/>:null}</g>)}
        <circle cx={c} cy={c} r={r} fill="url(#shine)" pointerEvents="none"/></g><circle cx={c} cy={c} r={r} fill="none" stroke="rgba(255,220,131,.25)" strokeWidth="7" opacity=".22"/>
    </svg>{!world&&!worldError?<div className="globe-loading">{t.loading}</div>:null}{worldError?<div className="globe-loading">{t.unavailable}</div>:null}</div>
    <div className="globe-controls"><label><span>{t.rotate}</span><input type="range" min={-180} max={180} value={rotation} onChange={e=>{setPlaying(false);setRotation(Number(e.target.value));}}/></label><button type="button" className="button secondary" onClick={()=>setPlaying(v=>!v)}>{playing?`Ⅱ ${t.stop}`:`▶ ${t.auto}`}</button></div>
    <div className="globe-legend"><span><i className="dot available"/> {t.available}</span><span><i className="dot connected"/> {t.connected}</span><span><i className="dot offline"/> {t.offline}</span></div><p className="globe-privacy">{t.privacy}</p>{hidden.length?<p className="globe-privacy">{hidden.length} agent(s) sans zone partagée restent visibles dans la liste.</p>:null}
    <style jsx>{`
      .operations-globe{position:relative}.globe-stage{position:relative;display:grid;place-items:center;isolation:isolate;min-height:300px}.globe-halo{position:absolute;width:78%;aspect-ratio:1;border-radius:50%;background:radial-gradient(circle,rgba(210,173,79,.14),transparent 68%);filter:blur(20px)}.world-globe{position:relative;z-index:1;max-width:590px;filter:drop-shadow(0 24px 34px rgba(0,0,0,.42))}.country{fill:rgba(70,87,72,.88);stroke:rgba(217,197,140,.28);stroke-width:.55;transition:fill .2s}.continent-europe{fill:#5a6257}.continent-africa{fill:#4e594c}.continent-asia{fill:#586052}.continent-north-america{fill:#515f5e}.continent-south-america{fill:#536057}.continent-oceania{fill:#5d6255}.continent-antarctica{fill:#687079}.country-label{fill:rgba(236,239,236,.76);font-size:6.4px;font-weight:720;paint-order:stroke;stroke:rgba(3,7,10,.78);stroke-width:1.8px;pointer-events:none}.country-label.rank-1,.country-label.rank-2{font-size:7.4px;fill:#fff}.continent-label{fill:rgba(239,200,99,.64);font-size:11px;font-weight:950;letter-spacing:.08em;text-transform:uppercase;paint-order:stroke;stroke:rgba(4,7,10,.7);stroke-width:2px}.zone-label{fill:rgba(167,194,214,.52);font-size:5.3px;font-weight:750;letter-spacing:.02em;paint-order:stroke;stroke:#071019;stroke-width:1.4px}.globe-loading{position:absolute;z-index:4;padding:8px 12px;border:1px solid rgba(210,173,79,.25);border-radius:999px;background:rgba(7,11,15,.72);backdrop-filter:blur(10px);color:#cbd3dc;font-size:10px}.globe-controls{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:end;max-width:590px;margin:3px auto 0}.globe-controls label{display:grid;gap:5px}.globe-controls label span{font-size:11px;font-weight:850;color:#aeb8c5}.globe-controls input{width:100%;accent-color:#d8ae45}.globe-controls .button{min-height:36px;padding:7px 10px;font-size:10px}.globe-legend{display:flex;justify-content:center;gap:14px;flex-wrap:wrap;margin-top:12px;color:#aeb8c5;font-size:10px}.dot{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:3px}.dot.available{background:#6fe09a}.dot.connected{background:#e0b94d}.dot.offline{background:#7c8794}.globe-privacy{text-align:center;color:#8e99a8;font-size:10px;line-height:1.45;margin:8px auto 0;max-width:590px}
      @media(max-width:600px){.globe-stage{min-height:260px}.country-label{font-size:5.7px}.continent-label{font-size:9px}.zone-label{display:none}.globe-controls{grid-template-columns:1fr}.globe-controls .button{justify-self:start}.globe-legend{gap:9px}}
    `}</style>
  </div>;
}
