'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useEffect,useRef,useState } from 'react';
import { apiRequest,getSessionUser } from '@/lib/api';
import { getApproximateLocationSharing,getOperationsSessionKey,setApproximateLocationSharing } from '@/lib/operations-session';

type Language='fr'|'en'|'de'|'it'|'es'|'pt';
type Presence={isAgent:boolean;online:boolean;availability:string;acceptingAssignments:boolean;requiresAvailabilityConfirmation:boolean;lastHeartbeatAt?:string|null;availableSince?:string|null;locationSharingEnabled?:boolean};
type WorkforceCompact={nextShift?:{id:string;startsAt:string;endsAt:string;confirmationStatus:string}|null;unreadNotices:number};
type LiveCompact={shift?:{id:string;startsAt:string;endsAt:string;liveStatus:string;confirmationStatus:string}|null;policy?:{requireActiveShiftForRouting:boolean}};
type BriefCompact={brief?:{id:string;status:string;shiftEndsAt:string;openConversationCount:number;urgentSlaCount:number;missingNoteCount:number}|null};
type RescueCompact={open:number;prepared:number;overdue:number;urgent:number};
const AVAILABILITY_PROMPT_KEY='khe.agent.availability-confirmed.v1';
const copy:Record<Language,Record<string,string>>={
fr:{agent:'Agent KHE',connected:'Connecté',disconnected:'Déconnecté',open:'Afficher les commandes agent',close:'Masquer les commandes agent',available:'Disponible',busy:'Occupé',away:'En pause',unavailable:'Indisponible',receive:'Disponible — recevoir les tâches',routingOn:'Routage intelligent actif',routingOff:'Aucune attribution automatique',presenceError:'Présence agent indisponible',statusError:'Impossible de modifier le statut',confirmTitle:'Souhaitez-vous recevoir des assignations ?',confirmBody:'Choisissez votre disponibilité. KHE mémorisera ce choix et vous pourrez la modifier à tout moment ici.',share:'Partager ma zone approximative',shareHelp:'Pays, région et commune estimés à partir de la connexion. Aucun suivi GPS précis en continu.',activate:'Me rendre disponible',activating:'Activation…',stayOff:'Rester indisponible',live:'Service en cours',paused:'Service en pause',until:'jusqu’à',next:'Prochain service',ongoing:'en cours / imminent',in:'dans',confirm:'à confirmer',confirmed:'confirmé',declined:'refusé',briefReady:'Brief de fin de service prêt',openConversations:'conversation(s) ouverte(s)',urgent:'SLA urgent(s)',missing:'note(s) manquante(s)',rescue:'Suivi SLA actif',decisions:'décision(s)',handoffs:'relais préparé(s)',overdue:'dépassé(s)',planning:'Mon planning',brief:'Brief',handover:'Relais',teamLive:'Service équipe',teamBrief:'Brief équipe',teamRescue:'SLA équipe',teamHandover:'Relais équipe',team:'Équipe',routing:'Routage',optimize:'Optimiser'},
en:{agent:'KHE Agent',connected:'Connected',disconnected:'Offline',open:'Show agent controls',close:'Hide agent controls',available:'Available',busy:'Busy',away:'On break',unavailable:'Unavailable',receive:'Available — receive tasks',routingOn:'Smart routing active',routingOff:'No automatic assignment',presenceError:'Agent presence unavailable',statusError:'Unable to update status',confirmTitle:'Would you like to receive assignments?',confirmBody:'Choose your availability. KHE will remember it and you can change it here at any time.',share:'Share my approximate area',shareHelp:'Country, region and municipality estimated from the connection. No continuous precise GPS tracking.',activate:'Make me available',activating:'Activating…',stayOff:'Stay unavailable',live:'Shift active',paused:'Shift paused',until:'until',next:'Next shift',ongoing:'ongoing / imminent',in:'in',confirm:'to confirm',confirmed:'confirmed',declined:'declined',briefReady:'End-of-shift brief ready',openConversations:'open conversation(s)',urgent:'urgent SLA(s)',missing:'missing note(s)',rescue:'SLA follow-up active',decisions:'decision(s)',handoffs:'prepared handoff(s)',overdue:'overdue',planning:'My schedule',brief:'Brief',handover:'Handover',teamLive:'Team live',teamBrief:'Team brief',teamRescue:'Team SLA',teamHandover:'Team handover',team:'Team',routing:'Routing',optimize:'Optimize'},
de:{agent:'KHE-Agent',connected:'Verbunden',disconnected:'Offline',open:'Agentensteuerung anzeigen',close:'Agentensteuerung ausblenden',available:'Verfügbar',busy:'Beschäftigt',away:'Pause',unavailable:'Nicht verfügbar',receive:'Verfügbar — Aufgaben empfangen',routingOn:'Intelligentes Routing aktiv',routingOff:'Keine automatische Zuweisung',presenceError:'Agentenpräsenz nicht verfügbar',statusError:'Status kann nicht geändert werden',confirmTitle:'Möchten Sie Zuweisungen erhalten?',confirmBody:'Wählen Sie Ihre Verfügbarkeit. KHE speichert die Auswahl; Sie können sie hier jederzeit ändern.',share:'Ungefähren Standort teilen',shareHelp:'Land, Region und Gemeinde werden aus der Verbindung geschätzt. Keine dauerhafte präzise GPS-Ortung.',activate:'Verfügbar werden',activating:'Aktivierung…',stayOff:'Nicht verfügbar bleiben',live:'Schicht aktiv',paused:'Schicht pausiert',until:'bis',next:'Nächste Schicht',ongoing:'läuft / unmittelbar',in:'in',confirm:'zu bestätigen',confirmed:'bestätigt',declined:'abgelehnt',briefReady:'Schichtabschluss-Briefing bereit',openConversations:'offene Unterhaltung(en)',urgent:'dringende SLA(s)',missing:'fehlende Notiz(en)',rescue:'SLA-Nachverfolgung aktiv',decisions:'Entscheidung(en)',handoffs:'vorbereitete Übergabe(n)',overdue:'überfällig',planning:'Mein Dienstplan',brief:'Briefing',handover:'Übergabe',teamLive:'Team-Schicht',teamBrief:'Team-Briefing',teamRescue:'Team-SLA',teamHandover:'Team-Übergabe',team:'Team',routing:'Routing',optimize:'Optimieren'},
it:{agent:'Agente KHE',connected:'Connesso',disconnected:'Offline',open:'Mostra comandi agente',close:'Nascondi comandi agente',available:'Disponibile',busy:'Occupato',away:'In pausa',unavailable:'Non disponibile',receive:'Disponibile — ricevere attività',routingOn:'Routing intelligente attivo',routingOff:'Nessuna assegnazione automatica',presenceError:'Presenza agente non disponibile',statusError:'Impossibile modificare lo stato',confirmTitle:'Vuoi ricevere assegnazioni?',confirmBody:'Scegli la disponibilità. KHE la memorizzerà e potrai modificarla qui in qualsiasi momento.',share:'Condividi la mia zona approssimativa',shareHelp:'Paese, regione e comune stimati dalla connessione. Nessun tracciamento GPS preciso continuo.',activate:'Rendimi disponibile',activating:'Attivazione…',stayOff:'Resta non disponibile',live:'Turno attivo',paused:'Turno in pausa',until:'fino alle',next:'Prossimo turno',ongoing:'in corso / imminente',in:'tra',confirm:'da confermare',confirmed:'confermato',declined:'rifiutato',briefReady:'Brief di fine turno pronto',openConversations:'conversazione/i aperta/e',urgent:'SLA urgente/i',missing:'nota/e mancante/i',rescue:'Monitoraggio SLA attivo',decisions:'decisione/i',handoffs:'passaggio/i preparato/i',overdue:'scaduto/i',planning:'Il mio planning',brief:'Brief',handover:'Passaggio',teamLive:'Turno team',teamBrief:'Brief team',teamRescue:'SLA team',teamHandover:'Passaggio team',team:'Team',routing:'Routing',optimize:'Ottimizza'},
es:{agent:'Agente KHE',connected:'Conectado',disconnected:'Desconectado',open:'Mostrar controles del agente',close:'Ocultar controles del agente',available:'Disponible',busy:'Ocupado',away:'En pausa',unavailable:'No disponible',receive:'Disponible — recibir tareas',routingOn:'Enrutamiento inteligente activo',routingOff:'Sin asignación automática',presenceError:'Presencia del agente no disponible',statusError:'No se puede modificar el estado',confirmTitle:'¿Deseas recibir asignaciones?',confirmBody:'Elige tu disponibilidad. KHE la recordará y podrás cambiarla aquí en cualquier momento.',share:'Compartir mi zona aproximada',shareHelp:'País, región y municipio estimados desde la conexión. Sin seguimiento GPS preciso continuo.',activate:'Ponerme disponible',activating:'Activando…',stayOff:'Seguir no disponible',live:'Turno activo',paused:'Turno en pausa',until:'hasta',next:'Próximo turno',ongoing:'en curso / inminente',in:'en',confirm:'por confirmar',confirmed:'confirmado',declined:'rechazado',briefReady:'Brief de fin de turno listo',openConversations:'conversación(es) abierta(s)',urgent:'SLA urgente(s)',missing:'nota(s) pendiente(s)',rescue:'Seguimiento SLA activo',decisions:'decisión(es)',handoffs:'relevo(s) preparado(s)',overdue:'vencido(s)',planning:'Mi planificación',brief:'Brief',handover:'Relevo',teamLive:'Turno del equipo',teamBrief:'Brief del equipo',teamRescue:'SLA del equipo',teamHandover:'Relevo del equipo',team:'Equipo',routing:'Enrutamiento',optimize:'Optimizar'},
pt:{agent:'Agente KHE',connected:'Ligado',disconnected:'Desligado',open:'Mostrar controlos do agente',close:'Ocultar controlos do agente',available:'Disponível',busy:'Ocupado',away:'Em pausa',unavailable:'Indisponível',receive:'Disponível — receber tarefas',routingOn:'Roteamento inteligente ativo',routingOff:'Sem atribuição automática',presenceError:'Presença do agente indisponível',statusError:'Não foi possível alterar o estado',confirmTitle:'Deseja receber atribuições?',confirmBody:'Escolha a sua disponibilidade. O KHE irá memorizá-la e poderá alterá-la aqui a qualquer momento.',share:'Partilhar a minha zona aproximada',shareHelp:'País, região e município estimados pela ligação. Sem seguimento GPS preciso contínuo.',activate:'Ficar disponível',activating:'A ativar…',stayOff:'Continuar indisponível',live:'Turno ativo',paused:'Turno em pausa',until:'até',next:'Próximo turno',ongoing:'em curso / iminente',in:'em',confirm:'por confirmar',confirmed:'confirmado',declined:'recusado',briefReady:'Brief de fim de turno pronto',openConversations:'conversa(s) aberta(s)',urgent:'SLA urgente(s)',missing:'nota(s) em falta',rescue:'Acompanhamento SLA ativo',decisions:'decisão(ões)',handoffs:'passagem(ns) preparada(s)',overdue:'em atraso',planning:'O meu planeamento',brief:'Brief',handover:'Passagem',teamLive:'Turno da equipa',teamBrief:'Brief da equipa',teamRescue:'SLA da equipa',teamHandover:'Passagem da equipa',team:'Equipa',routing:'Roteamento',optimize:'Otimizar'},
};
function readLanguage():Language{if(typeof window==='undefined')return'fr';const v=window.localStorage.getItem('khe.web.language');return v&&v in copy?v as Language:'fr';}
function availabilityPromptKey(){const userId=getSessionUser()?.id;return userId?`${AVAILABILITY_PROMPT_KEY}.${userId}`:AVAILABILITY_PROMPT_KEY;}
function readAvailabilityPromptAcknowledged(){if(typeof window==='undefined')return false;return window.localStorage.getItem(availabilityPromptKey())==='1';}
function rememberAvailabilityPromptAcknowledged(){if(typeof window!=='undefined')window.localStorage.setItem(availabilityPromptKey(),'1');}

export function OperationsPresenceControl({role}:{role?:string}){
  const pathname=usePathname();const isAgent=['OWNER','ADMIN','OPERATOR'].includes(role??'');const isManager=['OWNER','ADMIN'].includes(role??'');
  const[presence,setPresence]=useState<Presence|null>(null);const[workforce,setWorkforce]=useState<WorkforceCompact|null>(null);const[live,setLive]=useState<LiveCompact|null>(null);const[brief,setBrief]=useState<BriefCompact|null>(null);const[rescue,setRescue]=useState<RescueCompact|null>(null);const[shareLocation,setShareLocation]=useState(false);const[promptAcknowledged,setPromptAcknowledged]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[expanded,setExpanded]=useState(false);const[language,setLanguage]=useState<Language>('fr');
  const actionCount=useRef(0);const lastPath=useRef<string|null>(null);const lastWorkforcePulse=useRef(0);const closeTimer=useRef<number|null>(null);const t=copy[language];
  useEffect(()=>{setShareLocation(getApproximateLocationSharing());setPromptAcknowledged(readAvailabilityPromptAcknowledged());setLanguage(readLanguage());const handler=(event:Event)=>{const detail=(event as CustomEvent<string>).detail;if(detail&&detail in copy)setLanguage(detail as Language);};window.addEventListener('khe-language-changed',handler);return()=>window.removeEventListener('khe-language-changed',handler);},[]);
  useEffect(()=>{const handler=()=>{actionCount.current=Math.min(50,actionCount.current+1);};document.addEventListener('click',handler,{passive:true});return()=>document.removeEventListener('click',handler);},[]);
  useEffect(()=>()=>{if(closeTimer.current)window.clearTimeout(closeTimer.current);},[]);
  const refreshCompact=()=>{if(!isAgent)return;void Promise.all([apiRequest<WorkforceCompact>('/operations/workforce/agent/compact'),apiRequest<LiveCompact>('/operations/workforce/live/compact'),apiRequest<BriefCompact>('/operations/workforce/brief/compact'),apiRequest<RescueCompact>('/operations/workforce/rescue/compact')]).then(([w,l,b,r])=>{setWorkforce(w);setLive(l);setBrief(b);setRescue(r);}).catch(()=>undefined);};
  const pulseOperations=()=>{if(!isAgent)return;void apiRequest('/operations/routing/pulse',{method:'POST'}).catch(()=>undefined);const now=Date.now();if(now-lastWorkforcePulse.current>=300000){lastWorkforcePulse.current=now;void apiRequest('/operations/workforce/pulse',{method:'POST'}).catch(()=>undefined);void apiRequest('/operations/workforce/agent/pulse',{method:'POST'}).catch(()=>undefined);void apiRequest('/operations/workforce/live/pulse',{method:'POST'}).finally(refreshCompact).catch(()=>undefined);}};
  const heartbeat=async(pageView=0)=>{const sessionKey=getOperationsSessionKey();if(!sessionKey)return;const actions=actionCount.current;actionCount.current=0;try{const next=await apiRequest<Presence>('/operations/presence/heartbeat',{method:'POST',body:JSON.stringify({sessionKey,surface:'WEB_PORTAL',shareApproximateLocation:shareLocation,pageViews:pageView,actions})});setPresence(next);setError('');pulseOperations();}catch(e){actionCount.current=Math.min(50,actionCount.current+actions);setError(e instanceof Error?e.message:t.presenceError);}};
  useEffect(()=>{const pageView=lastPath.current===pathname?0:1;lastPath.current=pathname;void heartbeat(pageView);const timer=window.setInterval(()=>void heartbeat(0),30000);return()=>window.clearInterval(timer);},[pathname,shareLocation,isAgent,language]);
  const setAvailability=async(availability:string)=>{setBusy(true);setError('');try{const next=await apiRequest<Presence>('/operations/presence/availability',{method:'POST',body:JSON.stringify({sessionKey:getOperationsSessionKey(),availability,shareApproximateLocation:shareLocation})});setPresence(next);rememberAvailabilityPromptAcknowledged();setPromptAcknowledged(true);lastWorkforcePulse.current=0;pulseOperations();}catch(e){setError(e instanceof Error?e.message:t.statusError);}finally{setBusy(false);}};
  const changeLocation=(enabled:boolean)=>{setShareLocation(enabled);setApproximateLocationSharing(enabled);};
  const toggleExpanded=()=>{const next=!expanded;setExpanded(next);if(closeTimer.current)window.clearTimeout(closeTimer.current);if(next)closeTimer.current=window.setTimeout(()=>setExpanded(false),5000);};
  if(!presence||!isAgent)return null;
  const statusLabel=presence.availability==='AVAILABLE'?t.available:presence.availability==='BUSY'?t.busy:presence.availability==='AWAY'?t.away:t.unavailable;
  const countdown=(value?:string|null)=>{if(!value)return'';const minutes=Math.round((new Date(value).getTime()-Date.now())/60000);if(minutes<=0)return t.ongoing;if(minutes<60)return`${t.in} ${minutes} min`;const hours=Math.floor(minutes/60),mins=minutes%60;return hours<24?`${t.in} ${hours}h${mins?String(mins).padStart(2,'0'):''}`:`${t.in} ${Math.floor(hours/24)} j`;};
  const locale=language==='fr'?'fr-CH':language;
  return <div className="agent-presence-inline"><button type="button" className="agent-presence-toggle" onClick={toggleExpanded} aria-expanded={expanded} title={expanded?t.close:t.open}><span className="agent-presence-toggle-main"><span className="agent-presence-avatar">KHE</span><span><span className="agent-presence-title">{t.agent}</span><span className="agent-presence-subtitle">{statusLabel}{presence.acceptingAssignments?` · ${t.routingOn}`:` · ${t.routingOff}`}</span></span></span><span className={`agent-presence-state ${presence.online?'online':'offline'}`}>● {presence.online?t.connected:t.disconnected}</span></button><div className="agent-presence-details" data-open={expanded?'true':'false'}><div className="agent-presence-details-inner">
    {presence.requiresAvailabilityConfirmation&&!promptAcknowledged?<div className="agent-presence-consent"><strong>{t.confirmTitle}</strong><span className="muted">{t.confirmBody}</span><label><input type="checkbox" checked={shareLocation} onChange={e=>changeLocation(e.target.checked)}/><span><strong>{t.share}</strong><br/><span className="muted">{t.shareHelp}</span></span></label><div className="agent-presence-actions"><button className="button" disabled={busy} onClick={()=>void setAvailability('AVAILABLE')}>{busy?t.activating:t.activate}</button><button className="button secondary" disabled={busy} onClick={()=>void setAvailability('UNAVAILABLE')}>{t.stayOff}</button></div></div>:null}
    <select className="input" aria-label={t.agent} disabled={busy} value={presence.availability||'UNAVAILABLE'} onChange={e=>void setAvailability(e.target.value)} style={{marginTop:8}}><option value="AVAILABLE">{t.receive}</option><option value="BUSY">{t.busy}</option><option value="AWAY">{t.away}</option><option value="UNAVAILABLE">{t.unavailable}</option></select>{error?<div className="error" style={{fontSize:10,marginTop:6}}>{error}</div>:null}
    {live?.shift&&['ACTIVE','PAUSED'].includes(live.shift.liveStatus)?<div className="agent-presence-notice"><strong>{live.shift.liveStatus==='ACTIVE'?`● ${t.live}`:`⏸ ${t.paused}`}</strong><div className="muted">{t.until} {new Date(live.shift.endsAt).toLocaleTimeString(locale,{hour:'2-digit',minute:'2-digit'})}</div></div>:workforce?.nextShift?<div className="agent-presence-notice"><strong>◷ {t.next} {countdown(workforce.nextShift.startsAt)}</strong><div className="muted">{new Date(workforce.nextShift.startsAt).toLocaleString(locale,{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})} · {workforce.nextShift.confirmationStatus==='PENDING'?t.confirm:workforce.nextShift.confirmationStatus==='ACCEPTED'?t.confirmed:t.declined}</div></div>:null}
    {brief?.brief?<div className="agent-presence-notice"><strong>✓ {t.briefReady}</strong><div className="muted">{brief.brief.openConversationCount} {t.openConversations} · {brief.brief.urgentSlaCount} {t.urgent} · {brief.brief.missingNoteCount} {t.missing}</div></div>:null}
    {rescue&&(rescue.open||rescue.prepared||rescue.overdue)?<div className="agent-presence-notice"><strong>⚑ {t.rescue}</strong><div className="muted">{rescue.open} {t.decisions} · {rescue.prepared} {t.handoffs} · {rescue.overdue} {t.overdue}</div></div>:null}
    <div className="agent-presence-links"><Link href="/operations/workforce/live">{t.live} →</Link><Link href="/operations/workforce/brief">{t.brief} →</Link><Link href="/operations/workforce/rescue/me">SLA →</Link><Link href="/operations/workforce/handover/me">{t.handover} →</Link><Link href="/operations/workforce/me">{t.planning}{workforce?.unreadNotices?` (${workforce.unreadNotices})`:''} →</Link>{isManager?<><Link href="/operations/workforce/live/team">{t.teamLive} →</Link><Link href="/operations/workforce/brief/team">{t.teamBrief} →</Link><Link href="/operations/workforce/rescue">{t.teamRescue} →</Link><Link href="/operations/workforce/handover">{t.teamHandover} →</Link><Link href="/operations/workforce/team">{t.team} →</Link><Link href="/operations/routing">{t.routing} →</Link><Link href="/operations/workforce/optimizer">{t.optimize} →</Link></>:null}</div>
  </div></div></div>;
}
