'use client';

import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { useEffect, useMemo, useState } from 'react';
import { apiRequest, clearAccessToken, getAccessToken, setSessionUser } from '@/lib/api';
import { endOperationsSession } from '@/lib/operations-session';
import { OperationsPresenceControl } from './operations-presence-control';
import { SupportCenterTools } from './support-center-tools';
import { SupportFeedbackPrompt } from './support-feedback-prompt';
import { WebTermsGate } from './web-terms-gate';

type CurrentUser={id:string;organizationId?:string;email:string;username?:string|null;firstName?:string|null;lastName?:string|null;role:string;avatarUrl?:string|null;permissions?:Record<string,boolean>;termsAccepted?:boolean;tenantKind?:string;managedByOrganizationId?:string|null;securityDetailsAllowed?:boolean};
type Language='fr'|'en'|'de'|'it'|'es'|'pt';
const labels:Record<Language,Record<string,string>>={
fr:{dashboard:'Dashboard',clients:'Clients',crm:'↳ CRM & historique e-mails',events:'Événements',presets:'Presets',create:'Créer',help:'Aide / Messagerie',operations:'Centre opérations KHE',routing:'↳ Routing & SLA',workforce:'↳ Workforce & prévisions',marketing:'Marketing & Analytics',growth:'↳ Stripe & campagnes',emailing:'↳ E-mailing automatique',communications:'Communications clients',profile:'Profil',settings:'Paramètres',site:'Configuration du site web',team:'Équipe & autorisations',security:'SÉCURITÉ DES PLATEFORMES',guide:'Mode d’emploi',terms:'Conditions d’utilisation',logout:'Déconnexion',loading:'Chargement de KHE Booth…'},
en:{dashboard:'Dashboard',clients:'Clients',crm:'↳ CRM & email history',events:'Events',presets:'Presets',create:'Create',help:'Help / Messages',operations:'KHE Operations Center',routing:'↳ Routing & SLA',workforce:'↳ Workforce & forecasts',marketing:'Marketing & Analytics',growth:'↳ Stripe & campaigns',emailing:'↳ Automated emailing',communications:'Client communications',profile:'Profile',settings:'Settings',site:'Website configuration',team:'Team & permissions',security:'PLATFORM SECURITY',guide:'User guide',terms:'Terms of use',logout:'Log out',loading:'Loading KHE Booth…'},
de:{dashboard:'Dashboard',clients:'Kunden',crm:'↳ CRM & E-Mail-Verlauf',events:'Veranstaltungen',presets:'Vorlagen',create:'Erstellen',help:'Hilfe / Nachrichten',operations:'KHE Operationszentrum',routing:'↳ Routing & SLA',workforce:'↳ Personal & Prognosen',marketing:'Marketing & Analytics',growth:'↳ Stripe & Kampagnen',emailing:'↳ E-Mail-Automation',communications:'Kundenkommunikation',profile:'Profil',settings:'Einstellungen',site:'Website-Konfiguration',team:'Team & Berechtigungen',security:'PLATTFORMSICHERHEIT',guide:'Benutzerhandbuch',terms:'Nutzungsbedingungen',logout:'Abmelden',loading:'KHE Booth wird geladen…'},
it:{dashboard:'Dashboard',clients:'Clienti',crm:'↳ CRM & cronologia e-mail',events:'Eventi',presets:'Preset',create:'Crea',help:'Aiuto / Messaggi',operations:'Centro operativo KHE',routing:'↳ Routing & SLA',workforce:'↳ Personale & previsioni',marketing:'Marketing & Analytics',growth:'↳ Stripe & campagne',emailing:'↳ E-mail automatiche',communications:'Comunicazioni clienti',profile:'Profilo',settings:'Impostazioni',site:'Configurazione sito web',team:'Team e autorizzazioni',security:'SICUREZZA PIATTAFORME',guide:'Guida utente',terms:'Condizioni d’uso',logout:'Disconnetti',loading:'Caricamento KHE Booth…'},
es:{dashboard:'Dashboard',clients:'Clientes',crm:'↳ CRM e historial e-mail',events:'Eventos',presets:'Presets',create:'Crear',help:'Ayuda / Mensajes',operations:'Centro de operaciones KHE',routing:'↳ Routing & SLA',workforce:'↳ Personal y previsiones',marketing:'Marketing & Analytics',growth:'↳ Stripe y campañas',emailing:'↳ E-mail automático',communications:'Comunicaciones clientes',profile:'Perfil',settings:'Ajustes',site:'Configuración del sitio web',team:'Equipo y permisos',security:'SEGURIDAD DE PLATAFORMAS',guide:'Guía de uso',terms:'Condiciones de uso',logout:'Cerrar sesión',loading:'Cargando KHE Booth…'},
pt:{dashboard:'Dashboard',clients:'Clientes',crm:'↳ CRM e histórico de e-mails',events:'Eventos',presets:'Predefinições',create:'Criar',help:'Ajuda / Mensagens',operations:'Centro de operações KHE',routing:'↳ Routing & SLA',workforce:'↳ Equipa & previsões',marketing:'Marketing & Analytics',growth:'↳ Stripe e campanhas',emailing:'↳ E-mail automático',communications:'Comunicações clientes',profile:'Perfil',settings:'Definições',site:'Configuração do site',team:'Equipa e permissões',security:'SEGURANÇA DAS PLATAFORMAS',guide:'Manual de utilização',terms:'Termos de utilização',logout:'Terminar sessão',loading:'A carregar KHE Booth…'},
};
function readLanguage():Language{if(typeof window==='undefined')return'fr';const value=window.localStorage.getItem('khe.web.language');return value&&value in labels?value as Language:'fr';}
export function PortalShell({children}:Readonly<{children:React.ReactNode}>){
  const pathname=usePathname();const router=useRouter();const[user,setUser]=useState<CurrentUser|null>(null);const[ready,setReady]=useState(false);const[language,setLanguage]=useState<Language>('fr');
  useEffect(()=>{setLanguage(readLanguage());const onLanguage=(event:Event)=>{const detail=(event as CustomEvent<string>).detail;if(detail&&detail in labels)setLanguage(detail as Language);};window.addEventListener('khe-language-changed',onLanguage);return()=>window.removeEventListener('khe-language-changed',onLanguage);},[]);
  useEffect(()=>{if(!getAccessToken()){router.replace('/login');return;}apiRequest<CurrentUser>('/auth/me').then((currentUser)=>{setUser(currentUser);setSessionUser(currentUser);}).catch(()=>{clearAccessToken();router.replace('/login');}).finally(()=>setReady(true));},[router]);
  const text=labels[language];const can=(permission:string)=>user?.role==='OWNER'||Boolean(user?.permissions?.[permission]);
  const links=useMemo(()=>{if(!user)return[] as Array<readonly[string,string]>;const base:Array<readonly[string,string]>=[];if(user.role==='OPERATOR')base.push(['/agent','Espace Agent KHE']);if(can('dashboard.view'))base.push(['/dashboard',text.dashboard]);if(can('clients.view')){base.push(['/clients',text.clients]);base.push(['/clients/crm',text.crm]);}if(can('events.view'))base.push(['/events',text.events]);if(can('events.manage'))base.push(['/events/new',text.create]);if(can('studio.view'))base.push(['/presets',text.presets]);base.push(['/help',text.help]);if(['OWNER','ADMIN'].includes(user.role)){base.push(['/operations/command-center','↳ Command Center']);base.push(['/operations',text.operations]);base.push(['/operations/routing',text.routing]);base.push(['/operations/workforce',text.workforce]);}if(can('marketing.view')){base.push(['/marketing',text.marketing]);base.push(['/marketing/growth',text.growth]);base.push(['/marketing/emailing',text.emailing]);}if(can('communications.manage'))base.push(['/communications',text.communications]);if(can('site.manage'))base.push(['/site-configuration',text.site]);if(can('team.manage'))base.push(['/team',text.team]);if(user.securityDetailsAllowed===true)base.push(['/security',text.security]);base.push(['/guide',text.guide],['/terms',text.terms],['/profile',text.profile],['/settings',text.settings]);if(['OWNER','ADMIN'].includes(user.role))base.push(['/settings/agents','↳ Agents KHE']);return base;},[text,user]);
  if(!ready)return <main className="login"><div className="muted">{text.loading}</div></main>;if(user&&user.termsAccepted===false)return <WebTermsGate onAccepted={()=>setUser({...user,termsAccepted:true})}/>;
  const displayName=[user?.firstName,user?.lastName].filter(Boolean).join(' ')||user?.email;
  const logout=async()=>{await endOperationsSession();clearAccessToken();router.replace('/login');};
  return <div className="shell"><aside className="sidebar"><div className="brand">KHE <span>Booth</span></div><div className="muted" style={{marginTop:6,fontSize:13}}>Kurtis Hypnotic Events</div>{user?.tenantKind==='ENTERPRISE_CLIENT'?<div style={{marginTop:10,padding:'7px 9px',borderRadius:10,border:'1px solid rgba(210,173,79,.35)',color:'#d2ad4f',fontSize:10,fontWeight:900}}>ESPACE ENTERPRISE GÉRÉ PAR KHE</div>:null}<nav className="nav">{links.map(([href,label])=><Link key={href} href={href} aria-current={pathname===href||pathname.startsWith(`${href}/`)?'page':undefined}>{label}</Link>)}</nav><div style={{marginTop:32}}><div style={{display:'flex',alignItems:'center',gap:9}}>{user?.avatarUrl?<img src={user.avatarUrl} alt="" style={{width:34,height:34,borderRadius:17,objectFit:'cover',border:'1px solid #d2ad4f'}}/>:null}<div><div style={{fontWeight:800,fontSize:13}}>{displayName}</div>{user?.username?<div className="muted" style={{fontSize:11,marginTop:1}}>@{user.username}</div>:null}<div className="muted" style={{fontSize:12,marginTop:2}}>{user?.role}</div></div></div><button className="button secondary" style={{marginTop:14,width:'100%'}} onClick={()=>void logout()}>{text.logout}</button></div></aside><SupportCenterTools/><OperationsPresenceControl role={user?.role}/><SupportFeedbackPrompt/><main className="content">{children}</main></div>;
}
