'use client';

import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { useEffect, useMemo, useState } from 'react';
import { apiRequest, clearAccessToken, getAccessToken, setSessionUser } from '@/lib/api';
import { endOperationsSession } from '@/lib/operations-session';
import { OperationsPresenceControl } from './operations-presence-control';
import { SupportCenterTools } from './support-center-tools';
import { SupportFeedbackPrompt } from './support-feedback-prompt';
import { WebTermsGate } from './web-terms-gate';

type CurrentUser={id:string;organizationId?:string;email:string;username?:string|null;firstName?:string|null;lastName?:string|null;role:string;avatarUrl?:string|null;permissions?:Record<string,boolean>;termsAccepted?:boolean;tenantKind?:string;managedByOrganizationId?:string|null;securityDetailsAllowed?:boolean};
type Language='fr'|'en'|'de'|'it'|'es'|'pt';
type NavItem={href:string;label:string};
type NavGroup={id:string;label:string;icon:string;items:NavItem[]};
const NAV_OPEN_KEY='khe.portal.navigation.open.v2';
const labels:Record<Language,Record<string,string>>={
fr:{dashboard:'Dashboard',clients:'Clients',crm:'CRM & historique e-mails',events:'Événements',presets:'Presets',create:'Créer un événement',help:'Aide / Messagerie',operations:'Vue opérations',routing:'Routing & SLA',workforce:'Workforce & prévisions',marketing:'Marketing & Analytics',growth:'Stripe & campagnes',emailing:'E-mailing automatique',communications:'Communications clients',profile:'Profil',settings:'Paramètres généraux',site:'Configuration du site web',team:'Équipe & autorisations',security:'Sécurité des plateformes',guide:'Mode d’emploi',terms:'Conditions d’utilisation',logout:'Déconnexion',loading:'Chargement de KHE Booth…'},
en:{dashboard:'Dashboard',clients:'Clients',crm:'CRM & email history',events:'Events',presets:'Presets',create:'Create event',help:'Help / Messages',operations:'Operations overview',routing:'Routing & SLA',workforce:'Workforce & forecasts',marketing:'Marketing & Analytics',growth:'Stripe & campaigns',emailing:'Automated emailing',communications:'Client communications',profile:'Profile',settings:'General settings',site:'Website configuration',team:'Team & permissions',security:'Platform security',guide:'User guide',terms:'Terms of use',logout:'Log out',loading:'Loading KHE Booth…'},
de:{dashboard:'Dashboard',clients:'Kunden',crm:'CRM & E-Mail-Verlauf',events:'Veranstaltungen',presets:'Vorlagen',create:'Event erstellen',help:'Hilfe / Nachrichten',operations:'Operationsübersicht',routing:'Routing & SLA',workforce:'Personal & Prognosen',marketing:'Marketing & Analytics',growth:'Stripe & Kampagnen',emailing:'E-Mail-Automation',communications:'Kundenkommunikation',profile:'Profil',settings:'Allgemeine Einstellungen',site:'Website-Konfiguration',team:'Team & Berechtigungen',security:'Plattformsicherheit',guide:'Benutzerhandbuch',terms:'Nutzungsbedingungen',logout:'Abmelden',loading:'KHE Booth wird geladen…'},
it:{dashboard:'Dashboard',clients:'Clienti',crm:'CRM & cronologia e-mail',events:'Eventi',presets:'Preset',create:'Crea evento',help:'Aiuto / Messaggi',operations:'Panoramica operazioni',routing:'Routing & SLA',workforce:'Personale & previsioni',marketing:'Marketing & Analytics',growth:'Stripe & campagne',emailing:'E-mail automatiche',communications:'Comunicazioni clienti',profile:'Profilo',settings:'Impostazioni generali',site:'Configurazione sito web',team:'Team e autorizzazioni',security:'Sicurezza piattaforme',guide:'Guida utente',terms:'Condizioni d’uso',logout:'Disconnetti',loading:'Caricamento KHE Booth…'},
es:{dashboard:'Dashboard',clients:'Clientes',crm:'CRM e historial e-mail',events:'Eventos',presets:'Presets',create:'Crear evento',help:'Ayuda / Mensajes',operations:'Vista de operaciones',routing:'Routing & SLA',workforce:'Personal y previsiones',marketing:'Marketing & Analytics',growth:'Stripe y campañas',emailing:'E-mail automático',communications:'Comunicaciones clientes',profile:'Perfil',settings:'Ajustes generales',site:'Configuración del sitio web',team:'Equipo y permisos',security:'Seguridad de plataformas',guide:'Guía de uso',terms:'Condiciones de uso',logout:'Cerrar sesión',loading:'Cargando KHE Booth…'},
pt:{dashboard:'Dashboard',clients:'Clientes',crm:'CRM e histórico de e-mails',events:'Eventos',presets:'Predefinições',create:'Criar evento',help:'Ajuda / Mensagens',operations:'Visão de operações',routing:'Routing & SLA',workforce:'Equipa & previsões',marketing:'Marketing & Analytics',growth:'Stripe e campanhas',emailing:'E-mail automático',communications:'Comunicações clientes',profile:'Perfil',settings:'Definições gerais',site:'Configuração do site',team:'Equipa e permissões',security:'Segurança das plataformas',guide:'Manual de utilização',terms:'Termos de utilização',logout:'Terminar sessão',loading:'A carregar KHE Booth…'},
};
const menuCopy:Record<Language,{menu:string;collapse:string;home:string;clients:string;events:string;support:string;agent:string;operations:string;marketing:string;admin:string;settings:string;compliance:string}>={
fr:{menu:'MENU KHE',collapse:'Tout fermer',home:'Accueil',clients:'Clients',events:'Événements & Studio',support:'Support & communications',agent:'Mon activité agent',operations:'Centre opérations KHE',marketing:'Marketing & croissance',admin:'Administration',settings:'Paramètres',compliance:'Aide & conformité'},
en:{menu:'KHE MENU',collapse:'Close all',home:'Home',clients:'Clients',events:'Events & Studio',support:'Support & communications',agent:'My agent activity',operations:'KHE Operations Center',marketing:'Marketing & growth',admin:'Administration',settings:'Settings',compliance:'Help & compliance'},
de:{menu:'KHE MENÜ',collapse:'Alle schließen',home:'Start',clients:'Kunden',events:'Events & Studio',support:'Support & Kommunikation',agent:'Meine Agentenaktivität',operations:'KHE Operationszentrum',marketing:'Marketing & Wachstum',admin:'Administration',settings:'Einstellungen',compliance:'Hilfe & Compliance'},
it:{menu:'MENU KHE',collapse:'Chiudi tutto',home:'Home',clients:'Clienti',events:'Eventi & Studio',support:'Supporto & comunicazioni',agent:'La mia attività agente',operations:'Centro operativo KHE',marketing:'Marketing & crescita',admin:'Amministrazione',settings:'Impostazioni',compliance:'Aiuto & conformità'},
es:{menu:'MENÚ KHE',collapse:'Cerrar todo',home:'Inicio',clients:'Clientes',events:'Eventos & Studio',support:'Soporte y comunicaciones',agent:'Mi actividad de agente',operations:'Centro de operaciones KHE',marketing:'Marketing y crecimiento',admin:'Administración',settings:'Ajustes',compliance:'Ayuda y cumplimiento'},
pt:{menu:'MENU KHE',collapse:'Fechar tudo',home:'Início',clients:'Clientes',events:'Eventos & Studio',support:'Suporte & comunicações',agent:'Minha atividade de agente',operations:'Centro de operações KHE',marketing:'Marketing & crescimento',admin:'Administração',settings:'Definições',compliance:'Ajuda & conformidade'},
};
function readLanguage():Language{if(typeof window==='undefined')return'fr';const value=window.localStorage.getItem('khe.web.language');return value&&value in labels?value as Language:'fr';}
function pathMatches(pathname:string,href:string){return pathname===href||pathname.startsWith(`${href}/`);}
function readOpenGroups(){if(typeof window==='undefined')return[] as string[];try{const parsed=JSON.parse(window.localStorage.getItem(NAV_OPEN_KEY)??'[]');return Array.isArray(parsed)?parsed.filter(value=>typeof value==='string'):[];}catch{return[];}}
function persistOpenGroups(groups:string[]){if(typeof window!=='undefined')window.localStorage.setItem(NAV_OPEN_KEY,JSON.stringify(groups));}

export function PortalShell({children}:Readonly<{children:React.ReactNode}>){
  const pathname=usePathname();const router=useRouter();const[user,setUser]=useState<CurrentUser|null>(null);const[ready,setReady]=useState(false);const[language,setLanguage]=useState<Language>('fr');const[openGroups,setOpenGroups]=useState<string[]>([]);
  useEffect(()=>{setLanguage(readLanguage());setOpenGroups(readOpenGroups());const onLanguage=(event:Event)=>{const detail=(event as CustomEvent<string>).detail;if(detail&&detail in labels)setLanguage(detail as Language);};window.addEventListener('khe-language-changed',onLanguage);return()=>window.removeEventListener('khe-language-changed',onLanguage);},[]);
  useEffect(()=>{if(!getAccessToken()){router.replace('/login');return;}apiRequest<CurrentUser>('/auth/me').then((currentUser)=>{setUser(currentUser);setSessionUser(currentUser);}).catch(()=>{clearAccessToken();router.replace('/login');}).finally(()=>setReady(true));},[router]);
  const text=labels[language];const menu=menuCopy[language];
  const navGroups=useMemo<NavGroup[]>(()=>{if(!user)return[];const allowed=(permission:string)=>user.role==='OWNER'||Boolean(user.permissions?.[permission]);const isAgent=['OWNER','ADMIN','OPERATOR'].includes(user.role);const isManager=['OWNER','ADMIN'].includes(user.role);const groups:NavGroup[]=[];
    const home:NavItem[]=[];if(allowed('dashboard.view'))home.push({href:'/dashboard',label:text.dashboard});if(user.role==='OPERATOR')home.push({href:'/agent',label:'Espace Agent KHE'});if(home.length)groups.push({id:'home',label:menu.home,icon:'⌂',items:home});
    const clients:NavItem[]=[];if(allowed('clients.view'))clients.push({href:'/clients',label:text.clients},{href:'/clients/crm',label:text.crm});if(clients.length)groups.push({id:'clients',label:menu.clients,icon:'◎',items:clients});
    const events:NavItem[]=[];if(allowed('events.view'))events.push({href:'/events',label:text.events});if(allowed('events.manage'))events.push({href:'/events/new',label:text.create});if(allowed('studio.view'))events.push({href:'/presets',label:text.presets});if(events.length)groups.push({id:'events',label:menu.events,icon:'✦',items:events});
    const support:NavItem[]=[{href:'/help',label:text.help}];if(allowed('communications.manage'))support.push({href:'/communications',label:text.communications});groups.push({id:'support',label:menu.support,icon:'✉',items:support});
    if(isAgent)groups.push({id:'agent',label:menu.agent,icon:'◉',items:[{href:'/operations/workforce/me',label:'Mon planning'},{href:'/operations/workforce/live',label:'Live Shift'},{href:'/operations/workforce/brief',label:'Mon brief de shift'},{href:'/operations/workforce/handover/me',label:'Mon relais'},{href:'/operations/workforce/rescue/me',label:'Mon SLA Rescue'}]});
    if(isManager)groups.push({id:'operations',label:menu.operations,icon:'◈',items:[{href:'/operations',label:text.operations},{href:'/operations/command-center',label:'Command Center'},{href:'/operations/routing',label:text.routing},{href:'/operations/workforce',label:text.workforce},{href:'/operations/workforce/live/team',label:'Live Shift équipe'},{href:'/operations/workforce/brief/team',label:'Brief équipe'},{href:'/operations/workforce/handover',label:'Relais équipe'},{href:'/operations/workforce/rescue',label:'SLA Rescue équipe'},{href:'/operations/workforce/team',label:'Équipe Workforce'},{href:'/operations/workforce/optimizer',label:'Optimisation planning'}]});
    if(allowed('marketing.view'))groups.push({id:'marketing',label:menu.marketing,icon:'↗',items:[{href:'/marketing',label:text.marketing},{href:'/marketing/growth',label:text.growth},{href:'/marketing/emailing',label:text.emailing}]});
    const admin:NavItem[]=[];if(allowed('site.manage'))admin.push({href:'/site-configuration',label:text.site});if(allowed('team.manage'))admin.push({href:'/team',label:text.team});if(user.securityDetailsAllowed===true)admin.push({href:'/security',label:text.security});if(admin.length)groups.push({id:'admin',label:menu.admin,icon:'◆',items:admin});
    const settings:NavItem[]=[{href:'/settings',label:text.settings},{href:'/profile',label:text.profile},{href:'/account/subscription',label:'Abonnement & facturation'}];if(user.role==='OWNER')settings.splice(1,0,{href:'/settings/social-developer',label:'Connexions développeur'});if(isManager)settings.splice(user.role==='OWNER'?2:1,0,{href:'/settings/agents',label:'Agents KHE'});groups.push({id:'settings',label:menu.settings,icon:'⚙',items:settings});
    groups.push({id:'compliance',label:menu.compliance,icon:'§',items:[{href:'/guide',label:text.guide},{href:'/terms',label:text.terms},{href:'/privacy',label:'Confidentialité'},{href:'/data-deletion',label:'Suppression des données'}]});
    return groups;
  },[menu,text,user]);
  const activeHref=useMemo(()=>navGroups.flatMap(group=>group.items).filter(item=>pathMatches(pathname,item.href)).sort((a,b)=>b.href.length-a.href.length)[0]?.href,[navGroups,pathname]);
  useEffect(()=>{const activeGroup=navGroups.find(group=>group.items.some(item=>pathMatches(pathname,item.href)));if(!activeGroup)return;setOpenGroups(previous=>{if(previous.includes(activeGroup.id))return previous;const next=[...previous,activeGroup.id];persistOpenGroups(next);return next;});},[navGroups,pathname]);
  const toggleGroup=(id:string)=>setOpenGroups(previous=>{const next=previous.includes(id)?previous.filter(value=>value!==id):[...previous,id];persistOpenGroups(next);return next;});
  const closeAllGroups=()=>{setOpenGroups([]);persistOpenGroups([]);};
  if(!ready)return <main className="login"><div className="muted">{text.loading}</div></main>;if(user&&user.termsAccepted===false)return <WebTermsGate onAccepted={()=>setUser({...user,termsAccepted:true})}/>;
  const displayName=[user?.firstName,user?.lastName].filter(Boolean).join(' ')||user?.email;
  const logout=async()=>{await endOperationsSession();clearAccessToken();router.replace('/login');};
  return <div className="shell"><aside className="sidebar"><div className="brand">KHE <span>Booth</span></div><div className="muted" style={{marginTop:6,fontSize:13}}>Kurtis Hypnotic Events</div>{user?.tenantKind==='ENTERPRISE_CLIENT'?<div style={{marginTop:10,padding:'7px 9px',borderRadius:10,border:'1px solid rgba(210,173,79,.35)',color:'#d2ad4f',fontSize:10,fontWeight:900}}>ESPACE ENTERPRISE GÉRÉ PAR KHE</div>:null}<nav className="portal-nav" aria-label="Navigation KHE Booth"><div className="portal-nav-heading"><span>{menu.menu}</span>{openGroups.length?<button type="button" onClick={closeAllGroups}>{menu.collapse}</button>:null}</div>{navGroups.map(group=>{const isOpen=openGroups.includes(group.id);const isActive=group.items.some(item=>pathMatches(pathname,item.href));return <section className={`portal-nav-group${isOpen?' is-open':''}${isActive?' is-active':''}`} key={group.id}><button type="button" className="portal-nav-trigger" onClick={()=>toggleGroup(group.id)} aria-expanded={isOpen} aria-controls={`nav-${group.id}`}><span className="portal-nav-icon" aria-hidden="true">{group.icon}</span><span className="portal-nav-label">{group.label}</span><span className="portal-nav-chevron" aria-hidden="true">⌄</span></button><div id={`nav-${group.id}`} className="portal-nav-submenu" data-open={isOpen?'true':'false'}><div className="portal-nav-submenu-inner">{group.items.map(item=><Link key={item.href} href={item.href} aria-current={activeHref===item.href?'page':undefined}><span aria-hidden="true">→</span><span>{item.label}</span></Link>)}</div></div></section>;})}</nav><div className="portal-user-card"><div style={{display:'flex',alignItems:'center',gap:9}}>{user?.avatarUrl?<img src={user.avatarUrl} alt="" style={{width:34,height:34,borderRadius:17,objectFit:'cover',border:'1px solid #d2ad4f'}}/>:null}<div><div style={{fontWeight:800,fontSize:13}}>{displayName}</div>{user?.username?<div className="muted" style={{fontSize:11,marginTop:1}}>@{user.username}</div>:null}<div className="muted" style={{fontSize:12,marginTop:2}}>{user?.role}</div></div></div><button className="button secondary" style={{marginTop:14,width:'100%'}} onClick={()=>void logout()}>{text.logout}</button></div></aside><SupportCenterTools/><OperationsPresenceControl role={user?.role}/><SupportFeedbackPrompt/><main className="content">{children}</main></div>;
}
