'use client';

import { useEffect, useMemo, useState } from 'react';

export type RegionKey='SWITZERLAND'|'EUROZONE'|'AFRICA'|'ASIA'|'AMERICAS'|'OTHER';
export type RegionPolicy={enabled:boolean;showPrices:boolean;showDownload:boolean;showReviews:boolean;showPromoVideo:boolean;forceCurrency?:string;heroTitle?:string;heroSubtitle?:string;primaryCta?:string;announcement?:string};
export type RegionalSettings=Record<RegionKey,RegionPolicy>;
type Language='fr'|'en'|'de'|'it'|'es'|'pt';
type RegionOption={key:RegionKey;label:string;hint:string;defaultCurrency?:string;icon:string};

export const REGION_OPTIONS:RegionOption[]=[
  {key:'SWITZERLAND',label:'Suisse',hint:'Suisse et Liechtenstein',defaultCurrency:'CHF',icon:'🇨🇭'},
  {key:'EUROZONE',label:'Zone euro',hint:'Pays utilisant l’euro',defaultCurrency:'EUR',icon:'🇪🇺'},
  {key:'AFRICA',label:'Afrique',hint:'Pays du continent africain',icon:'🌍'},
  {key:'ASIA',label:'Asie',hint:'Pays du continent asiatique',icon:'🌏'},
  {key:'AMERICAS',label:'Amériques',hint:'Amérique du Nord, centrale, Caraïbes et Amérique du Sud',icon:'🌎'},
  {key:'OTHER',label:'Autres régions',hint:'Royaume-Uni, Océanie et autres pays',icon:'✦'},
];
const copy:Record<Language,Record<string,string>>={
fr:{switzerland:'Suisse',switzerlandHint:'Suisse et Liechtenstein',eurozone:'Zone euro',eurozoneHint:'Pays utilisant l’euro',africa:'Afrique',africaHint:'Pays du continent africain',asia:'Asie',asiaHint:'Pays du continent asiatique',americas:'Amériques',americasHint:'Amérique du Nord, centrale, Caraïbes et Amérique du Sud',other:'Autres régions',otherHint:'Royaume-Uni, Océanie et autres pays',active:'SITE ACTIF',hidden:'SITE MASQUÉ',visibility:'VISIBILITÉ',visibilityHelp:'Ce que les visiteurs de cette région peuvent voir',accessible:'Site accessible',accessibleHelp:'Autoriser l’accès à la vitrine KHE Booth dans cette zone.',prices:'Afficher les prix',pricesHelp:'Afficher les abonnements et les tarifs localisés.',download:'Téléchargement',downloadHelp:'Afficher le bouton de téléchargement de l’application.',reviews:'Avis clients',reviewsHelp:'Afficher les témoignages des abonnés vérifiés.',videos:'Vidéos promotionnelles',videosHelp:'Afficher les séquences vidéo et les animations marketing.',currency:'Devise imposée',currencyHelp:'Laissez automatique pour utiliser la devise du visiteur.',automatic:'Détection automatique',localized:'MESSAGE LOCALISÉ',localizedHelp:'Personnaliser le texte uniquement pour cette région',hero:'Titre principal',heroPh:'Utiliser le titre global',cta:'Bouton principal',ctaPh:'Utiliser le bouton global',subtitle:'Sous-titre',subtitlePh:'Utiliser le sous-titre global',announcement:'Annonce régionale',announcementPh:'Ex. Offre spéciale Suisse'},
en:{switzerland:'Switzerland',switzerlandHint:'Switzerland and Liechtenstein',eurozone:'Euro area',eurozoneHint:'Countries using the euro',africa:'Africa',africaHint:'Countries on the African continent',asia:'Asia',asiaHint:'Countries on the Asian continent',americas:'Americas',americasHint:'North, Central, Caribbean and South America',other:'Other regions',otherHint:'United Kingdom, Oceania and other countries',active:'SITE ACTIVE',hidden:'SITE HIDDEN',visibility:'VISIBILITY',visibilityHelp:'What visitors from this region can see',accessible:'Site accessible',accessibleHelp:'Allow access to the KHE Booth website in this area.',prices:'Show prices',pricesHelp:'Show localized subscriptions and pricing.',download:'Download',downloadHelp:'Show the application download button.',reviews:'Client reviews',reviewsHelp:'Show testimonials from verified subscribers.',videos:'Promotional videos',videosHelp:'Show promotional video sequences and animations.',currency:'Forced currency',currencyHelp:'Leave automatic to use the visitor’s currency.',automatic:'Automatic detection',localized:'LOCALIZED MESSAGE',localizedHelp:'Customize text only for this region',hero:'Main title',heroPh:'Use global title',cta:'Main button',ctaPh:'Use global button',subtitle:'Subtitle',subtitlePh:'Use global subtitle',announcement:'Regional announcement',announcementPh:'E.g. Switzerland special offer'},
de:{switzerland:'Schweiz',switzerlandHint:'Schweiz und Liechtenstein',eurozone:'Eurozone',eurozoneHint:'Länder mit dem Euro',africa:'Afrika',africaHint:'Länder auf dem afrikanischen Kontinent',asia:'Asien',asiaHint:'Länder auf dem asiatischen Kontinent',americas:'Amerika',americasHint:'Nord-, Mittel-, Karibik- und Südamerika',other:'Weitere Regionen',otherHint:'Vereinigtes Königreich, Ozeanien und weitere Länder',active:'SEITE AKTIV',hidden:'SEITE AUSGEBLENDET',visibility:'SICHTBARKEIT',visibilityHelp:'Was Besucher aus dieser Region sehen können',accessible:'Website erreichbar',accessibleHelp:'Zugriff auf die KHE-Booth-Website in dieser Region erlauben.',prices:'Preise anzeigen',pricesHelp:'Lokalisierte Abonnements und Preise anzeigen.',download:'Download',downloadHelp:'Download-Schaltfläche der Anwendung anzeigen.',reviews:'Kundenbewertungen',reviewsHelp:'Erfahrungsberichte verifizierter Abonnenten anzeigen.',videos:'Werbevideos',videosHelp:'Werbevideos und Marketinganimationen anzeigen.',currency:'Erzwungene Währung',currencyHelp:'Automatisch lassen, um die Währung des Besuchers zu verwenden.',automatic:'Automatisch erkennen',localized:'LOKALISIERTE NACHRICHT',localizedHelp:'Text nur für diese Region anpassen',hero:'Haupttitel',heroPh:'Globalen Titel verwenden',cta:'Hauptschaltfläche',ctaPh:'Globale Schaltfläche verwenden',subtitle:'Untertitel',subtitlePh:'Globalen Untertitel verwenden',announcement:'Regionale Ankündigung',announcementPh:'Z. B. Sonderangebot Schweiz'},
it:{switzerland:'Svizzera',switzerlandHint:'Svizzera e Liechtenstein',eurozone:'Zona euro',eurozoneHint:'Paesi che utilizzano l’euro',africa:'Africa',africaHint:'Paesi del continente africano',asia:'Asia',asiaHint:'Paesi del continente asiatico',americas:'Americhe',americasHint:'Nord, Centro, Caraibi e Sud America',other:'Altre regioni',otherHint:'Regno Unito, Oceania e altri paesi',active:'SITO ATTIVO',hidden:'SITO NASCOSTO',visibility:'VISIBILITÀ',visibilityHelp:'Cosa possono vedere i visitatori di questa regione',accessible:'Sito accessibile',accessibleHelp:'Consentire l’accesso al sito KHE Booth in questa zona.',prices:'Mostra prezzi',pricesHelp:'Mostrare abbonamenti e prezzi localizzati.',download:'Download',downloadHelp:'Mostrare il pulsante di download dell’applicazione.',reviews:'Recensioni clienti',reviewsHelp:'Mostrare le testimonianze degli abbonati verificati.',videos:'Video promozionali',videosHelp:'Mostrare sequenze video e animazioni promozionali.',currency:'Valuta forzata',currencyHelp:'Lasciare automatico per usare la valuta del visitatore.',automatic:'Rilevamento automatico',localized:'MESSAGGIO LOCALIZZATO',localizedHelp:'Personalizzare il testo solo per questa regione',hero:'Titolo principale',heroPh:'Usa il titolo globale',cta:'Pulsante principale',ctaPh:'Usa il pulsante globale',subtitle:'Sottotitolo',subtitlePh:'Usa il sottotitolo globale',announcement:'Annuncio regionale',announcementPh:'Es. Offerta speciale Svizzera'},
es:{switzerland:'Suiza',switzerlandHint:'Suiza y Liechtenstein',eurozone:'Zona euro',eurozoneHint:'Países que utilizan el euro',africa:'África',africaHint:'Países del continente africano',asia:'Asia',asiaHint:'Países del continente asiático',americas:'Américas',americasHint:'América del Norte, Central, Caribe y América del Sur',other:'Otras regiones',otherHint:'Reino Unido, Oceanía y otros países',active:'SITIO ACTIVO',hidden:'SITIO OCULTO',visibility:'VISIBILIDAD',visibilityHelp:'Lo que pueden ver los visitantes de esta región',accessible:'Sitio accesible',accessibleHelp:'Permitir el acceso al sitio KHE Booth en esta zona.',prices:'Mostrar precios',pricesHelp:'Mostrar suscripciones y precios localizados.',download:'Descarga',downloadHelp:'Mostrar el botón de descarga de la aplicación.',reviews:'Opiniones de clientes',reviewsHelp:'Mostrar testimonios de suscriptores verificados.',videos:'Vídeos promocionales',videosHelp:'Mostrar secuencias de vídeo y animaciones promocionales.',currency:'Moneda forzada',currencyHelp:'Dejar automático para usar la moneda del visitante.',automatic:'Detección automática',localized:'MENSAJE LOCALIZADO',localizedHelp:'Personalizar el texto solo para esta región',hero:'Título principal',heroPh:'Usar el título global',cta:'Botón principal',ctaPh:'Usar el botón global',subtitle:'Subtítulo',subtitlePh:'Usar el subtítulo global',announcement:'Anuncio regional',announcementPh:'Ej. Oferta especial Suiza'},
pt:{switzerland:'Suíça',switzerlandHint:'Suíça e Liechtenstein',eurozone:'Zona euro',eurozoneHint:'Países que utilizam o euro',africa:'África',africaHint:'Países do continente africano',asia:'Ásia',asiaHint:'Países do continente asiático',americas:'Américas',americasHint:'América do Norte, Central, Caraíbas e América do Sul',other:'Outras regiões',otherHint:'Reino Unido, Oceânia e outros países',active:'SITE ATIVO',hidden:'SITE OCULTO',visibility:'VISIBILIDADE',visibilityHelp:'O que os visitantes desta região podem ver',accessible:'Site acessível',accessibleHelp:'Permitir o acesso ao site KHE Booth nesta zona.',prices:'Mostrar preços',pricesHelp:'Mostrar subscrições e preços localizados.',download:'Transferência',downloadHelp:'Mostrar o botão de transferência da aplicação.',reviews:'Avaliações de clientes',reviewsHelp:'Mostrar testemunhos de subscritores verificados.',videos:'Vídeos promocionais',videosHelp:'Mostrar sequências de vídeo e animações promocionais.',currency:'Moeda imposta',currencyHelp:'Deixar automático para usar a moeda do visitante.',automatic:'Deteção automática',localized:'MENSAGEM LOCALIZADA',localizedHelp:'Personalizar o texto apenas para esta região',hero:'Título principal',heroPh:'Usar o título global',cta:'Botão principal',ctaPh:'Usar o botão global',subtitle:'Subtítulo',subtitlePh:'Usar o subtítulo global',announcement:'Anúncio regional',announcementPh:'Ex. Oferta especial Suíça'},
};
function readLanguage():Language{if(typeof window==='undefined')return'fr';const value=window.localStorage.getItem('khe.web.language');return value&&value in copy?value as Language:'fr';}
function localizedRegions(t:Record<string,string>):RegionOption[]{return[
  {key:'SWITZERLAND',label:t.switzerland,hint:t.switzerlandHint,defaultCurrency:'CHF',icon:'🇨🇭'},
  {key:'EUROZONE',label:t.eurozone,hint:t.eurozoneHint,defaultCurrency:'EUR',icon:'🇪🇺'},
  {key:'AFRICA',label:t.africa,hint:t.africaHint,icon:'🌍'},
  {key:'ASIA',label:t.asia,hint:t.asiaHint,icon:'🌏'},
  {key:'AMERICAS',label:t.americas,hint:t.americasHint,icon:'🌎'},
  {key:'OTHER',label:t.other,hint:t.otherHint,icon:'✦'},
];}
export const DEFAULT_REGIONAL_SETTINGS:RegionalSettings=Object.fromEntries(REGION_OPTIONS.map(region=>[region.key,{enabled:true,showPrices:true,showDownload:true,showReviews:true,showPromoVideo:true,forceCurrency:region.defaultCurrency}])) as RegionalSettings;
export function normalizeRegionalSettings(value:Partial<RegionalSettings>|undefined):RegionalSettings{const result={...DEFAULT_REGIONAL_SETTINGS} as RegionalSettings;for(const region of REGION_OPTIONS)result[region.key]={...DEFAULT_REGIONAL_SETTINGS[region.key],...(value?.[region.key]||{})};return result;}
function Toggle({label,help,checked,onChange}:{label:string;help:string;checked:boolean;onChange:(checked:boolean)=>void}){return <label className="region-option-card"><span className="region-option-copy"><strong>{label}</strong><span>{help}</span></span><span className={`region-switch${checked?' is-on':''}`} aria-hidden="true"><i/></span><input className="region-native-toggle" type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)}/></label>;}

export function RegionalSiteSettings({value,onChange,selected,onSelectedChange,compact=false}:{value:RegionalSettings;onChange:(next:RegionalSettings)=>void;selected:RegionKey;onSelectedChange:(next:RegionKey)=>void;compact?:boolean}){
  const[language,setLanguage]=useState<Language>('fr');useEffect(()=>{setLanguage(readLanguage());const handler=(event:Event)=>{const detail=(event as CustomEvent<string>).detail;if(detail&&detail in copy)setLanguage(detail as Language);};window.addEventListener('khe-language-changed',handler);return()=>window.removeEventListener('khe-language-changed',handler);},[]);
  const t=copy[language];const regions=useMemo(()=>localizedRegions(t),[t]);const policy=value[selected];const patch=(next:Partial<RegionPolicy>)=>onChange({...value,[selected]:{...policy,...next}});const current=regions.find(region=>region.key===selected)!;
  return <div className="regional-settings"><div className="region-selector-grid">{regions.map(region=><button key={region.key} type="button" className={`region-selector${selected===region.key?' active':''}`} onClick={()=>onSelectedChange(region.key)}><span className="region-selector-icon">{region.icon}</span><span><strong>{region.label}</strong><small>{region.hint}</small></span></button>)}</div>
    <section className="region-editor-panel"><header className="region-editor-header"><div className="region-current"><span className="region-current-icon">{current.icon}</span><div><strong>{current.label}</strong><p>{current.hint}</p></div></div><span className={`region-status${policy.enabled?' active':''}`}>{policy.enabled?t.active:t.hidden}</span></header>
      <div className="region-section-title"><span>{t.visibility}</span><strong>{t.visibilityHelp}</strong></div><div className="region-options-grid"><Toggle label={t.accessible} help={t.accessibleHelp} checked={policy.enabled} onChange={enabled=>patch({enabled})}/><Toggle label={t.prices} help={t.pricesHelp} checked={policy.showPrices} onChange={showPrices=>patch({showPrices})}/><Toggle label={t.download} help={t.downloadHelp} checked={policy.showDownload} onChange={showDownload=>patch({showDownload})}/><Toggle label={t.reviews} help={t.reviewsHelp} checked={policy.showReviews} onChange={showReviews=>patch({showReviews})}/><Toggle label={t.videos} help={t.videosHelp} checked={policy.showPromoVideo} onChange={showPromoVideo=>patch({showPromoVideo})}/><label className="region-currency-card"><span><strong>{t.currency}</strong><small>{t.currencyHelp}</small></span><select value={policy.forceCurrency||''} onChange={event=>patch({forceCurrency:event.target.value||undefined})}><option value="">{t.automatic}</option>{['CHF','EUR','GBP','USD','CAD','AUD'].map(currency=><option key={currency}>{currency}</option>)}</select></label></div>
      {!compact?<><div className="region-section-title region-section-spacing"><span>{t.localized}</span><strong>{t.localizedHelp}</strong></div><div className="region-fields-grid"><label>{t.hero}<input value={policy.heroTitle||''} placeholder={t.heroPh} onChange={event=>patch({heroTitle:event.target.value})}/></label><label>{t.cta}<input value={policy.primaryCta||''} placeholder={t.ctaPh} onChange={event=>patch({primaryCta:event.target.value})}/></label><label className="wide">{t.subtitle}<textarea rows={4} value={policy.heroSubtitle||''} placeholder={t.subtitlePh} onChange={event=>patch({heroSubtitle:event.target.value})}/></label><label className="wide">{t.announcement}<input value={policy.announcement||''} placeholder={t.announcementPh} onChange={event=>patch({announcement:event.target.value})}/></label></div></>:null}
    </section></div>;
}
