'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';

type Market={country:string;currency:string;locale:string;unitSystem:'metric'|'imperial';billingUnit:'month'};
type Plan={code:string;name:string;tagline:string;priceMonthlyChf:number|null;priceMonthlyCents:number|null;currency:string};
type Site={paymentMethods?:string[];plans:Plan[];market:Market;supportedCurrencies:string[]};
type Promotion={id:string;name:string;planCode?:string|null;discountPercent:number;startsAt:string;endsAt:string;messageTitle?:string|null;messageBody?:string|null}|null;
const API_BASE=(process.env.NEXT_PUBLIC_API_URL||'https://khebooth-api.vercel.app/api').replace(/\/$/,'');
const CURRENCY_LABELS:Record<string,string>={CHF:'CHF · Suisse',EUR:'EUR · Zone euro',GBP:'GBP · Royaume-Uni',USD:'USD · États-Unis',CAD:'CAD · Canada',AUD:'AUD · Australie'};

function anonymousId(){if(typeof window==='undefined')return'';const key='khe.analytics.id';let value=window.localStorage.getItem(key);if(!value){value=globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;window.localStorage.setItem(key,value);}return value;}
async function track(eventType:string,planCode?:string,metadata?:Record<string,unknown>){try{await fetch(`${API_BASE}/marketing/public/track`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({eventType,planCode,anonymousId:anonymousId(),metadata})});}catch{}}
function money(cents:number,currency:string,locale:string){return new Intl.NumberFormat(locale,{style:'currency',currency,minimumFractionDigits:0,maximumFractionDigits:2}).format(cents/100);}
function period(locale:string){if(locale.startsWith('en'))return'/month';if(locale.startsWith('de'))return'/Monat';if(locale.startsWith('it'))return'/mese';if(locale.startsWith('es'))return'/mes';if(locale.startsWith('pt'))return'/mês';return'/mois';}

export function SubscriptionCheckoutForm({initialPlan,initialCountry,initialCurrency}:{initialPlan?:string;initialCountry?:string;initialCurrency?:string}){
  const[site,setSite]=useState<Site|null>(null);const[promotion,setPromotion]=useState<Promotion>(null);const[plan,setPlan]=useState(initialPlan||'PRO');const[currency,setCurrency]=useState((initialCurrency||'').toUpperCase());const[email,setEmail]=useState('');const[name,setName]=useState('');const[paymentMethod,setPaymentMethod]=useState('card');const[marketingOptIn,setMarketingOptIn]=useState(false);const[autoRenewAcknowledged,setAutoRenewAcknowledged]=useState(false);const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);
  useEffect(()=>{const query=new URLSearchParams();if(initialCountry)query.set('country',initialCountry);if(currency)query.set('currency',currency);Promise.all([fetch(`${API_BASE}/commerce/public/site?${query.toString()}`).then((r)=>r.json() as Promise<Site>),fetch(`${API_BASE}/marketing/public/promotion`).then((r)=>r.ok?r.json() as Promise<Promotion>:null)]).then(([data,promo])=>{setSite(data);setPromotion(promo);if(!currency)setCurrency(data.market.currency);setPlan((current)=>data.plans.some((p)=>p.code===current)?current:(data.plans[0]?.code||current));}).catch(()=>setMessage('Impossible de charger les offres pour le moment.'));},[initialCountry,currency]);
  useEffect(()=>{void track('PLAN_VIEW',plan,{currency:site?.market.currency,country:site?.market.country});},[plan,site?.market.currency,site?.market.country]);
  const selected=site?.plans.find((p)=>p.code===plan);const applicable=promotion&&(!promotion.planCode||promotion.planCode===plan)?promotion:null;const displayedPrice=useMemo(()=>selected?.priceMonthlyCents==null?selected?.priceMonthlyCents:Math.round(selected.priceMonthlyCents*(100-(applicable?.discountPercent||0))/100),[selected,applicable]);const market=site?.market;
  async function submit(event:FormEvent){event.preventDefault();if(paymentMethod!=='twint'&&!autoRenewAcknowledged){setMessage('Confirmez le renouvellement automatique avant de poursuivre.');return;}setBusy(true);setMessage('Ouverture du paiement sécurisé…');await track('PLAN_SELECTED',plan,{paymentMethod,currency:market?.currency,country:market?.country});try{const response=await fetch(`${API_BASE}/commerce/public/checkout`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,email,planCode:plan,paymentMethod,marketingOptIn,autoRenewAcknowledged,currency:market?.currency||currency})});const data=await response.json() as {checkoutUrl?:string;free?:boolean;kheCode?:string;requiresContact?:boolean;message?:string;discountPercent?:number};if(!response.ok)throw new Error(data.message||'Paiement indisponible');if(data.checkoutUrl){window.location.assign(data.checkoutUrl);return;}if(data.free){setMessage(`✓ Offre activée. Votre KHE ID : ${data.kheCode||'en préparation'}`);return;}setMessage(data.message||'Nous allons vous contacter pour cette offre.');}catch(error){setMessage(error instanceof Error?error.message:'Impossible de démarrer le paiement.');}finally{setBusy(false);}}
  const methods=(site?.paymentMethods||['card','apple_pay','google_pay','twint']);const isRecurring=paymentMethod!=='twint'&&Boolean(selected&&selected.priceMonthlyCents&&selected.priceMonthlyCents>0);const locale=market?.locale||'fr-CH';const activeCurrency=market?.currency||currency||'CHF';
  return <form className="card" onSubmit={submit} style={{display:'grid',gap:14,maxWidth:680,margin:'0 auto'}}>
    <div className="grid two"><label>Devise<select value={activeCurrency} onChange={(e)=>setCurrency(e.target.value)}>{(site?.supportedCurrencies||['CHF','EUR','GBP','USD','CAD','AUD']).map((item)=><option value={item} key={item}>{CURRENCY_LABELS[item]||item}</option>)}</select></label><label>Pays détecté<input readOnly value={market?.country||initialCountry||'CH'}/></label></div>
    {applicable?<div style={{background:'#fff4cf',border:'1px solid #d2ad4f',borderRadius:14,padding:14}}><strong>{applicable.messageTitle||applicable.name}</strong><div>{applicable.messageBody||`Promotion actuelle : -${applicable.discountPercent}%`}</div><small>Valable jusqu’au {new Date(applicable.endsAt).toLocaleDateString(locale)}.</small></div>:null}
    <label>Offre<select value={plan} onChange={(e)=>setPlan(e.target.value)}>{site?.plans.map((p)=><option value={p.code} key={p.code}>{p.name}{p.priceMonthlyCents===null?' · Sur mesure':` · ${money(p.priceMonthlyCents,p.currency||activeCurrency,locale)} ${period(locale)}`}</option>)}</select></label>
    {selected&&displayedPrice!==null&&displayedPrice!==undefined?<div><strong>Prix actuel : {money(displayedPrice,activeCurrency,locale)} {period(locale)}</strong>{applicable&&selected.priceMonthlyCents!==displayedPrice?<span className="muted"> · au lieu de {money(selected.priceMonthlyCents!,activeCurrency,locale)}</span>:null}</div>:null}
    <label>Nom / entreprise<input value={name} onChange={(e)=>setName(e.target.value)} placeholder="Votre nom ou entreprise"/></label>
    <label>Adresse e-mail<input required type="email" value={email} onChange={(e)=>setEmail(e.target.value)} placeholder="vous@entreprise.ch"/></label>
    <fieldset><legend>Moyen de paiement</legend>{methods.map((method)=><label key={method} style={{display:'block',margin:'8px 0'}}><input type="radio" name="payment" checked={paymentMethod===method} onChange={()=>{setPaymentMethod(method);setAutoRenewAcknowledged(false);}}/>{' '}{method==='card'?'Carte bancaire / wallet':method==='apple_pay'?'Apple Pay':method==='google_pay'?'Google Pay':method==='twint'?'TWINT':'Paiement sécurisé'}</label>)}</fieldset>
    {isRecurring?<label style={{background:'#f3eee6',padding:12,borderRadius:12}}><input required type="checkbox" checked={autoRenewAcknowledged} onChange={(e)=>setAutoRenewAcknowledged(e.target.checked)}/>{' '}J’accepte le renouvellement automatique mensuel de mon abonnement jusqu’à résiliation. Je pourrai le gérer depuis « Mon abonnement ».</label>:paymentMethod==='twint'?<p className="muted">TWINT standard est facturé en CHF et reste un paiement ponctuel. Le renouvellement TWINT automatique sera disponible après activation du contrat marchand TWINT User on File.</p>:null}
    <label><input type="checkbox" checked={marketingOptIn} onChange={(e)=>setMarketingOptIn(e.target.checked)}/>{' '}Je souhaite recevoir les promotions et conseils KHE Booth par e-mail. Je pourrai me désabonner gratuitement à tout moment.</label>
    <p className="muted">KHE Booth adapte automatiquement la devise et le format au pays détecté. Vous gardez la possibilité de changer manuellement de devise avant le paiement.</p>
    <button className="button" disabled={busy} type="submit">{busy?'Connexion au paiement…':'Continuer vers le paiement sécurisé'}</button>{message?<p>{message}</p>:null}
  </form>;
}
