'use client';

import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { apiRequest } from '@/lib/api';

type NotificationItem={id:string;kind:string;title:string;body:string;actionUrl?:string|null;publishedAt:string;read:boolean};
type NotificationPayload={preferences:{notificationsEnabled:boolean;productUpdatesEnabled:boolean;supportNotificationsEnabled:boolean};unreadCount:number;items:NotificationItem[]};
type DeliveryPreferences={enabled:boolean;soundEnabled:boolean;sound:string;soundVolume:number;vibrationEnabled:boolean;vibrationMode:string;vibrationIntensity:string};
type Me={role?:string;notificationPreferences?:DeliveryPreferences};
type ConversationSummary={status:'BOT'|'HANDOFF_REQUESTED'|'ASSIGNED'|'RESOLVED'};
const DEFAULT_DELIVERY:DeliveryPreferences={enabled:true,soundEnabled:true,sound:'khe_chime',soundVolume:70,vibrationEnabled:true,vibrationMode:'double',vibrationIntensity:'medium'};
const AGENT_ROLES=['OWNER','ADMIN','OPERATOR'];

function signal(preferences:DeliveryPreferences){if(!preferences.enabled)return;if(preferences.soundEnabled&&preferences.sound!=='silent'&&typeof window!=='undefined'){const W=window as typeof window&{webkitAudioContext?:typeof AudioContext};const C=window.AudioContext||W.webkitAudioContext;if(C){const ctx=new C();const oscillator=ctx.createOscillator();const gain=ctx.createGain();const frequencies:Record<string,number>={default:640,khe_chime:760,khe_gold:920,khe_pulse:520};oscillator.frequency.value=frequencies[preferences.sound]||760;oscillator.type=preferences.sound==='khe_pulse'?'square':'sine';gain.gain.value=Math.max(0,Math.min(1,preferences.soundVolume/100))*.16;oscillator.connect(gain);gain.connect(ctx.destination);oscillator.start();gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.3);oscillator.stop(ctx.currentTime+.32);oscillator.addEventListener('ended',()=>void ctx.close());}}if(preferences.vibrationEnabled&&typeof navigator!=='undefined'&&'vibrate'in navigator){const intensity=preferences.vibrationIntensity==='strong'?1.4:preferences.vibrationIntensity==='light'?0.7:1;const unit=Math.round(90*intensity);const patterns:Record<string,number[]>={short:[unit],double:[unit,80,unit],triple:[unit,70,unit,70,unit],long:[unit*3]};navigator.vibrate(patterns[preferences.vibrationMode]||[unit]);}}

export function SupportCenterTools(){const[open,setOpen]=useState(false);const[data,setData]=useState<NotificationPayload|null>(null);const[delivery,setDelivery]=useState<DeliveryPreferences>(DEFAULT_DELIVERY);const[role,setRole]=useState('');const[supportCount,setSupportCount]=useState(0);const previousUnread=useRef<number|null>(null);
 const refreshNotifications=()=>{apiRequest<NotificationPayload>('/support/notifications').then((next)=>{if(previousUnread.current!==null&&next.unreadCount>previousUnread.current)signal(delivery);previousUnread.current=next.unreadCount;setData(next);}).catch(()=>undefined);};
 const refreshSupport=()=>{const endpoint=AGENT_ROLES.includes(role)?'/support/inbox':'/support/conversations/me';apiRequest<ConversationSummary[]>(endpoint).then((items)=>setSupportCount(items.filter((item)=>item.status!=='RESOLVED'&&(AGENT_ROLES.includes(role)?item.status!=='BOT':true)).length)).catch(()=>undefined);};
 useEffect(()=>{apiRequest<Me>('/auth/me').then((me)=>{setDelivery({...DEFAULT_DELIVERY,...me.notificationPreferences});setRole(me.role??'');}).catch(()=>undefined);},[]);
 useEffect(()=>{refreshNotifications();const timer=window.setInterval(refreshNotifications,30000);return()=>window.clearInterval(timer);},[delivery]);
 useEffect(()=>{refreshSupport();const timer=window.setInterval(refreshSupport,30000);return()=>window.clearInterval(timer);},[role]);
 const updatePreference=async(key:keyof NotificationPayload['preferences'],value:boolean)=>{await apiRequest('/support/notifications/preferences',{method:'PATCH',body:JSON.stringify({[key]:value})});refreshNotifications();};
 const markRead=async(item:NotificationItem)=>{if(!item.read){await apiRequest(`/support/notifications/${item.id}/read`,{method:'POST'});refreshNotifications();}};
 return <div className="support-tools"><Link className="button secondary support-help" href="/help">Help / KHE{supportCount>0?<span style={{marginLeft:7,minWidth:20,height:20,padding:'0 6px',borderRadius:10,display:'inline-grid',placeItems:'center',background:'#d6af52',color:'#111',fontSize:11,fontWeight:900}}>{supportCount}</span>:null}</Link><div className="support-bell-wrap"><button className="button secondary support-bell" aria-label="Notifications" aria-expanded={open} onClick={()=>setOpen((value)=>!value)}>🔔{(data?.unreadCount??0)>0?<span className="support-unread">{data?.unreadCount}</span>:null}</button>{open?<div className="card support-notification-panel"><div className="support-panel-head"><div><strong>Notifications</strong><div className="muted" style={{fontSize:12}}>Nouveautés, messages et informations KHE Booth</div></div><button className="button secondary" onClick={()=>setOpen(false)} style={{padding:'6px 9px'}}>×</button></div><div className="support-preferences"><label className="team-permission-option"><span>Notifications</span><input type="checkbox" checked={data?.preferences.notificationsEnabled??true} onChange={(event)=>updatePreference('notificationsEnabled',event.target.checked)}/></label><label className="team-permission-option"><span>Nouveautés produit</span><input type="checkbox" checked={data?.preferences.productUpdatesEnabled??true} disabled={!data?.preferences.notificationsEnabled} onChange={(event)=>updatePreference('productUpdatesEnabled',event.target.checked)}/></label><label className="team-permission-option"><span>Support</span><input type="checkbox" checked={data?.preferences.supportNotificationsEnabled??true} disabled={!data?.preferences.notificationsEnabled} onChange={(event)=>updatePreference('supportNotificationsEnabled',event.target.checked)}/></label><Link href="/settings" className="support-settings-link">Son, volume et vibration →</Link></div><div className="support-items">{(data?.items.length??0)===0?<div className="muted" style={{padding:'16px 0'}}>Aucune notification pour le moment.</div>:data?.items.map((item)=><div key={item.id} onClick={()=>markRead(item)} className={`support-item ${item.read?'read':'unread'}`}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><strong style={{fontSize:14}}>{item.title}</strong>{!item.read?<span title="Non lu" style={{color:'#d6af52'}}>●</span>:null}</div><div className="muted" style={{fontSize:13,marginTop:4}}>{item.body}</div><div className="muted" style={{fontSize:11,marginTop:5}}>{new Date(item.publishedAt).toLocaleString('fr-CH')}</div>{item.actionUrl?<Link href={item.actionUrl}>Ouvrir</Link>:null}</div>)}</div></div>:null}</div></div>;
}
