'use client';

import { useCallback, useEffect, useState } from 'react';
import { PortalShell } from '@/components/portal-shell';
import { apiRequest } from '@/lib/api';

type Health={surface:string;status:string;severity:string;openIncidents:number};
type Incident={id:string;surface:string;severity:string;status:string;title:string;description:string;detectedBy:string;automaticAction?:string|null;ownerActionRequired:boolean;createdAt:string};
type Overview={tenantKind:string;overall:string;surfaces:Health[];detailsRestricted:boolean;config:{mode:string;safeAutoContainment:boolean;emailAlerts:boolean;ownerReports:boolean;failedLoginThreshold:number;healthScanMinutes:number};incidents:Incident[];authEvents:Array<{id:string;email:string;eventType:string;ipAddress?:string|null;createdAt:string;metadata?:Record<string,unknown>}>;audit:Array<{id:string;action:string;entityType:string;entityId?:string|null;createdAt:string}>;safeAutomaticActions:string[];ownerApprovalRequiredFor:string[]};

const EMPTY:Overview={tenantKind:'UNKNOWN',overall:'HEALTHY',surfaces:[],detailsRestricted:false,config:{mode:'AUTO_SAFE',safeAutoContainment:true,emailAlerts:true,ownerReports:true,failedLoginThreshold:5,healthScanMinutes:60},incidents:[],authEvents:[],audit:[],safeAutomaticActions:[],ownerApprovalRequiredFor:[]};
const severityColor:Record<string,string>={INFO:'#8ea2b7',LOW:'#79c9a1',MEDIUM:'#e4c76e',HIGH:'#ff9f76',CRITICAL:'#ff7181'};

export default function SecurityPage(){
  const[data,setData]=useState<Overview>(EMPTY);const[loading,setLoading]=useState(true);const[message,setMessage]=useState('');const[saving,setSaving]=useState(false);
  const load=useCallback(async()=>{setLoading(true);try{setData(await apiRequest<Overview>('/security-center/overview'));setMessage('');}catch(e){setMessage(e instanceof Error?e.message:'Centre sécurité indisponible.');}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  async function save(){setSaving(true);try{setData(await apiRequest<Overview>('/security-center/config',{method:'PATCH',body:JSON.stringify(data.config)}));setMessage('✓ Paramètres de sécurité enregistrés.');}catch(e){setMessage(e instanceof Error?e.message:'Enregistrement impossible.');}finally{setSaving(false);}}
  async function incident(id:string,status:string){try{await apiRequest(`/security-center/incidents/${id}`,{method:'PATCH',body:JSON.stringify({status})});await load();}catch(e){setMessage(e instanceof Error?e.message:'Modification impossible.');}}
  return <PortalShell>
    <div className="page-header"><div><div className="eyebrow">SÉCURITÉ DES PLATEFORMES</div><h1>Santé & protection KHE</h1><p className="muted">KHE BOOTH, API, CAPTURE, SHARING, site promotionnel, facturation et authentification.</p></div><button className="button secondary" onClick={()=>void load()}>{loading?'Analyse…':'↻ Actualiser'}</button></div>
    <section className="card" style={{marginBottom:16,border:`1px solid ${data.overall==='HEALTHY'?'rgba(83,190,123,.35)':data.overall==='MONITORING'?'rgba(210,173,79,.4)':'rgba(220,69,83,.45)'}`,background:'linear-gradient(145deg,#0c1118,#15191f)'}}><div className="eyebrow">ÉTAT GLOBAL</div><div style={{display:'flex',gap:16,alignItems:'center',flexWrap:'wrap'}}><div style={{fontSize:34,fontWeight:950,color:data.overall==='HEALTHY'?'#79d59d':data.overall==='MONITORING'?'#e4c76e':'#ff7181'}}>{data.overall}</div><p className="muted" style={{margin:0}}>Mode {data.config.mode==='AUTO_SAFE'?'automatique sécurisé':'manuel'} • seuil connexion {data.config.failedLoginThreshold} erreurs • analyse toutes les {data.config.healthScanMinutes} min.</p></div></section>
    <div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',marginBottom:16}}>{data.surfaces.map(surface=><div className="card" key={surface.surface}><div className="eyebrow">{surface.surface.replaceAll('_',' ')}</div><div style={{fontSize:20,fontWeight:900,marginTop:8,color:severityColor[surface.severity]||'#fff'}}>{surface.status}</div><div className="muted" style={{fontSize:12,marginTop:6}}>{surface.openIncidents} incident(s) ouvert(s)</div></div>)}</div>
    <div className="grid two" style={{alignItems:'start',marginBottom:16}}><section className="card"><div className="eyebrow">MODE DE PROTECTION</div><h2>Automatique / manuel</h2><label>Mode<select value={data.config.mode} onChange={e=>setData(current=>({...current,config:{...current.config,mode:e.target.value}}))}><option value="AUTO_SAFE">Automatique sécurisé</option><option value="MANUAL">Manuel</option></select></label><label className="team-permission-option"><span>Confinement automatique sûr<small style={{display:'block',color:'#8f9bab'}}>Verrouillage, révocation de session, blocage d’authentification suspecte.</small></span><input type="checkbox" checked={data.config.safeAutoContainment} onChange={e=>setData(current=>({...current,config:{...current.config,safeAutoContainment:e.target.checked}}))}/></label><label className="team-permission-option"><span>Alertes e-mail propriétaire</span><input type="checkbox" checked={data.config.emailAlerts} onChange={e=>setData(current=>({...current,config:{...current.config,emailAlerts:e.target.checked}}))}/></label><label>Seuil de mauvais mots de passe<input type="number" min={3} max={10} value={data.config.failedLoginThreshold} onChange={e=>setData(current=>({...current,config:{...current.config,failedLoginThreshold:Number(e.target.value)}}))}/></label><label>Analyse de santé (minutes)<input type="number" min={15} max={1440} value={data.config.healthScanMinutes} onChange={e=>setData(current=>({...current,config:{...current.config,healthScanMinutes:Number(e.target.value)}}))}/></label><button className="button" disabled={saving} onClick={()=>void save()}>{saving?'Enregistrement…':'Enregistrer la sécurité'}</button></section><section className="card"><div className="eyebrow">GARDE-FOUS</div><h2>Ce que KHE peut faire seul</h2><ul>{data.safeAutomaticActions.map(action=><li key={action}>{action.replaceAll('_',' ')}</li>)}</ul><h3>Accord propriétaire obligatoire</h3><ul>{data.ownerApprovalRequiredFor.map(action=><li key={action}>{action.replaceAll('_',' ')}</li>)}</ul><p className="muted">Les comptes Enterprise gérés par KHE n’obtiennent qu’un état de santé simplifié, jamais ce centre de commande.</p></section></div>
    <section className="card" style={{marginBottom:16}}><div className="eyebrow">INCIDENTS</div><h2>Journal sécurité</h2><div style={{display:'grid',gap:10}}>{data.incidents.length?data.incidents.map(item=><article key={item.id} style={{padding:14,border:`1px solid ${severityColor[item.severity]||'#303945'}`,borderRadius:14}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><strong>{item.surface} • {item.title}</strong><span style={{color:severityColor[item.severity],fontWeight:900}}>{item.severity} • {item.status}</span></div><p>{item.description}</p>{item.automaticAction?<p className="muted">Action automatique : {item.automaticAction}</p>:null}<div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="button secondary" onClick={()=>void incident(item.id,'MONITORING')}>Surveiller</button><button className="button secondary" onClick={()=>void incident(item.id,'RESOLVED')}>Résolu</button><button className="button secondary" onClick={()=>void incident(item.id,'FALSE_POSITIVE')}>Faux positif</button></div></article>):<p className="muted">Aucun incident enregistré.</p>}</div></section>
    <div className="grid two"><section className="card"><div className="eyebrow">AUTHENTIFICATION</div><h2>Événements mots de passe</h2><div style={{display:'grid',gap:8}}>{data.authEvents.slice(0,25).map(event=><div key={event.id} style={{padding:10,border:'1px solid #303945',borderRadius:12}}><strong>{event.eventType.replaceAll('_',' ')}</strong><div className="muted" style={{fontSize:12}}>{event.email} • {new Date(event.createdAt).toLocaleString('fr-CH')}</div></div>)}</div></section><section className="card"><div className="eyebrow">AUDIT</div><h2>Activité sensible</h2><div style={{display:'grid',gap:8}}>{data.audit.slice(0,25).map(event=><div key={event.id} style={{padding:10,border:'1px solid #303945',borderRadius:12}}><strong>{event.action}</strong><div className="muted" style={{fontSize:12}}>{event.entityType} • {new Date(event.createdAt).toLocaleString('fr-CH')}</div></div>)}</div></section></div>
    {message?<p className={message.startsWith('✓')?'success':'error'} style={{marginTop:14}}>{message}</p>:null}
  </PortalShell>;
}
