'use client';
import { useEffect, useState, type CSSProperties } from 'react';

type Media={id:string;displayName:string;mimeType:string;byteSize:number;capturedAt:string|null;downloadUrl:string};
type Payload={eventId:string;eventName:string;startsAt:string;endsAt:string|null;updatedAt:string;expiresAt:string;media:Media[]};
function size(bytes:number){return`${Math.max(1,Math.round(bytes/1024/1024))} Mo`;}
function extension(mime:string){if(mime==='image/jpeg')return'jpg';if(mime==='image/png')return'png';if(mime==='image/webp')return'webp';if(mime==='video/quicktime')return'mov';return'mp4';}
export function EventGalleryClient({token}:{token:string}){
  const[data,setData]=useState<Payload|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
  useEffect(()=>{let cancelled=false,running=false;const load=async()=>{if(running||cancelled)return;running=true;try{const response=await fetch(`/api/guest-events/${encodeURIComponent(token)}`,{cache:'no-store',headers:{Accept:'application/json'}});if(!response.ok)throw new Error(response.status===404?'Cette galerie n’est plus disponible.':'Galerie temporairement indisponible.');const next=await response.json() as Payload;if(!cancelled){setData(next);setError('');setLoading(false);}}catch(cause){if(!cancelled){setError(cause instanceof Error?cause.message:'Galerie indisponible.');setLoading(false);}}finally{running=false;}};void load();const timer=setInterval(()=>void load(),5000);return()=>{cancelled=true;clearInterval(timer);};},[token]);
  return <main style={styles.page}><section style={styles.shell}><div style={styles.brandRow}><div style={styles.logoFrame}><img src="/khe-logo.jpeg" alt="KHE Booth" style={styles.logo}/></div><div><div style={styles.brand}>KHE BOOTH</div><div style={styles.slogan}>Votre événement, notre expertise</div></div></div><div style={styles.status}>● GALERIE INVITÉE SÉCURISÉE</div>{loading?<div style={styles.center}>Chargement des Moments…</div>:error&&!data?<><h1 style={styles.title}>Galerie indisponible</h1><p style={styles.copy}>{error}</p></>:data?<><p style={styles.eyebrow}>VOTRE ÉVÉNEMENT</p><h1 style={styles.title}>{data.eventName}</h1><p style={styles.copy}>{data.media.length} Moment{data.media.length===1?'':'s'} disponible{data.media.length===1?'':'s'} • actualisation automatique toutes les 5 secondes.</p>{error?<div style={styles.warning}>{error} La dernière galerie chargée reste affichée.</div>:null}{data.media.length===0?<div style={styles.empty}><strong>Les premiers Moments arrivent bientôt</strong><span>Gardez cette page ouverte : les photos et vidéos synchronisées apparaîtront automatiquement.</span></div>:<div style={styles.grid}>{data.media.map(item=>{const image=item.mimeType.startsWith('image/');const fileName=`${item.displayName}.${extension(item.mimeType)}`;return <article key={item.id} style={styles.card}><div style={styles.mediaShell}>{image?<img src={item.downloadUrl} alt={item.displayName} style={styles.media}/>:<video src={item.downloadUrl} controls playsInline preload="metadata" style={styles.media}/>}</div><div style={styles.meta}><strong style={styles.mediaTitle}>{item.displayName}</strong><span style={styles.muted}>{item.capturedAt?new Date(item.capturedAt).toLocaleTimeString('fr-CH',{hour:'2-digit',minute:'2-digit'}):'Moment KHE'} • {size(item.byteSize)}</span><a href={item.downloadUrl} download={fileName} style={styles.download}>↓ Enregistrer</a></div></article>;})}</div>}<div style={styles.security}><strong>Accès privé par QR d’événement</strong><span>Le QR reste identique pendant la prestation. Les fichiers restent privés et chaque accès média est temporairement signé.</span></div></>:null}</section></main>;
}
const styles:Record<string,CSSProperties>={page:{minHeight:'100vh',background:'radial-gradient(circle at top right,rgba(215,178,76,.14),transparent 32%),#090a0d',color:'#f7f7f7',padding:'22px 12px',fontFamily:'Inter,Arial,sans-serif'},shell:{width:'100%',maxWidth:1180,margin:'0 auto'},brandRow:{display:'flex',alignItems:'center',gap:12,marginBottom:18},logoFrame:{width:58,height:44,border:'1px solid rgba(215,178,76,.45)',borderRadius:12,overflow:'hidden',background:'#0b0c0f'},logo:{display:'block',width:'100%',height:'100%',objectFit:'contain'},brand:{fontWeight:950,letterSpacing:3,fontSize:13,color:'#f7df91'},slogan:{fontSize:10,opacity:.6,marginTop:3},status:{display:'inline-block',padding:'7px 10px',borderRadius:999,background:'rgba(25,130,72,.15)',border:'1px solid rgba(84,205,135,.35)',color:'#9ff0bd',fontSize:9,fontWeight:900,letterSpacing:1.3},eyebrow:{margin:'24px 0 5px',fontSize:10,fontWeight:900,letterSpacing:2.2,color:'#d7b24c'},title:{margin:'8px 0',fontSize:'clamp(30px,6vw,52px)',lineHeight:1.02},copy:{color:'#b9bbc2',margin:'0 0 22px',lineHeight:1.5},center:{padding:'60px 20px',textAlign:'center',color:'#d7b24c',fontWeight:800},warning:{background:'#44340f',border:'1px solid #70591b',borderRadius:12,padding:12,marginBottom:14,color:'#ffe4a0',fontSize:12},empty:{minHeight:260,border:'1px dashed rgba(215,178,76,.42)',borderRadius:22,display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:8,textAlign:'center',padding:20,color:'#d7b24c'},grid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:14},card:{background:'#15161a',border:'1px solid rgba(255,255,255,.08)',borderRadius:18,overflow:'hidden',boxShadow:'0 12px 34px rgba(0,0,0,.28)'},mediaShell:{background:'#050505',aspectRatio:'1 / 1',display:'flex',alignItems:'center',justifyContent:'center'},media:{display:'block',width:'100%',height:'100%',objectFit:'contain',background:'#050505'},meta:{padding:12,display:'flex',flexDirection:'column',gap:6},mediaTitle:{fontSize:13,color:'#fff',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'},muted:{fontSize:10,color:'#8f929a'},download:{marginTop:3,padding:'10px 12px',background:'linear-gradient(135deg,#d7b24c,#f7df91)',color:'#151515',borderRadius:10,textAlign:'center',textDecoration:'none',fontWeight:900,fontSize:11},security:{marginTop:22,padding:14,borderRadius:14,background:'rgba(255,255,255,.035)',border:'1px solid rgba(255,255,255,.07)',display:'flex',flexDirection:'column',gap:5,color:'#9ea1a9',fontSize:10},muted2:{color:'#999'}};
