'use client';

import { useEffect, useState } from 'react';
import { PortalShell } from '@/components/portal-shell';

type Language='fr'|'en'|'de'|'it'|'es'|'pt';type Mode='SIMPLE'|'PRO'|'ADMIN';
const MODE_KEY='khe.portal.mode';const INTRO_KEY='khe.web.intro.enabled';
const COPY:Record<Language,Record<string,string>>={
fr:{eyebrow:'EXPÉRIENCE KHE',title:'Simplicité & ouverture',subtitle:'Choisissez la quantité d’outils visibles et le comportement de l’animation KHE Booth.',menu:'Niveau du menu',simple:'Simple',simpleText:'Événements, Studio, aide et réglages essentiels. Idéal sur le terrain.',pro:'Professionnel',proText:'Ajoute Clients, CRM, marketing et outils agent selon vos droits.',admin:'Administration',adminText:'Affiche tous les outils autorisés, y compris opérations et administration.',intro:'Animation d’ouverture',introText:'Première ouverture cinématique, puis ouverture courte aux utilisations suivantes.',enabled:'Afficher l’animation KHE Booth',reset:'Rejouer la grande intro au prochain lancement',saved:'Préférence appliquée immédiatement.'},
en:{eyebrow:'KHE EXPERIENCE',title:'Simplicity & startup',subtitle:'Choose how many tools are visible and how the KHE Booth intro behaves.',menu:'Menu level',simple:'Simple',simpleText:'Events, Studio, help and essential settings. Best for field use.',pro:'Professional',proText:'Adds Clients, CRM, marketing and agent tools when permitted.',admin:'Administration',adminText:'Shows every permitted tool, including operations and administration.',intro:'Startup animation',introText:'Cinematic first run, then a shorter intro on later sessions.',enabled:'Show the KHE Booth intro',reset:'Replay the full intro next time',saved:'Preference applied immediately.'},
de:{eyebrow:'KHE ERLEBNIS',title:'Einfachheit & Start',subtitle:'Wählen Sie sichtbare Werkzeuge und das Verhalten der KHE-Booth-Intro.',menu:'Menüebene',simple:'Einfach',simpleText:'Events, Studio, Hilfe und wichtige Einstellungen für den Einsatz.',pro:'Professionell',proText:'Ergänzt Kunden, CRM, Marketing und Agentenwerkzeuge je nach Berechtigung.',admin:'Administration',adminText:'Zeigt alle erlaubten Werkzeuge einschließlich Operations und Administration.',intro:'Startanimation',introText:'Filmische erste Öffnung, danach kurze Intro.',enabled:'KHE-Booth-Intro anzeigen',reset:'Große Intro beim nächsten Start wiederholen',saved:'Einstellung sofort angewendet.'},
it:{eyebrow:'ESPERIENZA KHE',title:'Semplicità & apertura',subtitle:'Scegli quanti strumenti mostrare e come si comporta l’intro KHE Booth.',menu:'Livello menu',simple:'Semplice',simpleText:'Eventi, Studio, aiuto e impostazioni essenziali. Ideale sul campo.',pro:'Professionale',proText:'Aggiunge Clienti, CRM, marketing e strumenti agente se autorizzati.',admin:'Amministrazione',adminText:'Mostra tutti gli strumenti consentiti, comprese operazioni e amministrazione.',intro:'Animazione di apertura',introText:'Prima apertura cinematografica, poi intro breve.',enabled:'Mostra intro KHE Booth',reset:'Riproduci intro completa al prossimo avvio',saved:'Preferenza applicata subito.'},
es:{eyebrow:'EXPERIENCIA KHE',title:'Simplicidad & apertura',subtitle:'Elige cuántas herramientas mostrar y cómo se comporta la intro KHE Booth.',menu:'Nivel del menú',simple:'Simple',simpleText:'Eventos, Studio, ayuda y ajustes esenciales. Ideal para el terreno.',pro:'Profesional',proText:'Añade Clientes, CRM, marketing y herramientas de agente según permisos.',admin:'Administración',adminText:'Muestra todas las herramientas autorizadas, incluidas operaciones y administración.',intro:'Animación de apertura',introText:'Primera apertura cinematográfica y luego una intro corta.',enabled:'Mostrar intro de KHE Booth',reset:'Repetir la intro completa en el próximo inicio',saved:'Preferencia aplicada inmediatamente.'},
pt:{eyebrow:'EXPERIÊNCIA KHE',title:'Simplicidade & abertura',subtitle:'Escolha quantas ferramentas mostrar e como funciona a intro KHE Booth.',menu:'Nível do menu',simple:'Simples',simpleText:'Eventos, Studio, ajuda e definições essenciais. Ideal no terreno.',pro:'Profissional',proText:'Adiciona Clientes, CRM, marketing e ferramentas de agente quando permitido.',admin:'Administração',adminText:'Mostra todas as ferramentas permitidas, incluindo operações e administração.',intro:'Animação de abertura',introText:'Primeira abertura cinematográfica e depois uma intro curta.',enabled:'Mostrar intro KHE Booth',reset:'Repetir a intro completa no próximo arranque',saved:'Preferência aplicada imediatamente.'}
};
function lang():Language{if(typeof window==='undefined')return'fr';const value=localStorage.getItem('khe.web.language');return value&&value in COPY?value as Language:'fr';}
export default function ExperienceSettingsPage(){const[language,setLanguage]=useState<Language>('fr');const[mode,setMode]=useState<Mode>('PRO');const[intro,setIntro]=useState(true);const[message,setMessage]=useState('');const t=COPY[language];useEffect(()=>{setLanguage(lang());const saved=localStorage.getItem(MODE_KEY);if(saved==='SIMPLE'||saved==='PRO'||saved==='ADMIN')setMode(saved);setIntro(localStorage.getItem(INTRO_KEY)!=='false');const h=(event:Event)=>{const d=(event as CustomEvent<string>).detail;if(d&&d in COPY)setLanguage(d as Language);};window.addEventListener('khe-language-changed',h);return()=>window.removeEventListener('khe-language-changed',h);},[]);function choose(next:Mode){setMode(next);localStorage.setItem(MODE_KEY,next);window.dispatchEvent(new CustomEvent('khe-navigation-mode-changed',{detail:next}));setMessage(t.saved);}function toggleIntro(){const next=!intro;setIntro(next);localStorage.setItem(INTRO_KEY,String(next));setMessage(t.saved);}function resetIntro(){localStorage.removeItem('khe.web.intro.seen.v2');setMessage(t.saved);}return <PortalShell><div className="header"><div><div className="muted" style={{fontWeight:900,fontSize:12,letterSpacing:'.14em'}}>{t.eyebrow}</div><h1>{t.title}</h1><p>{t.subtitle}</p></div></div>{message?<p className="success">{message}</p>:null}<section className="card"><h2 style={{marginTop:0}}>{t.menu}</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:12}}>{([['SIMPLE',t.simple,t.simpleText],['PRO',t.pro,t.proText],['ADMIN',t.admin,t.adminText]] as [Mode,string,string][]).map(([value,title,body])=><button key={value} type="button" onClick={()=>choose(value)} style={{textAlign:'left',padding:18,borderRadius:18,border:`1px solid ${mode===value?'rgba(210,173,79,.7)':'rgba(255,255,255,.09)'}`,background:mode===value?'rgba(210,173,79,.11)':'rgba(255,255,255,.025)',color:'inherit',cursor:'pointer'}}><strong style={{display:'block',fontSize:16}}>{title}</strong><span className="muted" style={{display:'block',fontSize:13,lineHeight:1.5,marginTop:7}}>{body}</span></button>)}</div></section><section className="card" style={{marginTop:18}}><h2 style={{marginTop:0}}>{t.intro}</h2><p className="muted">{t.introText}</p><label style={{display:'flex',alignItems:'center',gap:10,fontWeight:800}}><input type="checkbox" checked={intro} onChange={toggleIntro}/>{t.enabled}</label><div style={{marginTop:16}}><button className="button secondary" onClick={resetIntro}>{t.reset}</button></div></section></PortalShell>;}
