import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { AlignmentType, BorderStyle, Document, HeadingLevel, Packer, Paragraph, Table, TableCell, TableRow, TextRun, WidthType } from 'docx';
import { createHash } from 'node:crypto';
import { PrismaService } from '../prisma/prisma.service';

function ascii(value:unknown){return String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7E]/g,'?');}
function escapePdf(value:unknown){return ascii(value).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');}
function safeFilename(value:unknown){return String(value??'KHE-AGENT-CONTRACT').replace(/[^a-zA-Z0-9_-]/g,'-');}
function asObject(value:unknown):Record<string,any>{return value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,any>:{};}

function pdf(lines:string[]):Buffer{
  const chunks:Array<string[]>=[];for(let index=0;index<lines.length;index+=38)chunks.push(lines.slice(index,index+38));if(!chunks.length)chunks.push(['KHE BOOTH']);
  const count=chunks.length;const normal=3+count*2;const bold=normal+1;const objects=new Map<number,string>();objects.set(1,'<< /Type /Catalog /Pages 2 0 R >>');objects.set(2,`<< /Type /Pages /Count ${count} /Kids [${chunks.map((_,index)=>`${3+index*2} 0 R`).join(' ')}] >>`);
  chunks.forEach((page,index)=>{const pageId=3+index*2;const contentId=pageId+1;const body=['BT','/F2 18 Tf','0.70 0.52 0.12 rg','48 800 Td','(KHE BOOTH) Tj','0 0 0 rg','/F1 10 Tf','0 -28 Td'];page.forEach((line,lineIndex)=>{if(lineIndex)body.push('0 -17 Td');body.push(/^(CONTRAT|CANDIDAT|SIGNATURE|[0-9]+\.)/.test(ascii(line).toUpperCase())?'/F2 10 Tf':'/F1 10 Tf',`(${escapePdf(line)}) Tj`);});body.push('/F1 8 Tf','0 -28 Td',`(Page ${index+1}/${count} - KHE Booth Agent) Tj`,'ET');const stream=body.join('\n');objects.set(pageId,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${normal} 0 R /F2 ${bold} 0 R >> >> /Contents ${contentId} 0 R >>`);objects.set(contentId,`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`);});
  objects.set(normal,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');objects.set(bold,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>');let output='%PDF-1.4\n';const offsets:number[]=[0];for(let id=1;id<=bold;id+=1){offsets[id]=Buffer.byteLength(output);output+=`${id} 0 obj\n${objects.get(id)}\nendobj\n`;}const xref=Buffer.byteLength(output);output+=`xref\n0 ${bold+1}\n0000000000 65535 f \n`;for(let id=1;id<=bold;id+=1)output+=`${String(offsets[id]).padStart(10,'0')} 00000 n \n`;output+=`trailer\n<< /Size ${bold+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(output,'ascii');
}

@Injectable()
export class AgentContractExportService {
  constructor(private readonly prisma:PrismaService){}

  private async byPublicToken(token:string){const hash=createHash('sha256').update(token).digest('hex');const rows=await this.prisma.$queryRaw<any[]>`SELECT c.* FROM "AgentContract" c JOIN "AgentApplication" a ON a.id=c."applicationId" WHERE a."accessTokenHash"=${hash} LIMIT 1`;if(!rows[0])throw new NotFoundException('Contrat introuvable');return rows[0];}
  private async byStaff(organizationId:string,applicationId:string){const rows=await this.prisma.$queryRaw<any[]>`SELECT * FROM "AgentContract" WHERE "organizationId"=${organizationId}::uuid AND "applicationId"=${applicationId}::uuid LIMIT 1`;if(!rows[0])throw new NotFoundException('Contrat introuvable');return rows[0];}
  publicExport(token:string,format:string){return this.generateFrom(this.byPublicToken(token),format);}
  staffExport(organizationId:string,applicationId:string,format:string){return this.generateFrom(this.byStaff(organizationId,applicationId),format);}

  private async generateFrom(rowPromise:Promise<any>,format:string){const row=await rowPromise;const normalized=format.toLowerCase();if(!['pdf','docx'].includes(normalized))throw new BadRequestException('Format accepté : PDF ou Word');const filename=`${safeFilename(row.contractNumber)}${row.status==='SIGNED'?'-signed':''}.${normalized}`;return normalized==='pdf'?{buffer:pdf(this.lines(row)),filename,contentType:'application/pdf'}:{buffer:await this.docx(row),filename,contentType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'};}

  private lines(row:any){const snapshot=asObject(row.contractSnapshot);const candidate=asObject(snapshot.candidate);const clauses=Array.isArray(snapshot.clauses)?snapshot.clauses:[];const lines=[`CONTRAT AGENT ${row.contractNumber}`,'Kurtis Hypnotic Events · KHE BOOTH','Votre evenement, notre expertise','',`CANDIDAT: ${candidate.name??''}`,`E-mail: ${candidate.email??''}`,`Telephone: ${candidate.phone??''}`,`Adresse: ${candidate.address??''}`,`Pays: ${row.countryCode??''}`,`Juridiction: ${row.jurisdiction??''}`,'',...clauses.flatMap((clause:any,index:number)=>[`${index+1}. ${String(clause.title??'Clause')}`,String(clause.body??''),'']),'AVERTISSEMENT JURIDIQUE',String(snapshot.notice??''),`Revue confirmee: ${row.legalReviewConfirmedAt?new Date(row.legalReviewConfirmedAt).toISOString():'Non'}`,`Reference: ${row.legalReviewReference??''}`,'','SIGNATURE',`Statut: ${row.status}`,`Signataire: ${row.signerName??''}`,`Mention: ${row.signatureMention??''}`,`Date: ${row.signedAt?new Date(row.signedAt).toISOString():''}`,`Empreinte contrat: ${row.contentHash}`,`Empreinte signature: ${row.signatureHash??''}`];return lines;}

  private async docx(row:any){const snapshot=asObject(row.contractSnapshot);const candidate=asObject(snapshot.candidate);const clauses=Array.isArray(snapshot.clauses)?snapshot.clauses:[];const border={style:BorderStyle.SINGLE,size:4,color:'D7B55B'};const cells=(label:string,value:unknown)=>new TableRow({children:[new TableCell({borders:{top:border,bottom:border,left:border,right:border},children:[new Paragraph({children:[new TextRun({text:label,bold:true})]})]}),new TableCell({borders:{top:border,bottom:border,left:border,right:border},children:[new Paragraph(String(value??''))]})]});const children=[new Paragraph({children:[new TextRun({text:'KHE BOOTH',bold:true,size:38,color:'B68A24'})],alignment:AlignmentType.CENTER}),new Paragraph({text:'Contrat Agent · Capture & Sharing',heading:HeadingLevel.TITLE,alignment:AlignmentType.CENTER}),new Paragraph({text:'Kurtis Hypnotic Events · Votre événement, notre expertise',alignment:AlignmentType.CENTER}),new Paragraph(''),new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[cells('Contrat',row.contractNumber),cells('Candidat',candidate.name),cells('E-mail',candidate.email),cells('Téléphone',candidate.phone),cells('Adresse',candidate.address),cells('Pays',row.countryCode),cells('Juridiction',row.jurisdiction)]}),new Paragraph(''),...clauses.flatMap((clause:any,index:number)=>[new Paragraph({text:`${index+1}. ${String(clause.title??'Clause')}`,heading:HeadingLevel.HEADING_2}),new Paragraph(String(clause.body??''))]),new Paragraph({text:'Revue juridique locale',heading:HeadingLevel.HEADING_2}),new Paragraph(String(snapshot.notice??'')),new Paragraph({text:'Signature',heading:HeadingLevel.HEADING_2}),new Paragraph(`Statut : ${row.status}`),new Paragraph(`Signataire : ${row.signerName??''}`),new Paragraph(`Mention : ${row.signatureMention??''}`),new Paragraph(`Date : ${row.signedAt?new Date(row.signedAt).toLocaleString('fr-CH'):''}`),new Paragraph(`Empreinte du contrat : ${row.contentHash}`),new Paragraph(`Empreinte de signature : ${row.signatureHash??''}`)];return Buffer.from(await Packer.toBuffer(new Document({sections:[{children}]})));}
}
