'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { OperationsGlobe } from '@/components/operations-globe';
import { PortalShell } from '@/components/portal-shell';
import { apiRequest } from '@/lib/api';

type Agent={id:string;email:string;firstName?:string|null;lastName?:string|null;role:string;online:boolean;available:boolean;availability?:string|null;acceptingAssignments?:boolean;lastHeartbeatAt?:string|null;availableSince?:string|null;countryCode?:string|null;regionCode?:string|null;municipality?:string|null;latitude?:number|null;longitude?:number|null;timezone?:string|null;locationSharingEnabled?:boolean;connectionCount:number;totalConnectedSeconds:number;lastLoginAt?:string|null;conversationAssignments:number;resolvedProblems:number;taskAssignments:number;completedTasks:number;failedAssignments:number;reviewCount:number;averageRating?:number|null};
type Client={id:string;name:string;email?:string|null;companyName?:string|null;connectionCount:number;activeDays:number;totalConnectedSeconds:number;lastSeenAt?:string|null;lastCountryCode?:string|null;lastRegionCode?:string|null;lastMunicipality?:string|null;eventCount:number;stationSessionCount:number;trackedActions:number;regular:boolean;engagementScore:number};
type Geo={countryCode?:string|null;regionCode?:string|null;municipality?:string|null;latitude?:number|null;longitude?:number|null;events:number;visitors:number};
type Visitor={visitorKey:string;events:number;visits:number;plans:number;checkouts:number;conversions:number;lastSeenAt:string;countryCode?:string|null;regionCode?:string|null;municipality?:string|null;intentScore:number;highIntent:boolean};
type Strategy={organizationId?:string;enabled:boolean;analysisWindowDays:number;highIntentScore:number;regularClientMinSessions:number;regularClientMinActiveDays:number;regularClientMinMinutes:number;geoSegmentationEnabled:boolean;anonymousAnalyticsEnabled:boolean;personalizedNurtureEnabled:boolean;autoPromotionEnabled:boolean;ownerApprovalForPaidCampaigns:boolean;strategyNotes?:string|null};
type Visitors={days:number;summary:{visits:number;visitors:number;planSelections:number;checkouts:number;conversions:number};highIntentVisitors:number;geographies:Geo[];visitors:Visitor[];recommendations:string[];strategy:Strategy};
type History={sessions:any[];availability:any[];assignments:any[];feedback:any[]};
type Tab='agents'|'clients'|'visitors'|'strategy';

const DEFAULT_STRATEGY:Strategy={enabled:true,analysisWindowDays:30,highIntentScore:60,regularClientMinSessions:5,regularClientMinActiveDays:3,regularClientMinMinutes:60,geoSegmentationEnabled:true,anonymousAnalyticsEnabled:true,personalizedNurtureEnabled:true,autoPromotionEnabled:false,ownerApprovalForPaidCampaigns:true,strategyNotes:''};
function duration(seconds:number){const total=Math.max(0,Math.round(seconds||0));const h=Math.floor(total/3600),m=Math.floor((total%3600)/60);return h?`${h} h ${m} min`:`${m} min`;}
function date(value?:string|null){return value?new Date(value).toLocaleString('fr-CH'):'—';}
function name(agent:Agent){return [agent.firstName,agent.lastName].filter(Boolean).join(' ')||agent.email;}
function geo(a:{municipality?:string|null;regionCode?:string|null;countryCode?:string|null}){return [a.municipality,a.regionCode,a.countryCode].filter(Boolean).join(' · ')||'Zone non partagée';}

export default function OperationsPage(){
  const[tab,setTab]=useState<Tab>('agents');const[agents,setAgents]=useState<Agent[]>([]);const[clients,setClients]=useState<Client[]>([]);const[visitors,setVisitors]=useState<Visitors|null>(null);const[strategy,setStrategy]=useState<Strategy>(DEFAULT_STRATEGY);const[history,setHistory]=useState<{agent:Agent;data:History}|null>(null);const[loading,setLoading]=useState(true);const[message,setMessage]=useState('');const[saving,setSaving]=useState(false);
  const load=useCallback(async(quiet=false)=>{if(!quiet)setLoading(true);try{const[a,c,v,s]=await Promise.all([apiRequest<Agent[]>('/operations/agents'),apiRequest<Client[]>('/operations/clients'),apiRequest<Visitors>('/operations/visitors'),apiRequest<Strategy>('/operations/strategy')]);setAgents(a);setClients(c);setVisitors(v);setStrategy({...DEFAULT_STRATEGY,...s});if(!quiet)setMessage('');}catch(e){if(!quiet)setMessage(e instanceof Error?e.message:'Impossible de charger le centre opérations.');}finally{if(!quiet)setLoading(false);}},[]);
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(true),15000);return()=>window.clearInterval(timer);},[load]);
  const stats=useMemo(()=>({online:agents.filter(a=>a.online).length,available:agents.filter(a=>a.available).length,offline:agents.filter(a=>!a.online).length,resolved:agents.reduce((s,a)=>s+a.resolvedProblems,0),reviews:agents.reduce((s,a)=>s+a.reviewCount,0),rating:(()=>{const rated=agents.filter(a=>a.averageRating!==null&&a.averageRating!==undefined);return rated.length?rated.reduce((s,a)=>s+Number(a.averageRating),0)/rated.length:null;})()}),[agents]);
  async function openHistory(agent:Agent){try{setHistory({agent,data:await apiRequest<History>(`/operations/agents/${agent.id}/history`)});}catch(e){setMessage(e instanceof Error?e.message:'Historique indisponible');}}
  async function saveStrategy(){setSaving(true);try{const next=await apiRequest<Strategy>('/operations/strategy',{method:'PATCH',body:JSON.stringify(strategy)});setStrategy({...DEFAULT_STRATEGY,...next});setMessage('✓ Stratégie KHE enregistrée. Les prochaines analyses utiliseront ces paramètres.');}catch(e){setMessage(e instanceof Error?e.message:'Enregistrement impossible');}finally{setSaving(false);}}

  return <PortalShell>
    <div className="page-header"><div><div className="eyebrow">KHE • CENTRE OPÉRATIONS & INTELLIGENCE</div><h1>Agents, clients & conversion</h1><p className="muted">Présence mondiale, auto-assignation, qualité support, comportement client et stratégie commerciale dans une vue propriétaire.</p></div><button className="button secondary" onClick={()=>void load()}>{loading?'Chargement…':'↻ Actualiser'}</button></div>
    {message?<p className={message.startsWith('✓')?'success':'error'}>{message}</p>:null}
    <div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:16}}>{([['agents','Agents & globe'],['clients','Clients'],['visitors','Visiteurs & conversion'],['strategy','Paramètres stratégie']] as const).map(([key,label])=><button key={key} className={tab===key?'button':'button secondary'} onClick={()=>setTab(key)}>{label}</button>)}</div>

    {tab==='agents'?<>
      <div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',marginBottom:16}}>{[['Connectés',stats.online],['Disponibles',stats.available],['Déconnectés',stats.offline],['Problèmes résolus',stats.resolved],['Avis clients',stats.reviews],['Note moyenne',stats.rating===null?'—':`${stats.rating.toFixed(2)} / 5`]].map(([label,value])=><div className="card" key={String(label)}><div className="eyebrow">{label}</div><div style={{fontSize:27,fontWeight:950,marginTop:8}}>{value}</div></div>)}</div>
      <div className="grid two" style={{alignItems:'start'}}><section className="card"><div className="eyebrow">PRÉSENCE MONDIALE</div><h2>Globe des agents</h2><OperationsGlobe agents={agents}/></section><section className="card"><div className="eyebrow">RÈGLE KHE</div><h2>Auto-assignation</h2><p>KHE n’assigne qu’un agent qui a <strong>cliqué pour devenir disponible</strong> et dont le heartbeat confirme qu’il est encore connecté. Parmi eux, la demande va à la charge active la plus faible.</p><div className="muted">Si aucun agent n’est disponible, la demande reste en attente. Elle n’est jamais supprimée ni attribuée à un agent hors ligne.</div></section></div>
      <section className="card" style={{marginTop:16}}><h2>Vue de tous les agents</h2><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:1050}}><thead><tr>{['Agent','Connexion','Disponibilité','Zone','Connexions / durée','Assignations','Échecs','Résolus','Avis'].map(h=><th key={h} style={{textAlign:'left',padding:9,borderBottom:'1px solid #303945'}}>{h}</th>)}</tr></thead><tbody>{agents.map(a=><tr key={a.id}><td style={{padding:9}}><button onClick={()=>void openHistory(a)} style={{background:'none',border:0,color:'inherit',padding:0,textAlign:'left',cursor:'pointer'}}><strong>{name(a)}</strong><div className="muted" style={{fontSize:11}}>{a.email} · {a.role}</div></button></td><td style={{padding:9,color:a.online?'#78d59c':'#ff9aa4',fontWeight:900}}>{a.online?'● Connecté':'○ Déconnecté'}</td><td style={{padding:9}}>{a.available?'Disponible':a.availability==='BUSY'?'Occupé':a.availability==='AWAY'?'Pause':'Indisponible'}</td><td style={{padding:9}}>{geo(a)}</td><td style={{padding:9}}>{a.connectionCount} · {duration(a.totalConnectedSeconds)}</td><td style={{padding:9}}>{a.conversationAssignments+a.taskAssignments}</td><td style={{padding:9}}>{a.failedAssignments}</td><td style={{padding:9}}>{a.resolvedProblems}</td><td style={{padding:9}}>{a.averageRating===null||a.averageRating===undefined?'—':`${Number(a.averageRating).toFixed(1)}★ (${a.reviewCount})`}</td></tr>)}</tbody></table></div></section>
    </>:null}

    {tab==='clients'?<><div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',marginBottom:16}}><div className="card"><div className="eyebrow">CLIENTS</div><div style={{fontSize:28,fontWeight:950}}>{clients.length}</div></div><div className="card"><div className="eyebrow">RÉGULIERS</div><div style={{fontSize:28,fontWeight:950}}>{clients.filter(c=>c.regular).length}</div></div><div className="card"><div className="eyebrow">SESSIONS</div><div style={{fontSize:28,fontWeight:950}}>{clients.reduce((s,c)=>s+c.connectionCount,0)}</div></div></div><section className="card"><div className="eyebrow">COMPORTEMENT CLIENT</div><h2>Fréquence & engagement</h2><p className="muted">Le score combine fréquence de connexion, durée, événements, sessions de stations et actions suivies. Le statut « régulier » suit les seuils modifiables dans Paramètres stratégie.</p><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:1000}}><thead><tr>{['Client','Profil','Connexions','Durée','Jours actifs','Événements','Stations','Engagement','Dernière zone'].map(h=><th key={h} style={{textAlign:'left',padding:9,borderBottom:'1px solid #303945'}}>{h}</th>)}</tr></thead><tbody>{clients.map(c=><tr key={c.id}><td style={{padding:9}}><strong>{c.name}</strong><div className="muted" style={{fontSize:11}}>{c.email||c.companyName||'—'}</div></td><td style={{padding:9}}>{c.regular?<span style={{color:'#78d59c',fontWeight:900}}>Régulier</span>:'Occasionnel'}</td><td style={{padding:9}}>{c.connectionCount}</td><td style={{padding:9}}>{duration(c.totalConnectedSeconds)}</td><td style={{padding:9}}>{c.activeDays}</td><td style={{padding:9}}>{c.eventCount}</td><td style={{padding:9}}>{c.stationSessionCount}</td><td style={{padding:9}}><strong>{c.engagementScore}/100</strong></td><td style={{padding:9}}>{[c.lastMunicipality,c.lastRegionCode,c.lastCountryCode].filter(Boolean).join(' · ')||'Non partagée'}</td></tr>)}</tbody></table></div></section></>:null}

    {tab==='visitors'&&visitors?<><div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',marginBottom:16}}>{[['Visites',visitors.summary.visits],['Visiteurs',visitors.summary.visitors],['Offres consultées',visitors.summary.planSelections],['Checkouts',visitors.summary.checkouts],['Conversions',visitors.summary.conversions],['Forte intention',visitors.highIntentVisitors]].map(([label,value])=><div className="card" key={String(label)}><div className="eyebrow">{label}</div><div style={{fontSize:27,fontWeight:950,marginTop:8}}>{value}</div></div>)}</div><div className="grid two" style={{alignItems:'start'}}><section className="card"><div className="eyebrow">STRATÉGIE AUTOMATIQUE KHE</div><h2>Ce que KHE recommande maintenant</h2><ol>{visitors.recommendations.map((x,i)=><li key={i} style={{marginBottom:9}}>{x}</li>)}</ol><p className="muted" style={{fontSize:12}}>Les recommandations utilisent les signaux de parcours. Aucune campagne payante n’est lancée automatiquement : la validation propriétaire reste requise.</p></section><section className="card"><div className="eyebrow">ZONES CONSENTIES</div><h2>Géographie des visiteurs</h2>{visitors.geographies.length?visitors.geographies.slice(0,12).map((g,i)=><div key={`${g.countryCode}-${g.regionCode}-${g.municipality}-${i}`} style={{display:'flex',justifyContent:'space-between',gap:10,padding:'8px 0',borderBottom:'1px solid #27303a'}}><span>{geo(g)}</span><strong>{g.visitors} visiteurs · {g.events} actions</strong></div>):<p className="muted">Aucune zone détaillée consentie pour le moment.</p>}</section></div><section className="card" style={{marginTop:16}}><div className="eyebrow">INTENTION COMMERCIALE</div><h2>Parcours visiteurs pseudonymisés</h2><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:850}}><thead><tr>{['Visiteur','Score','Visites','Offres','Checkouts','Conversions','Zone','Dernière activité'].map(h=><th key={h} style={{textAlign:'left',padding:9,borderBottom:'1px solid #303945'}}>{h}</th>)}</tr></thead><tbody>{visitors.visitors.map(v=><tr key={v.visitorKey}><td style={{padding:9}}>#{v.visitorKey}</td><td style={{padding:9,color:v.highIntent?'#e4c76e':undefined,fontWeight:900}}>{v.intentScore}/100{v.highIntent?' · Fort':''}</td><td style={{padding:9}}>{v.visits}</td><td style={{padding:9}}>{v.plans}</td><td style={{padding:9}}>{v.checkouts}</td><td style={{padding:9}}>{v.conversions}</td><td style={{padding:9}}>{geo(v)}</td><td style={{padding:9}}>{date(v.lastSeenAt)}</td></tr>)}</tbody></table></div></section></>:null}

    {tab==='strategy'?<section className="card"><div className="eyebrow">PARAMÈTRES • STRATÉGIE KHE</div><h2>Modifier les règles d’analyse & conversion</h2><p className="muted">Ces seuils pilotent la classification des clients réguliers, la détection d’intention et les recommandations. Les campagnes payantes restent soumises à approbation propriétaire.</p><div className="grid two">
      <label>Fenêtre d’analyse (jours)<input className="input" type="number" min={7} max={365} value={strategy.analysisWindowDays} onChange={e=>setStrategy({...strategy,analysisWindowDays:Number(e.target.value)})}/></label><label>Score « forte intention »<input className="input" type="number" min={1} max={100} value={strategy.highIntentScore} onChange={e=>setStrategy({...strategy,highIntentScore:Number(e.target.value)})}/></label>
      <label>Client régulier · sessions min.<input className="input" type="number" min={1} value={strategy.regularClientMinSessions} onChange={e=>setStrategy({...strategy,regularClientMinSessions:Number(e.target.value)})}/></label><label>Client régulier · jours actifs min.<input className="input" type="number" min={1} value={strategy.regularClientMinActiveDays} onChange={e=>setStrategy({...strategy,regularClientMinActiveDays:Number(e.target.value)})}/></label><label>Client régulier · minutes min.<input className="input" type="number" min={1} value={strategy.regularClientMinMinutes} onChange={e=>setStrategy({...strategy,regularClientMinMinutes:Number(e.target.value)})}/></label>
    </div><div style={{display:'grid',gap:9,marginTop:16}}>{[
      ['enabled','Analyse KHE active'],['geoSegmentationEnabled','Segmentation par zone géographique consentie'],['anonymousAnalyticsEnabled','Analytics visiteurs pseudonymisés'],['personalizedNurtureEnabled','Recommandations de nurturing personnalisé'],['autoPromotionEnabled','Autoriser les promotions automatiques gratuites'],['ownerApprovalForPaidCampaigns','Exiger la validation Owner pour toute campagne payante']
    ].map(([key,label])=><label key={key} style={{display:'flex',justifyContent:'space-between',gap:12,padding:10,border:'1px solid #303945',borderRadius:10}}><span>{label}</span><input type="checkbox" checked={Boolean(strategy[key as keyof Strategy])} disabled={key==='ownerApprovalForPaidCampaigns'} onChange={e=>setStrategy({...strategy,[key]:e.target.checked})}/></label>)}</div><label style={{display:'block',marginTop:14}}>Notes stratégiques<textarea className="input" rows={5} value={strategy.strategyNotes??''} onChange={e=>setStrategy({...strategy,strategyNotes:e.target.value})} placeholder="Ex. Priorité Business en France et Suisse, mettre en avant le partage instantané…"/></label><button className="button" disabled={saving} style={{marginTop:14}} onClick={()=>void saveStrategy()}>{saving?'Enregistrement…':'Enregistrer la stratégie KHE'}</button></section>:null}

    {history?<div role="dialog" aria-modal="true" style={{position:'fixed',inset:0,zIndex:1400,background:'rgba(0,0,0,.75)',overflowY:'auto',padding:20}}><section className="card" style={{maxWidth:920,margin:'30px auto'}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><div className="eyebrow">HISTORIQUE AGENT</div><h2>{name(history.agent)}</h2></div><button className="button secondary" onClick={()=>setHistory(null)}>Fermer</button></div><div className="grid two" style={{alignItems:'start'}}><div><h3>Connexions</h3>{history.data.sessions.slice(0,15).map(s=><div key={s.id} style={{padding:'8px 0',borderBottom:'1px solid #27303a'}}><strong>{date(s.startedAt)}</strong><div className="muted" style={{fontSize:11}}>Dernière activité {date(s.lastSeenAt)} · {s.surface} · {[s.municipality,s.regionCode,s.countryCode].filter(Boolean).join(' · ')||'zone non partagée'}</div></div>)}</div><div><h3>Disponibilité</h3>{history.data.availability.slice(0,20).map(x=><div key={x.id} style={{padding:'8px 0',borderBottom:'1px solid #27303a'}}><strong>{x.availability}</strong> · {x.acceptingAssignments?'reçoit les tâches':'hors assignation'}<div className="muted" style={{fontSize:11}}>{date(x.createdAt)} · {x.source}</div></div>)}</div></div><h3>Assignations & qualité</h3><div className="grid two"><div>{history.data.assignments.slice(0,20).map(x=><div key={x.id} style={{padding:'8px 0',borderBottom:'1px solid #27303a'}}><strong>{x.assignmentType} · {x.status}</strong><div className="muted" style={{fontSize:11}}>{date(x.createdAt)} · {x.reason||'—'}</div></div>)}</div><div>{history.data.feedback.length?history.data.feedback.slice(0,20).map(x=><div key={x.id} style={{padding:'8px 0',borderBottom:'1px solid #27303a'}}><strong>{'★'.repeat(x.rating)}{'☆'.repeat(5-x.rating)}</strong><div>{x.comment||'Sans commentaire'}</div><div className="muted" style={{fontSize:11}}>{date(x.createdAt)}</div></div>):<p className="muted">Aucun avis reçu.</p>}</div></div></section></div>:null}
  </PortalShell>;
}
