'use client';

import Link from 'next/link';
import { useCallback,useEffect,useState } from 'react';
import { PortalShell } from '@/components/portal-shell';
import { apiRequest } from '@/lib/api';

type Policy={enabled:boolean;prepareBeforeMinutes:number;slaUrgentMinutes:number;coverageLookaheadMinutes:number;notifyAgent:boolean;notifyManagers:boolean};
type Item={id:string;subject:string;priority:string;routingTopic:string;requestedLanguage:string;riskLevel:string;nextSlaDueAt?:string|null;suggestedAgentName?:string|null;reason?:string|null;agentNote?:string|null};
type Brief={id:string;status:string;agentName:string;shiftStartsAt:string;shiftEndsAt:string;openConversationCount:number;urgentSlaCount:number;missingNoteCount:number;candidateCoverageCount:number;incomingAgentCount:number;lastRefreshedAt:string;items:Item[]};
type Data={policy:Policy;summary:{activeBriefs:number;urgent:number;missingNotes:number;uncovered:number};briefs:Brief[]};
function when(v?:string|null){return v?new Date(v).toLocaleString('fr-CH',{weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';}
function riskColor(v:string){return v==='OVERDUE'?'#ff6b78':v==='URGENT'?'#ff9aa4':v==='WATCH'?'#f5c76b':'#78d59c';}
export default function ShiftBriefTeamPage(){
  const[data,setData]=useState<Data|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState('');const[message,setMessage]=useState('');
  const load=useCallback(async(quiet=false)=>{if(!quiet)setLoading(true);try{setData(await apiRequest<Data>('/operations/workforce/brief/team'));if(!quiet)setMessage('');}catch(e){if(!quiet)setMessage(e instanceof Error?e.message:'Shift Brief indisponible');}finally{if(!quiet)setLoading(false);}},[]);
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(true),30000);return()=>window.clearInterval(timer);},[load]);
  const setPolicy=<K extends keyof Policy>(key:K,value:Policy[K])=>setData(d=>d?{...d,policy:{...d.policy,[key]:value}}:d);
  async function savePolicy(){if(!data)return;setBusy('policy');try{await apiRequest('/operations/workforce/brief/policy',{method:'PATCH',body:JSON.stringify(data.policy)});setMessage('✓ Politique Shift Brief enregistrée.');await load(true);}catch(e){setMessage(e instanceof Error?e.message:'Enregistrement impossible');}finally{setBusy('');}}
  async function refresh(id:string){setBusy(id);try{await apiRequest(`/operations/workforce/brief/briefs/${id}/refresh`,{method:'POST'});setMessage('✓ Brief recalculé avec les dernières conversations, SLA et relèves.');await load(true);}catch(e){setMessage(e instanceof Error?e.message:'Rafraîchissement impossible');}finally{setBusy('');}}
  return <PortalShell><div className="page-header"><div><div className="eyebrow">KHE • SHIFT BRIEF SUPERVISION</div><h1>Préparation des fins de shift</h1><p className="muted">Anticipez les relais avant la sortie des agents. Cette vue est informative : aucun ticket n’est transféré avant validation dans le module Handover.</p><div style={{display:'flex',gap:12,flexWrap:'wrap',marginTop:8}}><Link href="/operations/workforce/live/team">← Live équipe</Link><Link href="/operations/workforce/handover">Relais à valider</Link><Link href="/operations/routing">Routing & SLA</Link></div></div><button className="button secondary" onClick={()=>void load()}>{loading?'Chargement…':'↻ Actualiser'}</button></div>
  {message?<p className={message.startsWith('✓')?'success':'error'}>{message}</p>:null}
  {!data?null:<><div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',marginBottom:16}}>{[['Briefs actifs',data.summary.activeBriefs],['SLA urgents',data.summary.urgent],['Notes manquantes',data.summary.missingNotes],['Sans relève',data.summary.uncovered]].map(([label,value])=><div className="card" key={String(label)}><div className="eyebrow">{label}</div><div style={{fontSize:28,fontWeight:950,marginTop:8}}>{value}</div></div>)}</div>
  <div className="grid two" style={{alignItems:'start'}}><section className="card"><div className="eyebrow">BRIEFS EN COURS</div><h2>Sorties à préparer</h2>{data.briefs.length?data.briefs.map(b=><div key={b.id} style={{padding:'14px 0',borderBottom:'1px solid #27303a'}}><div style={{display:'flex',justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><div><strong>{b.agentName}</strong><div className="muted" style={{fontSize:11}}>{when(b.shiftStartsAt)} → {when(b.shiftEndsAt)} · {b.status}</div></div><button className="button secondary" disabled={busy===b.id} onClick={()=>void refresh(b.id)}>{busy===b.id?'Calcul…':'Recalculer'}</button></div><div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(120px,1fr))',marginTop:10}}>{[['Ouvertes',b.openConversationCount],['SLA urgents',b.urgentSlaCount],['Notes manquantes',b.missingNoteCount],['Couvertes',`${b.candidateCoverageCount}/${b.openConversationCount}`],['Agents entrants',b.incomingAgentCount]].map(([label,value])=><div key={String(label)}><div className="muted" style={{fontSize:10}}>{label}</div><strong>{value}</strong></div>)}</div>{b.items.filter(i=>i.riskLevel!=='NORMAL'||!i.agentNote).slice(0,6).map(i=><div key={i.id} style={{marginTop:9,padding:'8px 0',borderTop:'1px solid #27303a'}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><strong style={{fontSize:12}}>{i.subject}</strong><span style={{fontSize:11,fontWeight:900,color:riskColor(i.riskLevel)}}>{i.riskLevel}</span></div><div className="muted" style={{fontSize:10}}>{i.priority} · {i.routingTopic}/{i.requestedLanguage}{i.nextSlaDueAt?` · SLA ${when(i.nextSlaDueAt)}`:''}</div><div style={{fontSize:11,marginTop:3}}>Relève : {i.suggestedAgentName??'aucune'}{!i.agentNote?<span style={{color:'#f5c76b'}}> · note manquante</span>:''}</div></div>)}</div>):<p className="muted">Aucun brief actif ou récent.</p>}</section>
  <section className="card"><div className="eyebrow">POLITIQUE SHIFT BRIEF</div><h2>Fenêtre de préparation</h2><label style={{display:'flex',gap:8,alignItems:'center',marginBottom:12}}><input type="checkbox" checked={data.policy.enabled} onChange={e=>setPolicy('enabled',e.target.checked)}/> Shift Brief actif</label><label>Préparer avant la fin (minutes)<input className="input" type="number" min={5} max={120} value={data.policy.prepareBeforeMinutes} onChange={e=>setPolicy('prepareBeforeMinutes',Number(e.target.value))}/></label><label>SLA considéré urgent autour du relais (minutes)<input className="input" type="number" min={15} max={240} value={data.policy.slaUrgentMinutes} onChange={e=>setPolicy('slaUrgentMinutes',Number(e.target.value))}/></label><label>Couverture du prochain shift à regarder (minutes)<input className="input" type="number" min={30} max={360} value={data.policy.coverageLookaheadMinutes} onChange={e=>setPolicy('coverageLookaheadMinutes',Number(e.target.value))}/></label><label style={{display:'flex',gap:8,alignItems:'center',padding:'8px 0'}}><input type="checkbox" checked={data.policy.notifyAgent} onChange={e=>setPolicy('notifyAgent',e.target.checked)}/> Rappeler l’agent quand son brief est prêt</label><label style={{display:'flex',gap:8,alignItems:'center',padding:'8px 0 14px'}}><input type="checkbox" checked={data.policy.notifyManagers} onChange={e=>setPolicy('notifyManagers',e.target.checked)}/> Informer OWNER/ADMIN qu’un brief est à surveiller</label><p className="muted" style={{fontSize:11}}>Ces alertes préparent la continuité du support. Elles ne déclenchent ni sanction, ni transfert, ni changement automatique du statut d’un agent.</p><button className="button" disabled={busy==='policy'} onClick={()=>void savePolicy()}>{busy==='policy'?'Enregistrement…':'Enregistrer la politique'}</button></section></div></>}
  </PortalShell>;
}
