'use client';

import Link from 'next/link';
import { useCallback,useEffect,useState } from 'react';
import { PortalShell } from '@/components/portal-shell';
import { apiRequest } from '@/lib/api';

type RescueCase={id:string;status:string;riskLevel:string;nextSlaDueAt?:string|null;recommendedAction:string;suggestedAgentName?:string|null;selectedAgentName?:string|null;subject:string;priority:string;routingTopic:string;requestedLanguage:string;shiftEndsAt:string};
type Mine={summary:{total:number;open:number;prepared:number;overdue:number};cases:RescueCase[]};
function when(v?:string|null){return v?new Date(v).toLocaleString('fr-CH',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';}
function statusLabel(v:string){return v==='OPEN'?'Décision manager en attente':v==='PREPARED'?'Relève préparée':v==='HOLD'?'Dossier conservé':v==='ESCALATED'?'Dossier escaladé':v==='APPLIED'?'Relève appliquée':v==='STALE'?'État remplacé':'Clos';}
export default function SlaRescueMePage(){const[data,setData]=useState<Mine|null>(null);const[loading,setLoading]=useState(true);const[message,setMessage]=useState('');const load=useCallback(async(quiet=false)=>{if(!quiet)setLoading(true);try{setData(await apiRequest<Mine>('/operations/workforce/rescue/me'));if(!quiet)setMessage('');}catch(e){if(!quiet)setMessage(e instanceof Error?e.message:'SLA Rescue indisponible');}finally{if(!quiet)setLoading(false);}},[]);useEffect(()=>{void load();const timer=window.setInterval(()=>void load(true),30000);return()=>window.clearInterval(timer);},[load]);return <PortalShell><div className="page-header"><div><div className="eyebrow">KHE • SLA RESCUE</div><h1>Mes dossiers SLA à risque</h1><p className="muted">Cette vue est informative. Les décisions de conservation, d’escalade ou de transfert sont prises par OWNER/ADMIN ; KHE ne vous applique aucune sanction automatique.</p><div style={{display:'flex',gap:12,flexWrap:'wrap',marginTop:8}}><Link href="/operations/workforce/brief">← Shift Brief</Link><Link href="/operations/workforce/handover/me">Passage de relais</Link><Link href="/operations/workforce/live">Live Shift</Link></div></div><button className="button secondary" onClick={()=>void load()}>{loading?'Chargement…':'↻ Actualiser'}</button></div>{message?<p className="error">{message}</p>:null}{!data?null:<><div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',marginBottom:16}}>{[['Cas récents',data.summary.total],['À décider',data.summary.open],['Relèves préparées',data.summary.prepared],['SLA dépassés',data.summary.overdue]].map(([label,value])=><div className="card" key={String(label)}><div className="eyebrow">{label}</div><div style={{fontSize:28,fontWeight:950,marginTop:8}}>{value}</div></div>)}</div><section className="card"><div className="eyebrow">SUIVI</div><h2>Décisions de continuité</h2>{data.cases.length?data.cases.map(c=><div key={c.id} style={{padding:'12px 0',borderBottom:'1px solid #27303a'}}><div style={{display:'flex',justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><strong>{c.subject}</strong><span style={{fontWeight:900,color:c.riskLevel==='OVERDUE'?'#ff9aa4':'#f5c76b'}}>{c.riskLevel}</span></div><div className="muted" style={{fontSize:11,marginTop:3}}>Fin du shift : {when(c.shiftEndsAt)} · SLA : {when(c.nextSlaDueAt)} · {c.routingTopic}/{c.requestedLanguage}</div><div style={{fontSize:12,marginTop:7}}><strong>{statusLabel(c.status)}</strong></div>{c.selectedAgentName?<div className="muted" style={{fontSize:11,marginTop:3}}>Relève sélectionnée : {c.selectedAgentName}</div>:c.suggestedAgentName?<div className="muted" style={{fontSize:11,marginTop:3}}>Relève pressentie : {c.suggestedAgentName}</div>:null}</div>):<p className="muted">Aucun dossier SLA Rescue récent.</p>}</section></>}</PortalShell>;}
