import * as SecureStore from 'expo-secure-store';
import { useEffect, useState } from 'react';
import { Linking, Pressable, StyleSheet, Text, View } from 'react-native';
import { API_BASE_URL } from '../config';
import { fetchReleaseInfo, type ReleaseInfo } from '../legal/legal-and-info';

const STATION_TOKEN_KEY='khe.station.token.v1';
const SUBSCRIPTION_URL='https://khebooth.vercel.app/account/subscription';
type Message={kind:string;title:string;body:string;actionUrl?:string|null;createdAt?:string};
type Experience={client:null|{kheCode?:string|null;subscriptionPlan:string;subscriptionStatus:string;paymentStatus:string;subscriptionStartedAt?:string|null;subscriptionEndsAt?:string|null};automaticMessages:Message[];messages:Message[]};
const statusLabel:Record<string,string>={PROSPECT:'Prospect',PLAN_SELECTED:'Offre choisie',PAYMENT_PENDING:'Paiement en attente',ACTIVE:'Actif',SUSPENDED:'Suspendu',CANCELLED:'Résilié'};
const paymentLabel:Record<string,string>={UNPAID:'Non payé',PENDING:'En attente',PAID:'Payé',OVERDUE:'À régulariser',REFUNDED:'Remboursé'};

export function SubscriptionPanel(){
  const[data,setData]=useState<Experience|null>(null);const[error,setError]=useState('');const[release,setRelease]=useState<ReleaseInfo|null>(null);const[openingUpdate,setOpeningUpdate]=useState(false);
  useEffect(()=>{let cancelled=false;const load=async()=>{const token=await SecureStore.getItemAsync(STATION_TOKEN_KEY);if(token){try{const response=await fetch(`${API_BASE_URL.replace(/\/$/,'')}/stations/client-experience`,{headers:{Authorization:`Bearer ${token}`,Accept:'application/json'}});if(!response.ok)throw new Error(`HTTP ${response.status}`);const payload=await response.json() as Experience;if(!cancelled){setData(payload);setError('');}}catch(e){if(!cancelled)setError(e instanceof Error?e.message:'Synchronisation indisponible');}}try{const nextRelease=await fetchReleaseInfo();if(!cancelled)setRelease(nextRelease);}catch{/* version courante conservée */}};void load();const timer=setInterval(()=>void load(),60_000);return()=>{cancelled=true;clearInterval(timer);};},[]);
  async function openUpdate(url?:string|null){if(!url||openingUpdate)return;setOpeningUpdate(true);try{const supported=await Linking.canOpenURL(url);if(!supported)throw new Error('Lien de téléchargement indisponible');await Linking.openURL(url);}catch(e){setError(e instanceof Error?e.message:'Impossible d’ouvrir le téléchargement.');}finally{setOpeningUpdate(false);}}
  if(!data?.client)return <View style={styles.card}><Text style={styles.title}>Abonnement</Text><Text style={styles.muted}>{error||'Associez cette station à un événement client pour afficher son abonnement KHE Booth.'}</Text>{release?.updateAvailable&&release.installUrl?<UpdateCard release={release} busy={openingUpdate} onDownload={()=>void openUpdate(release.installUrl)}/>:null}</View>;
  const client=data.client;const all=[...data.automaticMessages,...data.messages].slice(0,8);
  return <View style={{gap:12}}><View style={styles.card}><View style={styles.row}><View style={{flex:1}}><Text style={styles.kicker}>ABONNEMENT KHE</Text><Text style={styles.plan}>{client.subscriptionPlan}</Text></View><View style={[styles.badge,client.subscriptionStatus==='ACTIVE'&&styles.active]}><Text style={styles.badgeText}>{statusLabel[client.subscriptionStatus]||client.subscriptionStatus}</Text></View></View><Text style={styles.line}>Paiement : <Text style={styles.strong}>{paymentLabel[client.paymentStatus]||client.paymentStatus}</Text></Text><Text style={styles.line}>KHE ID : <Text style={styles.strong}>{client.kheCode||'Attribution automatique en cours'}</Text></Text><Text style={styles.muted}>Ces informations sont synchronisées entre CAPTURE, SHARING et la plateforme KHE Booth.</Text><Pressable style={styles.manageButton} onPress={()=>void Linking.openURL(SUBSCRIPTION_URL)}><Text style={styles.manageText}>Gérer mon abonnement</Text></Pressable></View>{release?.updateAvailable&&release.installUrl?<UpdateCard release={release} busy={openingUpdate} onDownload={()=>void openUpdate(release.installUrl)}/>:null}{all.length?<View style={styles.card}><Text style={styles.title}>Messages KHE</Text>{all.map((message,index)=>{const update=message.kind.toUpperCase()==='UPDATE';const url=message.actionUrl&&/^https?:\/\//.test(message.actionUrl)?message.actionUrl:null;return <View style={styles.message} key={`${message.kind}-${message.title}-${index}`}><Text style={styles.messageKind}>{message.kind}</Text><Text style={styles.messageTitle}>{message.title}</Text><Text style={styles.messageBody}>{message.body}</Text>{url?<Pressable style={update?styles.downloadMini:undefined} onPress={()=>void openUpdate(url)}><Text style={update?styles.downloadMiniText:styles.link}>{update?'TÉLÉCHARGER →':'Ouvrir →'}</Text></Pressable>:null}</View>;})}</View>:null}{error?<Text style={styles.error}>Dernière synchronisation : {error}</Text>:null}</View>;
}

function UpdateCard({release,busy,onDownload}:{release:ReleaseInfo;busy:boolean;onDownload:()=>void}){return <View style={styles.updateCard}><Text style={styles.updateEyebrow}>NOUVELLE VERSION KHE BOOTH</Text><Text style={styles.updateTitle}>Version {release.latestVersion}</Text><Text style={styles.updateBody}>{release.releaseNotes||'Une version plus récente de KHE Booth est disponible pour cette tablette.'}</Text><Pressable disabled={busy} style={[styles.downloadButton,busy&&{opacity:.55}]} onPress={onDownload}><Text style={styles.downloadText}>{busy?'OUVERTURE…':'TÉLÉCHARGER LA MISE À JOUR'}</Text></Pressable></View>;}

const styles=StyleSheet.create({card:{backgroundColor:'#fff',borderRadius:18,padding:16,borderWidth:1,borderColor:'#e0d6c8',gap:9},row:{flexDirection:'row',alignItems:'center',gap:10},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.7,color:'#b31520'},plan:{fontSize:24,fontWeight:'900',color:'#111',marginTop:2},badge:{backgroundColor:'#efe5d4',borderRadius:999,paddingHorizontal:10,paddingVertical:7},active:{backgroundColor:'#dff4e7'},badgeText:{fontWeight:'900',fontSize:11},title:{fontSize:18,fontWeight:'900'},line:{color:'#5f574f'},strong:{fontWeight:'900',color:'#111'},muted:{color:'#756b61',fontSize:12,lineHeight:17},manageButton:{marginTop:4,borderWidth:1,borderColor:'#b31520',borderRadius:12,paddingVertical:10,paddingHorizontal:12,alignSelf:'flex-start'},manageText:{color:'#b31520',fontWeight:'900'},updateCard:{backgroundColor:'#111113',borderRadius:18,padding:16,borderWidth:1,borderColor:'#d2ad4f',gap:8},updateEyebrow:{color:'#d2ad4f',fontSize:9,fontWeight:'900',letterSpacing:1.4},updateTitle:{color:'#fff',fontSize:22,fontWeight:'900'},updateBody:{color:'#c9c1b6',fontSize:12,lineHeight:18},downloadButton:{backgroundColor:'#b31520',borderRadius:13,paddingVertical:13,paddingHorizontal:14,alignItems:'center',marginTop:3},downloadText:{color:'#fff',fontWeight:'900',fontSize:11},message:{borderTopWidth:1,borderTopColor:'#eee4d8',paddingTop:10,marginTop:4},messageKind:{fontSize:9,fontWeight:'900',letterSpacing:1.2,color:'#b31520'},messageTitle:{fontWeight:'900',marginTop:2},messageBody:{color:'#665d55',marginTop:3,lineHeight:17},link:{color:'#b31520',fontWeight:'900',marginTop:6},downloadMini:{backgroundColor:'#b31520',borderRadius:10,paddingVertical:9,paddingHorizontal:11,alignSelf:'flex-start',marginTop:7},downloadMiniText:{color:'#fff',fontWeight:'900',fontSize:10},error:{color:'#8a5b17',fontSize:11}});
