import * as SecureStore from 'expo-secure-store';
import { useEffect, useState } from 'react';
import { Linking, Pressable, StyleSheet, Text, View } from 'react-native';
import { API_BASE_URL } from '../config';

const STATION_TOKEN_KEY='khe.station.token.v1';
type Message={kind:string;title:string;body:string;actionUrl?:string|null;createdAt?:string};
type Experience={client:null|{kheCode?:string|null;subscriptionPlan:string;subscriptionStatus:string;paymentStatus:string;subscriptionStartedAt?:string|null;subscriptionEndsAt?:string|null};automaticMessages:Message[];messages:Message[]};

const statusLabel:Record<string,string>={PROSPECT:'Prospect',PLAN_SELECTED:'Offre choisie',PAYMENT_PENDING:'Paiement en attente',ACTIVE:'Actif',SUSPENDED:'Suspendu',CANCELLED:'Résilié'};
const paymentLabel:Record<string,string>={UNPAID:'Non payé',PENDING:'En attente',PAID:'Payé',OVERDUE:'À régulariser',REFUNDED:'Remboursé'};

export function SubscriptionPanel(){
  const [data,setData]=useState<Experience|null>(null);const [error,setError]=useState('');
  useEffect(()=>{let cancelled=false;const load=async()=>{const token=await SecureStore.getItemAsync(STATION_TOKEN_KEY);if(!token)return;try{const response=await fetch(`${API_BASE_URL.replace(/\/$/,'')}/stations/client-experience`,{headers:{Authorization:`Bearer ${token}`,Accept:'application/json'}});if(!response.ok)throw new Error(`HTTP ${response.status}`);const payload=await response.json() as Experience;if(!cancelled){setData(payload);setError('');}}catch(e){if(!cancelled)setError(e instanceof Error?e.message:'Synchronisation indisponible');}};void load();const timer=setInterval(()=>void load(),60_000);return()=>{cancelled=true;clearInterval(timer);};},[]);
  if(!data?.client)return <View style={styles.card}><Text style={styles.title}>Abonnement</Text><Text style={styles.muted}>{error||'Associez cette station à un événement client pour afficher son abonnement KHE Booth.'}</Text></View>;
  const client=data.client;const all=[...data.automaticMessages,...data.messages].slice(0,8);
  return <View style={{gap:12}}><View style={styles.card}><View style={styles.row}><View style={{flex:1}}><Text style={styles.kicker}>ABONNEMENT KHE</Text><Text style={styles.plan}>{client.subscriptionPlan}</Text></View><View style={[styles.badge,client.subscriptionStatus==='ACTIVE'&&styles.active]}><Text style={styles.badgeText}>{statusLabel[client.subscriptionStatus]||client.subscriptionStatus}</Text></View></View><Text style={styles.line}>Paiement : <Text style={styles.strong}>{paymentLabel[client.paymentStatus]||client.paymentStatus}</Text></Text><Text style={styles.line}>KHE ID : <Text style={styles.strong}>{client.kheCode||'En préparation'}</Text></Text><Text style={styles.muted}>Ces informations sont synchronisées entre CAPTURE, SHARING et la plateforme KHE Booth.</Text></View>{all.length?<View style={styles.card}><Text style={styles.title}>Messages KHE</Text>{all.map((message,index)=><View style={styles.message} key={`${message.kind}-${message.title}-${index}`}><Text style={styles.messageKind}>{message.kind}</Text><Text style={styles.messageTitle}>{message.title}</Text><Text style={styles.messageBody}>{message.body}</Text>{message.actionUrl&&/^https?:\/\//.test(message.actionUrl)?<Pressable onPress={()=>void Linking.openURL(message.actionUrl!)}><Text style={styles.link}>Ouvrir →</Text></Pressable>:null}</View>)}</View>:null}{error?<Text style={styles.error}>Dernière synchronisation : {error}</Text>:null}</View>;
}

const styles=StyleSheet.create({card:{backgroundColor:'#fff',borderRadius:18,padding:16,borderWidth:1,borderColor:'#e0d6c8',gap:9},row:{flexDirection:'row',alignItems:'center',gap:10},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.7,color:'#b31520'},plan:{fontSize:24,fontWeight:'900',color:'#111',marginTop:2},badge:{backgroundColor:'#efe5d4',borderRadius:999,paddingHorizontal:10,paddingVertical:7},active:{backgroundColor:'#dff4e7'},badgeText:{fontWeight:'900',fontSize:11},title:{fontSize:18,fontWeight:'900'},line:{color:'#5f574f'},strong:{fontWeight:'900',color:'#111'},muted:{color:'#756b61',fontSize:12,lineHeight:17},message:{borderTopWidth:1,borderTopColor:'#eee4d8',paddingTop:10,marginTop:4},messageKind:{fontSize:9,fontWeight:'900',letterSpacing:1.2,color:'#b31520'},messageTitle:{fontWeight:'900',marginTop:2},messageBody:{color:'#665d55',marginTop:3,lineHeight:17},link:{color:'#b31520',fontWeight:'900',marginTop:6},error:{color:'#8a5b17',fontSize:11}});
