import * as DocumentPicker from 'expo-document-picker';
import { Directory, File, Paths } from 'expo-file-system';
import * as SecureStore from 'expo-secure-store';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { HttpStationApi, type StationProfileContract, type StationProfileUpdate } from '../api/station-api';
import { API_BASE_URL } from '../config';
import { SubscriptionPanel } from './subscription-panel';

interface UserProfileData extends StationProfileUpdate {
  buildingNumber: string;
  postalCode: string;
  avatarUri: string | null;
  avatarPath: string | null;
}

type RemoteProfile=StationProfileContract&{buildingNumber?:string;postalCode?:string};
const PROFILE_KEY='khe.profile.v3';
const LEGACY_PROFILE_KEY='khe.profile.v2';
const STATION_TOKEN_KEY='khe.station.token.v1';
const PROFILE_SYNC_INTERVAL_MS=1_000;
const EMPTY_PROFILE:UserProfileData={firstName:'',lastName:'',displayName:'',company:'',role:'',email:'',phone:'',address:'',buildingNumber:'',postalCode:'',birthDate:null,city:'',country:'',bio:'',avatarUri:null,avatarPath:null};

async function loadLocalProfile():Promise<UserProfileData>{
  const raw=(await SecureStore.getItemAsync(PROFILE_KEY))??(await SecureStore.getItemAsync(LEGACY_PROFILE_KEY));
  if(!raw)return EMPTY_PROFILE;
  try{return{...EMPTY_PROFILE,...JSON.parse(raw) as Partial<UserProfileData>};}catch{return EMPTY_PROFILE;}
}
async function saveLocalProfile(profile:UserProfileData){await SecureStore.setItemAsync(PROFILE_KEY,JSON.stringify(profile),{keychainAccessible:SecureStore.WHEN_UNLOCKED_THIS_DEVICE_ONLY});}
function normalizedBirthDate(value:string|Date|null){if(!value)return null;const date=value instanceof Date?value:new Date(value);return Number.isNaN(date.getTime())?(typeof value==='string'?value.slice(0,10):null):date.toISOString().slice(0,10);}
function extensionForAvatar(contentType?:string){if(contentType==='image/png')return'png';if(contentType==='image/webp')return'webp';return'jpg';}

function Field({label,value,onChange,placeholder,multiline=false,required=false,keyboardType='default'}:{label:string;value:string;onChange:(value:string)=>void;placeholder:string;multiline?:boolean;required?:boolean;keyboardType?:'default'|'email-address'|'phone-pad'}){
  return <View style={styles.field}><Text style={styles.label}>{label}{required?<Text style={styles.required}> *</Text>:<Text style={styles.optional}> · facultatif</Text>}</Text><TextInput value={value} onChangeText={onChange} placeholder={placeholder} placeholderTextColor="#9b948b" multiline={multiline} keyboardType={keyboardType} autoCapitalize={keyboardType==='email-address'?'none':'sentences'} autoCorrect={false} style={[styles.input,multiline&&styles.multiline]}/></View>;
}

export function UserProfile({onClose}:{onClose:()=>void}){
  const api=useMemo(()=>new HttpStationApi(API_BASE_URL),[]);
  const[profile,setProfile]=useState<UserProfileData>(EMPTY_PROFILE);const profileRef=useRef<UserProfileData>(EMPTY_PROFILE);const dirtyRef=useRef(false);const syncingRef=useRef(false);
  const[message,setMessage]=useState('');const[saving,setSaving]=useState(false);const[syncing,setSyncing]=useState(true);const[avatarDirty,setAvatarDirty]=useState(false);const[lastSyncAt,setLastSyncAt]=useState<Date|null>(null);

  function commitLocal(next:UserProfileData){profileRef.current=next;setProfile(next);void saveLocalProfile(next);}
  function patch(value:Partial<UserProfileData>){dirtyRef.current=true;const next={...profileRef.current,...value};profileRef.current=next;setProfile(next);setMessage('');}

  async function synchronizeAvatar(token:string,remote:RemoteProfile,current:UserProfileData):Promise<UserProfileData>{
    if(!remote.avatarPath)return current;
    if(remote.avatarPath===current.avatarPath&&current.avatarUri)return current;
    try{const ticket=await api.profileAvatarDownload(token);if(!ticket.pathname||!ticket.downloadUrl)return current;const directory=new Directory(Paths.document,'profile');await directory.create({idempotent:true,intermediates:true});const revision=ticket.pathname.split('/').pop()?.replace(/[^A-Za-z0-9._-]/g,'_').slice(0,120)||`avatar-${new Date(remote.updatedAt).getTime()}`;const destination=new File(directory,`shared-${revision}.${extensionForAvatar(ticket.contentType)}`);if(destination.exists&&destination.size>0)return{...current,avatarUri:destination.uri,avatarPath:ticket.pathname};const downloaded=await File.downloadFileAsync(ticket.downloadUrl,destination,{idempotent:true});if(!downloaded.exists||downloaded.size<=0)throw new Error('Photo de profil incomplète');return{...current,avatarUri:downloaded.uri,avatarPath:ticket.pathname};}catch{return current;}
  }

  async function pullRemote(token:string,announce=false){if(syncingRef.current||dirtyRef.current||saving)return;syncingRef.current=true;try{const remote=await api.profile(token) as RemoteProfile;let merged:UserProfileData={firstName:remote.firstName,lastName:remote.lastName,displayName:remote.displayName,company:remote.company,role:remote.role,email:remote.email,phone:remote.phone,address:remote.address,buildingNumber:remote.buildingNumber??'',postalCode:remote.postalCode??'',birthDate:normalizedBirthDate(remote.birthDate),city:remote.city,country:remote.country,bio:remote.bio,avatarUri:profileRef.current.avatarUri,avatarPath:profileRef.current.avatarPath};merged=await synchronizeAvatar(token,remote,merged);commitLocal(merged);setLastSyncAt(new Date());if(announce)setMessage('✓ Profil unique synchronisé entre CAPTURE et SHARING.');}catch(error){if(announce)setMessage(`Profil local disponible hors ligne. ${error instanceof Error?error.message:''}`.trim());}finally{syncingRef.current=false;setSyncing(false);}}

  useEffect(()=>{let cancelled=false;let timer:ReturnType<typeof setInterval>|null=null;void(async()=>{const local=await loadLocalProfile();if(cancelled)return;profileRef.current=local;setProfile(local);const token=await SecureStore.getItemAsync(STATION_TOKEN_KEY);if(!token){setSyncing(false);setMessage('Profil local chargé. Activez une station pour le synchroniser.');return;}await pullRemote(token,true);timer=setInterval(()=>void pullRemote(token,false),PROFILE_SYNC_INTERVAL_MS);})();return()=>{cancelled=true;if(timer)clearInterval(timer);};},[api]);

  const completion=useMemo(()=>{const required=[profile.firstName,profile.lastName,profile.email,profile.address,profile.buildingNumber,profile.postalCode,profile.city,profile.country];const optional=[profile.company,profile.phone,profile.birthDate?String(profile.birthDate):'',profile.bio,profile.avatarUri??''];return Math.round(required.filter(v=>String(v??'').trim()).length/required.length*85+optional.filter(v=>String(v??'').trim()).length/optional.length*15);},[profile]);

  async function chooseAvatar(){const result=await DocumentPicker.getDocumentAsync({type:['image/jpeg','image/png','image/webp','image/*'],copyToCacheDirectory:true,multiple:false});if(result.canceled||!result.assets[0])return;const asset=result.assets[0];try{const directory=new Directory(Paths.document,'profile');await directory.create({idempotent:true,intermediates:true});const extension=asset.name?.split('.').pop()?.toLowerCase()||'jpg';const source=new File(asset.uri);const destination=new File(directory,`avatar-pending.${extension}`);if(destination.exists)destination.delete();await source.copy(destination);setAvatarDirty(true);patch({avatarUri:destination.uri});}catch(error){setMessage(error instanceof Error?error.message:'Impossible d’enregistrer la photo de profil.');}}

  function validate(next:UserProfileData):string|null{
    if(!next.firstName.trim())return'Le prénom est obligatoire.';if(!next.lastName.trim())return'Le nom est obligatoire.';if(!next.email.trim())return'L’adresse e-mail est obligatoire.';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(next.email.trim()))return'L’adresse e-mail n’est pas valide.';
    if(!next.address.trim())return'L’adresse de domiciliation est obligatoire.';if(!next.buildingNumber.trim())return'Le numéro de bâtiment est obligatoire.';if(!next.postalCode.trim())return'Le code postal est obligatoire.';if(!next.city.trim())return'La ville est obligatoire.';if(!next.country.trim())return'Le pays est obligatoire.';
    if(next.birthDate){const date=new Date(String(next.birthDate));if(Number.isNaN(date.getTime()))return'La date de naissance doit être au format AAAA-MM-JJ.';if(date>new Date())return'La date de naissance ne peut pas être dans le futur.';}return null;
  }

  async function uploadAvatar(token:string,next:UserProfileData):Promise<UserProfileData>{if(!avatarDirty||!next.avatarUri)return next;const file=new File(next.avatarUri);if(!file.exists||file.size<=0)throw new Error('La photo de profil locale est introuvable.');const lower=next.avatarUri.toLowerCase();const contentType=lower.endsWith('.png')?'image/png':lower.endsWith('.webp')?'image/webp':'image/jpeg';const ticket=await api.prepareProfileAvatarUpload(token,contentType,file.size);const task=file.createUploadTask(ticket.uploadUrl,{httpMethod:'PUT',mimeType:contentType,headers:{'Content-Type':contentType}});const result=await task.uploadAsync();if(!result||result.status<200||result.status>=300)throw new Error(`Envoi de la photo impossible (HTTP ${result?.status??'?'})`);await api.confirmProfileAvatar(token,ticket.pathname);setAvatarDirty(false);return{...next,avatarPath:ticket.pathname};}

  async function persist(){const base=profileRef.current;const normalized:UserProfileData={...base,firstName:base.firstName.trim(),lastName:base.lastName.trim(),email:base.email.trim().toLowerCase(),company:base.company.trim(),phone:base.phone.trim(),address:base.address.trim(),buildingNumber:base.buildingNumber.trim(),postalCode:base.postalCode.trim(),role:base.role.trim(),city:base.city.trim(),country:base.country.trim(),bio:base.bio.trim(),displayName:base.displayName.trim()||`${base.firstName.trim()} ${base.lastName.trim()}`.trim(),birthDate:base.birthDate?String(base.birthDate).slice(0,10):null};const validation=validate(normalized);if(validation){setMessage(validation);return;}setSaving(true);setMessage('');
    try{const token=await SecureStore.getItemAsync(STATION_TOKEN_KEY);if(!token){commitLocal(normalized);dirtyRef.current=false;setMessage('Profil enregistré localement. Il sera synchronisé dès qu’une station KHE sera active.');return;}const{avatarUri:_avatarUri,avatarPath:_avatarPath,...shared}=normalized;const remote=await api.updateProfile(token,shared);let saved={...normalized,avatarPath:remote.avatarPath};commitLocal(saved);try{saved=await uploadAvatar(token,saved);commitLocal(saved);dirtyRef.current=false;setLastSyncAt(new Date());setMessage('✓ Profil et photo synchronisés. CAPTURE et SHARING utilisent maintenant les mêmes informations.');}catch(avatarError){dirtyRef.current=true;setLastSyncAt(new Date());setMessage(`✓ Informations synchronisées. Photo conservée sur cette tablette et nouvel envoi requis : ${avatarError instanceof Error?avatarError.message:'stockage photo indisponible'}.`);}}catch(error){commitLocal(normalized);dirtyRef.current=true;setMessage(error instanceof Error?`Profil conservé localement. Synchronisation distante : ${error.message}`:'Impossible de synchroniser le profil.');}finally{setSaving(false);}}

  return <View style={styles.page}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.header}><View style={{flex:1}}><Text style={styles.brand}>KHE IDENTITY</Text><Text style={styles.title}>Votre profil</Text><Text style={styles.help}>Une identité centrale partagée automatiquement entre CAPTURE et SHARING.</Text></View><Pressable style={styles.close} onPress={onClose}><Text style={styles.closeText}>Fermer</Text></Pressable></View>
    <View style={styles.syncBanner}><View style={[styles.syncDot,syncing?styles.syncDotBusy:styles.syncDotReady]}/><View style={{flex:1}}><Text style={styles.syncText}>{syncing?'Synchronisation du profil…':'Profil unique synchronisé'}</Text><Text style={styles.syncSub}>{lastSyncAt?`Dernière vérification ${lastSyncAt.toLocaleTimeString()} · actualisation automatique`:'CAPTURE et SHARING utilisent le même profil.'}</Text></View></View>
    <View style={styles.identityCard}><Pressable style={styles.avatarButton} onPress={()=>void chooseAvatar()}>{profile.avatarUri?<Image key={profile.avatarPath??profile.avatarUri} source={{uri:profile.avatarUri}} style={styles.avatar}/>:<View style={styles.avatarPlaceholder}><Text style={styles.avatarPlaceholderText}>＋</Text></View>}<View style={styles.avatarEdit}><Text style={styles.avatarEditText}>PHOTO</Text></View></Pressable><View style={{flex:1}}><Text style={styles.profileName}>{profile.displayName||`${profile.firstName} ${profile.lastName}`.trim()||'Votre profil KHE'}</Text><Text style={styles.profileMeta}>{profile.company||'Profil personnel'}{profile.email?` • ${profile.email}`:''}</Text><Text style={styles.completion}>Profil complété à {completion}%</Text><View style={styles.progressTrack}><View style={[styles.progressFill,{width:`${completion}%`}]}/></View></View></View>
    <SubscriptionPanel/>
    <View style={styles.sectionCard}><Text style={styles.sectionEyebrow}>INFORMATIONS OBLIGATOIRES</Text><Text style={styles.sectionTitle}>Identité, contact et domiciliation</Text><View style={styles.twoCols}><View style={styles.col}><Field required label="Prénom" value={profile.firstName} onChange={v=>patch({firstName:v})} placeholder="Votre prénom"/></View><View style={styles.col}><Field required label="Nom" value={profile.lastName} onChange={v=>patch({lastName:v})} placeholder="Votre nom"/></View></View><Field required label="Adresse e-mail" value={profile.email} onChange={v=>patch({email:v})} placeholder="contact@exemple.ch" keyboardType="email-address"/><Field required label="Adresse de domiciliation" value={profile.address} onChange={v=>patch({address:v})} placeholder="Nom de rue"/><View style={styles.twoCols}><View style={styles.col}><Field required label="N° de bâtiment" value={profile.buildingNumber} onChange={v=>patch({buildingNumber:v})} placeholder="43"/></View><View style={styles.col}><Field required label="Code postal" value={profile.postalCode} onChange={v=>patch({postalCode:v})} placeholder="3185"/></View></View><View style={styles.twoCols}><View style={styles.col}><Field required label="Ville" value={profile.city} onChange={v=>patch({city:v})} placeholder="Ville"/></View><View style={styles.col}><Field required label="Pays" value={profile.country} onChange={v=>patch({country:v})} placeholder="Pays"/></View></View></View>
    <View style={styles.sectionCard}><Text style={styles.sectionEyebrow}>INFORMATIONS FACULTATIVES</Text><Text style={styles.sectionTitle}>Informations complémentaires</Text><Field label="Nom de l’entreprise" value={profile.company} onChange={v=>patch({company:v})} placeholder="Votre entreprise"/><View style={styles.twoCols}><View style={styles.col}><Field label="Téléphone" value={profile.phone} onChange={v=>patch({phone:v})} placeholder="+41 …" keyboardType="phone-pad"/></View><View style={styles.col}><Field label="Date de naissance" value={profile.birthDate?String(profile.birthDate):''} onChange={v=>patch({birthDate:v||null})} placeholder="AAAA-MM-JJ"/></View></View><Field label="Fonction / rôle" value={profile.role} onChange={v=>patch({role:v})} placeholder="DJ, organisateur, photobooth…"/><Field label="À propos" value={profile.bio} onChange={v=>patch({bio:v})} placeholder="Présentez votre activité…" multiline/></View>
    <View style={styles.tipCard}><Text style={styles.tipTitle}>Même profil sur les deux tablettes</Text><Text style={styles.tipText}>La photo et les informations validées sont conservées localement puis synchronisées. Une panne d’un service secondaire ne doit plus annuler le profil principal.</Text></View><Pressable disabled={saving} style={[styles.saveButton,saving&&styles.disabled]} onPress={()=>void persist()}><Text style={styles.saveText}>{saving?'SYNCHRONISATION…':'ENREGISTRER LE PROFIL'}</Text></Pressable>{message?<Text style={styles.message}>{message}</Text>:null}</ScrollView></View>;
}

const RED='#b31520',GOLD='#d2ad4f';
const styles=StyleSheet.create({page:{flex:1,backgroundColor:'#f7f4ef'},content:{padding:22,paddingBottom:60,gap:16},header:{flexDirection:'row',gap:14,alignItems:'flex-start'},brand:{color:GOLD,fontWeight:'900',letterSpacing:4,fontSize:11},title:{fontSize:36,fontWeight:'900',color:'#111',marginTop:5},help:{color:'#746d66',lineHeight:21,marginTop:5},close:{backgroundColor:'#111',borderRadius:14,paddingHorizontal:16,paddingVertical:12},closeText:{color:'#fff',fontWeight:'900'},syncBanner:{flexDirection:'row',gap:10,alignItems:'center',padding:14,borderRadius:16,backgroundColor:'#fff',borderWidth:1,borderColor:'#e3dacd'},syncDot:{width:9,height:9,borderRadius:5},syncDotBusy:{backgroundColor:GOLD},syncDotReady:{backgroundColor:'#38a66a'},syncText:{fontWeight:'900',color:'#111'},syncSub:{fontSize:11,color:'#766e66',marginTop:2},identityCard:{backgroundColor:'#111113',borderRadius:20,padding:16,flexDirection:'row',gap:16,alignItems:'center'},avatarButton:{width:86,height:86},avatar:{width:86,height:86,borderRadius:43},avatarPlaceholder:{width:86,height:86,borderRadius:43,backgroundColor:'#f7f4ef',borderWidth:2,borderColor:RED,alignItems:'center',justifyContent:'center'},avatarPlaceholderText:{fontSize:42,color:'#8e847b'},avatarEdit:{position:'absolute',bottom:-2,left:9,right:9,backgroundColor:RED,borderRadius:999,paddingVertical:4,alignItems:'center'},avatarEditText:{fontSize:8,color:'#fff',fontWeight:'900',letterSpacing:1},profileName:{color:'#fff',fontSize:21,fontWeight:'900'},profileMeta:{color:'#c8b78e',fontSize:11,marginTop:4},completion:{color:'#f1db9b',fontSize:10,fontWeight:'800',marginTop:12},progressTrack:{height:5,borderRadius:4,backgroundColor:'#39302a',marginTop:6,overflow:'hidden'},progressFill:{height:5,backgroundColor:GOLD},sectionCard:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e2d8ca',borderRadius:20,padding:16,gap:12},sectionEyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.8,color:RED},sectionTitle:{fontSize:22,fontWeight:'900',color:'#111'},field:{gap:5},label:{fontSize:11,fontWeight:'800',color:'#504943'},required:{color:RED},optional:{color:'#999087',fontWeight:'500'},input:{borderWidth:1,borderColor:'#d8cfc4',borderRadius:12,paddingHorizontal:13,paddingVertical:12,color:'#111',backgroundColor:'#fbfaf8'},multiline:{minHeight:90,textAlignVertical:'top'},twoCols:{flexDirection:'row',gap:10},col:{flex:1},tipCard:{backgroundColor:'#fff8e6',borderLeftWidth:4,borderLeftColor:GOLD,borderRadius:14,padding:14},tipTitle:{fontWeight:'900',color:'#3a3124'},tipText:{color:'#756953',lineHeight:19,marginTop:4},saveButton:{backgroundColor:RED,borderRadius:15,padding:16,alignItems:'center'},saveText:{color:'#fff',fontWeight:'900',letterSpacing:.5},message:{backgroundColor:'#fff',borderRadius:12,padding:13,color:'#5f574f',lineHeight:18},disabled:{opacity:.55}});
